### ISSUE TITLE
Allow for pytest

### ISSUE THREAD

**Issue by hagenw** [pytorch/audio#102]
`unittest` is a great starting point for checking the implementation, but I would prefer to allow [`pytest`](https://pytest.readthedocs.io/en/latest/) for testing as well. It allows an easier way to write heavily parametrized tests. See also the discussion at https://github.com/pytorch/pytorch/issues/11578.

It will perfectly fine [work together with `unittest`](https://docs.pytest.org/en/4.4.1/unittest.html), so there is no need to rewrite any tests, but it would allow to add new tests using `pytest`. What we would have to do is to install it, e.g. add a `test/requirement.txt` file or use `pip`, basically replace
```bash
$ python -m unittest
```
with
```bash
$ pip install pytest  # or: pip install -r test/requirements.txt
$ pytest
```

BTW, it is used by [pytorch/vision](https://github.com/pytorch/vision) on travis, see https://github.com/pytorch/vision/blob/master/.travis.yml#L53

If you would be fine with the proposal, I could create a pull request integrating it.

**Comment by soumith** [comment]
pytest in torchaudio sounds fine to me

**Comment by jamarshon** [comment]
Using pytest now https://github.com/pytorch/audio/pull/131
