### ISSUE TITLE
Correct notation fluctuation in README.md

### ISSUE THREAD

**Issue by forest1988** [pytorch/audio#1030]
## 📚 Documentation

I've just started using this project, and while I was reading the README, I noticed that PyTorch and Pytorch are not written consistently.

If this is a deliberate change, I apologize for my misunderstanding.
However, If my understanding is correct, I would like to suggest changing the notation from Pytorch to PyTorch, just in case.

Excuse me for my sudden PR https://github.com/pytorch/audio/pull/1029 .
I should have consulted with you on the issue first.
I have not received a Facebook CLA and I am in a state of PR failure, should I wait for someone who have the CLA to fix it?
Or can I go through the process of getting the CLA?

Thank you very much for your consideration.

**Comment by vincentqb** [comment]
Thanks for opening a PR for this :) The CLA instructions are linked directly in the PR: [comment](https://github.com/pytorch/audio/pull/1029#issuecomment-727538189).

**Comment by forest1988** [comment]
Thank you for your kind comment!
I've just signed the CLA. I'll write about that in the PR, too.
