### ISSUE TITLE
CI: Nightly build is not running build_docs

### ISSUE THREAD

**Issue by mattip** [pytorch/audio#1031]
PR gh-1006 added `build_docs` and `upload_docs` jobs, the former is meant to run on every PR, merge, and nightly run, and the latter on nightly and tags. But the `build_docs` does not [run on nightly](https://app.circleci.com/pipelines/github/pytorch/audio/3868/workflows/b30f6af1-3252-4eaf-b81c-a8d6b230c43b) since it [requires `binary_linux_wheel_py3.8`](https://github.com/pytorch/audio/pull/1006/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R781) and not one of the nightly jobs. One alternative would be to have `build_docs_nightly` and `upload_docs_nightly` that duplicate the current ones but use `requires: nightly_binary_linux_wheel_py3.8`

**Comment by mthrok** [comment]
Closing as this is addressed in  #1033 and #1034.
