### ISSUE TITLE
Install from PyPI

### ISSUE THREAD

**Issue by xuhdev** [pytorch/audio#109]
Is this package available on PyPI? If so, can you add instructions to README?

**Comment by cpuhrsch** [comment]
Hey @xuhdev - we're currently working on adding better release engineering support for this library. This should also include pip.

**Comment by jamarshon** [comment]
Closing as we now have binaries on [conda](https://anaconda.org/pytorch/torchaudio), [pip](https://pypi.org/project/torchaudio/), and [nightlies](https://github.com/pytorch/audio#binaries)
