### ISSUE TITLE
SignalInfo in new AudioMetaData

### ISSUE THREAD

**Issue by RimaOlson** [pytorch/audio#1094]
Hi,
We're using `sox_io` backend for torchaudio. New version of the `AudioMetaData` class returned by the `info` method doesn't have all the data I need for analysis.
` info` method in the deprecated `sox` backend used to return `sox_signalinfo_t` and `sox_encodinginfo_t` that had much more detailed information about encoding, bit depth etc.
What should I use to get the info about audio file's encoding, bit depth and other details?

**Comment by vincentqb** [comment]
(since this is part of the BC-breaking change discussed in #903, cc @mthrok)

**Comment by mthrok** [comment]
Hi @RimaOlson 

Currently there is no way to get the other information using "sox_io" backend.
We made this decision because, exposing the internal of `libsox` makes it very difficult to maintain the backends across the different OS.

Having said that, could you give information of what type of attributes you are using as a form of feature request?
From there I can come up with a way to make it available again.

**Comment by RimaOlson** [comment]
@mthrok we use following attributes to ensure proper encoding of audio files before feeding them into our models:

```
sox_signalinfo_t.length
sox_encodinginfo_t.encoding
sox_encodinginfo_t.bits_per_sample
```

**Comment by mthrok** [comment]
> @mthrok we use following attributes to ensure proper encoding of audio files before feeding them into our models:
> 
> ```
> sox_signalinfo_t.length
> sox_encodinginfo_t.encoding
> sox_encodinginfo_t.bits_per_sample
> ```

Thanks @RimaOlson 

1. Could you tell, which value do you use for `encoding`?
    For the available values of `encoding`, you can see https://fossies.org/dox/sox-14.4.2/sox_8h.html#ab0a659b0258d1989c751ba5415e6a4cd 

2. `length` is the number of samples (across channels) so you should be able to get the number with `num_channels * num_frames`. Let me know if this is not the case.

**Comment by RimaOlson** [comment]
1. `encoding-> 1 (SOX_ENCODING_SIGN2) `and `encoding-> 9 (SOX_ENCODING_ULAW )`
2. So `num_frames` is the same as `sox_signalinfo_t.length` for `mono` files?

**Comment by mthrok** [comment]
@RimaOlson 

> 1. `encoding-> 1 (SOX_ENCODING_SIGN2) `and `encoding-> 9 (SOX_ENCODING_ULAW )`

Thanks

> 2. So `num_frames` is the same as `sox_signalinfo_t.length` for `mono` files?

Yes.

**Comment by mthrok** [comment]
@RimaOlson One more question about encoding. What formats (extensions) does your application expect?
I think there are formats other than WAV that are mapped to `SOX_ENCODING_SIGN2`, and would like to get a clearer vision if possible.

**Comment by RimaOlson** [comment]
@mthrok we use wav files

**Comment by mthrok** [comment]
Note to self: this is the corresponding encoding + bit depth part in PySoundFile 

https://github.com/bastibe/python-soundfile/blob/744efb4b01abc72498a96b09115b42a4cabd85e4/soundfile.py#L38-L94

**Comment by mthrok** [comment]
Note2: It is ideal that the mapping we create from [sox_encoding_t](https://fossies.org/dox/sox-14.4.2/sox_8h.html#ab0a659b0258d1989c751ba5415e6a4cd) to our custom type is generic enough to handle ffmpeg's ffmpeg's [AVCodecID enum](https://libav.org/documentation/doxygen/master/group__lavc__core.html#gaadca229ad2c20e060a14fec08a5cc7ce).

**Comment by mthrok** [comment]
Hi @RimaOlson

Can you illustrate what your `if` statement looks like when you use `sox_encodinginfo_t.encoding`?
I am wondering what the new data structure should look like. Strongly typed ENUM type or just string would do.

**Comment by mthrok** [comment]
@RimaOlson 

> @mthrok it will be something like this:
>  
> 
> ```
>    switcher = {
>         0: "SOX_ENCODING_UNKNOWN ",
>         1: "SOX_ENCODING_SIGN2",
>         2: "SOX_ENCODING_UNSIGNED",
>     …
>     }
> ```
> 

Thanks. Suppose, the type of format does not seem to matter. I will most likely pass as string.

> QQ: does `torchaudio.load` automatically transcode to linear by default?

I am not an audio expert so I am not sure if I understand the question correctly, but assuming "transcode to linear" means something like Linear PCM, I think the answer is yes.

`libsox` internally decode audio samples into 32bit signed integer [[doc](https://fossies.org/dox/sox-14.4.2/sox_8h.html#a233b12557ff42fb9bf5dd1545ec9f818)], which is what `torchaudio.load` is returning (with or without normalization to float32).

**Comment by RimaOlson** [comment]
@mthrok thank you. 
Yes, I did mean transcoding to Linear PCM from the original encoding. I'll take a look at `libsox`

**Comment by mthrok** [comment]
@RimaOlson 

FYI: For bit depth, we are adding `bits_per_sample` attribute in #1177.

**Comment by RimaOlson** [comment]
@mthrok Sounds good, thank you.

**Comment by mthrok** [comment]
Hi @RimaOlson 

Here is the mapping I am thinking to add. Let me know if this might not work for you.

SoX Representation | torchaudio Representation
-- | --
SOX_ENCODING_UNKNOWN | `"UNKNOWN"`
SOX_ENCODING_SIGN2 | `"PCM_S"`
SOX_ENCODING_UNSIGNED | `"PCM_U"`
SOX_ENCODING_FLOAT | `"PCM_F"`
SOX_ENCODING_ULAW | `"ULAW"`
SOX_ENCODING_ALAW | `"ALAW"`
SOX_ENCODING_MP3 | `"MP3"`
SOX_ENCODING_VORBIS | `"VORBIS"`
SOX_ENCODING_AMR_WB | `"AMR_WB"`
SOX_ENCODING_AMR_NB | `"AMR_NB"`
SOX_ENCODING_OPUS | `"OPUS"`

**Comment by RimaOlson** [comment]
@mthrok above list looks good, thank you.

**Comment by mthrok** [comment]
@RimaOlson I have merged #1206, which adds `encoding` attribute to `AudioMetaData` class. This will become available in tomorrow's nightly build. Please try it out and let me know if this works.

**Comment by mthrok** [comment]
@RimaOlson Did you have time to try it out? Let me know if it is not working as you expected.

**Comment by RimaOlson** [comment]
Thank you @mthrok , I checked out the nightly build. Tested the `pcm` and `mulaw`, they look good. Still trying to test OPUS and MP3. The issue might that it's more of a `sox` issue than `torchaidio`.

**Comment by RimaOlson** [comment]
Actually I looked at the headers with ffmpeg, it looks the same as in `AudioMetaData.encoding`. When can it be merged into master?

**Comment by mthrok** [comment]
Hi @RimaOlson 

It's been merged to master and it will be released as part of 0.8 soon. We expect the release to happen early March.

**Comment by mthrok** [comment]
Closing the issue. If you find something, please open a a new one. Thanks for the feedback!

**Comment by RimaOlson** [comment]
Thanks a lot @mthrok !
