### ISSUE TITLE
Remove `walk_files`

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1109]
Thanks to @krishnakalyan3, all the dataset implementations no longer uses `walk_files`. We can remove this by removing the following codes.

After removing, the following test should pass.

```
pytest test/torchaudio_unittest/datasets/
```

https://github.com/pytorch/audio/blob/7a3e15bc54d42081699da186e58d76143a30fae9/torchaudio/datasets/utils.py#L250-L283

https://github.com/pytorch/audio/blob/7a3e15bc54d42081699da186e58d76143a30fae9/test/torchaudio_unittest/datasets/utils_test.py#L14-L49

**Comment by 1nF0rmed** [comment]
Hey!, I would like to work on this

**Comment by 1nF0rmed** [comment]
I've made a PR #1112

**Comment by vincentqb** [comment]
- Closing this issue will close #1051.
- Let's flag this as BC-breaking (even though I'd guess the risk low).

**Comment by mthrok** [comment]
@1nF0rmed There was another PR submitted by @AzizCode92, slightly earlier than yours so I merged it. Sorry about that, but still thanks for the contribution.
