### ISSUE TITLE
Remove deprecated transform from Dataset

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1118]
VCTK and YesNo dataset have `transform` and `target_transform` arguments which have been deprecated over  AFAIK at least two releases, so we can get rid of them.

* (If you are interested in working on, please leave a comment so that other people will not do duplicated work.)
* When you make a PR, please, set title `[BC-Breaking] ...`
* Once the code is updated, the following test should pass.
    
    ```python
    pytest test/torchaudio_unittest/datasets -vs
    ```

https://github.com/pytorch/audio/blob/be442561a538b1ecc73394eeba610c8a7e2b7f4a/torchaudio/datasets/vctk.py#L95-L100

https://github.com/pytorch/audio/blob/be442561a538b1ecc73394eeba610c8a7e2b7f4a/torchaudio/datasets/yesno.py#L58-L63

**Comment by aadarsh10c** [comment]
Hey @mthrok , i am ready to work on this issue... 
I  will only have to remove line 95-100 from vctk.py  and line 58-63 from yesno.py ,

> * Once the code is updated, the following test should pass.
>   ```python
>   pytest test/torchaudio_unittest/datasets -vs
>   ```
Also i am not familiar with ML and its packages , will i have to perform the tests as well.

**Comment by mthrok** [comment]
Hi @aadarsh10c 

Thanks for the help. 

> I will only have to remove line 95-100 from vctk.py and line 58-63 from yesno.py ,

well, you need to remove the corresponding arguments from the class constructor, and the logic that uses these arguments too.

> Also i am not familiar with ML and its packages , 

This task does not require any ML specific knowledge, just a regular software engineering stuff.
That is;
  - instaling Python environment and dependencies (PyTorch)
  - cloning torchaudio (for this specific task, you should be able to do it without building torchaudio)
  - making changes
  - running test (run the test command from the root directory of the repository)
  - pushing changes
  - making PR
  - asking for review (tag @mthrok as a reviewer)
 
> will i have to perform the tests as well.

When you make a PR, these tests run automatically, so you can rely on that too, but you have to wait like 10 mins every time you push a commit. If you run the test locally, then you get the result with in few seconds.

**Comment by AzizCode92** [comment]
I can work on this issue.

**Comment by mthrok** [comment]
@aadarsh10c 

@AzizCode92 has created the PR #1120 however, since you raised hand first, I would like to honor your efforts too. Would you still want to work on this? 


@AzizCode92 

Thanks for the contribution but but let me wait for @aadarsh10c first.

**Comment by AzizCode92** [comment]
@mthrok
Sure, no problems.

**Comment by aadarsh10c** [comment]
I saw #1122 , I think I still require some knowledge before I work on this type o issues, anyways thanks for consideration, if there is any other way I can help let me know. 😀

**Comment by mthrok** [comment]
@aadarsh10c 

I see, then I will proceed with @AzizCode92 PR #1122.

If you are new to GitHub open source contribution workflow, there is a bunch of tutorials like this https://www.dataschool.io/how-to-contribute-on-github/
