### ISSUE TITLE
[Doc] the return type for load functions are wrong

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1119]
## 📚 Documentation

The return type of `load` functions (`"sox_io"` backend and `"soundfile"` backend) are wrong.

https://github.com/pytorch/audio/blob/be442561a538b1ecc73394eeba610c8a7e2b7f4a/torchaudio/backend/sox_io_backend.py#L110-L113

https://github.com/pytorch/audio/blob/be442561a538b1ecc73394eeba610c8a7e2b7f4a/torchaudio/backend/_soundfile_backend.py#L107-L110

They should be `tuple of torch.Tensor and int`, instead of just torch.Tensor.

For the description of `torch.Tensor`, keep the current description. For `int`, add the description that says it's sample rate.

Check out https://github.com/pytorch/audio/issues/1002 for how to build the documentation.

When you make a PR, please attach a screen shot of the resulting documentation.

**Comment by AzizCode92** [comment]
I can work on this issue.

**Comment by mthrok** [comment]
@AzizCode92 

Sure, thanks. Let me know if you need help in building documentation.
This is very high-impact fix.

**Comment by AzizCode92** [comment]
Hi @mthrok, I made the change inside the documentation of the methods, did the steps as described here #1002.
But I got always the old documentation displayed in my browser. 
I did the following change 
```
Returns:
        Tuple[torch.Tensor, int]:
        torch.Tensor:
            If the input file has integer wav format and normalization is off, then it has
            integer type, else ``float32`` type. If ``channels_first=True``, it has
            ``[channel, time]`` else ``[time, channel]``.
        int: sample rate
```

**Comment by mthrok** [comment]
Hi @AzizCode92 

Probably you have a pip/conda package installation of torchaudio somewhere in your system and when you do `make html`, the changes you added to the repo is not picked up.

If that's the case, you can do either
1. remove the package installation
2. at the beginning of `docs/source/conf.py` before `import torchaudio`, modify `sys.path` list object and insert the repository root at the beginning of the list.

**Comment by AzizCode92** [comment]
Hi, @mthrok, is it ok? 
<img width="731" alt="Screen Shot 2020-12-23 at 17 25 01" src="https://user-images.githubusercontent.com/19540527/103017556-135eba80-4544-11eb-9945-7562af929a52.png">

**Comment by mthrok** [comment]
> Hi, @mthrok, is it ok?
> <img alt="Screen Shot 2020-12-23 at 17 25 01" width="731" src="https://user-images.githubusercontent.com/19540527/103017556-135eba80-4544-11eb-9945-7562af929a52.png">

Hi @AzizCode92 

Look good, but please change description of `int:` from `sample_rate` something else like `Sample rate of the audio`.

**Comment by AzizCode92** [comment]
Hi @mthrok, done. 
I have created a PR (#1122), please review it.
thank you.
