### ISSUE TITLE
`format` arg missing in new soundfile backend.

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1128]
In #1104, the new `format` argument was added to `load` and `info` function of `sox_io` and `soundfile (new interface)` backend.

But #1104 forgot to add the same argument to the `info` function of `soundfile (new interface)`.

For the consistency of backends, `format` argument has to be present in `soundfile (new interface)` too.

1. Add `format: Optional[str] = None,` to https://github.com/pytorch/audio/blob/9c484027147cf90a253ad52c4f24a814b74125d7/torchaudio/backend/_soundfile_backend.py#L15
2. Copy the docstring https://github.com/pytorch/audio/blob/9c484027147cf90a253ad52c4f24a814b74125d7/torchaudio/backend/_soundfile_backend.py#L103-L104

Note, in `_soundfile` backend, the new argument is not used, as the PySoundFile does not have format-hinting mechanism.

**Comment by AzizCode92** [comment]
@mthrok, I can work on this.

**Comment by mthrok** [comment]
Closed via #1129
