### ISSUE TITLE
Improve Dataset utility test

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1130]
There are couple of improvements we can make for dataset utility test.

https://github.com/pytorch/audio/blob/71214b48548b1dcb6ebd581dd36a9d0e60af6837/test/torchaudio_unittest/datasets/utils_test.py#L12-L36 

1. Use temporary directory for cache
    `test_disckcache_iterator` creates cache directory at working directory which does not get cleaned up. To improve this, one should use temporary directory for the `location` argument in `diskcache_iterator`. 
    To do this,
    1. Subclass the test suite with [`TempDirMixin`](https://github.com/pytorch/audio/blob/master/test/torchaudio_unittest/common_utils/case_utils.py#L14-L40)
    2. Use `self.get_temp_path()` to get a temporary directory.
    3. Pass the temporary directory to `location` argument.
    
2. Make utility test not depend on an Dataset class
    CommonVoice dataset is another library code that can be broken anytime. The fact that utility test depends on both utility and another component from the library makes it confusing what is the cause when this test fails. Therefore CommonVoice should not be used in this test suite.
    The workaround is to define a simple dataset for this test suite. Something as simple as the following would do
    ```python
    class Dataset(torch.utils.data.Dataset):
        def __getitem__(self, n):
            return torch.randn(32, 2, 256)
    ```

**Comment by AzizCode92** [comment]
I can work on this.
