### ISSUE TITLE
Expose `center` argument of Spectrogram and derivative transforms

### ISSUE THREAD

**Issue by RuABraun** [pytorch/audio#1155]
## 🚀 Feature

At the moment `center=True` is hardcoded inside `torchaudio.transforms.Spectrogram`. I think it would be nice to expose this as a parameter.

## Motivation

If one is doing anything where frame alignment matters the current default can mess things up. Doing the change would be very easy so I don't see why not. I'd be willing to do it.

## Pitch

Add `center` parameter to `Spectrogram` and pass to `stft` call, also requires adding to functional interface. Maybe also add to derivatives. Like I said I could do it.

**Comment by mthrok** [comment]
HI @RuABraun 

Sorry for the late response.
This sounds like a valid proposal.
I am not sure what `also add to derivatives` means, but please open a PR.
(and let me know if you no longer have time for that, I will find someone else who can work on it.)

**Comment by mthrok** [comment]
Actually #892 seems to resolve this. Let me merge that one.

**Comment by mthrok** [comment]
Closed via #892
