### ISSUE TITLE
Replace pytest's paremeterization with parameterized

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1156]
If you are interested working on this, please leave a comment here (so that other people will not do a duplicated work), then create a PR and tag @mthrok.

---

For historical and technical reasons, torchaudio's test suite cannot use `pytest` as a module. (we still use it as a runner in CircleCI, which is fine.)

There are couple of pytest utilities used in torchaudio's test code.

https://github.com/pytorch/audio/blob/6b07bcf80fafd77cb8bee32c316ce8b55323b868/test/torchaudio_unittest/functional/functional_cpu_test.py#L115-L163

We would like to replace `pytest.mark.parametrize` with `parameterized` module like the following

https://github.com/pytorch/audio/blob/3250d3df168c956389bd16956aa458ce111570d0/test/torchaudio_unittest/sox_compatibility_test.py#L305-L310

Steps
1. Convert the test function into test class using `TorchaudioTestCase`
2. In test method, use `parameterized.expand`
3. Additionally, when generating a tensor with random values, do it in the method and set the seed value first so that the test is more deterministic.

**Comment by krishnakalyan3** [comment]
@mthrok I would be happy to work on this.

**Comment by mthrok** [comment]
@krishnakalyan3 sure. thanks!
