### ISSUE TITLE
Add `bits_per_sample` to `info`

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1173]
The legacy sox backend exposed libsox's structures (`sox_signalinfo_t` and `sox_encodinginfo_t`) and that allowed to access most of audio metadata. In the transition to the new backends, these structures were abstracted away and introduced `AudioMetaData` which only contain very basic information. 

Now we would like to add some metadata, in this time, with more consistent behaviors across the backends.

First, we can add `bits_per_sample` attribute. (See also https://github.com/pytorch/audio/issues/1094)
 
## Steps
Here is the gist of how we can add that.
### sox_io backend
1. the core of `info` function is implemented [here](https://github.com/pytorch/audio/blob/master/torchaudio/csrc/sox/io.cpp#L33-L50). In this function `sf->encoding.bits_per_sample` contains the `bits_per_sample` information. See also [sox_format_t](https://fossies.org/dox/sox-14.4.2/structsox__format__t.html).
2. Add `bits_per_sample` to `SignalInfo` class and getter. ([interface](https://github.com/pytorch/audio/blob/master/torchaudio/csrc/sox/io.h#L14-L26), [implementation](https://github.com/pytorch/audio/blob/7a36c5573d4fac310d694ab758052f8d5aa55ed3/torchaudio/csrc/sox/io.cpp#L13-L31))
`SignalInfo` class is the structure passed from C++ code to Python.
3. Add `bits_per_sample` to [`AudioMetaData` class](https://github.com/pytorch/audio/blob/master/torchaudio/backend/common.py#L6-L19)
This will allow client code to fetch the resulting `bits_per_sample` attributed.
4. Update [`info` function](https://github.com/pytorch/audio/blob/master/torchaudio/backend/sox_io_backend.py#L13-L35
) to pass the `bit_per_sample` from `SignalInfo` to `AudioMetaData`.

### soundfile backend
1. Update the `info` func to add the `bit_per_sample` data to `AudioMetaData`
The caveat is that `PySoundFile` does not have exact equivalent of `bit_per_sample` information. So we need to figure it out. I think we can create a mapping from [`subtypes`](https://github.com/bastibe/python-soundfile/blob/master/soundfile.py#L66-L94) to `bit_per_sample` (integer). We still need to figure out the detail for some of the formats, like vorbis. or we can leave the `bit_per_sample = 0` for the case where we cannot figure out or if there is no good definition of `bit_per_sample` for a given format. (we need to check with how libsox handles and make sure that the behavior is consistent.)

### testing 
With the addition to `bits_per_sample`, the info tests need to be updated.
- [`sox_io`](https://github.com/pytorch/audio/blob/7a36c5573d4fac310d694ab758052f8d5aa55ed3/test/torchaudio_unittest/sox_io_backend/info_test.py)
- [`soundfile`](https://github.com/pytorch/audio/blob/7a36c5573d4fac310d694ab758052f8d5aa55ed3/test/torchaudio_unittest/soundfile_backend/info_test.py)

## Building

To work on this, `torchaudio` needs to be built from source. Use of `conda` environment (anaconda/miniconda) is highly recommended.

Also, build requires `cmake` and nightly build version of PyTorch. Refer to pytorch.org for the installation.
To install `cmake`, do `pip install cmake`.

Once the environment is setup, the following command will build and run the corresponding tests

```
BUILD_SOX=1 python setup.py develop
(cd test && pytest torchaudio_unittest -v -k "info_test"
```

**Comment by NicolasHug** [comment]
I'll take a stab at this
