### ISSUE TITLE
support on windows

### ISSUE THREAD

**Issue by QHenry1990** [pytorch/audio#1178]
## To Reproduce

1. I use wheel pip in windows when I install torchaudio,but load mp3 file is failed, unsupported format. version torchaudio 0.7.0
1.
1.

## Environment

 - What commands did you used to install torchaudio (conda/pip/build from source)?
 - If you are building from source, which commit is it?
 - What does `torchaudio.__version__` print? (If applicable)

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by QHenry1990** [comment]
it is rewrited#394

**Comment by mthrok** [comment]
Hi @QHenry1990 

Currently mp3 is not supported on Windows. We plan to add support for mp3 on Windows, but it will take some time. If you are simply loading then you can use other libraries like [miniaudio](https://pypi.org/project/miniaudio/) to load audio into NumPy array, then convert it to PyTorch tensor. `torch.from_numpy`. If you are trying to load TED-LIUM dataset, then you need to overwrite [TEDLIUM._load_audio](https://github.com/pytorch/audio/blob/72b768033c5a3910f619550100d248d96eb7aefa/torchaudio/datasets/tedlium.py#L141-L160) method to do the same.

**Comment by vincentqb** [comment]
Thanks for reporting this :) As pointed out above, mp3 is not yet available. Since we already have #425 opened, I'll close this, but feel free to re-open if this doesn't address your concern.
