### ISSUE TITLE
Error building torchaudio: /torchaudio/csrc/sox/register.cpp:5:23: error: expected constructor, destructor, or type conversion before ‘(’ token

### ISSUE THREAD

**Issue by cocolacre** [pytorch/audio#1179]
Setup: windows 10, WSL
Command: python3 -m pip install git+https://github.com/pytorch/audio
Error:
    /tmp/pip-req-build-8whigxa0/torchaudio/csrc/sox/register.cpp:5:23: error: expected constructor, destructor, or type conversion before ‘(’ token
     TORCH_LIBRARY_FRAGMENT(torchaudio, m) {
                           ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Thank you

**Comment by mthrok** [comment]
Hi @cocolacre 

Which version of PyTorch are you using? `TORCH_LIBRARY_FRAGMENT` was added kind of recent, so you need the latest PyTorch. (I think 1.7 at minimum.)
(Torchaudio's C++ extension is not supported on Windows, but I assume it works on WSL)

**Comment by mthrok** [comment]
Closing as I assume this is about the mismatched PyTorch version. Feel free to re-open if that's not the case.
