### ISSUE TITLE
Adding target `dtype` argument to `save` function

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1197]
In `"sox_io"` backend and `"soundfile"` backend with new interface, when saving a Tensor to file with`save` function, it is expected to that client code converts the Tensor to the dtype with desired precision. It was pointed out that this is somewhat inconvenient and `save` function should handle type conversion for improved UX. (See #903)

To address this, we would like to add a new parameter `dtype` to `save` function so that dtype conversion is handled by `save` function.

## Specification

- `dtype` is optional string type, valid values are (`"uint8"`, `"int16"`, `"int32"`, `"float32"` and `None`)
- `dtype=None` means no conversion is performed.
- `dtype` parameter is only effective for float Tensor.
  - If user provide a Tensor with other dtype, (like `uint8`), `dtype` parameter is ignored and no conversion is performed.

In release 0.8
- The default value of `dtype` is `None`, for the sake of backward compatibility.

In release 0.9
- The default value of `dtype` is changed to `int16`.

## Migration plan

<table class="tg">
<thead>
  <tr>
    <th class="tg-4e34" colspan="3"><span style="font-weight:600">Release</span></th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-q7lb">0.7</td>
    <td class="tg-q7lb">0.8 (Default to `dtype=None`)</td>
    <td class="tg-q7lb">0.9 (Default to `dtype=int16`)</td>
  </tr>
  <tr>
    <td class="tg-q7lb">The precision of saved audio <br>depends on the input Tensor dtype.</td>
    <td class="tg-q7lb"><ul>
<li>`dtype` parameter is added to `save` function</li>
<li>If the input Tensor is float type and `dtype` is `None`, <br>&nbsp;&nbsp;&nbsp;then issue warning saying the default value will be changed to `int16`.</li>
</ul></td>
    <td class="tg-q7lb"> `dtype` parameter defaults to `int16`.</td>
  </tr>
</tbody>
</table>

### "sox_io" backend

Addressed in #1204 
See the [comment](https://github.com/pytorch/audio/issues/1197#issuecomment-768548251)

### "soundfile" backend

1. Add `dtype` parameter to `save` functions of [`"soundfile"` backend with new interface](https://github.com/pytorch/audio/blob/674a71d1a239fd6bf48d5797053590f593efff08/torchaudio/backend/_soundfile_backend.py#L183-L191). Set the default value of `dtype` parameter to `None`.
2. Update [the part it figures out subtype](https://github.com/pytorch/audio/blob/674a71d1a239fd6bf48d5797053590f593efff08/torchaudio/backend/_soundfile_backend.py#L239-L252), so that if the input Tensor is floating type and `dtype` is provided, then subtype is overwritten.
3. Add warning when the input Tensor's `dtype` is `float32` and `dtype` parameter is not given (`None`), saying that the default value will be changed to `dtype='int16'` in `0.9` release.  You can use the same message as ["sox_io" backend](https://github.com/pytorch/audio/blob/674a71d1a239fd6bf48d5797053590f593efff08/torchaudio/backend/sox_io_backend.py#L255-L259)

### soundfile backend

The [`save_test.py`](https://github.com/pytorch/audio/blob/674a71d1a239fd6bf48d5797053590f593efff08/test/torchaudio_unittest/soundfile_backend/save_test.py) needs to be updated.

1. Define a new test method under [`TestSave` class](https://github.com/pytorch/audio/blob/674a71d1a239fd6bf48d5797053590f593efff08/test/torchaudio_unittest/soundfile_backend/save_test.py#L158)
2. Parameterize the target dtype value and perform `soundfile_backend.save` with mocked `soundfile.write` function
3. Check that the `subtype` argument which `soundfile.write` function received is the expected value.

### Build

To work on this, `torchaudio` needs to be built from source. Use of `conda` environment (anaconda/miniconda) is highly recommended.

Also, build requires `cmake` and nightly build version of PyTorch. Refer to pytorch.org for the installation.
To install `cmake`, do `pip install cmake`.

Once the environment is setup, the following command will build and run the corresponding tests

```
BUILD_SOX=1 python setup.py develop
(cd test && pytest torchaudio_unittest/soundfile_backend/save_test -v -k "<name of the test you added>"
```

**Comment by carolineechen** [comment]
@mthrok I can work on this

**Comment by mthrok** [comment]
> @mthrok I can work on this

@carolineechen Thanks. Let me know if you need help.

**Comment by mthrok** [comment]
## An alternative approach

Following the offline discussion with @carolineechen, I noticed that we do not need custom un-normalization function. We can just change the part sox converts the internal representation (int32_t) to target encoding.

## Steps
1. Add target `dtype` to 
    - [`save`](https://github.com/pytorch/audio/blob/47d97e30c36d6b5baef166664cbfb057470c39fd/torchaudio/backend/sox_io_backend.py#L193-L251)
    - `save_audio_file` [[header](https://github.com/pytorch/audio/blob/47d97e30c36d6b5baef166664cbfb057470c39fd/torchaudio/csrc/sox/io.h#L43-L49), [impl](https://github.com/pytorch/audio/blob/47d97e30c36d6b5baef166664cbfb057470c39fd/torchaudio/csrc/sox/io.cpp#L104-L110)]
    - `save_audio_fileobj` [[header](https://github.com/pytorch/audio/blob/47d97e30c36d6b5baef166664cbfb057470c39fd/torchaudio/csrc/sox/io.h#L65-L71), [imp](https://github.com/pytorch/audio/blob/47d97e30c36d6b5baef166664cbfb057470c39fd/torchaudio/csrc/sox/io.cpp#L236-L242)]
2. Change the `encoding_info` to have target dtype (if given) or the native dtype.
In [`save_audio_file`](https://github.com/pytorch/audio/blob/47d97e30c36d6b5baef166664cbfb057470c39fd/torchaudio/csrc/sox/io.cpp#L127-L128) and [`save_audio_fileobj`](https://github.com/pytorch/audio/blob/47d97e30c36d6b5baef166664cbfb057470c39fd/torchaudio/csrc/sox/io.cpp#L256-L257), replace `tensor.dtype()` with a logic to use the given dtype or tensor's dtype. (Add a helper function to convert `std::string` to `caffe2::TypeMeta`, which will be similar to [`get_dtype` function](https://github.com/pytorch/audio/blob/47d97e30c36d6b5baef166664cbfb057470c39fd/torchaudio/csrc/sox/utils.cpp#L130-L157))

**Comment by mthrok** [comment]
Closing as I need to reconsider the approach for clean interface and proper mapping to encodings and bits.
