### ISSUE TITLE
Expose stft arguments to MelSpectorgram

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1203]
In #892, arguments for `stft` have been added to `torchaudio.transform.Spectrogram` constructor. We can further extend it to `MelSpectrogram`, which simply reuses `torchaudio.transform.Spectrogram`.

## Steps

1. Update the [`MelSpectrogram.__init__`](https://github.com/pytorch/audio/blob/47d97e30c36d6b5baef166664cbfb057470c39fd/torchaudio/transforms.py#L421-L433) 
  * Add the arguments [[src](https://github.com/pytorch/audio/blob/47d97e30c36d6b5baef166664cbfb057470c39fd/torchaudio/transforms.py#L69-L71)], pass them to [`Spectrogram.__init__`](https://github.com/pytorch/audio/blob/47d97e30c36d6b5baef166664cbfb057470c39fd/torchaudio/transforms.py#L445-L448)
  * Update the docstring [[src](https://github.com/pytorch/audio/blob/47d97e30c36d6b5baef166664cbfb057470c39fd/torchaudio/transforms.py#L50-L56)]

2. Add a smoke test that confirms that the `MelSpectrogram` transform with the combinations of these new parameters do not crush.

**Comment by jieruan02** [comment]
I was trying this task and did the step1, but wasn't familiar about how smoke test should be written. 

do I add some additional checks in test_melspectrogram_load_save()? or
should I do something similar to the class SmokeTest() as in https://github.com/pytorch/audio/blob/3250d3df168c956389bd16956aa458ce111570d0/test/torchaudio_unittest/sox_io_backend/smoke_test.py?

**Comment by jieruan02** [comment]
I can work on this. but I am not familiar with how smoke test should be written, do you add test inside the test_transform or do  I need to do a SmokeTest class as in https://github.com/pytorch/audio/blob/3250d3df168c956389bd16956aa458ce111570d0/test/torchaudio_unittest/sox_io_backend/smoke_test.py?

**Comment by mthrok** [comment]
Hi @jieruan02 

You can add classes `MelSpectrogramTest` and `SpectrogramTest` in [`transforms_test.py`](https://github.com/pytorch/audio/blob/master/test/torchaudio_unittest/transforms_test.py) and add method like `smoke_test` in each of them.

**Comment by jieruan02** [comment]
Hi @mthrok, thank you for the hint! Also is there any local test we should run before making a PR instead of letting the ci do all the checks after submission?

**Comment by jieruan02** [comment]
There were some minor issues and I figured them out. now it should be correct, let me know what you think~ Thank you!
