### ISSUE TITLE
Add ITU-R BS.1770-4 Loudness

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/audio#1205]
## 🚀 Feature

Implement a standard algorithm for computing audio loudness, like ITU-R BS.1770-4.

## Motivation

Audio loudness is an important feature for representing audio. For example, it's used in this popular library: https://github.com/magenta/ddsp

## Pitch

Here is a `numpy` implementation of ITU-R BS.1770-4. It'd be helpful to have this translated to PyTorch and included in this library: https://github.com/csteinmetz1/pyloudnorm/blob/master/pyloudnorm/meter.py

Here is the official loudness implementation from the original paper: https://github.com/BrechtDeMan/loudness.py/blob/master/loudness.py

**Comment by mthrok** [comment]
Hi @PetrochukM 

Sounds good idea. Couple of clarification questions;
1. What are the differences between the csteinmetz1 implementation and BrechtDeMan?
2. Are these implementations work for float dtype within the range of [-1.0, 1.0] or do they expect integer type?
3. What is the equivalent found in DDSP? Is the API there good to follow?

**Comment by PetrochukM** [comment]
Thanks for the questions:

1. "csteinmetz1" includes multiple loudness implementations, including "BrechtDeMan". They have a `filter_class` called "DeMan".
2. They both expect floating `dtype` for the audio.
3. a. In DDSP, they implemented loudness here: https://github.com/magenta/ddsp/blob/5a06bced8e4b2f77aabe418d07f7279fe237daff/ddsp/spectral_ops.py#L184
    Their loudness implementation is A-weighted, instead of K-weighted, like in ITU-R BS.1770-4. They also calculate loudness with a spectrogram, instead of the raw audio. Either way, the calculation of loudness can be done either way, equivalently. They also don't filter out quiet frames before calculating the audio loudness, as recommended in ITU-R BS.1770-4. 
3. b. I have not used their API in the past, so I don't have a good gauge of its effectiveness. Their library is only "used by" 5 people based on Github statistics.
