### ISSUE TITLE
[Refactor] Simplify C++ interface for sox_io's `info` func

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1219]
Currently, `torchaudio.info` function for `"sox_io"` backend gets the information via `SignalInfo` structure in C++.

https://github.com/pytorch/audio/blob/828df46a95310453dda13599a29fa22a1cc049da/torchaudio/csrc/sox/io.h#L14-L32

The signature of the actual function that performs querying looks like following;

https://github.com/pytorch/audio/blob/828df46a95310453dda13599a29fa22a1cc049da/torchaudio/csrc/sox/io.h#L34-L36

When binding this function (making it available on Python), the `SignalInfo` structure has to be bound before the function. When updating the `info` function, this forces updating multiple components.

Also the recently added function that performs the same operation on file-like object, which is bound via PyBind11, simplifies this via directly returning tuple object.

https://github.com/pytorch/audio/blob/828df46a95310453dda13599a29fa22a1cc049da/torchaudio/csrc/sox/io.h#L57-L59

`get_info_file` should also do the same and return tuple object directly.

## Steps

1. Change the interface / implementation of `torchaudio.info`
    1. `get_info_file` to return the tuple. The implementation should be swapped from [this](https://github.com/pytorch/audio/blob/828df46a95310453dda13599a29fa22a1cc049da/torchaudio/csrc/sox/io.cpp#L93-L98) to [this](https://github.com/pytorch/audio/blob/828df46a95310453dda13599a29fa22a1cc049da/torchaudio/csrc/sox/io.cpp#L245-L250)
    2. Update the Python frontend. [The construction of AudioMetaData](https://github.com/pytorch/audio/blob/828df46a95310453dda13599a29fa22a1cc049da/torchaudio/backend/sox_io_backend.py#L23-L29) should be replaced with [the one with tuple destruction](https://github.com/pytorch/audio/blob/828df46a95310453dda13599a29fa22a1cc049da/torchaudio/backend/sox_io_backend.py#L21).
2. Remove [the registration](https://github.com/pytorch/audio/blob/828df46a95310453dda13599a29fa22a1cc049da/torchaudio/csrc/sox/register.cpp#L42-L49).
3. Remove [the interface](https://github.com/pytorch/audio/blob/828df46a95310453dda13599a29fa22a1cc049da/torchaudio/csrc/sox/io.h#L14-L32) and [the implementation](https://github.com/pytorch/audio/blob/828df46a95310453dda13599a29fa22a1cc049da/torchaudio/csrc/sox/io.cpp#L13-L43) of `SignalInfo`.

## Building and Testing

1. Install nightly build of PyTorch
2. Clone repo and build torchaudio
    ```
    # mac
    BUILD_SOX=1 MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py develop
    # linux
    BUILD_SOX=1 python setup.py clean develop
    ```
3. Set `PATH` variable so that the `sox` command created as a part of torchaudio build process is used.
    `export PATH="<path_to_torchaudio>/third_party/install/bin:${PATH}"`
4. Run test
    Run test with `pytest test/torchaudio_unittest/sox_io_backend -v`, this should pass after each step 1, 2 and 3.

**Comment by prabhat00155** [comment]
I can work on this.

**Comment by mthrok** [comment]
> I can work on this.

@prabhat00155 

Thanks. Let me know if you need help.

**Comment by prabhat00155** [comment]
@mthrok The PR has been merged and this issue can be closed now, thanks!

**Comment by mthrok** [comment]
Thanks for the contribution!
