### ISSUE TITLE
Add torchaudio.datasets.AudioFolder to load audio files from a local directory

### ISSUE THREAD

**Issue by cassieview** [pytorch/audio#1220]
## 🚀 Feature
This feature would allow you to pass in a path and other optional parameters to load data from a local file path when working with audio data. Currently you have to build your own method to do this. It was inspired by the `torchvision.datasets.ImageFolder` convention. 

## Motivation

When I was working with `torchaudio` I looked for similar functionality that the `torchvision` library has with `ImageFolder`, however it didn't exist. Adding `torchaudio.datasets.AudioFolder` follows the same pattern found in torchvision and makes it consistent across libraries.  I am currently working on tutorials around torchaudio and this simplifies the code for my tutorials and blogs.

## Pitch

Below is how I propose the solution to work:
For more implementation check out the code in the [PR 1215](https://github.com/pytorch/audio/pull/1215)

![image](https://user-images.githubusercontent.com/46505951/106518379-69a60e00-649f-11eb-876c-d3fbb18cb24c.png)

## Additional context

I already created a simple PR. Happy to look at expanding on the functionality here if needed.
[PR 1215](https://github.com/pytorch/audio/pull/1215)

**Comment by mthrok** [comment]
Hi @cassieview 

 - Can you describe the goal that the proposed data set is trying to solve? The PR doesn't explain the design behind it.
 - What data directory structure is this data set expected to handle and what not?
 - What is the expected task? The problem I see is that the current implementation only works on audio classification task, and giving such a generic name as `AudioFolder` feels misnomer.

For the arguments;
 - Like I commented on #1215, from the usage above, it is not immediately clear why `label` has to be a constructor argument if the entire dataset is the same label.
 - Also the `spectrogram_transform` is very restrictive as users their preference on how spectrogram is computed.

The proposal sounds fits better for a dataset that is dedicated for tutorial purpose, which is very simple.

**Comment by Ezraorich** [comment]
where I can find the code for AudioFolder extension? I really need this for loading audio files as a dataset. thanks

**Comment by mthrok** [comment]
> where I can find the code for AudioFolder extension? I really need this for loading audio files as a dataset. thanks

See #1215
