### ISSUE TITLE
[Refactor] Move TorchScript tests for functional to dedicated directory.

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1231]
The number of unit tests we have in torchaudio has grown a lot. It is critical to keep tests organized so as to make it easy for contributors to write tests for the feature they are working on.

TorchScript consistency tests are for validating that the execution results are same between Python eager mode and TorchScript runtime. We put all the tests in [test/torchaudio_unittest/torchscript_consistency_impl.py](https://github.com/pytorch/audio/blob/3651412bbcb0c4faf56bc7be7fe5e5ae2a7a63fd/test/torchaudio_unittest/torchscript_consistency_impl.py)(definitions of tests that are common for CPU and CUDA), [test/torchaudio_unittest/torchscript_consistency_cpu_test.py](https://github.com/pytorch/audio/blob/3651412bbcb0c4faf56bc7be7fe5e5ae2a7a63fd/test/torchaudio_unittest/torchscript_consistency_cpu_test.py) and [test/torchaudio_unittest/torchscript_consistency_cuda_test.py](https://github.com/pytorch/audio/blob/3651412bbcb0c4faf56bc7be7fe5e5ae2a7a63fd/test/torchaudio_unittest/torchscript_consistency_cuda_test.py). As the list of ops in `torchaudio.functional` grows, we have a dedicated directory for functional tests, [test/torchaudio_unittest/functional](https://github.com/pytorch/audio/blob/3651412bbcb0c4faf56bc7be7fe5e5ae2a7a63fd/test/torchaudio_unittest/functional). Moving the TorchScript consistency tests for functional to the directory better decouples the test module.

## Steps
1. Create the equivalent of `torchscript_consistency_impl.py`, `torchscript_consistency_cpu_test.py` and `torchscript_consistency_cuda_test.py` in [test/torchaudio_unittest/functional](https://github.com/pytorch/audio/blob/3651412bbcb0c4faf56bc7be7fe5e5ae2a7a63fd/test/torchaudio_unittest/functional) directory.
2. Move the tests for `functional` from the original location to the newly created scripts.

## Testing

1. Install nightly build of PyTorch
2. Clone repo and build torchaudio
3. Run test
    Run test with `pytest test/torchaudio_unittest/functional -v`

**Comment by jieruan02** [comment]
I will give it a try

**Comment by mthrok** [comment]
@jieruan02 

Thanks. Let me know if you need help.

**Comment by jieruan02** [comment]
The flakey test you mentioned seems appear again. How should I rerun the test? the rerun botton is disable as I don't have write permission, so I always close the PR and make a new PR from my fork to rerun...

**Comment by mthrok** [comment]
> The flakey test you mentioned seems to appear again. How should I rerun the test? the rerun botton is disable as I don't have write permission, so I always close the PR and make a new PR from my fork to rerun...

Rerunning test does not require write permission. You need to wait until all the jobs finish.

**Comment by jieruan02** [comment]
> > The flakey test you mentioned seems to appear again. How should I rerun the test? the rerun botton is disable as I don't have write permission, so I always close the PR and make a new PR from my fork to rerun...
> 
> Rerunning test does not require write permission. You need to wait until all the jobs finish.

oh, I found I can rerun by git commit --amend and then push again the branch, not sure if this is the way you meant.

previously I was trying to use the rerun button on [test_result] (https://app.circleci.com/pipelines/github/pytorch/audio/4823/workflows/ca91bee1-f064-4490-af88-9f1159f9c4ee/jobs/155395), that's where I got the disabled...
