### ISSUE TITLE
[Refactor] Move batch tests for functional to dedicated directory

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1252]
The number of unit tests we have in torchaudio has grown. It is critical to keep tests organized so as to make it easy for contributors to write tests for the feature they are working on.

Batch consistency tests are for validating that ops return the same result regardless of the number of dimensions/batches/channels. Currently We put all the tests in [test/torchaudio_unittest/batch_consistency_test.py](https://github.com/pytorch/audio/blob/77de2b9616c47c114124a8e002447ad927799dbd/test/torchaudio_unittest/batch_consistency_test.py#L14). As the list of ops in `torchaudio.functional` grows, we have a dedicated directory for functional tests, [test/torchaudio_unittest/functional](https://github.com/pytorch/audio/blob/77de2b9616c47c114124a8e002447ad927799dbd/test/torchaudio_unittest/functional). Moving the batch consistency tests for functional to the directory better decouples the test module.

## Steps
1. Create the equivalent of `batch_consistency_test.py`, in [test/torchaudio_unittest/functional](https://github.com/pytorch/audio/blob/77de2b9616c47c114124a8e002447ad927799dbd/test/torchaudio_unittest/functional) directory.
2. Move the tests for `functional` from the original location to the newly created scripts.

## Testing

1. Install nightly build of PyTorch
2. Clone repo and build torchaudio
3. Run test with `pytest test/torchaudio_unittest/functional -v`

**Comment by kychow** [comment]
Hey, I'm starting work on this task

**Comment by prabhat00155** [comment]
I can work on this. Is there a bootcamp task for this?

**Comment by prabhat00155** [comment]
@mthrok This could be closed as PR has been merged, thanks!
