### ISSUE TITLE
Refactor librosa compatibility test

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1255]
The number of unit tests we have in torchaudio has grown a lot. It is critical to keep tests organized so as to make it easy for contributors to write tests for the feature they are working on.

[librosa consistency tests](https://github.com/pytorch/audio/blob/9e58e75cfd8eae48b36165da1fd9812f3f595197/test/torchaudio_unittest/librosa_compatibility_test.py) are for checking that torchaudio's implementations (functional/transform) are numerically comparable against the librosa's implementation.

The list of functional has grown, so we now have [a dedicated test submodule for functional](https://github.com/pytorch/audio/blob/9e58e75cfd8eae48b36165da1fd9812f3f595197/test/torchaudio_unittest/functional). We would like to move librosa consistency tests for functionals to this module.

## Steps
1. Create a `librosa_compatibility_test.py` in `test/torchaudio_unittest/functional`
2. Move the [`TestFunctional` and `TestPhaseVocoder`](https://github.com/pytorch/audio/blob/9e58e75cfd8eae48b36165da1fd9812f3f595197/test/torchaudio_unittest/librosa_compatibility_test.py#L23-L156) to the new script. (fix import and stuff)

## Building and testing 

Please refer to [CONTRIBUTING](https://github.com/pytorch/audio/blob/master/CONTRIBUTING.md) for build process. You can check that the tests success with

`(cd test && pytest torchaudio_unittest/functional/librosa_compatibility_test.py torchaudio_unittest/librosa_compatibility_test.py)`

**Comment by mthrok** [comment]
Temporarily assigning @kychow

**Comment by AzizCode92** [comment]
Hi @mthrok, @kychow,  I have created a PR for this issue.

**Comment by mthrok** [comment]
@AzizCode92 

Thanks for the contribution. The PR looks good but let me wait for @kychow 's response a bit. I would like to stick to first-come first-served principle for fairness.

**Comment by AzizCode92** [comment]
Sure.
thanks
