### ISSUE TITLE
Adding `encoding` and `bits_per_sample` options to `save`

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1258]
The current release version's "soundfile" backend's `save` function changes the encoding of the audio file based on the dtype of the provided Tensor. For example, if the dtype is "float32", then it will be saved as 32bit floating point PCM. This behavior was taken from [SciPy's `scipy.io.wavefile.write` function](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.wavfile.write.html#scipy-io-wavfile-write). However it was pointed out that this is inconvenient for torchaudio users. Because most torchaudio's functionality works on float32 Tensor yet, the common audio formats typically retains only 16 bit, such as 16 bit signed integer PCM.

To resolve the inconvenience while keeping the functionality to support different encodings, we would like to add; 
1. Add `encoding` and `bits_per_sample` parameters to `save` function.
2. ~For non-compressed format (such as "wav"), it defaults to 16-bit signed integer PCM. (This is BC-breaking behavior if users were dumping Tensor object without converting to the matching dtype)~

See #1226 for the corresponding changes for "sox_io" backend. (but for "soundfile" backend the expected changes are much simpler)

## Steps
1. Add `encoding` and `bits_per_sample` options to [`save` function of soundfile backend](https://github.com/pytorch/audio/blob/5efb13e36b434a7d432dcc8486d8e8a2712288a7/torchaudio/backend/_soundfile_backend.py#L212-L220). Refer to the #1226 for the specification (valid values, fallback values etc). Note that sound file does not support all the formats `libsox` does. (`wav` and `flac` are the ones that should be covered and match the behavior of `"sox_io"` backend as much as possible)
2. Update [the logic that determines "subtype" argument](https://github.com/pytorch/audio/blob/5efb13e36b434a7d432dcc8486d8e8a2712288a7/torchaudio/backend/_soundfile_backend.py#L267-L280) so that `subtype` is determined by `format`, `encoding` and `bits_per_sample` parameters. **Note** To learn how PySoundFile internally expresses audio format, see [here](https://github.com/bastibe/python-soundfile/blob/744efb4b01abc72498a96b09115b42a4cabd85e4/soundfile.py#L38-L94)
3. Update the test
    1. Update [the mocked test](https://github.com/pytorch/audio/blob/5efb13e36b434a7d432dcc8486d8e8a2712288a7/test/torchaudio_unittest/backend/soundfile/save_test.py#L20-L106) that checks what parameters are given to the underlying `soundfile` module. (Input parameter should be changed from `dtype` to `encoding` and `bits_per_sample` so that the logic added in step 2 is tested)
    2. Fix the reset of the test which will brake because for wav format the function will now default to 16bit PCM.

## Build and test
Refer to [CONTRIBUTING](https://github.com/pytorch/audio/blob/master/CONTRIBUTING.md#development-installation) for the development setup.

To run the tests;
```
pytest test/torchaudio_unittest/backend/soundfile/save_test.py
```

**Comment by mthrok** [comment]
Assigning @prabhat00155 temporarily

**Comment by prabhat00155** [comment]
Thanks @mthrok, I can work on this.

**Comment by mthrok** [comment]
@prabhat00155 Thanks. 

Following the feedback in #1226, we drop the requirement 2 (defaulting to 16 bit signed PCM).
Keep [the original logic](https://github.com/pytorch/audio/blob/5efb13e36b434a7d432dcc8486d8e8a2712288a7/torchaudio/backend/_soundfile_backend.py#L267-L280) for the case neither `encoding` or `bits_per_sample` are provided. Let me know if you need help.

**Comment by prabhat00155** [comment]
This issue could be closed now; PR merged.
