### ISSUE TITLE
Add GSM format support to save function

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1264]
We would like to add more format support to "sox_io"'s `save` function. [`Full Rate`](https://en.wikipedia.org/wiki/Full_Rate) is the codec used in mobile phone system and the `libsox` torchaudio binds have capability to handle this format.

### Implementation
1. Add `GSM` to [`Format` enum](https://github.com/pytorch/audio/blob/05bff83fdec3e8f70f80bf7a1b89951bf7050114/torchaudio/csrc/sox/types.h#L9-L18) and [`get_format_from_string`](https://github.com/pytorch/audio/blob/05bff83fdec3e8f70f80bf7a1b89951bf7050114/torchaudio/csrc/sox/types.cpp#L6-L26) function. The expected string form is `"gsm"`.
2. Add GSM branch in [`get_save_encoding`](https://github.com/pytorch/audio/blob/05bff83fdec3e8f70f80bf7a1b89951bf7050114/torchaudio/csrc/sox/utils.cpp#L290-L377) function. Similar to [the case MP3](https://github.com/pytorch/audio/blob/05bff83fdec3e8f70f80bf7a1b89951bf7050114/torchaudio/csrc/sox/utils.cpp#L303-L309), GSM does not take any encoding or bit depth option. Use `SOX_ENCODING_GSM, 16` for return value.
3. Add GSM branch in [`get_precision`](https://github.com/pytorch/audio/blob/05bff83fdec3e8f70f80bf7a1b89951bf7050114/torchaudio/csrc/sox/utils.cpp#L379) function. the return value should be 16.
### Update documentation
1. Update the docstring of `save` function. (add `"gsm"` in [`format`](https://github.com/pytorch/audio/blob/05bff83fdec3e8f70f80bf7a1b89951bf7050114/torchaudio/backend/sox_io_backend.py#L190-L198) section  then [at the bottom before `Note:`](https://github.com/pytorch/audio/blob/master/torchaudio/backend/sox_io_backend.py#L255-L298) add some explanation from http://sox.sourceforge.net/soxformat.html (do text search `"gsm"`

### Add test
1. Add a new method `test_save_gsm` to [`SaveTest`](https://github.com/pytorch/audio/blob/05bff83fdec3e8f70f80bf7a1b89951bf7050114/test/torchaudio_unittest/backend/sox_io/save_test.py#L161) class, following other method like [`test_save_flac`](https://github.com/pytorch/audio/blob/05bff83fdec3e8f70f80bf7a1b89951bf7050114/test/torchaudio_unittest/backend/sox_io/save_test.py#L219-L238). Only parameterize the `test_mode`. GSM does not support `compression`/`encoding`/`bits_per_sample`.

## Building and testing locally
1. Follow [the CONTRIBUTING guide](https://github.com/pytorch/audio/blob/master/CONTRIBUTING.md#development-installation) to set up development environment.
2. Build and run test with;
```
BUILD_SOX=1 python setup.py develop && (cd test && pytest torchaudio_unittest/backend/sox_io/save_test.py -v --ff -k gsm )
```

**Comment by prabhat00155** [comment]
I can work on this.

**Comment by mthrok** [comment]
@prabhat00155 

Thanks, let me know if you need help.

**Comment by imaginary-person** [comment]
Hello @prabhat00155, you seem to work at Facebook, so if you haven't started working on it yet, can I please request @mthrok to assign this issue to me, as it has a `good first issue` label? Thanks!

Hello @mthrok, there don't seem to be any useful details regarding GSM (default bit-depth, etc) at the [link you provided](http://sox.sourceforge.net/soxformat.html). Even if I won't be assigned this issue, this information might be helpful to Prabhat.

**Comment by imaginary-person** [comment]
Hello @mthrok, there don't seem to be any useful details regarding GSM (default bit-depth, etc) at the [link you provided](http://sox.sourceforge.net/soxformat.html). Even if I won't be assigned this issue, this information might be helpful to Prabhat. Thanks!

**Comment by mthrok** [comment]
@imaginary-person 

If you would like to work on something complementary to this issue, you can make `info` function work for `gsm` format.
The [`encoding`](https://github.com/pytorch/audio/blob/e5c4de87a0b530a4fed51aad33578ca4e642f5cb/torchaudio/backend/common.py#L16) attribute does not resolve `gsm`. You can add `gsm` case [here](https://github.com/pytorch/audio/blob/e5c4de87a0b530a4fed51aad33578ca4e642f5cb/torchaudio/csrc/sox/io.cpp#L15-L44) and add test like [this one](https://github.com/pytorch/audio/blob/e5c4de87a0b530a4fed51aad33578ca4e642f5cb/test/torchaudio_unittest/backend/sox_io/info_test.py#L207-L222). Bonus point: move the `get_encoding` function to `types.[h|cpp]` so that all the encoding/format related functionalities are consolidated to one place.

**Comment by imaginary-person** [comment]
Thank you, @mthrok. I'll get started right away.
