### ISSUE TITLE
Use switch statements

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1265]
In torchaudio's `libsox` bindings (I/O and sox effects), there are couple of locations where different operation is applied based on Tensor's dtype.

Currently the code uses `caffe2::TypeMeta` type to check the dtype, such as the following example;

https://github.com/pytorch/audio/blob/05bff83fdec3e8f70f80bf7a1b89951bf7050114/torchaudio/csrc/sox/effects_chain.cpp#L83-L107

For this kind of execution flow, using `switch` statement makes the code cleaner. `caffe2::TypeMeta` is not an integral type so `switch` statement is not applicable. Converting it to `c10::ScalarType` make s it possible to use `switch` statement. For the above case, the resulting code looks like the following.

```c++
  switch (tensor_.dtype().toScalarType()) {
  case c10::ScalarType::Float: {
    auto ptr = tensor_.data_ptr<float_t>();
    for (size_t i = 0; i < *osamp; ++i) {
      obuf[i] = SOX_FLOAT_32BIT_TO_SAMPLE(ptr[i], effp->clips);
    }
    break;
  }
  case c10::ScalarType::Int: {
    auto ptr = tensor_.data_ptr<int32_t>();
    for (size_t i = 0; i < *osamp; ++i) {
      obuf[i] = SOX_SIGNED_32BIT_TO_SAMPLE(ptr[i], effp->clips);
    }
    break;
  }
  case c10::ScalarType::Short: {
    auto ptr = tensor_.data_ptr<int16_t>();
    for (size_t i = 0; i < *osamp; ++i) {
      obuf[i] = SOX_SIGNED_16BIT_TO_SAMPLE(ptr[i], effp->clips);
    }
    break;
  }
  case c10::ScalarType::Byte: {
    auto ptr = tensor_.data_ptr<uint8_t>();
    for (size_t i = 0; i < *osamp; ++i) {
      obuf[i] = SOX_UNSIGNED_8BIT_TO_SAMPLE(ptr[i], effp->clips);
    }
    break;
  }
  default:
    throw std::runtime_error("Unexpected dtype.");
  }
```

We would like to apply the same pattern to all the usage of `caffe2::TypeMeta`. The following is the list of such usage.

https://github.com/pytorch/audio/blob/05bff83fdec3e8f70f80bf7a1b89951bf7050114/torchaudio/csrc/sox/utils.cpp#L105-L110

https://github.com/pytorch/audio/blob/05bff83fdec3e8f70f80bf7a1b89951bf7050114/torchaudio/csrc/sox/utils.cpp#L219-L226

https://github.com/pytorch/audio/blob/05bff83fdec3e8f70f80bf7a1b89951bf7050114/torchaudio/csrc/sox/utils.cpp#L389-L397

https://github.com/pytorch/audio/blob/05bff83fdec3e8f70f80bf7a1b89951bf7050114/torchaudio/csrc/sox/utils.cpp#L423-L444

## Steps
1. Replace the `if ~ else if ~ else` statements listed above with `switch` statement on `c10::ScalarType`. Use `toScalarType()` method to convert `caffe2::TypeMeta` to `c10::ScalarType`.

## Building and testing locally
1. Follow [the CONTRIBUTING guide](https://github.com/pytorch/audio/blob/master/CONTRIBUTING.md#development-installation) to set up development environment.
2. Build and run test with;
```
BUILD_SOX=1 python setup.py develop && (cd test && pytest torchaudio_unittest/backend/sox_io -v --ff )
```
All the test should pass.

**Comment by prabhat00155** [comment]
I can work on this.

**Comment by mthrok** [comment]
@prabhat00155 

Thanks, let me know if you need help.

**Comment by prabhat00155** [comment]
Is there any point in modifying this: https://github.com/pytorch/audio/blob/05bff83fdec3e8f70f80bf7a1b89951bf7050114/torchaudio/csrc/sox/utils.cpp#L105-L110

**Comment by mthrok** [comment]
> Is there any advantage of modifying this?
> 
> https://github.com/pytorch/audio/blob/05bff83fdec3e8f70f80bf7a1b89951bf7050114/torchaudio/csrc/sox/utils.cpp#L105-L110

Not much from practical view point. It's more cosmetic.

**Comment by mthrok** [comment]
Well, there should be a tiny performance improvement because `ScalarType` is backed by integral type. But that will be negligible improvement.
