### ISSUE TITLE
Can torchaudio synthesize audio?

### ISSUE THREAD

**Issue by Huangsh17** [pytorch/audio#1292]
Can torchaudio synthesize audio?

**Comment by vincentqb** [comment]
Are you looking you looking for specific techniques? Along the line of Text-To-Speech, we have an [example](https://github.com/pytorch/audio/tree/master/examples/pipeline_wavernn) of a vocoder based on WaveRNN.

More generally, there's also a [forum](https://discuss.pytorch.org/) were users of pytorch and torchaudio can discuss different applications. Would that help?
