### ISSUE TITLE
how to compute log filter bank energy in torch audio compare with python_speech_feature?

### ISSUE THREAD

**Issue by trangtv57** [pytorch/audio#1298]
## ❓ I want re-procedure result like when i use compute log-filterbank energy of lib: python_speech_feature by using torchaudio.

this is my code, and I'm see the result is difference:

```
# load audio data by librosa
path_audio = "audio_a.wav"
y, sr = librosa.load(path_audio, sr=16000, offset=0.5, duration=0.4)

# load audio data by torch audio
audio_ft, sr = torchaudio.load(path_audio)
audio_ft = audio_ft.squeeze(0)
y_torch = audio_ft[int(0.5*16000):int(0.9*16000)]

# the result is the same then i compute log filterbank energy
ft_f_bank = python_speech_features.logfbank(y, samplerate=16000, winlen=0.025, winstep=0.01, nfilt=64,nfft=512)
print(ft_f_bank.shape) # result: (39, 64)
ft_f_bank_by_torch = torchaudio.compliance.kaldi.fbank(y_torch, sample_frequency=16000.0, frame_length=25.0, frame_shift=10.0, use_log_fbank=True, use_energy=True, num_mel_bins=64)
print(ft_f_bank_by_torch.shape) # result: (38, 65)
```
How can i make result return by torchaudio is the same with python speech feature. I'm not have deep understand more about speech feature, so question can so weird, sorry. 
Thankyou

**Comment by mthrok** [comment]
Hi @trangtv57 

Thanks for using `torchaudio`. I do not have experience with the package. 
The question better falls into user support, so can you post it in https://discuss.pytorch.org/ ?
