### ISSUE TITLE
Windows build missing on PyPI?

### ISSUE THREAD

**Issue by 1enn0** [pytorch/audio#1320]
## 🐛 Bug

Is there a reason `torchaudio` is not pushed to PyPI?

## To Reproduce

1. `pip install torch==1.7.1 torchaudio==0.7.2`

Output:
```
Collecting torch==1.7.1
  Downloading torch-1.7.1-cp38-cp38-win_amd64.whl (184.0 MB)
     |████████████████████████████████| 184.0 MB 201 kB/s
ERROR: Could not find a version that satisfies the requirement torchaudio==0.7.2
ERROR: No matching distribution found for torchaudio==0.7.2
```

## Expected behavior

`torch` (CPU build) and `torchaudio` are installed.

## Environment

 - OS: Windows
 - Python version: 3.8.6

## Additional context

I'm wondering why the `torchaudio` and `torchvision` wheels for Windows are not available on PyPI (btw, I have opened [a similiar issue for `torchvision`](https://github.com/pytorch/vision/issues/3436). While `torchvision` _used_ to be pushed to PyPI, `torchaudio` has never been available on PyPI, as far as I can see.

I'm aware the standard/recommended way of installing is through [the pytorch.org index](https://download.pytorch.org/whl/torch_stable.html). However, the main `torch` package (CPU only) is being pushed to PyPI, so I'm wondering whether it is inteded that both `torchvision` and `torchaudio` are not or if it's just a bug?

The only somewhat related information I could find for `torchaudio` is [#425](https://github.com/pytorch/audio/issues/425). However, this should not be a reason to not publish the wheel to PyPI?

Does anybody have some information on this? :)

**Comment by mthrok** [comment]
Hi @1enn0 

Thanks for reporting. I believe Windows build should be available and if it's not, there is an issue.

@seemethere could you take a look into this?

**Comment by vincentqb** [comment]
FYI the new release 0.8 has been uploaded to [pypi](https://pypi.org/project/torchaudio/#files) :)

**Comment by 1enn0** [comment]
@vincentqb thanks, that's great news! 👍 

Just out of curiosity: How does this upload actually happen? Is it automatically done by the CI or is it a manual script someone with access to the PyPI repo has to run? I had a look around the repo but could not really figure this out. :)

**Comment by vincentqb** [comment]
Most of it is automated, see #682, but there is a little more "human supervision" for releases to make sure there are no surprises there :)

**Comment by seemethere** [comment]
Windows builds started to be uploaded to PyPI as of torchaudio 0.8.0, please use those binaries moving forward.

We will most likely not upload windows binaries for 0.7.2

**Comment by vincentqb** [comment]
Closing issue following comment from @seemethere. @1enn0, please feel free to re-open the issue if this does not address it.
