### ISSUE TITLE
Making `AudioMetaData` print friendly

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1323]
`AudioMetaData` class reports meta-data of audio source. It is however not print friendly.

```python
print(torchaudio.info(src))
>>> <torchaudio.backend.common.AudioMetaData object at 0x7f1bc5cd2890>
```

It is nice if we can simply print the attributes like `dataclass` objects do.

```python
print(torchaudio.info(src))
>>> AudioMetaData(sample_rate=900, encoding="PCM", ...)
```

## Steps

There are two approaches I can think of
1. Add `__str__` method.
2. Use `dataclasses.dataclass`

For 2, the `info` function has to be TorchScript-compatible. This means that its return type `AudioMetaData` has to be TorchScript-able. For this reason, `dataclass` might not be applicable. This can be checked with the following test;

```bash
(cd test && pytest torchaudio_unittest/backend/sox_io/torchscript_test.py)
```

## Build and test

Please refer to the [contribution guide](https://github.com/pytorch/audio/blob/master/CONTRIBUTING.md) for how to setup development environment.

To test, 

```bash
(cd test && pytest torchaudio_unittest/backend/sox_io/torchscript_test.py torchaudio_unittest/backend/sox_io/info_test.py torchaudio_unittest/backend/soundfile_io/info_test.py)
```

**Comment by majabojarska** [comment]
Hi. I want to work on this issue.

**Comment by mthrok** [comment]
Hi @majabojarska 

thanks. Let me know if you need help.
