### ISSUE TITLE
Get difference result from server and local ( mel spectrogram)

### ISSUE THREAD

**Issue by zion-h** [pytorch/audio#1343]
## 🐛 Bug

![image](https://user-images.githubusercontent.com/79956493/109750604-16e77f80-7c20-11eb-8cd8-29195c8177e6.png)

I'm used this code to mp3->mel spectrogram data.(not using gpu, only cpu)
But I got a problem that is server and local make different result.
Server and local running same code.

python : 3.7.0
torch : 1.7.1
torchaudio : 0.7.2

server : centos7.4
local : mac os

How to solve this problem??

## Environment

server
![image](https://user-images.githubusercontent.com/79956493/109756336-1b656580-7c2b-11eb-94b3-18a38fed7d7f.png)

local
![image](https://user-images.githubusercontent.com/79956493/109755529-8a41bf00-7c29-11eb-99cd-e87fd1fd02e7.png)

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by mthrok** [comment]
Hi @zion-h 

Please run the environment collection script in each of your environment and report them as instructed in the issue template.

**Comment by zion-h** [comment]
Hi, @mthrok 
modified!
