### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by NoCodeAvaible** [pytorch/audio#1352]
Hey guys,
when I try to setup the soundfile backend I get this error:

`AttributeError: partially initialized module 'torchaudio' has no attribute 'set_audio_backend' (most likely due to a circular import)`

This is how I try to setup the soundfile backend:
![backend](https://user-images.githubusercontent.com/77166330/109978211-f1c93e80-7cfd-11eb-8e20-6cb5b1d14b3c.JPG)

PS: I try to setup the backend in the utils.py of the torchaudio module.

Thank's for every help in advance:)

**Comment by mthrok** [comment]
Hi @NoCodeAvaible 

Looks like you are editing the installed package. That's not a standard way to do but I understand why one wants to do so.

Can you do it at the very end of `torchaudio/__init__.py` (the top level `__init__.py`) ? Then it should work.

**Comment by NoCodeAvaible** [comment]
ok thank you very much for your help

**Comment by NoCodeAvaible** [comment]
in the folder backend?

**Comment by mthrok** [comment]
just at the top level, that's it. that will be almost equivalent setting the backend in user-side script.

**Comment by NoCodeAvaible** [comment]
ok

**Comment by mthrok** [comment]
Closing as this is not an issue in torchaudio.
