### ISSUE TITLE
Support 24bit wave in sox_io `load` function.

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1376]
Currently the `save` and `info` functions of "sox_io" backend support 24-bit signed integer liner PCM, but `load` function does not support it.

```python
import io
import torch
import torchaudio


tensor = torch.randn([2, 256])
buffer_ = io.BytesIO()
torchaudio.save(buffer_, tensor, 256, format='wav', encoding='PCM_S', bits_per_sample=24)

buffer_.seek(0)
print(torchaudio.info(buffer_))

buffer_.seek(0)
torchaudio.load(buffer_)
```

```
AudioMetaData(sample_rate=256, num_frames=256, num_channels=2, bits_per_sample=24, encoding=PCM_S)
Traceback (most recent call last):
  File "foo.py", line 14, in <module>
    torchaudio.load(buffer_)
  File "torchaudio/backend/sox_io_backend.py", line 147, in load
    return torchaudio._torchaudio.load_audio_fileobj(
RuntimeError: Only 16 and 32 bits are supported for signed PCM.
```

We can support add support for 24-bit signed integer linear PCM. It is straightforward for the case `normalize=True` as the returned Tensor will be `float` type with value range [-1.0, 1.0] but there is an open question of what to do when `normalize=False`. When `normalize=False`, and the audio format is WAVE, our `load` function picks the corresponding Tensor type, such as `torch.int16` for 16-bit signed integer linear PCM, but Pytorch does not have 24-bit data type so we need to decide what to do when `normalize=False`.

1. Raise an error.
2. Use 32-bit signed integer (and maybe add warning)
3. Something else.

In the following, we assume that we will take the approach 2.

## Steps 
1. Update the [`get_dtype`](https://github.com/pytorch/audio/blob/master/torchaudio/csrc/sox/utils.cpp#L114-L140) function which is used by [`apply_effects_file `](https://github.com/pytorch/audio/blob/ea857940de9e3738166989ad3bf1726741a13f04/torchaudio/csrc/sox/effects.cpp#L106) and [`apply_effects_fileobj `](https://github.com/pytorch/audio/blob/ea857940de9e3738166989ad3bf1726741a13f04/torchaudio/csrc/sox/effects.cpp#L161).

## Testing
1. We need to add test for `24-bit` to [the test function](https://github.com/pytorch/audio/blob/ea857940de9e3738166989ad3bf1726741a13f04/test/torchaudio_unittest/backend/sox_io/load_test.py#L206-L214), but our test fixtures for WAVE I/O relies on `scipy`, which cannot handle 24-bit audio so we one will need to work around. This is not straightforward. One workaround is to do something similar to [how `mp3` loading is tested](https://github.com/pytorch/audio/blob/ea857940de9e3738166989ad3bf1726741a13f04/test/torchaudio_unittest/backend/sox_io/load_test.py#L45-L70). We can generate 24-bit audio file with `sox` command and load it with `torchaudio.load` and create a reference value by first converting the file to 32bit signed integer then loading it with `scipy`. For the detail of this approach, please refer the docstring of `mp3` test above.

## Setting up dev env

Please refer to [CONTRIBUTING.md](https://github.com/pytorch/audio/blob/master/CONTRIBUTING.md) for setting up a dev env.

**Comment by iseessel** [comment]
Hi I'll be working on this :)!

**Comment by mthrok** [comment]
@iseessel Thanks, let me know if you need help.
