### ISSUE TITLE
Fix docstring of `sliding_window_cmn`

### ISSUE THREAD

**Issue by jackyguo624** [pytorch/audio#1380]
https://github.com/pytorch/audio/blob/ea857940de9e3738166989ad3bf1726741a13f04/torchaudio/functional/functional.py#L947

the input `specgram `shoud be in shape (channel, ..., time, freq), instead of `(..., freq, time)` as doc says.

Right?

**Comment by mthrok** [comment]
Hi @jackyguo624 

Thanks for the report. I think you are right about it and we should fix it.

**Comment by mthrok** [comment]
CC @jcaw Sorry we missed it in the review process.

**Comment by yoyololicon** [comment]
@jackyguo624 
Hmm, I think the docstring is right, `(..., freq, time)` means you can drop the batch dimension, directly feed a matrix into it.

https://github.com/pytorch/audio/blob/ea857940de9e3738166989ad3bf1726741a13f04/torchaudio/functional/functional.py#L1022

This line handle when input is a 2-dimensional matrix.

**Comment by mthrok** [comment]
> @jackyguo624
> Hmm, I think the docstring is right, `(..., freq, time)` means you can drop the batch dimension, directly feed a matrix into it.
> 
> https://github.com/pytorch/audio/blob/ea857940de9e3738166989ad3bf1726741a13f04/torchaudio/functional/functional.py#L1022
> 
> This line handle when input is a 2-dimensional matrix.

@yoyololicon 

Well, the batch/channel dimension is fine. I think the issue is about the order of the last two dimensions. The expected order is `(..., time, freq)` whereas the docstring is `(..., freq, time)`

**Comment by yoyololicon** [comment]
Oh, I see it, nevermind.😅

**Comment by jcaw** [comment]
Spectrograms returned by torchaudio do have the [order](https://github.com/pytorch/audio/blob/ea857940de9e3738166989ad3bf1726741a13f04/torchaudio/functional/functional.py#L75), `(..., freq, time)` though. Should `sliding_window_cmn` be operating on a different order? That seems like a bug.

**Comment by mthrok** [comment]
> Spectrograms returned by torchaudio [do have](https://github.com/pytorch/audio/blob/ea857940de9e3738166989ad3bf1726741a13f04/torchaudio/functional/functional.py#L75) the order `(..., freq, time)` though. Should `sliding_window_cmn` be operating on a different order? That seems like a bug.

This is the inconsistent design principles between the libraries `torchaudio` followed. `sliding_window_cmn` is from Kaldi while `spectrogram` is from another different source. We could think of changing it but it will be a bc-breaking change, so it needs a separate discussion. For now, let's make the docstring of `sliding_window_cmn` accurately reflect the operation.

**Comment by mohamedirfansh** [comment]
Hello, can I work on this and fix this issue?

**Comment by mthrok** [comment]
Thanks. The docstring itself has changed. I'll think of what we can do about the inconsistent design. There are bunch of inconsistent interface design around Kaldi-originated functions.

**Comment by mthrok** [comment]
> Thanks. The docstring itself has changed. I'll think of what we can do about the inconsistent design. There are bunch of inconsistent interface design around Kaldi-originated functions.

and if you have any suggestion, we are happy to hear.
