### ISSUE TITLE
Save should raise an error when saving invalid GSM config.

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1381]
GSM format only supports 8kHz single-channel waveform. The current `save` function always assumes this is the case, and interpret the input Tensor to be 8kHz single-channel even when it's not. The following script demonstrates it.

```python
import torch
import torchaudio

sr = 16000
tensor = torch.randn([2, 16000])
torchaudio.save('foo.gsm', tensor, sr)
print(torchaudio.info('foo.gsm'))

tensor_, sr_ = torchaudio.load('foo.gsm')
print(sr_, tensor_.shape)
```

prints

```
>>> AudioMetaData(sample_rate=8000, num_frames=0, num_channels=1, bits_per_sample=0, encoding=GSM)
>>> 8000 torch.Size([1, 32000])
```

Instead the `save` function should reject `save` operation when it's not 8kHz single-channel waveform.

## Steps
1. Add check for sample rate and number of channels [here](https://github.com/pytorch/audio/blob/ea857940de9e3738166989ad3bf1726741a13f04/torchaudio/csrc/sox/io.cpp#L96-L104) and [here](https://github.com/pytorch/audio/blob/ea857940de9e3738166989ad3bf1726741a13f04/torchaudio/csrc/sox/io.cpp#L234-L246)
2. Update [the existing test](https://github.com/pytorch/audio/blob/ea857940de9e3738166989ad3bf1726741a13f04/test/torchaudio_unittest/backend/sox_io/save_test.py#L303-L308), which uses `num_channels=2` , to pass the test. (explicitly pass `sample_rate=8000` and `num_channels=1`.)
3. Add a new test under `test_save_gsm`, which verifies that `save` function raises an error when it receives `sample_rate!=8000` or Tensor with multiple channel dimension. (can use [`assertRaises`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises))

## Testing
For setting up the development environment, please refer to [CONTRIBUTING.md](https://github.com/pytorch/audio/blob/master/CONTRIBUTING.md).

The following test shall pass.
```bash
(cd test && pytest torchaudio_unittest/backend/sox_io/save_test.py -k gsm)
```

**Comment by jhurt** [comment]
@mthrok I'll take a look at this

**Comment by mthrok** [comment]
@jhurt 

Thanks. Let me know if you need help.
