### ISSUE TITLE
Call to .info for non-existent file causes crash (Jupyter kernel dies)

### ISSUE THREAD

**Issue by rbracco** [pytorch/audio#139]

**Comment by rbracco** [comment]
A call to `torchaudio.info(path)` for a path that doesn't exist causes the kernel to die in Jupyter. It likely just needs to be wrapped in a check for the file's existence before handing it off to sox. Low priority as user can just wrap with their own check, but quite annoying because when Jupyter's kernel dies it doesn't display output from print statements or debug so it is hard to trace.

**Comment by jamarshon** [comment]
@rbracco What is the expected/desired behaviour for a file does not exist? Currently it throws a RuntimeError
```
>>> torchaudio.info('hello.wav')
formats: can't open input file `hello.wav': No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/jamarshon/audio/torchaudio/__init__.py", line 219, in info
    return _torch_sox.get_info(filepath)
RuntimeError: Error opening audio file
```
since in torch_sox.cpp's get_info, it says
```
if (fd.get() == nullptr) {
  throw std::runtime_error("Error opening audio file");
}
```
I think that throwing an error is acceptable here as the user can do 
```
try:
	torchaudio.info('hello.wav')
except Exception as e:
	print('An exception occured')
	print(e)
```
with the output
```
formats: can't open input file `hello.wav': No such file or directory
An exception occured
Error opening audio file
```

**Comment by rbracco** [comment]
Sorry about this, I actually thought I'd already closed it. I was running an older version of torchaudio in which this was a problem, I believe it has been fixed. Thank you for the reply and info.
