### ISSUE TITLE
Saving stereo files causes fatal error if re-loading generated file

### ISSUE THREAD

**Issue by dhpollack** [pytorch/audio#14]
Saving stereo files does not properly add the length info to the saved file.  Thus you cannot reload these files with torchaudio, although they are playable in most audio programs.  Below is a test case.

```sh
import torchaudio
sig, sr = torchaudio.load("test/steam-train-whistle-daniel_simon.mp3")
torchaudio.save("test/file.wav", sig, sr)
sig, sr = torchaudio.load("test/file.wav")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dhpollack/repos/audio/torchaudio/__init__.py", line 30, in load
    func(str(filepath).encode("utf-8"), out, sample_rate_p)
  File "/home/dhpollack/miniconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 177, in safe_cal
l
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: [read_audio] Unknown length at torchaudio/src/generic/th_sox.c:14
```

**Comment by marikgoldstein** [comment]
Confirming that this is still a problem. Any thoughts? Is this an issue in th_sox.c or in what is being passed to it from python?

**Comment by dhpollack** [comment]
@marikgoldstein, I looked a little more into this.  It has to do with how the save function saves certain file types and specifically, something to do with the file length.  You can try saving to other file types and see if they work.  This is all to say, I think it's what's getting passed to th_sox.c and not th_sox.c itself.

**Comment by rivaud** [comment]
The bug is apparently still happening.
It seems that there are problem when saving stereo files.
Mono files seems to work fine.
However the bug seems not to happen all the time.

Do you have any update on this issue ?

**Comment by dhpollack** [comment]
I believe this problem has been resolved.  Still need to do a few more tests, but if anyone is still experiencing this issue let me know.

**Comment by thommiano** [comment]
I'm experiencing this issue.
