### ISSUE TITLE
I have a question about mel spectrogram.

### ISSUE THREAD

**Issue by hjlee9182** [pytorch/audio#1407]
## ❓ Questions and Help

Hi guys I have a question
1. First picture. I'm using torchaudio.Melspectrogram and that result size (2,128,16846).
       So I don't understand because I think mel spectrogram x-axis is time.
       How to calculate that's x-axis? ( 16846) , this audio length is 196s. and what ms per frame?
![image](https://user-images.githubusercontent.com/46337218/112596504-42404180-8e4f-11eb-8039-eb6fa825c639.png)

2. Second picture is used librosa.Melspectrogram. And that's result is (128,8421)
   I don't understand why this two result is different. becuase I give same option.
   Can anybody explain that?
![image](https://user-images.githubusercontent.com/46337218/112596527-4bc9a980-8e4f-11eb-907d-af0cda5fc641.png)

Thanks for advising!

**Comment by yoyololicon** [comment]
@hjlee9182 

> 1. First picture. I'm using torchaudio.Melspectrogram and that result size (2,128,16846).
>    So I don't understand because I think mel spectrogram x-axis is time.
>    How to calculate that's x-axis? ( 16846) , this audio length is 196s. and what ms per frame?

I would recommend you checking the value of `sr`, it might not be 16000.

> 2. Second picture is used librosa.Melspectrogram. And that's result is (128,8421)
>    I don't understand why this two result is different. becuase I give same option.
>    Can anybody explain that?

Use `librosa.load('test.mp3', sr=None, mono=False)` should give the accurate result.
Again, please check whether `sr` is indeed 16000.

#

**Comment by hjlee9182** [comment]
@yoyololicon 

> @hjlee9182
> 
> > 1. First picture. I'm using torchaudio.Melspectrogram and that result size (2,128,16846).
> >    So I don't understand because I think mel spectrogram x-axis is time.
> >    How to calculate that's x-axis? ( 16846) , this audio length is 196s. and what ms per frame?
> 
> I would recommend you checking the value of `sr`, it might not be 16000.

Yes , sr is 44100. and I did re-run mel spectrogram(sr =44100), but size is not change(2,128,16846). 

> 
> > 1. Second picture is used librosa.Melspectrogram. And that's result is (128,8421)
> >    I don't understand why this two result is different. becuase I give same option.
> >    Can anybody explain that?
> 
> Use `librosa.load('test.mp3', sr=None, mono=False)` should give the accurate result.
> Again, please check whether `sr` is indeed 16000.

I try to this code. mono option occured error. so I try `librosa.load('test.mp3',sr=None)`
It's result (128,16842)!

**Comment by yoyololicon** [comment]
@hjlee9182 
What version of librosa are you using? Old version of librosa always mix down the signal to mono and didn't have `mono` keywords.

The number of frames can be calculated by 192 * 44100 / 512 ~= 16882. I think it's pretty close to your result. ms per frame is 512 / 44100 * 1000 ~= 11.6 ms.

**Comment by hjlee9182** [comment]
@yoyololicon 

Thank you for your answer. 
So I have one another question.
What is difference between  sr =16000's result and sr=44100's result ? 
That's size is same.

**Comment by yoyololicon** [comment]
> @yoyololicon
> 
> Thank you for your answer.
> So I have one another question.
> What is difference between sr =16000's result and sr=44100's result ?
> That's size is same.

The output shape of mel is determined by `n_fft`, `hop_length` and some other keywords, but not the sampling rate.
The sampling rate affects the calculation of mel frequenceis, so different sr will have different mel filters.

**Comment by hjlee9182** [comment]
@yoyololicon 

Really thanks your answer!!

**Comment by xXDarkCubeXx** [comment]
> @hjlee9182
> The number of frames can be calculated by 192 * 44100 / 512 ~= 16882. I think it's pretty close to your result. ms per frame is 512 / 44100 * 1000 ~= 11.6 ms.

the number of frames can actually be calculated by 192*44100/512 +1 ~= 16883. I suspect the audio clip is a little less than 192 seconds and that's why he's getting a shape of (2,128,16846)
