### ISSUE TITLE
Torch Audio repository description

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#141]
The repository's description is "simple audio I/O for pytorch". We should change that to something like "Data manipulation and transformation for audio signal processing, powered by PyTorch."

See [torch text](https://github.com/pytorch/vision), [torch vision](https://github.com/pytorch/vision) and [doc](https://pytorch.org/docs/stable/torchvision/index.html), [pytorch](https://github.com/pytorch/pytorch).

**Comment by soumith** [comment]
done
