### ISSUE TITLE
Autograd tests for Transforms

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1414]
Until recent, we have been assumed that ops provided in torchaudio support autograd just because they are implemented with PyTorch. However, this assumption was not correct all the time. For example, in #704, it was pointed out that `lfitler` does not support autograd, and this was resolved in #1310 with proper unit tests by community contribution. Similarly, as a part of #1337, I have added autograd test to some transforms in #1340. We would like to extend the autograd testing to as many functionals and transforms as possible. We would like to ask your help.

## Steps
1. Pick a transform from the list bellow and see if someone is working on it. If not, leave a comment in this thread that you will be working on it.
2. Add a test in [AutogradTestMixin](https://github.com/pytorch/audio/blob/7d45851d97d35a703817e2b037df03d57b748018/test/torchaudio_unittest/transforms/autograd_test_impl.py#L29) similar to the existing tests.
**NOTE** Please first try adding test without providing `nondet_tol` to see if the transform's backward pass is deterministic or not. If you see `Backward is not reentrant` error message, that means it is not deterministic. Please report it back here, so that we can discuss how to handle it.
3. Run test with `(cd test && pytest torchaudio_unittest/transforms/autograd_*_test.py)`.
4. Make a PR and add `cc @mthrok` in the description (or comment)

 **Note**: We are not sure if all the transforms actually support autograd. If you find a Transform does not support autograd please report back in this thread.

For the instruction to set up development environment, please refer to [CONTRIBUTING.md](https://github.com/pytorch/audio/blob/master/CONTRIBUTING.md).

## Transforms
- [x] `AmplitudeToDB` #1447 
    is used by `MFCC` so it should support but having an independent test is be nice
- [x] `Spectrogram` #1340
- [x] `GriffinLim` #1421 
- [x] `MelScale` #1467 
    is used by `MelSpectrogram` so it should support but having an independent test is be nice
- ~`InverseMelScale`~
    this transform most likely does not support autograd
- [x] `MelSpectrogram` #1340
- [x] `MFCC` #1415
- ~`MuLawEncoding`~
- ~`MuLawDecoding`~
    `MuLaw`s are quantization operation, thus they do not support autograd. 
- [x] `Resample` #1416
- [x] `ComputeDeltas` #1422
- ~`TimeStretch`~ ~#1420~
    `TimeStretch` requires coordinate transform from cartesian to polar which uses `atan2`. `atan2` is not differentiable everywhere.
- [x] `Fade` #1424
- [x] `FrequencyMasking` #1498
- [x] `TimeMasking` #1498
- [x] `Vol` #1460 
- [x] `SlidingWindowCmn` #1482
- [x] `SpectralCentroid` #1425
- ~`Vad`~
    this transform most likely does not support autograd

**Comment by yoyololicon** [comment]
@mthrok 
I have some experiences with spectrogram inversion before, so I would like to take on `GriffinLim`.

**Comment by mthrok** [comment]
> @mthrok
> I have some experiences with spectrogram inversion before, so I would like to take on `GriffinLim`.

@yoyololicon 

Thanks. Let me know if you need help there.

**Comment by krishnakalyan3** [comment]
I will be working on `MFCC`

**Comment by Moh-Yakoub** [comment]
@mthrok

I will try working with `Fade`

**Comment by krishnakalyan3** [comment]
Working on `resample`, `SpectralCentroid` and `Fade`

**Comment by yoyololicon** [comment]
I don't think `Mulaw*coding` needs autograd cuz it quantized value to integers, right?

**Comment by mthrok** [comment]
> I don't think `Mulaw*coding` needs autograd cuz it quantized value to integers, right?

Hi @yoyololicon 
Yes, you are right. Scratching them out. Thanks for the pointer.

**Comment by dhthompson** [comment]
I'm taking a look at `Vol`

**Comment by kiri11** [comment]
I'm going to take a stab at `FrequencyMasking`/`TimeMasking`, the only ones left!

**Comment by mthrok** [comment]
Now all the Transforms with autograd supports are properly tested. Thanks for the help!
