### ISSUE TITLE
Scale transform does not fail on non-integers

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#144]
Since `Scale` assumes integer-valued float-typed signal, giving a float-valued float-typed signal results is not what one would expect for a float-valued float-typed signal. We could either
* update `Scale` to take float-valued float-typed, 
* give a warning if float-valued are detected happens,
* we could rename the transform to IntegerScale, and introduce another FloatScale for this, with a deprecation warning.

The documentation does highlight this property, so we could also leave it at that. :)

**Comment by jamarshon** [comment]
Removed Scale in https://github.com/pytorch/audio/pull/152
