### ISSUE TITLE
Remove T.VAD from transform batch consistency test

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1449]
See https://github.com/pytorch/audio/issues/1348 for the background

`T.VAD` currently treats all the tracks in the input batch as belong to the same audio data. This means that it returns different results when samples are batched and samples are fed independently.

There is a test to ensure the consistency of operation result regardless of batched/un-bached, but `T.VAD` in this test does not make sense. We would like to remove it.

https://github.com/pytorch/audio/blob/6a677ac8bfa2fd97f6d30a1ec0308ded98ba8020/test/torchaudio_unittest/transforms/torchscript_consistency_impl.py#L92-L95

# Steps

1. Remove the test

# Testing and building

Please refer to [`CONTRIBUTING.md`](https://github.com/pytorch/audio/blob/master/CONTRIBUTING.md).

**Comment by jcaw** [comment]
I'll take this, but doesn't the test you quoted test JIT consistency, rather than batch consistency?

**Comment by mthrok** [comment]
Oops my bad. Yes, I meant the batch consistency test.
