### ISSUE TITLE
Support m4a format in torchaudio

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#1453]
We would like to support m4a format directly in torchaudio.
* This is the format used in the VoxCeleb2 dataset.
* It is supported by ffmpeg.

cc https://github.com/pytorch/audio/issues/104, @mravanelli

**Comment by faroit** [comment]
@vincentqb Without having looked at the ffmpeg io module... does it support multiple streams? If no, can this be supported?

See https://github.com/faroit/stempeg

**Comment by mthrok** [comment]
It does. You can map pick/duplicates source streams into arbitral combinations of output streams.

https://pytorch.org/audio/stable/tutorials/streaming_api_tutorial.html#example

**Comment by faroit** [comment]
> It does. You can map pick/duplicates source streams into arbitral combinations of output streams.
> 
> 
> 
> https://pytorch.org/audio/stable/tutorials/streaming_api_tutorial.html#example 

Oh that's cool. I can finally retire stempeg
