### ISSUE TITLE
Remove unused module

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1464]
[`torchaudio._internal.misc_ops`](https://github.com/pytorch/audio/blob/b059f08742e70700ce4c92296a1131118f67a588/torchaudio/_internal/misc_ops.py) is a residue from refactoring of I/O features in the past releases. We can get rid of the whole module.

**Comment by itsabhianant** [comment]
Hi @mthrok ,

I would like to work on this issue. As per my understanding, I think we have to remove the [misc_ops.py](https://github.com/pytorch/audio/blob/b059f08742e70700ce4c92296a1131118f67a588/torchaudio/_internal/misc_ops.py) file from the project. If I got your issue correct then please do assign this issue to me or please do explain what I have to do. It will be cool if you assign me the issue after explaining the issue in a bit of detail.

Best,
Abhishek

**Comment by mthrok** [comment]
Hi @itsabhianant 

Thanks for the signing up. Yes, your understanding is correct. It's as simple as removing `misc_ops.py`. please go ahead and make a PR and add `Closes #1464 cc @mthrok` in the description.
