### ISSUE TITLE
Batch support

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#147]
Many (all?) of the transformers do not currently support batches, and operate on only one non-batched tensor  at a time. This can be fixed as part while setting a convention on the meaning of the indices across torchaudio.

Since signals don't necessarily have the same lengths unless pre-processing is done (i.e. padding, truncating, etc), we should wait on nested tensors.

**Comment by vgoklani** [comment]
why was this closed?

**Comment by vincentqb** [comment]
> why was this closed?

Thanks for pointing this out: it should have remained open :)

**Comment by vincentqb** [comment]
In the meantime, a workaround is to convert `(batch, channel, time)`-waveform into `(batch*channel, time)`-waveform, apply the transform, and then convert back.

**Comment by vincentqb** [comment]
Fixed with #337
