### ISSUE TITLE
Could not find a version that satisfies the requirement torchaudio

### ISSUE THREAD

**Issue by tangyuelm** [pytorch/audio#1489]
### Please note that this issue tracker is not a help form and this issue will be closed.

Hello,

I want to install the torchaudio on my aws server/ I have tried 
pip install torchaudio -f https://download.pytorch.org/whl/torch_stable.html
but it shows that  
ERROR: Could not find a version that satisfies the requirement torchaudio (from versions: none)
ERROR: No matching distribution found for torchaudio

I used CUDA 10.0, python 3.7.6, and torch 1.4.0, which should satisfied the installation requirement. Could anyone help me?
Best

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by mthrok** [comment]
Hi @tangyuelm 

Can you try `pip install torchaudio==0.4.0`?

**Comment by tangyuelm** [comment]
It still cannot work.

**Comment by mthrok** [comment]
Can you paste the followings?
1. the error you are getting 
2. the result of `python -m torch.utils.collect_env`

**Comment by tangyuelm** [comment]
Thanks for your reply. 
Here is the result of my error.
ubuntu@ip-172-31-44-135:~/src/dataset/audio$ pip install torchaudio==0.4.0
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8d874f80d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/torchaudio/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8d8753cbd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/torchaudio/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8d8753cb50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/torchaudio/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8d8753c490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/torchaudio/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8d8753c2d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/torchaudio/
ERROR: Could not find a version that satisfies the requirement torchaudio==0.4.0 (from versions: none)
ERROR: No matching distribution found for torchaudio==0.4.0

And here is the result of typing the command.
ubuntu@ip-172-31-44-135:~/src/dataset/audio$ python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.18.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.4

Versions of relevant libraries:
[pip3] numpy==1.19.3
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.0                      166
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[2]-  Exit 2                  nohup python3 cpc/train.py --pathDB $dataset/librispeech/train/LibriSpeech/train-clean-100 --pathCheckpoint $PATH_CHECKPOINT_DIR --pathTrain $TRAINING_SET --pathVal $VAL_SET --file_extension $EXTENSION > train.out 2>&1
ubuntu@ip-172-31-44-135:~/src/dataset/audio$ python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.18.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.4

Versions of relevant libraries:
[pip3] numpy==1.19.3
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.0                      166
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
ubuntu@ip-172-31-44-135:~/src/dataset/audio$

**Comment by mthrok** [comment]
Looking at the warnings, I think it's something about your network. 

```
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8d874f80d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/torchaudio/
```

You might have a custom PyPi configuration or maybe your `pip` is very old.

Also it's `Temporary failure in name resolution')': /simple/torchaudio/` seems like the index URL is wrong. maybe something like the following might work.

`pip install --index-url=https://pypi.python.org/simple/ torchaudio==0.4.0`

I just opened a Google colab notebook and did `!pip install torchaudio==0.4.0` and `pip install --index-url=https://pypi.python.org/simple/ torchaudio==0.4.0`, it works fine.

<img width="1619" alt="Screen Shot 2021-05-05 at 16 45 19" src="https://user-images.githubusercontent.com/855818/117206829-50c03800-adc1-11eb-99be-a87040bc7883.png">

**Comment by tangyuelm** [comment]
Thanks for your attention but it still cannot work. I also tried pip3 and pip --user, but got the same error. I checked my pip version it is 20.0.2. I also tried the conda command but still failed. 
 pip --version
pip 20.0.2 from /home/ubuntu/anaconda3/lib/python3.7/site-packages/pip (python 3.7)

**Comment by mthrok** [comment]
What happens with another package?
say, `pip install --ignore-installed requests`

**Comment by tangyuelm** [comment]
Oh. The same errors happen when I both try the conda or pip. It seems that my server has some problem. Thank you very much.

**Comment by mthrok** [comment]
Glad to help.
