### ISSUE TITLE
Display filepath for `RuntimeError: Error loading audio file` in sox_io backend

### ISSUE THREAD

**Issue by rbracco** [pytorch/audio#1502]
## 🚀 Feature
When user encounters the error `RuntimeError: Error loading audio file: failed to open file.` using sox_io backend, the filepath should be displayed as part of the error message at the bottom of the stack trace.

## Motivation
This is a very common error when setting up a new dataset and it would be much faster to fix if the filepath were output to the user.

## Pitch
Wrap the relevant section of load with a try/except to catch RuntimeError and reraise with the filepath included so that the user may more easily fix the issue. I'm happy to PR if this is an acceptable fix. 

## Alternatives

Ideally the filepath would be added to the error at the original point of failure but it appears to be in c++ so I'm not sure how.

## Additional context

relevant code from [torchaudio/backend/sox_io_backend.py](https://github.com/pytorch/audio/blob/master/torchaudio/backend/sox_io_backend.py)
```python
if not torch.jit.is_scripting():
        if hasattr(filepath, 'read'):
            return torchaudio._torchaudio.load_audio_fileobj(
                filepath, frame_offset, num_frames, normalize, channels_first, format)
        filepath = os.fspath(filepath)
    return torch.ops.torchaudio.sox_io_load_audio_file(
        filepath, frame_offset, num_frames, normalize, channels_first, format)
```

**Comment by mthrok** [comment]
HI @rbracco 

Thanks for the suggestion. I'll take a look into it.

**Comment by mthrok** [comment]
Filed #1503. If no one picks it up, I will come back before the release.

**Comment by rbracco** [comment]
Awesome, thank you so much. Closing the issue.

**Comment by mthrok** [comment]
@rbracco I will keep this open until the actual change is implemented.
