### ISSUE TITLE
DownmixMono "channels_first" kwarg is unexpected keyword 

### ISSUE THREAD

**Issue by deepwilson** [pytorch/audio#155]
```
transform = torchaudio.transforms.DownmixMono(channels_first=True)
 __init__() got an unexpected keyword argument 'channels_first'
```

Hash : d92de5b

**Comment by jamarshon** [comment]
Hmm that's strange. It works for me
```
>>> torchaudio.transforms.DownmixMono(channels_first=True)
DownmixMono()
```
and it should work since it is in the code:
https://github.com/pytorch/audio/blob/d92de5b/torchaudio/transforms.py#L108
and it was added a while [back](https://github.com/pytorch/audio/pull/60).

Could you run [test_transforms.py](https://github.com/pytorch/audio/blob/d92de5b97fc6204db4b1e3ed20c03ac06f5d53f0/test/test_transforms.py#L70) and see if an error appears?
```
python -m unittest test/test_transforms.py
```

**Comment by deepwilson** [comment]
Running:
`python -m unittest test/test_transforms.py`
gives me
`RuntimeError: Failed to parse the argument list of a type annotation: name 'Optional' is not defined`

**Comment by deepwilson** [comment]
What would be the proper method to install torchaudio on colab?
@jamarshon please help.

**Comment by jamarshon** [comment]
@deepwilson I ran this on a Python3 colab and it worked. Let me know if it does 😄, although you may have to adjust the pytorch installation depending on desired Python and Cuda versions.
```
# Install dependencies
!apt-get install sox libsox-dev libsox-fmt-all

# Install pytorch 1.1.0 (https://pytorch.org/). Depends on Python and Cuda versions so look for correct commands
!pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
!pip3 install https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl

# install torchaudio
!pip install git+https://github.com/pytorch/audio.git@v0.2.0

# Run torchaudio
import torchaudio
transform = torchaudio.transforms.DownmixMono(channels_first=True)
print(transform)  # prints DownmixMono()
print(torchaudio.__version__)  # prints 0.2.0a0+7d7342f
```

**Comment by deepwilson** [comment]
Thank you so much @jamarshon !
I ran the following code which was wrong:
```
!apt-get install sox libsox-dev libsox-fmt-all
!git clone https://github.com/pytorch/audio.git
import os
os.chdir("audio")
!git checkout 5c9d33d  #301e2e9 d92de5b
!python setup.py install
import torchaudio
```


**Correct code/procedure to follow as per your instructions:**
```
import sys
sys.version
'3.6.8 (default, Jan 14 2019, 11:02:34) \n[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]'
```

```
!cat /usr/local/cuda/version.txt
CUDA Version 10.0.130
```

```
# Install dependencies
!apt-get install sox libsox-dev libsox-fmt-all
```

Go to [the following link and check for links corresponding to your python and CUDA versions](https://pytorch.org/get-started/locally/)
![image](https://user-images.githubusercontent.com/25292456/61643300-2d95c880-acc0-11e9-9c17-136ef854a1e4.png)

```
!pip3 install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
!pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
```

```
# install torchaudio
!pip install git+https://github.com/pytorch/audio.git@v0.2.0
```

```
# Run torchaudio
import torchaudio
transform = torchaudio.transforms.DownmixMono(channels_first=True)
print(transform)  # prints DownmixMono()
print(torchaudio.__version__)  # prints 0.2.0a0+7d7342f
```
Thanks once again @jamarshon !

**Comment by jamarshon** [comment]
@deepwilson Glad to hear it worked 😄
