### ISSUE TITLE
Force GPU tests run in GPU CIs

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1552]
We use [`skipIfNoCuda`](https://github.com/pytorch/audio/blob/15a7f78c4ecb007f4d1dcf70da2dc8791376d9b9/test/torchaudio_unittest/common_utils/case_utils.py#L107) decorator to skip CUDA tests when CUDA is not available. This is nice but in CI with GPUs we should raise an error if CUDA is not available. We should update the decorator, so that we can provide further option to fail.

## Setup
Please refer to the CONTRIBUTING.md for setting up `torchaudio` development environment.

## Steps

1. Update the decorator to something like the following:
```python
def skipIfNoCuda(test_item):
    if torch.cuda.is_available():
        return test_item
    force_cuda_test = os.environ.get('TORCHAUDIO_TEST_FORCE_CUDA', '0')
    if force_cuda_test not in ['0', '1']:
        raise ValueError('"TORCHAUDIO_TEST_FORCE_CUDA" must be either "0" or "1".')
    if force_cuda_test == '1':
        raise RuntimeError('"TORCHAUDIO_TEST_FORCE_CUDA" is set but CUDA is not available.')
    return unittest.skip('CUDA is not available.')(test_item)
```
2. Update CI to device `TORCHAUDIO_TEST_FORCE_CUDA` environment variable
    1. Add the definition [here](https://github.com/pytorch/audio/blob/d4d09074f4cd0b92f168836638b8ecd81186a4c9/.circleci/config.yml.in#L468) and [here](https://github.com/pytorch/audio/blob/d4d09074f4cd0b92f168836638b8ecd81186a4c9/.circleci/config.yml.in#L502)
    2. Run `.circleci/regenerate.py`, so that `.circleci/config.yml` is updated.
    3. Use [CircleCI CLI](https://circleci.com/docs/2.0/local-cli/#installation) to verify that the `config.yml` is valid. (`circleci config validate`)

## Test

1. local test
This should work
```
CUDA_VISIBLE_DEVICES=0  TORCHAUDIO_TEST_FORCE_CUDA=0 pytest test/torchaudio_unittest/functional/torchscript_consistency_cuda_test.py
```
This should fail
```
CUDA_VISIBLE_DEVICES=0 TORCHAUDIO_TEST_FORCE_CUDA=1 pytest test/torchaudio_unittest/functional/torchscript_consistency_cuda_test.py
```

2. CI test
Please make a draft PR and see if the GPU tests pass.

**Comment by salilsdesai** [comment]
I'd like to work on this.

**Comment by mthrok** [comment]
Hi @salilsdesai 

Thanks. Let me know if you need help.
