### ISSUE TITLE
reverb in apply_effects_tensor output -> 2 channels

### ISSUE THREAD

**Issue by songtaoshi** [pytorch/audio#1560]
## ❓ Questions and Help

Hi, I am using apply_effects_tensor to reverb my data, but I find that the output will generate 2 channels and the two channels are not the same, Is there any explanation?

**Comment by songtaoshi** [comment]
@brianw @ezyang @swolchok @raff

**Comment by mthrok** [comment]
Hi @songtaoshi 

From the `sox` documentation http://sox.sourceforge.net/sox.html
> Add reverberation to the audio using the ‘freeverb’ algorithm. A reverberation effect is sometimes desirable for concert halls that are too small or contain so many people that the hall’s natural reverberance is diminished. Applying a small amount of stereo reverb to a (dry) mono signal will usually make it sound more natural. See [3] for a detailed description of reverberation.

The link to [3] is found [here](https://web.archive.org/web/20051221051245/http://www.harmony-central.com/Effects/Articles/Reverb/).

I think sox is applying stereo reverb to emulate the different reverberation to each channel.

The description of `freeverb` algorithm can be found here. https://ccrma.stanford.edu/~jos/pasp/Freeverb.html
> Figure 3.8 shows the default signal-processing settings for the Freeverb left stereo channel. Processing for the right channel is obtained by adding an integer to each of the twelve delay-line lengths.
