### ISSUE TITLE
Using the library directly from Libtorch in C++

### ISSUE THREAD

**Issue by QuantScientist** [pytorch/audio#1562]
Hello,
How can I use this library directly from Libtorch in C++ in order to read a wave file into a torch::tensor?
I am only interested in C++, not Python. 

Thanks,

**Comment by mthrok** [comment]
Hi @QuantScientist 

There is a way to use torchaudio's I/O function from C++ but it's not like the usual C++ code, where you include header file and link your application.

We use TorchScript to deploy models and data processing pipelines. To do that,
1. Write operation in Python
2. Compile the Python code with TorchScript and save the object.
3. Load the saved TorchScript object from C++ and run.

There is an example directory [`libtorchaudio`](https://github.com/pytorch/audio/tree/master/examples/libtorchaudio), which explains the process. Specifically you can use [Loader](https://github.com/mthrok/audio/blob/436692d761fbe34d68f470bfd4c606d320a18eeb/examples/libtorchaudio/speech_recognition/build_pipeline_from_fairseq.py#L65-L70) to load audio from file in C++.

If you want to hack around the original code, then you can use [`load_audio_file`](https://github.com/pytorch/audio/blob/afb6626c440e92423549818401afa54f4addfb39/torchaudio/csrc/sox/io.h#L18-L24), however, C++ code in torchaudio is not public API so it can change anytime, and we do not provide support for the regular use (including the header in your project).

**Comment by QuantScientist** [comment]
Thanks @mthrok 
I hacked this lib: https://github.com/adamstark/AudioFile to read and write wav files between and to a torch::Tensor and it works without any problems.

**Comment by mthrok** [comment]
Cool. Nice to know there is such a solution.

**Comment by dtitov** [comment]
@ghost, do you have an example if your “hack” somewhere?
