### ISSUE TITLE
Windows GPU CI is not running GPU tests

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1565]
Creating this issue for the sake of keep tracking the issue and come back later to resolve it. In https://github.com/pytorch/audio/pull/1559, we tried forcing GPU tests in Windows. Turned out that GPU driver that CircleCI provides as default in `windows-gpu` executor is too old to run GPU operation from PyTorch nightly. We need to fix this.

cc @NicolasHug @malfet @seemethere

**Comment by NicolasHug** [comment]
For ref, sibling issue in torchvision: https://github.com/pytorch/vision/issues/4006

**Comment by nbcsm** [comment]
@mszhanyi

**Comment by mszhanyi** [comment]
looks it's resolved.
https://github.com/pytorch/audio/pull/1708
![image](https://user-images.githubusercontent.com/16190118/130570749-417df28b-5ca0-4989-b2cc-6c277b981e65.png)
