### ISSUE TITLE
Remove lazy behavior from MelScale

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1569]
Address https://github.com/pytorch/audio/issues/1510

In 0.9.0 we are deprecating the lazy behavior of MelScale because it can make an invalid TorchScript object and it does not align with the design of torchaudio. Now in master branch, we can remove the implementation.

See [CONTRIBUTING.md](https://github.com/pytorch/audio/blob/master/CONTRIBUTING.md) for setting up the development environment.

## Steps
1.  Replace [`n_stft: Optional[int] = None`](https://github.com/pytorch/audio/blob/6f9c14bec787d952c2aa1b6a13d11509c7a38bed/torchaudio/transforms.py#L258) with `n_stft: int = 201`. 
2. Remove [the branches](https://github.com/pytorch/audio/blob/6f9c14bec787d952c2aa1b6a13d11509c7a38bed/torchaudio/transforms.py#L271-L282) for `n_stft = None`
3. Remove [`__prepare_script__`](https://github.com/pytorch/audio/blob/6f9c14bec787d952c2aa1b6a13d11509c7a38bed/torchaudio/transforms.py#L285-L297) method
4. Remove [the case `numel() == 0`](https://github.com/pytorch/audio/blob/6f9c14bec787d952c2aa1b6a13d11509c7a38bed/torchaudio/transforms.py#L312-L319)
5. Remove [test](https://github.com/pytorch/audio/blob/6f9c14bec787d952c2aa1b6a13d11509c7a38bed/test/torchaudio_unittest/transforms/torchscript_consistency_impl.py#L62-L65)

## Tests

Run test `cd test && pytest torchaudio_unittest.transforms -vk MelScale` and make changes to failures.

**Comment by Patil2099** [comment]
I would love to work on this @mthrok

**Comment by mthrok** [comment]
Resolved by #1636
