### ISSUE TITLE
torchaudio.compliance.kaldi.spectrogram is very different from torchaudio.transforms.spectrogram

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#157]
Does `torchaudio.compliance.kaldi.spectrogram` only currently support vectors? 

When feeding a tensor of shape `torch.Size([2, 276858])` the result is not what's expected, yet there is no error. I would expect a "train pattern" to be visible, as in the second figure below.

This is what kaldi gives
![download (1)](https://user-images.githubusercontent.com/3047868/61561315-a553c100-aa3c-11e9-8ad8-e5aab8a96069.png)

This is what `torchaudio.transforms.spectrogram` gives
![download (2)](https://user-images.githubusercontent.com/3047868/61561316-a553c100-aa3c-11e9-83c1-4787f3fce509.png)

The "train pattern" is also visible on [academo.org](https://academo.org/demos/spectrum-analyzer/).

**Comment by vincentqb** [comment]
Code to generate the two figures below. Sound file [here](https://github.com/vincentqb/audio-tutorial/blob/master/assets/steam-train-whistle-daniel_simon-converted-from-mp3.wav).

```
import torch
import torchaudio
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt

filename = "assets/steam-train-whistle-daniel_simon-converted-from-mp3.wav"
tensor, frequency = torchaudio.load(filename)

spec = torchaudio.transforms.Spectrogram()(tensor)
plt.imshow(spec.log2().transpose(1,2)[0,:,:].numpy(), cmap='gray')
plt.show()

spec = torchaudio.compliance.kaldi.spectrogram(tensor)
plt.imshow(spec.log2().transpose(0,1).numpy(), cmap='gray')
plt.show()
```

**Comment by vincentqb** [comment]
I get similar result with
```
spec = torchaudio.compliance.kaldi.spectrogram(tensor[0,:].view(1,-1))
plt.imshow(spec.log2().transpose(0,1).numpy(), cmap='gray')
plt.show()
```

**Comment by vincentqb** [comment]
Note also that I had to feed the tensor with shape `torch.Size([1, 276858])` and not `torch.Size([276858])`.

**Comment by vincentqb** [comment]
The main issue is that the result from kaldi looks like noise, and the fact that the train pattern is not visible in the spectrogram is unexpected.

**Comment by cpuhrsch** [comment]
Try smaller inputs, zeros, ones, arange, etc. ; but in general we want to standardize on kaldi and whatever they produce is what we produce.

**Comment by jamarshon** [comment]
@vincentqb I could investigate the flags more [kaldi.spectrogram](https://pytorch.org/audio/compliance.kaldi.html#torchaudio.compliance.kaldi.spectrogram) to get a more closer result but is this more similar to what you would expect?
```
import torch
import torchaudio
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt

filename = "/Users/jamarshon/Documents/GitHub/audio/test/assets/steam-train-whistle-daniel_simon.mp3"
s, sr = torchaudio.load(filename)
EPSILON = torch.tensor(torch.finfo(torch.float).eps, dtype=torch.get_default_dtype())

spec = torchaudio.transforms.Spectrogram()(s)
x = torch.max(EPSILON, spec).log2().transpose(1,2)[0,:,:]
plt.imshow(x.numpy(), cmap='gray')
plt.show()

n_fft = 400.0
fl = n_fft / sr * 1000.0
fs = fl / 2.0
spec2 = torchaudio.compliance.kaldi.spectrogram(
	s, dither=0.0, window_type='hanning', 
	frame_length=fl, frame_shift=fs, remove_dc_offset=False, 
	round_to_power_of_two=False, sample_frequency=sr)
y = spec2.t()
plt.imshow(y.numpy(), cmap='gray')
plt.show()
```
Spec1:
![spec1](https://user-images.githubusercontent.com/10252970/61650721-4da69700-ac82-11e9-94eb-2ced8c8a3be1.png)
Spec2:
![spec2](https://user-images.githubusercontent.com/10252970/61650725-50a18780-ac82-11e9-9785-8008c6db6599.png)

**Comment by vincentqb** [comment]
Great, that's good enough. Thanks!

**Comment by mahmoodn** [comment]
@vincentqb 
Can you upload the wav file again. I can not find it. The link is broken.

**Comment by vincentqb** [comment]
> @vincentqb
> Can you upload the wav file again. I can not find it. The link is broken.

The file can still be accessed [here](https://raw.githubusercontent.com/vincentqb/audio-tutorial/90371e6ab64ad04f1930fa079a816630145c89d2/assets/steam-train-whistle-daniel_simon-converted-from-mp3.wav).

**Comment by vincentqb** [comment]
For reference, this is enough to produce reasonable spectrogram.
```
spec = torchaudio.compliance.kaldi.spectrogram(tensor, dither=0.)
plt.imshow(spec.log2().transpose(0,1).numpy(), cmap='gray')
plt.show()
```
