### ISSUE TITLE
Using MelSpec when power=None

### ISSUE THREAD

**Issue by SaoYear** [pytorch/audio#1570]
## To Reproduce

1. Use MelSpectrogram(..., power=None)

```
mel_spec = MelSpectrogram(
            sample_rate=self.feat_params["sample_rate"],
            n_fft=self.feat_params["n_window"],
            win_length=self.feat_params["n_window"],
            hop_length=self.feat_params["hop_length"],
            f_min=self.feat_params["f_min"],
            f_max=self.feat_params["f_max"],
            n_mels=self.feat_params["n_mels"],
            window_fn=torch.hamming_window,
            wkwargs={"periodic": False},
            power=None,
            )
mel_utt = mel_spec(utt_in_time)
```

## Environment

 - What commands did you used to install torchaudio (conda/pip/build from source)?
 - If you are building from source, which commit is it?
 - What does `torchaudio.__version__` print? (If applicable)

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.8.1+cu111
 - Torchaudio: 0.8.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): from pytorch.org
 - Python version: 3.85
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: A-100
 - Any other relevant information:

## Additional context
I actually wanted to implement time-stretching here. Think what I shall do is to use Spectrogram(..., power=0) to transform time-domain signal into frequency domain with complex numbers, and then use TimeStretch to do the time stretching. If I want to get the Mel_spec, I shall use MelScale to the obtained data from TimeStrecth right?
Anyways, just found there is a bug when am using Mel_Spec with power=0.

**Comment by mthrok** [comment]
Hi @SaoYear 

To stretch mel spectrogram, you should be able to do `Spectrogram(power=None)` -> `TimeStretch` -> `.abs().power(power)` -> `MelScale`.

MelScale conversion, in my understanding, is simply weighted sum over different frequency bins, and it is implemented as matrix multiplication between spectrogram and frequency bin matrix. The reason why we see is frequency bin matrix is real-valued, while raw spectrogram is complex-valued and we recently switched native complex type.
I was aware of this error but I am not yet sure what is the right fix. Specifically, I am not sure if Mel scale conversion is defined on raw (complex valued) spectrogram. If you know a reference of scientific definition of Mel scale conversion, please let me know.
If we fix the mel scale conversion for raw spectrogram, (matrix multiplication of raw spectrogram and frequency bin matrix) in a way that frequency bin matrix is converted to complex type with 0 for imaginary value, I think the resulting modified spectrogram has a different norm than applying mel scale to a power spectrogram.
@carolineechen and I had a casual discussion and we are considering to change `MelSpectrogram`'s `power` annotation from `Optional[float]` to `float`.
What do you think?

**Comment by SaoYear** [comment]
Thanks! I have finished the time stretching part for Mel spec. 

As for the MFCC, I think a good reference might be SLP2 by J&M. 
https://github.com/rain1024/slp2-pdf/blob/master/chapter-wise-pdf/%5B09%5D%20Automatic%20Speech%20Recognition.pdf
Section 9.3. For my understanding, the Mel scale is designed for approaching human hearing, which is mostly related with energy only. So, it might be somehow weird to use complex spectrogram with Mel Scale. But... am not sure about that.

And I think changing optional float to float sounds like a great solution. It might reduce the confusion for some degree.

**Comment by mthrok** [comment]
@SaoYear 

Thanks for the link. Indeed the section 9.3.4 says `The result of FFT will be information about the amount of energy at each frequency band.`, so I think it's okay for us to only consider the case where `power` is not `None` for Mel scale.

@carolineechen Does this make sense to you?

**Comment by carolineechen** [comment]
@mthrok yup, I think it makes sense to only consider the case where `power` is not `None` for MelSpectrogram.

**Comment by SaoYear** [comment]
Hi mthrok, 

Got one more problem that may need your advise. 

I wanna do random pitch shifting to one batch of clips. Right now I'm using apply_sox_effect to do this part, but found really slow (4mins per epoch):
```
with torch.no_grad():
            scale = random.randint(1, scale)
            level = scale * [-50, 50][self.rand_bool()]
            effect = [
              ["pitch", str(level)],
              ["rate", str(self.sample_rate)]
            ]
            utt_aug, _ = apply_effects_tensor(utt.clone().detach().cpu(), self.sample_rate, effect, channels_first=True)
        return self.mel_spec(utt_aug.to(utt.get_device())), labels
```

Then I changed the code by resample + time stretching:
```
        scale = [-1, 1][self.rand_bool()] * random.randint(1, scale) * 0.5
        level = 2 ** (scale/12)
        resampler = self.__get_resampler(level)
        utt_resample = resampler(utt)
        utt_cp = self.spec_complex(utt_resample)
        utt_ts = torch.view_as_complex(self.time_stretcher(utt_cp, level)).abs()
        utt_aug = self.mel_scale(utt_ts)
        print((self.sample_rate * 3 * 10) // self.feat_params["hop_length"])
        return utt_aug[:, :, :(441000) // self.feat_params["hop_length"] + 1], labels, level
```
where get_resampler just creates a Resample object from torchaudio.transforms.Resample. But this made the code even slower! (~4mins30s per epoch)...

Do you have any advise on how to accelerate the computation?

**Comment by mthrok** [comment]
@SaoYear 

I do see why it is not fast, but it is not trivial to resolve it.

Couple of suggestions
- Can you move `apply_effects_tensor` and pitch shift to right after data is loaded? Probably somewhere close to DataLoader. Moving data from CUDA to CPU is expensive here.
- For the use of `Resample`, we have made `T.Resample` significantly faster in the latest release (scheduled to be released tomorrow, but you can try with nightly build), by caching the kernel. If you can pick couple of combinations for sampling rates, and keep the same resample object, (not instantiating one every time), then as a total, you will benefit from caching.

If you use `Resample` with prefixed sample rate, you can keep the batch in CUDA device, and since internally, it's convolution, it should be very fast.

**Comment by SaoYear** [comment]
Thanks a lot for your recommendations!

Looking forward to the newest `Resample` since I am changing the sample rate in each batch.

Cheers!

**Comment by mthrok** [comment]
@SaoYear 

0.9 has been released and @carolineechen has added a very detailed tutorial about resampling. Please have a look https://pytorch.org/tutorials/beginner/audio_preprocessing_tutorial.html#resampling

BTW there was an attempt to add pitch shift
https://github.com/pytorch/audio/pull/445

I am wondering if it will be useful to have a native implementation in `torchaudio`. What do you think?
