### ISSUE TITLE
🚀 Feature Proposal: Linear Frequency Cepstral Coefficients (LFCC)

### ISSUE THREAD

**Issue by Joool** [pytorch/audio#1574]
## 🚀 Feature
Add linear frequency cepstral coefficients (think MFCC but with a liner filterbank instead of mel) as a transform.

## Motivation
I implemented linear frequency cepstral coefficients (LFCC) for a recent project based on the torchaudio MFCC implementation. If this is of interest to the project, I would happily commit them.

## Pitch
LFCCs are, for example, used in automatic speaker verification. This would also ease experimentation in other contexts.

## Additional context
This is related to #942 and #943. These PRs propose changes that might help people build different cepstral coefficients by chaining together different other transforms. My solution would be an end-to-end solution, i.e., add a new transform similar to MFCCs. I see value in both approaches and would like some input on this.

**Comment by mthrok** [comment]
Hi @Joool 

Thanks for the proposal. I think idea-wise it is a nice extension.
Couple of questions
- Is there a paper that we can learn the effect / usage of this?
- `torchaudio.transforms.MFCC` is composed of `Spectrogram`, `MelScale` and `DCT transformation`. Is LFCC simply replacing `MelScale`? or did you have to do something more to make it work with the current interface?

**Comment by Joool** [comment]
Hi,

> * Is there a paper that we can learn the effect / usage of this?

Sorry forgot to link a paper: 
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.717.6743&rep=rep1&type=pdf

See Figure 1 for a comparison.

> * `torchaudio.transforms.MFCC` is composed of `Spectrogram`, `MelScale` and `DCT transformation`. Is LFCC simply replacing `MelScale`? or did you have to do something more to make it work with the current interface?

Yes, I basically replaced the matrix creation of MelScale to use a linear scale filter bank instead:

https://github.com/pytorch/audio/blob/c5d0390c8d9a0356d350bfced1c2152ae308e9b9/torchaudio/transforms.py#L280-L283

I would add a new function for that and I would also propose to rename `create_fb_matrix` to something which makes clear it creates a mel filterbank.
#943 goes in a similar direction, but instead wants to change the spectrogram API.

Additionally, spafe offers an implementation in numpy which could be used for differential testing:

https://github.com/SuperKogito/spafe/blob/master/spafe/fbanks/linear_fbanks.py

However, that would add a new dependency.

**Comment by mthrok** [comment]
Hi @Joool

Here is my understanding of the proposal here.

1. Add `torchaudio.functional.linear_fbanks`.
1. Add `torchaudio.transforms.LFCC`
1. Rename `torchaudio.functional.create_fb_matrix` to `torchaudio.functional.melscale_fbanks`. (this will take 2 release cycles)

I think these are reasonable / good addition / row risk.

Now we need to think of interfaces of new functions / transforms.

Did you find the interface of `spafe`'s `linear_fbanks` good? How do you recommend?
We do not want to add a new dependency and we do not even depend on numpy so we will need to implement it with PyTorch.

**Comment by Joool** [comment]
Hi @mthrok 

I would propose a similar interface to `torchaudio.functional.create_fb_matrix` excluding the `norm` and `mel_scale` parameters. The implementation would work analogous except the mel scaling.

I think the only sensible place for `spafe` would be for testing, i.e., similarly on how `librosa` is used. However, that would be optional.

**Comment by mthrok** [comment]
LFCC was added in #1611. Closing the issue. Feel free to re-open if that's not the case. @nateanl @Joool 

Thanks!
