### ISSUE TITLE
Cannot set audio backend Apple M1

### ISSUE THREAD

**Issue by antic11d** [pytorch/audio#1594]
## 🐛 Bug

Hi, I can't seem to set audio backend, it always error even though I have installed `sox`.
## To Reproduce

```python
import torchaudio
torchaudio.set_audio_backend("sox_io")
```

I get the following error:
> RuntimeError: Backend "sox_io" is not one of available backends: [].

## Environment

 - What commands did you used to install torchaudio (conda/pip/build from source)? 
 > pip
 - If you are building from source, which commit is it?
 - What does `torchaudio.__version__` print? (If applicable)
> '0.9.0'

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

>PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A
OS: macOS 11.4 (arm64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.9)
CMake version: Could not collect
Libc version: N/A
Python version: 3.9 (64-bit runtime)
Python platform: macOS-11.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0
[conda] numpy                     1.20.3           py39h1f3b974_1    conda-forge
[conda] torch                     1.9.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi

## Additional context

I am trying to load `.ogg` files, and this is what's blocking me from doing it.

**Comment by mthrok** [comment]
Hi @antic11d 

Thanks for the report. This means the M1 binary is not compiled with sox capability. (note that `torchaudio` does not depend on external `sox`)

@malfet I'm sorry I forgot to tell you but `BUILD_SOX=1` must be set when building packages for Linux and macOS. How can we resolve the situation for M1?

**Comment by suissemaxx** [comment]
I observe the same error. Any hints how to solve this issue would be very helpful. Thanks in advance. 👍

**Comment by malfet** [comment]
Rebuilt the binaries and uploaded them to `https://download.pytorch.org/whl/test/cpu/torchaudio/`
Please try installing them using `pip3 install --extra-index-url https://download.pytorch.org/whl/test/cpu torchaudio` and let me know if they work as expected

**Comment by antic11d** [comment]
Hi @malfet,
I've tested the new build, and it seems like everything works fine, i.e. I can now set the `sox` backend successfully.
AFAIC, this issue can be closed. Thanks, again! 😊
