### ISSUE TITLE
Does nightly build pytorchaudio support GPU RNNT loss?

### ISSUE THREAD

**Issue by SoonSYJ** [pytorch/audio#1617]
Dear researchers,
I have tried to pip install torchaudio-0.10.0.dev20210627-cp36-cp36m-linux_x86_64.whl. After installing the package successfully, I found the RNNT loss only have a CPU version. And move tensors from cuda to cpu really cost a lot of time. So I just ask about how can I get a GPU version isntalling.

**Comment by carolineechen** [comment]
Hi @SoonSYJ,

I don't believe the torchaudio nightly binary supports GPU RNNT loss, but it is currently supported in master, and you should be able to use it if you install torchaudio from source, as described in the [contributing doc](https://github.com/pytorch/audio/blob/master/CONTRIBUTING.md#development-installation), with the following change(s)
- RNNT loss is not supported by default, so you will need to add `BUILD_RNNT=1` to this command `BUILD_SOX=1 python setup.py develop`
- It should automatically compile RNNT loss with GPU support if it detects a CUDA device, but you can optionally add `USE_CUDA=1` option here to force it to build with CUDA.

Let me know if you have any other questions.

**Comment by SoonSYJ** [comment]
Hi @carolineechen,
Built the GPU version successfully, finally. Here I have got some time consumption and gpu memory usage matrics which is tested on a Telsa M40. Do you have any benchmark to be a reference, expecially the GPU usage?

B:10 T:125 U:20 V:14830 t_forward: 0.03090s t_backward:0.00570s GPU:5.94G

B: batch size
T: frames
U: number of tokens
V: vocabulary size

**Comment by carolineechen** [comment]
Hi @SoonSYJ, unfortunately we do not currently have reference benchmarks for RNNT loss, as this feature is not yet finalized and not included in our release binary. We do plan on documenting some benchmarks when we release this feature though.

**Comment by mthrok** [comment]
Consolidating the issue. Please comment on #1657
