### ISSUE TITLE
Error when using Resampler on GPU with torchaudio 0.9

### ISSUE THREAD

**Issue by mravanelli** [pytorch/audio#1619]
Hi,
it looks like there is a small issue when using the resampler with torchaudio 0.9.
I indeed got the error below, when running the following code:

```
import torch
import torchaudio
resampler = torchaudio.transforms.Resample(16000, 8000)
x = torch.rand(4, 32000, device='cuda:0')
resampler(x)
```

```
  File "<stdin>", line 1, in <module>
  File "/home/mila/r/ravanelm/anaconda3/envs/py19/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mila/r/ravanelm/anaconda3/envs/py19/lib/python3.9/site-packages/torchaudio/transforms.py", line 716, in forward
    return _apply_sinc_resample_kernel(
  File "/home/mila/r/ravanelm/anaconda3/envs/py19/lib/python3.9/site-packages/torchaudio/functional/functional.py", line 1387, in _apply_sinc_resample_kernel
    resampled = torch.nn.functional.conv1d(waveform[:, None], kernel, stride=orig_freq)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the sam
```
Note that everything is fine with cpu and with torchaudio 0.8.1

**Comment by yoyololicon** [comment]
@mravanelli 
You didn't move your resampler to the same device. 
Use `resampler = torchaudio.transforms.Resample(16000, 8000).to('cuda:0')` should fix the problem.

**Comment by mravanelli** [comment]
Hi @yoyololicon,
thank you for your reply. 
The issue is that with torchaudio 0.8 the error doesn't show up and this might cause incompatibilities with pre-existing codes written with torchaudio 0.8. Isn't it reasonable to put the kernel in the same device as the input signal (as probably done before)?

**Comment by yoyololicon** [comment]
Hi @mravanelli 
Yes, it was meant to be a BC-breaking change according to #1514, I'll just copy some of the statements here.

> To maintain the original behavior would require moving the cached kernel to the device and dtype of the input waveform every time transforms.Resample is called, and this could result in unintended side effects; running a CPU transforms on CUDA inputs would have overhead from constantly moving a cached CPU kernel to CUDA, and the expectation is that the user will manually move the transforms themself to the correct device and dtype (ex/ resample = transforms.Resample; resample = resample.to(device=torch.device('cuda'), dtype=torch.float16). This PR removes the moving of the cached kernel to be of the correct device and dtype at every call to it, which will now throw an error if a user does not move the transform to CUDA but calls the function on a CUDA waveform.

**Comment by mravanelli** [comment]
ok,
thank you for the clarification. I will change my code to make it work with
the latest version.

Best,

Mirco

**Comment by mthrok** [comment]
We have added kernel cache mechanism to `transforms.Resample` in `0.9`.
The kernel is pre-computed when the transform is instantiated, and it has to be moved to the proper device. This semantic follows the regular usage of `torch.nn.Module`.

Looks like this was missing from [0.9 release note](https://github.com/pytorch/audio/releases/tag/v0.9.0), I will fix the release note.

cc @carolineechen
