### ISSUE TITLE
Error while importing torchaudio

### ISSUE THREAD

**Issue by xXDarkCubeXx** [pytorch/audio#1632]
## 🐛 Bug

I'm getting this error:
`AttributeError: module 'torchaudio._internal.module_utils' has no attribute 'requires_sox'`
while importing torchaudio

## To Reproduce
I'm using a kaggle notebook
just executed these lines:
```python
!pip install --upgrade torch
!pip install --upgrade torchaudio
import torchaudio
```
## Environment
(collect_env.py output)
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.10

Python version: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.120+-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 450.119.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.7.1
[pip3] numpy==1.19.5
[pip3] pytorch-ignite==0.4.5
[pip3] pytorch-lightning==1.3.8
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0
[pip3] torchmetrics==0.4.1
[pip3] torchtext==0.8.0a0+cd6902d
[pip3] torchvision==0.8.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.0.221             h6bb024c_0    nvidia
[conda] libblas                   3.9.0                     9_mkl    conda-forge
[conda] libcblas                  3.9.0                     9_mkl    conda-forge
[conda] liblapack                 3.9.0                     9_mkl    conda-forge
[conda] liblapacke                3.9.0                     9_mkl    conda-forge
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] msgpack-numpy             0.4.7.1                  pypi_0    pypi
[conda] numpy                     1.19.5           py37haa41c4c_1    conda-forge
[conda] pytorch-ignite            0.4.5                    pypi_0    pypi
[conda] pytorch-lightning         1.3.8                    pypi_0    pypi
[conda] torch                     1.9.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
[conda] torchmetrics              0.4.1                    pypi_0    pypi
[conda] torchtext                 0.8.0                      py37    pytorch
[conda] torchvision               0.8.1                py37_cu110    pytorch

**Comment by nameless-akash** [comment]
Can you please share the screenshot of the error
.

**Comment by xXDarkCubeXx** [comment]
sure,
![image](https://user-images.githubusercontent.com/41758992/126063459-5a7d13f2-16de-4f5a-a155-4b43658b6437.png)

**Comment by xXDarkCubeXx** [comment]
huh, this now is peculiar. I think I know what's wrong. in my code (after playing around for a while) I imported torchaudio and THEN upgraded it. I don't know why but it messed things up (i.e. trying to import torchaudio caused the above error)
