### ISSUE TITLE
module 'torchaudio' has no attribute 'models'

### ISSUE THREAD

**Issue by aligoglos** [pytorch/audio#1660]
## 🐛 Bug

I tried to run these lines :
```
import torchaudio
model = torchaudio.models.Wav2Vec2Model()
```
but got error:
```

    model = torchaudio.models.Wav2Vec2Model()
AttributeError: module 'torchaudio' has no attribute 'models'
```

## Environment
PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: (GCC) 10.2.0
Clang version: Could not collect
CMake version: version 3.20.3
Libc version: N/A

Python version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19043-SP0
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 960M
Nvidia driver version: 471.11
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-msssim==0.2.1
[pip3] torch==1.9.0+cu111
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0

**Comment by mthrok** [comment]
Hi @aligoglos 

Looks like `models` import is missing from `torchaudio.__init__.py`.
Can you try the following?

```python
import torchaudio.models
```

**Comment by aligoglos** [comment]
It works.
Thanks.

**Comment by nateanl** [comment]
Hi @aligoglos. #1664 should fix the models import issue. Now you can use ``torchaudio.models.Wav2Vec2Model()`` for your code.
