### ISSUE TITLE
LFCC sporadically fails autograd test for some config

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1661]
The newly added LFCC is failing autograd test.
https://app.circleci.com/pipelines/github/pytorch/audio/6801/workflows/c08649af-e7cf-443d-8dc0-d60cd3e66cb2/jobs/282812

It only happens on Linux CUDA Python 3.9 environment (so far).

Looking at [the code](https://github.com/pytorch/audio/pull/1611), there is no obvious randomness used.

Needs investigation.

cc @nateanl

**Comment by nateanl** [comment]
Interesting. Let me dig into it.

**Comment by nateanl** [comment]
It's interesting that [MelSpectrogram](https://github.com/pytorch/audio/blob/main/test/torchaudio_unittest/transforms/autograd_test_impl.py#L87) needs a ``nondet_tol`` for gradcheck while MFCC doesn't need it.
```
def test_melspectrogram(self):
    # replication_pad1d_backward_cuda is not deteministic and
    # gives very small (~2.7756e-17) difference.
    #
    # See https://github.com/pytorch/pytorch/issues/54093
    sample_rate = 8000
    transform = T.MelSpectrogram(sample_rate=sample_rate)
    waveform = get_whitenoise(sample_rate=sample_rate, duration=0.05, n_channels=2)
    self.assert_grad(transform, [waveform], nondet_tol=1e-10)
```
```
@parameterized.expand([(False, ), (True, )])
def test_mfcc(self, log_mels):
    sample_rate = 8000
    transform = T.MFCC(sample_rate=sample_rate, log_mels=log_mels)
    waveform = get_whitenoise(sample_rate=sample_rate, duration=0.05, n_channels=2)
    self.assert_grad(transform, [waveform])
```

**Comment by mthrok** [comment]
TODO: 
- double check that the input is not modified.
- compare MFCC and LFCC step by step to see where it might happen.
