### ISSUE TITLE
Typo in audio_preprocessing_tutorial

### ISSUE THREAD

**Issue by saareliad** [pytorch/audio#1699]
## 📚 Documentation

see here:
https://pytorch.org/tutorials/beginner/audio_preprocessing_tutorial.html#performance-benchmarking 
got a typo in last line, 

    "upsample (8 -> 16 kHz)": [8000, 1600],

should be

    "upsample (8 -> 16 kHz)": [8000, 16000],

I was looking at the tutorial to find real-life application examples of these functions (resampling, Pitch, GrifinLim) in DL pipelines,  
if you can point me out it would be great :)

**Comment by carolineechen** [comment]
Hi @saareliad, thanks for pointing this out! I have created a PR to fix this https://github.com/pytorch/tutorials/pull/1649. Resampling in DL pipelines is generally used in the preprocessing stage, to ensure that all audio waveforms (training/valid/test) have consistent sampling rates, despite potentially coming from sources that sampled at different rates. [Here](https://github.com/huggingface/transformers/blob/e87505f3a1a6f1b301f16ecb8522451eee13e726/examples/research_projects/wav2vec2/run_common_voice.py#L389) is one such example.

@mthrok @nateanl Could you provide context/examples of Pitch and GiffinLim?

**Comment by nateanl** [comment]
Sure. GriffinLim aims at recovering the waveform from a magnitude-only spectrogram. The spectrogram doesn't contain the phase information. GriffinLim initializes the phase (either randomly or an all-ones matrix) and apply iSTFT on ``spectrogram * phase`` (a complex-valued matrix) to get the waveform. Then it applies STFT on the waveform to get an updated phase matrix, and so on. After several iterations of STFT and iSTFT, we can get an estimated waveform from the spectrogram.
