### ISSUE TITLE
Cannot find modules after install

### ISSUE THREAD

**Issue by tarekmaketechno** [pytorch/audio#172]
After successful installation of torchaudio in conda environment, I am able to import the module `import torchaudio`, but I am unable to import any submodules (i.e. `import torchaudio.transforms as t` ) 

This seems like a very promising project... sorry to see that there are so many installation issues. Let me know if any further information is needed to reproduce the error.

Thank you for your efforts!

**Comment by jamarshon** [comment]
@tarekmaketechno What command did you use to install torchaudio? Also what is the error message when trying to import the submodules?

**Comment by tarekmaketechno** [comment]
@jamarshon I think I fixed the issue - I had run setup using sudo (to work around a dependency issue)...  this seems to have caused all sorts of other dependency problems. I've gotten it working now by redoing the entire install in a fresh conda environment.

Thanks just the same though!
