### ISSUE TITLE
Working with ".webm" files 

### ISSUE THREAD

**Issue by m-ali-awan** [pytorch/audio#1723]
As fastaudio uses torchaudio, so that's why I am referring both.

I have included .webm in audio_extensions, but right now it's now working with AudioTensor.create, and also with plain torchaudio.
I have tried different backends sox_io,soundfile, but it doesn't work.

But with librosa, load, I am able to work with it.

So, kindly guide me how to use .webm audio files with torchaudio.

Thanks.

**Comment by mthrok** [comment]
Starting v0.12.0, WebM data can be loaded with FFmpeg-based I/O (either sox_io backend with FFmpeg fallback or `torchaudio.io.StreamReader`)
