### ISSUE TITLE
[BUG] ImportError when importing torchaudio (nightly)

### ISSUE THREAD

**Issue by nateanl** [pytorch/audio#1749]
## To Reproduce

- Install the nightly torchaudio
- Run:
``import torchaudio``

## Expected behavior

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "conda/envs/dev/lib/python3.9/site-packages/torchaudio/__init__.py", line 32, in <module>
    from torchaudio import _torchaudio  # noqa
ImportError: libtorch_hip.so: cannot open shared object file: No such file or directory
```

## Environment

PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.20.4
Libc version: glibc-2.27

Python version: 3.9.6 (default, Jul 30 2021, 16:35:19)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1051-aws-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.1.105

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-lightning==1.4.5
[pip3] torch==1.9.0+cu111
[pip3] torchaudio==0.10.0.dev20210902+rocm4.1
[pip3] torchmetrics==0.5.1
[conda] numpy                     1.21.2                   pypi_0    pypi
[conda] pytorch-lightning         1.4.5                    pypi_0    pypi
[conda] torch                     1.9.0+cu111              pypi_0    pypi
[conda] torchaudio                0.10.0.dev20210902+rocm4.1          pypi_0    pypi
[conda] torchmetrics              0.5.1                    pypi_0    pypi

cc @mthrok

**Comment by mthrok** [comment]
Now, this should be resolved by #1751.

**Comment by malfet** [comment]
Updated nightly indicies, could you please try again?

**Comment by nateanl** [comment]
Yes it's resolved. Thanks @malfet!
