### ISSUE TITLE
torchaudio nightly installs rocm when cuda11 install command is used

### ISSUE THREAD

**Issue by frank-dong-ms** [pytorch/audio#1750]
## 🐛 Bug

Intend to install torchaudio nightly cuda11 version but got rocm version

## To Reproduce

1. create new conda env: conda create -n torch-nightly python=3.7
2. activate the conda env: conda activate torch-nightly
3. install torchaudio nighly with pip: pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html
4. check install version: pip list
5. find below result:
    torch             1.10.0.dev20210901+cu111
    torchaudio        0.10.0.dev20210901+**rocm4.1**
    torchvision       0.11.0.dev20210901+cu111

## Expected behavior

Expect to get below result:
    torch             1.10.0.dev20210901+cu111
    torchaudio        0.10.0.dev20210901+cu111
    torchvision       0.11.0.dev20210901+cu111

## Environment

 - What commands did you used to install torchaudio (conda/pip/build from source)?
 - If you are building from source, which commit is it?
 - What does `torchaudio.__version__` print? (If applicable)

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by seemethere** [comment]
Looks like this should be resolved now:
```
❯ docker run --rm -it python:3 pip3 install --pre torchaudio -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html 
Looking in links: https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/nightly/cu111/torchaudio-0.10.0.dev20210902%2Bcu111-cp39-cp39-linux_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 552 kB/s
```
