### ISSUE TITLE
Type inconsistencies when using MelSpectrogram

### ISSUE THREAD

**Issue by lewiswolf** [pytorch/audio#1753]
_potential_ 🐛 Bug

I noticed this little type inconsistency a while back. I'm unsure whether or not I should expect `MelSpectrogram` to infer its internal types from the input type, or if the intended use is to set the global default using `torch.set_default_dtype`?

```python
import numpy as np
import torch
import torchaudio

# generate 1 second of a sine wave
waveform = torch.from_numpy(np.sin(2 * np.pi * 440.0 * (np.arange(44100) / 44100)))

# regular spectrograms work fine on floats and doubles
spectrogram_float = torchaudio.transforms.Spectrogram()(waveform.float())
spectrogram_double = torchaudio.transforms.Spectrogram()(waveform.double())

# mel spectrograms however...
spectrogram_float = torchaudio.transforms.MelSpectrogram(
    sample_rate=44100,
)(waveform.float())

# without this line:
torch.set_default_dtype(torch.float64)
# RuntimeError: expected scalar type Double but found Float
spectrogram_double = torchaudio.transforms.MelSpectrogram(
    sample_rate=44100,
)(waveform.double())
```

**Comment by mthrok** [comment]
Hi @lewiswolf 

This is working as expected. `MelSpectrogram` is a stateful model building block, which inherits `torch.nn.Module`, and the idiom to use `torch.nn.Modules` is to move the parameters to the desired device and data type.

https://pytorch.org/docs/stable/notes/modules.html

Something like the following should work fine.

```python
trans = torchaudio.transforms.Melspectrogram(...)
trans.to(dtype=torch.float64)
mel_spec = trans(waveform.double())
```

**Comment by mthrok** [comment]
Although, now that I realize that the frequency bin is computed with `float32` precision once, so instead of moving it to `float64`, it might be better to generate the frequency bin with the higher precision.

cc @carolineechen this is a similar pattern as resampling cache mechanism.
