### ISSUE TITLE
Build sox with mad in binary packaging

### ISSUE THREAD

**Issue by ezyang** [pytorch/audio#177]
Our binary build of torchaudio is unable to decode mp3 because our static copy of sox is not built with mp3 decoding support. This is different from lame (which is a encoder). We need to also build and install mad. cc @soumith

**Comment by soumith** [comment]
I thought `mad` is the encoder and `lame` is the decoder. " unable to decode mp3 " ???

**Comment by ezyang** [comment]
Other way around. (In fact, I made that mistake when I wrote this post initially)

```
formats: can't open input file `/tmp/tmphc4feoxk/assets/steam-train-whistle-daniel_simon.mp3': SoX was compiled without MP3 decoding support                                                                                                                    
Eformats: can't open input file `/tmp/tmphc4feoxk/assets/steam-train-whistle-daniel_simon.mp3': SoX was compiled without MP3 decoding support  
```
