### ISSUE TITLE
cuda_version can't be changed in CI. It needs to be improved.

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/audio#1798]
## 🐛 Bug

In unittest_windows_gpu, there's an environment variable of CUDA_VERSION.
https://github.com/pytorch/audio/blob/ecd068f583e4e45ef80635d975ac2bf38d4e819a/.circleci/config.yml.in#L514-L520
But the value couldn't be changed in fact, because it will be revert to 10.2 by regenerate.py
https://github.com/pytorch/audio/blob/ecd068f583e4e45ef80635d975ac2bf38d4e819a/.circleci/regenerate.py#L212

It's worse than https://github.com/pytorch/vision/issues/4443

It's obvious that many cuda workflow, both linux and windows are affected.

**Comment by mthrok** [comment]
Hi @mszhanyi 

Would simply removing these conditions help?
For `CUDA_VERSION` and `CU_VERSION`, maybe we can simply merge them into `CU_VERSION`.

cc @malfet
