### ISSUE TITLE
libGOMP not found

### ISSUE THREAD

**Issue by greaber** [pytorch/audio#18]
I had an error similar to that reported here on trying to load torchaudio: https://github.com/pytorch/pytorch/issues/643

I found that there were two independent things that would each lead to the error.  One was compiling with an older version of gcc (4.8.something instead of 5.4.0).  The other was importing torch before torchaudio.

**Comment by greaber** [comment]
Actually, I just encountered this libGOMP problem again even though I compiled torchaudio with gcc 5.4.0 and imported torchaudio before torch.

**Comment by drscotthawley** [comment]
I see similar behavior:

$ python
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/envs/py35/lib/python3.5/site-packages/torchaudio-0.1-py3.5-linux-x86_64.egg/torchaudio/__init__.py", line 9, in <module>
    from ._ext import th_sox
  File "/opt/anaconda/envs/py35/lib/python3.5/site-packages/torchaudio-0.1-py3.5-linux-x86_64.egg/torchaudio/_ext/th_sox/__init__.py", line 3, in <module>
    from ._th_sox import lib as _lib, ffi as _ffi
ImportError: /opt/anaconda/envs/py35/lib/python3.5/site-packages/torch/lib/../../../../libgomp.so.1: version `GOMP_4.0' not found (required by /usr/lib/x86_64-linux-gnu/libsox.so.2)
>>> 

Everything except torchaudio was installed via pip (using anaconda distribution) or apt-get (e.g. sox, ffmpeg)   in the past few days.

**Comment by vincentqb** [comment]
Since pytorch/pytorch#643 has been closed, I will close this issue. Please feel free to re-open or create a [new bug report](https://github.com/pytorch/audio/issues/new?template=bug-report.md) while providing the information given in the template..

**Comment by Manamama** [comment]
I have the same error in Termux, AD 2024:

```
 File "/data/data/com.termux/files/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen failed: library "libgomp.so.1" not found: needed by /data/data/com.termux/files/usr/lib/python3.11/site-packages/torchaudio/lib/libtorchaudio.so in namespace (default)
```
despite:
```
~ $ apt list | grep  gomp

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gomp/stable,now 2023.02.02-2 aarch64 [installed]
libgomp-7/termux 7.4.0-2 aarch64
libgomp-8/termux,now 8.3.0-3 aarch64 [installed]
~ $ 
```

Locate finds it as part of some glibc and experimental bazel-like toolchains only. 
If one hand-compiles it with clang from archive .a, then :
`OSError: dlopen failed: library "libstdc++.so.6" not found: needed by /data/data/com.termux/files/usr/lib/python3.11/site-packages/torchaudio/lib/libtorchaudio.so in namespace (default)`


Experimenting now with each, just in case it has these. 

`~ $ apt list | grep  gcc

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gcc-10/tur-packages 10.5.0-1 aarch64
gcc-11/tur-packages 11.4.0-1 aarch64
gcc-12/tur-packages 12.3.0 aarch64
gcc-13/tur-packages 13.2.0 aarch64
gcc-14/tur-packages 14.1.0 aarch64
gcc-6/termux 6.5.0-2 aarch64
gcc-7/termux 7.4.0-2 aarch64
gcc-8/termux,now 8.3.0-3 aarch64 [installed,automatic]
gcc-9/tur-packages 9.5.0-2 aarch64
gcc-default-10/tur-packages 0.3-1 all
gcc-default-11/tur-packages 0.3-1 all
gcc-default-12/tur-packages 0.3-1 all
gcc-default-13/tur-packages 0.3-1 all
gcc-default-14/tur-packages 0.3-1 all
gcc-default-9/tur-packages 0.3-1 all
gcc-default/tur-packages 0.3-1 all
gcc-glibc/glibc,now 14.1.0 aarch64 [installed,automatic]
gcc-libs-glibc/glibc,now 14.1.0 aarch64 [installed,automatic]
libgccjit-8-dev/termux 8.3.0-3 aarch64
ndk-sysroot-gcc-compact/tur-packages 26b-7 aarch64
~ `
...
