### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torchaudio (from versions: none) ERROR: No matching distribution found for torchaudio

### ISSUE THREAD

**Issue by clort81** [pytorch/audio#1837]
### 🐛 Describe the bug

ERROR: Could not find a version that satisfies the requirement torchaudio>=0.5.0 (from asteroid) (from versions: none)
ERROR: No matching distribution found for torchaudio>=0.5.0 (from asteroid)
21:40:18-root@Desktop:/pr/Neural/voicefixer_main# pip3 install torchaudio

### Versions

python collect_env.py 
Traceback (most recent call last):
  File "/media/sd/Projects/Neural/voicefixer_main/collect_env.py", line 16, in <module>
    import torch
  File "/home/plab/.local/lib/python3.9/site-packages/torch/__init__.py", line 196, in <module>
    from torch._C import *
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

21:45:45-root@Desktop:/pr/Neural/voicefixer_main# pip3 install numpy
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.19.5)

Please fix torchaudio to install.  Thanks!

**Comment by mthrok** [comment]
Hi @clort81 

This looks like there is something wrong with the installation of PyTorch itself.
What version did you install, and how?
Also torchaudio does not have binary distribution for `Aarch64`, so the installation failure is expected.
Is it possible for you to switch to conda, install PyTorch core and build torchaudio manually?

**Comment by clort81** [comment]
Thanks for pointing me to the problem.  I'll wait for aarch64 support.

**Comment by mthrok** [comment]
Closing as build on aarch64 has been fixed a while ago, and there are aarch64 distributions since PT 2.0
