### ISSUE TITLE
Publish an official release for torchaudio 0.8.2

### ISSUE THREAD

**Issue by gkowarzyk** [pytorch/audio#1863]
PyTorch v1.8.2 LTS has been released.

The corresponding `torchaudio` version is presumably `v0.8.2`, but there exists no such official release.
This has been an issue for us, [as commented here](https://github.com/pytorch/pytorch.github.io/issues/828#issuecomment-941370876).

Would it be possible to please:
- [x] include detailed info for LTS versions in the [compatibility matrix](https://github.com/pytorch/audio/#dependencies)
   #1896
- [ ] publish an official release of `torchaudio` `v0.8.2` on the Releases page
- [ ] make sure there exists a tag for the official commit.

Thanks in advance!

**Comment by gkowarzyk** [comment]
Thank you for the quick reply @mthrok.
I think it should be relatively easy to add to the process (since presumably those packages are being built somewhere for the conda distribution).

**Comment by gkowarzyk** [comment]
Hello again,

Following up: @harishsk I still do not see the 0.8.2 tag, would it be possible to add it please?
(I only see `0.8.2-rc1`, `0.8.2-rc2`, `0.8.2-rc3`).

Thanks in advance!

**Comment by harishsk** [comment]
@malfet / @seemethere I do not have permissions to create tags. Can you please help with this?

**Comment by mthrok** [comment]
Closing as it's been a while since LTS has been deprecated.

https://pytorch.org/blog/pytorch-enterprise-support-update/
