### ISSUE TITLE
Updates necessary to WaveRNN training script

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1868]
1. Get rid of `bg_iterator`
https://github.com/pytorch/audio/blob/a6f9cf8babfb096381e914e23950371478672b3e/examples/pipeline_wavernn/main.py#L13
This is known to slow down the process, and was removed from the library.
2. Replace `DataParallel` with `DistributedDataParallel`.
https://github.com/pytorch/audio/blob/a6f9cf8babfb096381e914e23950371478672b3e/examples/pipeline_wavernn/main.py#L325
`DataParallel` is officially deprecated and slower than `DistributedDataParallel`.

**Comment by nateanl** [comment]
We can replace the training recipe by using PyTorch Lightning which provides ``ddp`` as the backend. Then the two issues will be resolved.

**Comment by mthrok** [comment]
Addressed via #2645
