### ISSUE TITLE
[Doc] Explain the effect of `length` in `Wav2Vec2Model`

### ISSUE THREAD

**Issue by hihunjin** [pytorch/audio#1889]
### 🚀 The feature

More specific explanation in the docs.
in [here](https://github.com/pytorch/audio/blob/e885204ea0d343b8bddd7e829b9e7b29e7c5a9bb/torchaudio/models/wav2vec2/model.py#L83-L85), I need more in-detailed explanation about ``length``. Is it a sample rate?

### Motivation, pitch

It's confusing to understand what the variable/argument behaves.

**Comment by mthrok** [comment]
Length computation in convolution layer

https://github.com/pytorch/audio/blob/e885204ea0d343b8bddd7e829b9e7b29e7c5a9bb/torchaudio/models/wav2vec2/components.py#L62-L65

Mask computation in Transformer layer

https://github.com/pytorch/audio/blob/e885204ea0d343b8bddd7e829b9e7b29e7c5a9bb/torchaudio/models/wav2vec2/components.py#L442-L449

**Comment by mthrok** [comment]
Feel free to give us feedback on how we can improve the documentation.

**Comment by hihunjin** [comment]
Thanks a lot. I appreciate it.

**Comment by mthrok** [comment]
Glad to help.
I will keep this open until we update the doc to include the above information. Thanks for your feedback.
