### ISSUE TITLE
Add audio I/O support for other audio formats, such as m4a

### ISSUE THREAD

**Issue by underdogliu** [pytorch/audio#1979]
### 🚀 The feature

I would like to add support on I/O for other audio formats, such as m4a (primary goal. Other formats can be addressed later). 

### Motivation, pitch

This is in response to a issue from speechbrain speechbrain/speechbrain#1093. Currently as described in the issue, we have to create wav files first from the m4a files, which is default of VoxCeleb2, in order to enable torchaudio processing modules.

### Additional context

If necessary which means no other issues are talking about same thing and nobody recently has time, I can personally have a look at it.

**Comment by mthrok** [comment]
Hi @underdogliu 

Thanks for filing a request. We are considering integrating ffmpeg for various reasons. We cannot promise anything but when we have an update we will let you know. Meanwhile, `torchvision`'s Video API can also handle audio, so it might serve your purpose. https://pytorch.org/vision/master/auto_examples/plot_video_api.html

**Comment by underdogliu** [comment]
@mthrok Thanks for your reply! So just asking do we have a WIP PR or related issue thread for this?

**Comment by mthrok** [comment]
Hi @underdogliu 

I prototyped ffmpeg integration in https://github.com/pytorch/audio/pull/1986. C++ part is mostly feature complete but I still need to polish it (testing, packaging, build process and most importantly the user-facing API).
I will try to land it on nightly build soon and iterate on it.

**Comment by mthrok** [comment]
This has been added in v0.12 using FFmpeg.
