### ISSUE TITLE
Issue with `MelScale`'s `n_fft` used in `MelSpectrogram`

### ISSUE THREAD

**Issue by wesbz** [pytorch/audio#1984]
I have been working with torchaudio and the `MelSpectrogram` class. It seems like the following line is weird:
https://github.com/pytorch/audio/blob/c670898c057904cce9b5108e7ba68b862b66f779/torchaudio/transforms.py#L571
There's apparently no reason to change `n_fft`. What was the idea behind that?

**Comment by mthrok** [comment]
Hi @wesbz 

It's related to `onesided` argument of `Spectrogram`.

The `Spectrogram(n_fft, onesided=True)` returns a Tensor with `n_fft // 2 + 1` bins as it drops the negative frequencies.

The implementation seems to assume that always `onesided=True` even though it exposes the parameter. (so this is technically a bug and it is supposed to be `self.n_fft // 2 + 1 if onesided else self.n_fft`)

So this script works 

```python
import torch
import torchaudio

waveform = torch.randn(2, 256)

transform = torchaudio.transforms.MelSpectrogram()
spec = transform(waveform)
print(spec.shape)
```

```
torch.Size([2, 128, 2])
```

while the following fails

```python
import torch
import torchaudio

waveform = torch.randn(2, 256)
transform = torchaudio.transforms.MelSpectrogram(onesided=False)
spec = transform(waveform)  # Fail
```

```
Traceback (most recent call last):
  File "issue-1984.py", line 12, in <module>
    spec = transform(waveform)
  File "/torch/nn/modules/module.py", line 1106, in _call_impl
    return forward_call(*input, **kwargs)
  File "/torchaudio/torchaudio/transforms.py", line 585, in forward
    mel_specgram = self.mel_scale(specgram)
  File "/torch/nn/modules/module.py", line 1106, in _call_impl
    return forward_call(*input, **kwargs)
  File "/torchaudio/torchaudio/transforms.py", line 381, in forward
    mel_specgram = torch.matmul(specgram.transpose(-1, -2), self.fb).transpose(-1, -2)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x400 and 201x128)
```

**Comment by mthrok** [comment]
> so this is technically a bug and it is supposed to be `self.n_fft // 2 + 1 if onesided else self.n_fft`)
> 

Now that I think of it, I do not think mel-scale Spectrogram is defined in negative frequency. Probably the correct fix is to remove or not to use `onesided` argument.

**Comment by wesbz** [comment]
I never saw mel-scale Spectrogram using negative frequencies :sweat_smile:
Given the mel-scale formula, you couldn't even go below a certain negative frequency.
Real-valued signals do not need negative frequencies anyway and since the mel-scale has been built for audio signals, hence real-valued, I don't think it would make sens to try and use them from complex-valued signal, hence I don't think it would make sense to consider negative frequencies.
To me, you should either give control of the `n_fft` parameter given to `MelScale` or set it to `self.n_fft`. Also https://github.com/pytorch/audio/blob/c670898c057904cce9b5108e7ba68b862b66f779/torchaudio/functional/functional.py#L556 implicitly consider positive frequencies only.

**Comment by mthrok** [comment]
> To me, you should either give control of the `n_fft` parameter given to `MelScale` or set it to `self.n_fft`.

`MelSpectrogram` performs `Spectrogram` and `MelScale`.
The number of bins used by Spectrogram is `n_fft // 2 + 1`, so `MelScale` has to use that value.
I do not think that other values would work. Am I missing something?

You can control the number of intermediate frequency bins indirectly with `n_fft` and output mel frequency bins with `n_mel`.
