### ISSUE TITLE
Google Colab issue with PyTorch 1.10

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#2007]
The recent PyTorch update on Google Colab is causing issue with torchaudio.

If you encounter this issue please report https://github.com/googlecolab/colabtools/issues/2417

It seems that `!pip3 install torchaudio==0.10.0 -f https://download.pytorch.org/whl/cu111/torch_stable.html` would work

**Comment by tarepan** [comment]
Same error.  
I will share *latest* default Google Colab environment.  

```
Model: 		 Tesla P100-PCIE-16GB
Python 3.7.12
Version: 1.10.0+cu111
Cuda compilation tools, release 11.1, V11.1.105
```

Generated by
```bash
!head -n 1 /proc/driver/nvidia/gpus/**/information
!python --version
!pip show torch | sed '2!d'
!/usr/local/cuda/bin/nvcc --version | sed '4!d'
```

It is apparently CUDA version issue.

**Comment by Pathos0925** [comment]
> The recent PyTorch update on Google Colab is causing issue with torchaudio.
> 
> If you encounter this issue please report [googlecolab/colabtools#2417](https://github.com/googlecolab/colabtools/issues/2417)
> 
> It seems that `!pip3 install torchaudio==0.10.0 -f https://download.pytorch.org/whl/cu111/torch_stable.html` would work

This worked for me after uninstalling torchaudio with ```!pip uninstall -y torchaudio```

**Comment by mthrok** [comment]
Now the issue is resolved and `torchaudio` is pre-installed on Google Colab.
