### ISSUE TITLE
torchaudio Jetson TX2

### ISSUE THREAD

**Issue by zang5xixi** [pytorch/audio#2009]
### 🚀 The feature

how to install torchaudio into Jetson TX2. 

### Motivation, pitch

i want to run a program on Jetson TX2, and need to install torchaudio which version is 0.8.0

**Comment by malfet** [comment]
You can install pytorch from jetpack as described in https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-10-now-available/72048 and then build torchaudio from source.

**Comment by mthrok** [comment]
I think it's necessary to patch libsox (`config.guess` file) to build 0.8 on Jetson.
Please refer to this discussion https://github.com/pytorch/audio/issues/1796 for how to apply.
