### ISSUE TITLE
Split `_TORCH_CUDA_ARCH_LIST` by either whitespace or semicolon

### ISSUE THREAD

**Issue by crcrpar** [pytorch/audio#2049]
### 🚀 The feature

As per title.

### Motivation, pitch

In https://github.com/pytorch/audio/blob/e3734feff3df2fd4c81572ba84ca7b8d52c4fab2/tools/setup_helpers/extension.py#L104, `_TORCH_CUDA_ARCH_LIST` is split by a semicolon.
On the other hand, in https://pytorch.org/docs/stable/cpp_extension.html?highlight=cudaextension#torch.utils.cpp_extension.CUDAExtension and https://github.com/pytorch/pytorch/blob/9dd1824741ab13a13ae84aadf5a0226831a118ee/Dockerfile#L48, `TORCH_CUDA_ARCH_LIST` uses whitespace as its separator.

### Additional context

The following Dockerfile fails to be built.
```Dockerfile
FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel

RUN apt update && \
    apt install -y --no-install-recommends git sox libsox-dev

RUN conda install -y cmake

RUN pip install --no-cache-dir sox kaldi_io

RUN git clone --depth 1 https://github.com/pytorch/audio && \
    cd audio && \
    git submodule update --init --recursive && \
    TORCH_CUDA_ARCH_LIST="7.0 7.5 8.0 8.6+PTX" USE_CUDA=1 python setup.py develop
```

**Comment by mthrok** [comment]
Hi @crcrpar 

Thanks for bringing this up.

@malfet I went ahead and made https://github.com/pytorch/audio/pull/2050. Could you take a look?
