### ISSUE TITLE
TorchAudio datasets does not have `transform` argument

### ISSUE THREAD

**Issue by RahulBhalley** [pytorch/audio#2058]
## 🐛 Bug

The TorchAudio datasets documentation says, "All the datasets have almost similar API. They all have two common arguments: `transform` and `target_transform` to transform the input and target respectively.." But wrong argument error is thrown when passing the `transform` to any datasets.

## To Reproduce

I need to transform the raw audio waveform into Mel spectrogram before passing it to my neural network. 
```python
tranform = ta.transforms.MelSpectrogram()
dataset = ta.datasets.LJSPEECH("/Users/me/.cache/torch/datasets", transform=transform)
```

Doing the above, I get the following error.
```
TypeError: __init__() got an unexpected keyword argument 'transform'
```

## Expected behavior

The raw audio waveform must be pre-processed when `transform` argument is passed to any `torchaudio.datasets`.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 PyTorch version: 1.11.0.dev20211109
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.0.1 (x86_64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.3)
CMake version: version 3.22.0
Libc version: N/A

Python version: 3.9.9 (main, Nov 21 2021, 03:23:44) [Clang 13.0.0 (clang-1300.0.29.3)] (64-bit runtime)
Python platform: macOS-12.0.1-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] pytorch-lightning==1.5.4
[pip3] pytorchvideo==0.1.3
[pip3] torch==1.11.0.dev20211109
[pip3] torchaudio==0.11.0.dev20211109
[pip3] torchmetrics==0.6.0
[pip3] torchtext==0.12.0.dev20211109
[pip3] torchvision==0.12.0.dev20211109
[conda] Could not collect

**Comment by mthrok** [comment]
Hi @RahulBhalley 

The description was from legacy feature implementation.
Only some datasets had such feature and they were removed more than a year ago.
The documentation was not updated properly, but recently we removed the description.
Sorry about the confusion.

You can simply apply the transforms in your code.

**Comment by RahulBhalley** [comment]
Hi @mthrok

Thanks for the answer and sorry about that I opened this issue in [pytorch/pytorch](https://github.com/pytorch/pytorch) repo. But there is still a problem. If I try to load `LJSpeech` dataset and put it in `DataLoader` then I can't iterate through that `dataloader`.

```python
dataset = ta.datasets.LJSPEECH("/Users/me/.cache/torch/datasets")
dataloader = DataLoader(dataset, 16, True, num_workers=mp.cpu_count())

for data in dataloader:
    print(type(data))
    # Thought I would do the following for samples transformation.
    samples, sr = transform(data[0]), data[1]
    break
```

I get the error saying: `RuntimeError: stack expects each tensor to be equal size, but got [1, 203933] at entry 0 and [1, 109469] at entry 1`.

Although I can iterate through `dataset` a single sample-by-sample but too many benefits of `DataLoader` class are lost! I wanna have batch of samples, shuffle through dataset for stochasticity, multithread the data loading, and a lot more. 

I believe all these issues can be solved by bringing `transform` argument back. It also aligns it intuitively well with super common/popular [pytorch/vision](https://github.com/pytorch/vision) API.

But if you have some workaround this problem please let me know!

Regards
Rahul Bhalley

**Comment by mthrok** [comment]
@RahulBhalley 

The audio tensors have different lengths so the default collating mechanism does not work. One needs to provide custom [`collate_fn`](https://pytorch.org/docs/stable/data.html#dataloader-collate-fn) to handle the different lengths. A common way is to pad the tensors to the longest one. A simple example is https://discuss.pytorch.org/t/dataloader-for-various-length-of-data/6418/13, however, for the sake of efficiency, you might want to bucket the samples with similar lengths.

**Comment by RahulBhalley** [comment]
Awesome! Looks like `collate_fn` argument is what I need to batch inputs. Thanks for the help. 😀

**Comment by mthrok** [comment]
Note: We have updated the documentation and removed the legacy description from the stable doc. https://pytorch.org/audio/stable/datasets.html

**Comment by RahulBhalley** [comment]
Yeah, saw that. Great. 

Btw won't `transform` be a good way of pre-processing? Because now I am just planning to call my transform function inside collate function to keep my training loop code clean.

**Comment by mthrok** [comment]
> Btw won't `transform` be a good way of pre-processing?

Not necessarily. Some transforms are better applied on (or constrained to) single audio Tensor and others are better for batch audio. Also the notion of `channel` makes it more complicated, and simple `transform` argument is not powerful enough.

Recently, there is an activity to rearchitect the dataloader/dataset with `DataPipe` from `torchdata` https://github.com/pytorch/data, which is expected to be more efficient and flexible. We are thinking to adopt it at some points.

**Comment by RahulBhalley** [comment]
Okay, sounds good!

**Comment by RahulBhalley** [comment]
I made progress with creating `collate_fn` that returns `(torch.Tensor, torch.Tensor, torch.Tensor)`. 

The iteration through `dataloader` works fine if I set `num_workers` to `0`. But when I set it to any other positive integer, I get the following error. It says it's because of multithreading. 

How can I fix this?

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'collate_fn' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'collate_fn' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'collate_fn' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'collate_fn' on <module '__main__' (built-in)>
```

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py in _try_get_data(self, timeout)
    989         try:
--> 990             data = self._data_queue.get(timeout=timeout)
    991             return (True, data)

/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/queues.py in get(self, block, timeout)
    112                     timeout = deadline - time.monotonic()
--> 113                     if not self._poll(timeout):
    114                         raise Empty

/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py in poll(self, timeout)
    261         self._check_readable()
--> 262         return self._poll(timeout)
    263 

/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py in _poll(self, timeout)
    428     def _poll(self, timeout):
--> 429         r = wait([self], timeout)
    430         return bool(r)

/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py in wait(object_list, timeout)
    935             while True:
--> 936                 ready = selector.select(timeout)
    937                 if ready:

/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py in select(self, timeout)
    415         try:
--> 416             fd_event_list = self._selector.poll(timeout)
    417         except InterruptedError:

/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py in handler(signum, frame)
     65         # Python can still get and update the process status successfully.
---> 66         _error_if_any_worker_fails()
     67         if previous_handler is not None:

RuntimeError: DataLoader worker (pid 2653) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
/var/folders/v8/72133fq53mngvq334v2xn0w00000gn/T/ipykernel_2108/4290653212.py in <module>
      1 text, mel, spec = None, None, None
      2 
----> 3 for _text, _spec, _mel in dataloader:
      4     text = _text
      5     mel = _mel

/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py in __next__(self)
    519             if self._sampler_iter is None:
    520                 self._reset()
--> 521             data = self._next_data()
    522             self._num_yielded += 1
    523             if self._dataset_kind == _DatasetKind.Iterable and \

/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py in _next_data(self)
   1184 
   1185             assert not self._shutdown and self._tasks_outstanding > 0
-> 1186             idx, data = self._get_data()
   1187             self._tasks_outstanding -= 1
   1188             if self._dataset_kind == _DatasetKind.Iterable:

/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py in _get_data(self)
   1150         else:
   1151             while True:
-> 1152                 success, data = self._try_get_data()
   1153                 if success:
   1154                     return data

/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py in _try_get_data(self, timeout)
   1001             if len(failed_workers) > 0:
   1002                 pids_str = ', '.join(str(w.pid) for w in failed_workers)
-> 1003                 raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
   1004             if isinstance(e, queue.Empty):
   1005                 return (False, None)

RuntimeError: DataLoader worker (pid(s) 2650, 2651, 2653, 2654) exited unexpectedly
```

**Comment by RahulBhalley** [comment]
Never mind. Had that error on my MBP but doesn't matter 'cause I'm using GPU now.
