### ISSUE TITLE
When can torchaudio(0.10.0) adapt to Apple M1？

### ISSUE THREAD

**Issue by w962402254** [pytorch/audio#2065]
### 🚀 The feature

torchaudio.pipelines cannot be called

### Motivation, pitch

torchaudio.pipelines cannot be called

**Comment by mthrok** [comment]
Hi @w962402254 

Thanks for the feedback. Meanwhile, you can build torchaudio based on nightly build of pytorch.

1. Install miniforge3 - arm64 https://github.com/conda-forge/miniforge#miniforge3
2. Install PyTorch nightly build - `pip3 install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html`
3. Install build tools. `pip3 install "cmake>=3.18" ninja pkg-config`
4. Install torchaudio from main branch. `pip3 install git+https://github.com/pytorch/audio.git`

**Comment by mthrok** [comment]
Note that `pipelines` had some BC-breaking change recently so if you are using  `wav2vec2`, please refer to the latest documentation.  https://pytorch.org/audio/versions.html

**Comment by w962402254** [comment]
torchaudio(0.10.1) arm !!!
I finally waited
Thank you very much！
