### ISSUE TITLE
Broken Load from Bytes (with 24 bits per sample?)

### ISSUE THREAD

**Issue by timnlupo** [pytorch/audio#2083]
### 🐛 Describe the bug

Hi all! I'm noticing some weird behavior with `tochaudio.load` from bytes. For some samples, the sound loads as glitchy harsh noise. Sample code is below.

```python
with open("./CLAP_5.wav", "rb") as fp:
        waveform, sample_rate = torchaudio.load(fp)
        torchaudio.save("out.wav", waveform, sample_rate)
```

If I try this same code without the bytes, the sample loads fine.

```python
waveform, sample_rate = torchaudio.load("./CLAP_5.wav")
torchaudio.save("out.wav", waveform, sample_rate)
```

Weirdly, other samples seem to load fine from bytes. I tried looking through their metadata info to identify the issue and it seems to be a common problem with 24 bits per sample. I'm not sure if the bps is the cause, or perhaps it's the PCM_S encoding or something else entirely.

```python
# The broken one
print(torchaudio.info("./CLAP_5.wav"))
> AudioMetaData(sample_rate=44100, num_frames=22050, num_channels=2, bits_per_sample=24, encoding=PCM_S)

# Another one that works fine
print(torchaudio.info("./SYNTH_F.wav"))
> AudioMetaData(sample_rate=44100, num_frames=8862, num_channels=2, bits_per_sample=32, encoding=PCM_F)
```

I also tried explicitly declaring metadata anywhere I could (according to the [docs](https://pytorch.org/audio/stable/backend.html)) to no avail.

```python
info = torchaudio.info(fp)
fp.seek(0)
waveform, sample_rate = torchaudio.load(fp, num_frames=info.num_frames)
torchaudio.save("out.wav", waveform, sample_rate, encoding=info.encoding, bits_per_sample=info.bits_per_sample)
```

I tried this with a number of different samples from my library and it seemed like anything that was 24 bits per sample had this issue (and anything else did not). This leads me to believe that there may an issue with the handling of certain types of bytestream files. I'm linking [the original sample](https://www.dropbox.com/s/ihlpn6ycyeqxy0n/CLAP_5.wav?dl=0) and [the broken output](https://www.dropbox.com/s/zi5j7tl2ex4e6vz/out.wav?dl=0). Thanks so much!

### Versions

```
PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.6 (x86_64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.3)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.7 (default, Sep 16 2021, 08:50:36)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-lightning==1.5.6
[pip3] torch==1.10.1
[pip3] torchaudio==0.10.1
[pip3] torchmetrics==0.6.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           hecd8cb5_637  
[conda] mkl-service               2.4.0            py39h9ed2024_0  
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0  
[conda] mkl_random                1.2.2            py39hb2f4e1b_0  
[conda] numpy                     1.21.2           py39h4b4dc7a_0  
[conda] numpy-base                1.21.2           py39he0bd621_0  
[conda] pytorch                   1.10.1                  py3.9_0    pytorch
[conda] pytorch-lightning         1.5.6                    pypi_0    pypi
[conda] torchaudio                0.10.1                 py39_cpu    pytorch
[conda] torchmetrics              0.6.2                    pypi_0    pypi
```

**Comment by mthrok** [comment]
Hi @timnlupo 

Thanks for the report. I can reproduce the issue.
I quickly looked into it and it seems that something is wrong when the data is passed from Python file-like object to underlying memory buffer in C++. I will look into it further later.

**Comment by mthrok** [comment]
Fix https://github.com/pytorch/audio/pull/2084

**Comment by mthrok** [comment]
Hi @timnlupo 

Thanks to your detailed bug report, I could spot the bug. #2084 should solve it.

**Comment by timnlupo** [comment]
Awesome! Thank you for the help :)
