### ISSUE TITLE
Emformer pretrained model

### ISSUE THREAD

**Issue by oplatek** [pytorch/audio#2145]
### 🚀 The feature

Thank you for releasing the [Emformer implementation](/fsx/home/oplatek/code/moosenet02/moosenet/emformer.py).

Do you plan to release also any pretrained model?

### Motivation, pitch

The pretrained model would increase the adoption of the code for sure :-)

**Comment by Tomiinek** [comment]
+1

**Comment by hwangjeff** [comment]
Hi @oplatek and @Tomiinek — thanks for the request! We currently have one pretrained Emformer-RNNT model trained on LibriSpeech available as a prototype feature; it is accessible via [`torchaudio.prototype.pipelines.EMFORMER_RNNT_BASE_LIBRISPEECH`](https://pytorch.org/audio/main/prototype.pipelines.html#emformer-rnnt-base-librispeech).

https://github.com/pytorch/audio/tree/main/examples/asr/librispeech_emformer_rnnt contains the training recipe we used to produce the model as well as a demo script (`pipeline_demo.py`) that shows how to use the pretrained model (see #2093 for a video of the demo in action).

Please let us know if you have any questions or feedback.

**Comment by Tomiinek** [comment]
Thanks for your prompt reply! We will try it out :slightly_smiling_face:

**Comment by hwangjeff** [comment]
> Hi @hwangjeff, I do not see a conformer experimental pipeline (or regular pipeline). Does it mean there is no pretrained model for conformer, right?

That's right — at the moment, we don't have a pretrained model for Conformer available. That being said, we are actively working on building a LibriSpeech training recipe for it, and so we may release the corresponding pretrained model in the coming weeks.

**Comment by husenzhang** [comment]
> Hi @oplatek and @Tomiinek — thanks for the request! We currently have one pretrained Emformer-RNNT model trained on LibriSpeech available as a prototype feature; it is accessible via [`torchaudio.prototype.pipelines.EMFORMER_RNNT_BASE_LIBRISPEECH`](https://pytorch.org/audio/main/prototype.pipelines.html#emformer-rnnt-base-librispeech).
> 
> https://github.com/pytorch/audio/tree/main/examples/asr/librispeech_emformer_rnnt contains the training recipe we used to produce the model as well as a demo script (`pipeline_demo.py`) that shows how to use the pretrained model (see #2093 for a video of the demo in action).
> 
> Please let us know if you have any questions or feedback.

Hi @hwangjeff - do you have an quick pointer on using pre-trained pipeline with torchserve?
