### ISSUE TITLE
Remove multiprocessing from audio dataset tutorial

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#2162]
There are couple of audio tutorials in https://github.com/pytorch/audio/tree/main/examples/tutorials.

These `audio_XXX.py` were split from one big tutorial.

Since the original tutorial was long, and the dataset portion was at the very end of the tutorial, I put dataset download run in the background. `audio_datasets_tutorial` is now a standalone, simple tutorial, which no longer benefits from downloading dataset in subprocess. We can remove the subprocess portion.

https://github.com/pytorch/audio/blob/7a83f84fe4bde8eaca3124261bbc564472471095/examples/tutorials/audio_datasets_tutorial.py#L46-L53

## Steps
1. Remove the subprocessing part from the `tutorial/audio_datasets_tutorial.py`
2. Build the doc by running `GALLERY_PATTERN=audio_datasets_tutorial make html` in `docs` directory.
3. Check the resulting documentation in `build/html/index.html`.

## Setup
Please refer to CONTRIBUTING.md https://github.com/pytorch/audio/blob/main/CONTRIBUTING.md

**Comment by yonMaor** [comment]
Hey, I can probably help on this.
Can you eleborate further? 
Is the code snippet that you attached the only thing that needs to be deleted?

**Comment by mthrok** [comment]
> Hey, I can probably help on this.
> Can you eleborate further?
> Is the code snippet that you attached the only thing that needs to be deleted?

Hi @yonMaor 

Thanks. It is simply removing `YESNO_DOWNLOAD_PROCESS` variable. (it occurs one more time later)

**Comment by yonMaor** [comment]
@mthrok Sounds good, I'll take care of it

**Comment by yonMaor** [comment]
Should the _download_yesno function also be removed?

**Comment by mthrok** [comment]
Yes. The resulting tutorial should be simple straight forward script, just demonstrating how to use dataset class.

**Comment by yonMaor** [comment]
Another question, I'm unfamiliar with the second part (running GALLERY_PATTERN...).
Where do I run this command?

**Comment by yonMaor** [comment]
I've made the changes, but I'm not 100% sure what I'm supposed to see in the documentation to make sure that I've made the change correctly

**Comment by mthrok** [comment]
So from `docs` directory, by running `GALLERY_PATTERN=audio_datasets_tutorial make html` (or BUILD_GALLERY=1 make html), the documentation that resembles https://pytorch.org/audio/main/ is created in `build/html`.

Check that the tutorial was run properly, like the spectrograms are plotted properly like https://pytorch.org/audio/main/tutorials/audio_datasets_tutorial.html

Alternatively, you can make a PR and build doc CI job will kick off, so we can see if your change is correct.

**Comment by mthrok** [comment]
`GALLERY_PATTERN=audio_datasets_tutorial make html` is a shell command.
