### ISSUE TITLE
Soundfile backend does not accept Path objects

### ISSUE THREAD

**Issue by eric-mc2** [pytorch/audio#2234]
## File
torchaudio/backend/soundfile_backend.py

## Function
info(filepath)

## Description
The type annotation is incorrect on the filepath argument. The docstring says it accepts `str` or `pathlib.Path` objects. This function calls `soundfile.info(filepath)` which does not accept Path objects. If called with a Path object, this function will throw a TypeError through the soundfile dependency.

```
import torchaudio.backend.soundfile_backend as sb
from pathlib import Path
filepath = "example.wav"  # substitute with some valid audio file
sb.info(filepath)  # successfully creates torchaudio.backend.common.AudioMetaData
sb.info(Path(filepath))  # raises TypeError
```

## Stacktrace:
```
Traceback (most recent call last):
  File "torchaudio/backend/soundfile_backend.py", line 102, in info
    sinfo = soundfile.info(filepath)
  File "soundfile.py", line 552, in info
    return _SoundFileInfo(file, verbose)
  File "soundfile.py", line 499, in __init__
    with SoundFile(file) as f:
  File "soundfile.py", line 740, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "soundfile.py", line 1263, in _open
    raise TypeError("Invalid file: {0!r}".format(self.name))
TypeError: Invalid file: PosixPath('example.wav')
```

### Versions

Collecting environment information...
PyTorch version: 1.10.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux 8 (x86_64)
GCC version: (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
Clang version: Could not collect
CMake version: version 3.18.2
Libc version: glibc-2.28

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.18.0-305.19.1.el8_4.x86_64-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-lightning==1.5.10
[pip3] pytorch-metric-learning==1.1.1
[pip3] torch==1.10.1
[pip3] torch-audiomentations==0.10.0
[pip3] torch-pitch-shift==1.2.0
[pip3] torchaudio==0.10.1
[pip3] torchmetrics==0.7.2
[pip3] torchvision==0.11.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.21.2           py38h20f2e39_0  
[conda] numpy-base                1.21.2           py38h79a1101_0  
[conda] pytorch                   1.10.2          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-lightning         1.5.10             pyhd8ed1ab_0    conda-forge
[conda] pytorch-metric-learning   1.1.1                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-audiomentations     0.10.0                   pypi_0    pypi
[conda] torch-pitch-shift         1.2.0                    pypi_0    pypi
[conda] torchaudio                0.10.2               py38_cu113    pytorch
[conda] torchmetrics              0.7.2              pyhd8ed1ab_0    conda-forge
[conda] torchvision               0.11.2                   pypi_0    pypi
[conda] pysoundfile              0.10.3                 pyhd3deb0d_0     conda-forge

**Comment by carolineechen** [comment]
Hi @eric-mc2, I tried reproducing your env and followed your code, but everything ran smoothly on my end and I get identical results using both the str and the Path versions. The Soundfile dependency should be able to take accept either (see [here](https://github.com/bastibe/python-soundfile/blob/d1d125f5749780b0b068b5fcb49d8e84f7f4f045/soundfile.py#L563)).

**Comment by eric-mc2** [comment]
Hi @carolineechen, thanks for looking into this so quickly. In the docstring you linked to, it says the "file" parameter should be str, int, or file-like. A pathlib.Path is neither of these. 
```
>>> from pathlib import Path
>>> p = Path('.')
>>> isinstance(p, str)
False
>>> isinstance(p, int)
False
>>> isinstance(p, bytes)
False
>>> hasattr(p, 'seek') or hasattr(p, 'read')
False
```
Therefore it ought to throw a TypeError  [here](https://github.com/bastibe/python-soundfile/blob/d1d125f5749780b0b068b5fcb49d8e84f7f4f045/soundfile.py#L1192) after failing the explicit type checks for string, int, and file-interface. 

What platform did you test on? I've also failed to replicate the issue on Mac, but still observe the error on Linux. My best guess is that conda downloads two versions of this library: a source code version soundfile.py and a compiled version _soundfile.py, that these versions express different behavior, and that different systems load different versions. This hypothesis is substantiated by putting print statements into conda's soundfile.py: on Linux they print but on Mac they don't.

**Comment by carolineechen** [comment]
Hi @eric-mc2, I've tested this on both Mac and Linux and have still been unable to reproduce on either (I've also tried both the pip and conda versions of soundfile). 

Looking a bit more closely at the soundfile source code [here](https://github.com/bastibe/python-soundfile/blob/d1d125f5749780b0b068b5fcb49d8e84f7f4f045/soundfile.py#L630), soundfile should be able to handle PathLike objects, as it converts the object to its str or byte representation through `__fspath__`, and these types should be accepted by soundfile [`_open`](https://github.com/bastibe/python-soundfile/blob/d1d125f5749780b0b068b5fcb49d8e84f7f4f045/soundfile.py#L1172) function. Let me know if that looks correct to you

```
>>> from pathlib import Path
>>> file = Path('.')
>>> hasattr(file, '__fspath__')
True
>>> file = file.__fspath__()
>>> isinstance(file, (str, bytes))
True
```

**Comment by mthrok** [comment]
@eric-mc2 What is the version of soundfile you are using?

I also tried your code snippet and it worked fine on my MacBook Pro. The version of PySoundFile is `0.10.3`.

The call graph looks like

- `torchaudio.info`
    https://github.com/pytorch/audio/blob/6f539cf3edc4224b51798e962ca28519e5479ffb/torchaudio/backend/soundfile_backend.py

- `soundfile.info`
    https://github.com/bastibe/python-soundfile/blob/f147eafdb549bf35cef24d30ada30f235bf86cc5/soundfile.py#L430-L438

- `soundfile._SoundFileInfo`
    https://github.com/bastibe/python-soundfile/blob/f147eafdb549bf35cef24d30ada30f235bf86cc5/soundfile.py#L378-L383

- Inside of `soundfile._SoundFileInfo` constructor
  - `file = file.__fspath__()`
      https://github.com/bastibe/python-soundfile/blob/f147eafdb549bf35cef24d30ada30f235bf86cc5/soundfile.py#L621

  - finally, the resulting `file` is used to interact with `libsndfile`.
      https://github.com/bastibe/python-soundfile/blob/f147eafdb549bf35cef24d30ada30f235bf86cc5/soundfile.py#L627-L629

**Comment by eric-mc2** [comment]
I'm going to close this thread due to lack of reproducibility. As @carolineechen points out, the `file = file.__fspath__()` line makes pathlib.Path a legal argument. After cleaning and simplifying my environment setup, I can't reproduce the original stacktrace either.

**Comment by 980202006** [comment]
![image](https://user-images.githubusercontent.com/24452502/168949513-ce5bea8d-420b-4fc8-93de-6477cb11366d.png)
I had the same problem. The same package version I compared different environments.I reinstall pathlib: pip install pathlib. Temporarily solved the problem.
