### ISSUE TITLE
torchaudio.backend.sox_io_backend does not normalize

### ISSUE THREAD

**Issue by mcomunita** [pytorch/audio#2253]
### 🐛 Describe the bug

Hi,

I am experiencing a bug when loading a WAV file using _sox_io_ backend where the loaded file is not normalized (i.e. fit in the range of ``[-1.0, 1.0]``).

Torchaudio version: 0.10.2

Below is the code and prints if I load the file without normalization (original file format int32):
<img width="449" alt="image" src="https://user-images.githubusercontent.com/34679334/155411255-02471297-62f6-4e3f-ab42-7f177bb3002a.png">

And here's with normalization:
<img width="449" alt="image" src="https://user-images.githubusercontent.com/34679334/155411396-f0847f0e-bf27-4a38-ab2f-d57c62b0b89b.png">

The audio is converted to float32 but it is NOT normalized. Unless it is a language problem and you used "normalize" instead of "convert", but I doubt since in this context _to normalize_ should mean `audio_normalized = audio / max(abs(audio))`.

Thanks

### Versions

Collecting environment information...
PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.6 (x86_64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.3)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.10 (main, Jan 15 2022, 11:48:00)  [Clang 13.0.0 (clang-1300.0.29.3)] (64-bit runtime)
Python platform: macOS-11.6-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] torch==1.10.2
[pip3] torchaudio==0.10.2
[conda] Could not collect

**Comment by mthrok** [comment]
Hi @mcomunita 

> Unless it is a language problem and you used "normalize" instead of "convert"

This is indeed a language problem that exists from the very beginning of the library, and persists for API compatibility reason. What it really does is to convert the values from native type to float32 type. It does not perform any actual normalization. Sorry for the confusion. Let us follow up with updating the documentation.

**Comment by filipmu** [comment]
This looks like its still an issue in the docs for v0.11  .  It took a lot of debugging to find the culprit, which turned out to be torchaudio.load.  The docs state pretty clearly  and twice that it normalizes from [-1,1].

![image](https://user-images.githubusercontent.com/3823334/165666582-88fb7a5f-43cc-4f40-a948-cd2e599f4527.png)

[https://pytorch.org/audio/stable/backend.html](https://pytorch.org/audio/stable/backend.html)
