### ISSUE TITLE
get_version.sh needs to be run with bash not sh

### ISSUE THREAD

**Issue by pallgeuer** [pytorch/audio#2268]
### 🐛 Describe the bug

The `get_version.sh` script should be run with bash (see its shebang), not `sh` as called on this line:
https://github.com/pytorch/audio/blob/main/third_party/kaldi/CMakeLists.txt#L16
which is:
```
  COMMAND sh get_version.sh
```
This results in:
```
Updated 2 paths from the index
get_version.sh: 37: Bad substitution
get_version.sh: The version number "5.5" specified in src/.version is not in MAJOR.MINOR format.
get_version.sh: Stopping the construction of full version number from git history.
get_version.sh: 45: [[: not found
```
Best fix would be to change the line to:
```
  COMMAND ./get_version.sh
```
and let the script itself decide what it should be run with. I tested it.

### Versions

Not relevant

**Comment by mthrok** [comment]
Hi @pallgeuer 

Thanks for pointing out. I prepared fix in #2269.
