### ISSUE TITLE
Running lexicon decoder on GPU causes crash on notebook

### ISSUE THREAD

**Issue by mmdalix** [pytorch/audio#2274]
### 🐛 Describe the bug

My notebook on kaggle crashes every time I try to run lexicon decoder with emissions on GPU, and the container has to be rebooted.
No exceptions or output will be printed.

I'm using it this way:
```
beam_search_decoder = lexicon_decoder(
    lexicon=lexicon_file,
    tokens=tokens,
    lm=kenlm_file,
    nbest=1,
    beam_size=350,
    lm_weight=LM_WEIGHT,
    word_score=WORD_SCORE,
)
beam_search_decoder(emissions.to('cpu:0'))     #if I dont use .to('cpu:0') it will crash

```

### Versions

!pip3 install torch==1.12.0.dev20220305+cu113 torchaudio==0.12.0.dev20220305+cu113 -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html

**Comment by hwangjeff** [comment]
Hi @mmdalix, thanks for reporting this issue. I suspect the cause of the exception is a device mismatch between the input and the `lengths` tensor that's being inferred: https://github.com/pytorch/audio/blob/4b47412e91c22d75a1d5f4ea5f71e0ceaa26efd7/torchaudio/prototype/ctc_decoder/ctc_decoder.py#L144

Here, `lengths` is placed on cpu, so when you provide an input that's placed on gpu, we observe a mismatch.

To test this assumption, could you try explicitly supplying a lengths tensor placed on gpu and see if that resolves the mismatch? e.g.
```
B, T, N = emissions.size()
lengths = torch.full((B,), T)
beam_search_decoder(emissions.to('cuda'), lengths.to('cuda'))
```

**Comment by mthrok** [comment]
CTC decoder access memories directly so it expects the tensor to be contingent and on CPU.
We should perhaps add the check for CPU tensor. cc @carolineechen

**Comment by mmdalix** [comment]
> 

I don't have any idea about how it works under the hood. but it would a lot better if it was designed to be GPU-compatible because it will take a long time when I increase the beam_size parameter

**Comment by mthrok** [comment]
I am not CUDA expert but they say that decoding in GPU is not necessarily faster than CPU because of the nature of the search algorithm. Decoding is a causal operation, which is very difficult, if not impossible, to pallalelize in a way that can take advantage of GPU pallalelism.

**Comment by mthrok** [comment]
Now the CTC decoder code properly rejects CPU Tensors. Thanks for the report.
