### ISSUE TITLE
[feature request] In-memory tensor as input to SoX effects pipeline

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/audio#230]
As far as I understand, currently [SoxEffects.set_input_file](https://github.com/pytorch/audio/blob/master/torchaudio/torch_sox.cpp#L207) accepts file names as input. It would be nice (and allow for more flexible usage in mixed pipelines) if it supported using PCM16 or float tensors as input as well.

My usecase: I have an existing data reading pipeline for speech recognition and I wanted to use SoxEffects for fast in-memory audio data augmentation.

**Comment by cpuhrsch** [comment]
Hello @vadimkantorov, as a workaround for now, have you tried using named tempfiles in /dev/shm?

**Comment by vadimkantorov** [comment]
Thanks for the suggestion, I might try that. Alternatively, I'm thinking of reworking the data reading the pipeline to use an alternative sox path if audio is augmented.

**Comment by vadimkantorov** [comment]
E.g. pitch_shift and time_stretch have much worse quality in librosa compared to sox / rubberband.

**Comment by cpuhrsch** [comment]
Ideally pitch_shift and time_stretch will be easy enough to implement from our transforms and can become examples or convenience utilities. We can then look at librosa, sox or rubberband to see how their implementations differ and what tradeoffs they chose etc.

**Comment by vadimkantorov** [comment]
I mean it would be nice to have some final sound quality (sth like psnr for images) measures as well (or at least providing samples): at least for some cases of speech and music.

**Comment by mthrok** [comment]
In 0.7.0 release, we have added sox effects what work on tensor directly https://pytorch.org/audio/0.7/sox_effects.html#applying-effects-on-tensor. They should produce the same result as `sox` command line.
