### ISSUE TITLE
 Library not loaded: libavdevice.58.dylib

### ISSUE THREAD

**Issue by innarid** [pytorch/audio#2357]
### 🐛 Describe the bug

I got an error while importing Streamer.
`from torchaudio.prototype.io import Streamer`
Torchaudio couldn't load ffmpeg library. But the files exists in `/usr/local/Cellar/ffmpeg@4/4.4.2/lib/libavdevice.58.dylib`
```
Traceback (most recent call last):
  File "inference.py", line 5, in <module>
    from torchaudio.prototype.io import Streamer
  File "/***/emf_venv/lib/python3.8/site-packages/torchaudio/prototype/io/__init__.py", line 4, in <module>
    torchaudio._extension._load_lib("libtorchaudio_ffmpeg")
  File "/***/emf_venv/lib/python3.8/site-packages/torchaudio/_extension.py", line 51, in _load_lib
    torch.ops.load_library(path)
  File "/***/emf_venv/lib/python3.8/site-packages/torch/_ops.py", line 244, in load_library
    ctypes.CDLL(path)
  File "/Users/***/.pyenv/versions/3.8.13/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/***/emf_venv/lib/python3.8/site-packages/torchaudio/lib/libtorchaudio_ffmpeg.so, 6): Library not loaded: @rpath/libavdevice.58.dylib
  Referenced from: /***/emf_venv/lib/python3.8/site-packages/torchaudio/lib/libtorchaudio_ffmpeg.so
  Reason: image not found
```

### Versions

PyTorch version: 1.12.0.dev20220427
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.6.4 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.19.3
Libc version: N/A

Python version: 3.8.13 (default, Apr 28 2022, 12:42:44)  [Clang 12.0.0 (clang-1200.0.32.29)] (64-bit runtime)
Python platform: macOS-11.6.4-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0.dev20220427
[pip3] torchaudio==0.12.0.dev20220427
[conda] Could not collect

ffmpeg version 4.4.2 (Also tried the latest version)

**Comment by nateanl** [comment]
Hi @innarid, thanks for sharing the issue. It seems cmake didn't recognize the ffmpeg path when building torchaudio. Could you try to build torchaudio from source using:
```bash
FFMPEG_ROOT=/usr/local/Cellar/ffmpeg@4/4.4.2
BUILD_FFMPEG=1 python setup.py clean develop
```

**Comment by mthrok** [comment]
@nateanl That's build time discovery. The issue is about runtime discovery.

@innarid Is `/usr/local/Cellar/ffmpeg@4/4.4.2/lib/` set as library search path? Can you set `LD_LIBRARY_PATH=/usr/local/Cellar/ffmpeg@4/4.4.2/lib/:${LD_LIBRARY_PATH}` before starting Python, and see what happens?

**Comment by innarid** [comment]
> Hi @innarid, thanks for sharing the issue. It seems cmake didn't recognize the ffmpeg path when building torchaudio. Could you try to build torchaudio from source using:
> 
> ```shell
> FFMPEG_ROOT=/usr/local/Cellar/ffmpeg@4/4.4.2
> BUILD_FFMPEG=1 python setup.py clean develop
> ```

Thak you! It helped
