### ISSUE TITLE
Cache Resample kernel inside transform.PitchShift() 

### ISSUE THREAD

**Issue by xvdp** [pytorch/audio#2359]
### 🚀 The feature

Cache PitchShift Resample kernel to improve speed of this transform on second usage.

### Motivation, pitch

In porting some augmentation code from `librosa` to `torchaudio`, I noticed that `PitchShift()` and `Resample()` are slower than librosa in CPU.

In the case of `transforms.Resample()`, this changes on second run as the kernel is cached. But PitchShift does no such caching, calling instead the functional.
As to the first run. I didnt dig into librosa `core.resample()` to see why under similar conditions on first run resample is faster in one of the directions. Perhaps this is another opportunity, but besides this suggestio.

`transforms.PitchShift()` calls the `resample()` functional, rebuilding the kernel every time.
 
Alt .1 declare `class PitchShift(Resample):` and hardcode whatever doesn't require the full set of options.

Alt.2 partial code replication in `PitchShift`, cache `kernel` buffer, and call  ` _get_sinc_resample_kernel()` and ` _apply_sinc_resample_kernel()` instead of `resample()` inside the PitchShift functional code.

**Comment by mthrok** [comment]
Hi @xvdp 

Thanks for the pitch. This is a good point and make sense. I think Alt.2 is somewhat better from maintaining perspective.

I will put this as help-wanted issue, as I do not have bandwidth to look into this right now. We welcome your contribution as well.

**Comment by xvdp** [comment]
Thanks, I fixed it on my end but I have some unrelated issue on the install from source; So I cannot test it properly in its context, even if with a simple overriding the classes on _transform and functional it works. I presume you want a proper set of tests before doing pull request.
