### ISSUE TITLE
import torchaudio error 

### ISSUE THREAD

**Issue by arijit17** [pytorch/audio#239]
Thanks for introducing torchaudio. 
However, I'm getting an error on Linux, Python 3.5, CUDA 10.
Works OK on Linux, Python 3.5, and CUDA 9.2

Here is the error
```
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torchaudio/__init__.py", line 8, in <module>
    from torchaudio import transforms, datasets, kaldi_io, sox_effects, compliance, _docs
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torchaudio/transforms.py", line 6, in <module>
    from . import functional as F
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torchaudio/functional.py", line 175, in <module>
    @torch.jit.script
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torch/jit/__init__.py", line 1181, in script
    return _compile_function(fn=obj, qualified_name=qualified_name, _frames_up=_frames_up + 1, _rcb=_rcb)
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torch/jit/__init__.py", line 1077, in _compile_function
    script_fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(fn))
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torch/jit/annotations.py", line 58, in get_signature
    return parse_type_line(type_line)
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torch/jit/annotations.py", line 110, in parse_type_line
    arg_types = [ann_to_type(ann) for ann in arg_ann]
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torch/jit/annotations.py", line 110, in <listcomp>
    arg_types = [ann_to_type(ann) for ann in arg_ann]
  File "/home/abisw/pytorch-py35/lib/python3.5/site-packages/torch/jit/annotations.py", line 227, in ann_to_type
    raise ValueError("Unknown type annotation: '{}'".format(ann))
ValueError: Unknown type annotation: 'typing.Union[int, NoneType]'
>>>

```

**Comment by jamarshon** [comment]
@arijit17 what is your torch version?

**Comment by arijit17** [comment]
@jamarshon latest n'  greatest PyTorch 1.2
Installed with (Stable 1.2, Linux, Pip, Python 3.6, CUDA 10):
pip3 install torch torchvision

**Comment by jamarshon** [comment]
@arijit17 hmm what is your torchaudio version? is this issue only seen when you change from cuda 9.2 to 10?

**Comment by arijit17** [comment]
It should be the latest n' greatest torchaudio 0.3, installed yesterday. 

I don't know, I have two different machines. 
One with Python 3.6 and CUDA 9.2, where is works!
The other with Python 3.5 and CUDA 10, where is complains with error shown above. 

Could these errors be related to some sox stuff?

**Comment by jamarshon** [comment]
@arijit17 I don't think it's related to sox. I suspect your torch version isn't 1.2.0 because I look here
https://github.com/pytorch/pytorch/blob/cef0443464a4ff5e3fd2e3b6eca0ee76c5c428ce/torch/_jit_internal.py#L306
and it's basically complaining about Optional[int] which is a jit feature that was added pytorch 1.2.0. Could you double check this on your CUDA 10 machine?
```python
import torch
print(torch.__version__)
```

**Comment by arijit17** [comment]
@jamarshon 
```
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.2.0'
```

**Comment by jamarshon** [comment]
Hmm that's very strange. I tried a new conda Python 3.5 environment on Linux with CUDA 10 and it seems to work okay

```bash
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

$ rm -rf ~/.cache/pip

$ conda create --name env3.5 python=3.5
$ conda activate env3.5

$ python --version
Python 3.5.6 :: Anaconda, Inc.
$ pip --version
pip 10.0.1 from /private/home/jamarshon/anaconda3/envs/env3.5/lib/python3.5/site-packages/pip (python 3.5)


$ pip install https://download.pytorch.org/whl/cu100/torch-1.2.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting torch==1.2.0 from https://download.pytorch.org/whl/cu100/torch-1.2.0-cp35-cp35m-manylinux1_x86_64.whl
  Downloading https://download.pytorch.org/whl/cu100/torch-1.2.0-cp35-cp35m-manylinux1_x86_64.whl (748.9MB)
    100% |████████████████████████████████| 748.9MB 35kB/s
Collecting numpy (from torch==1.2.0)
  Downloading https://files.pythonhosted.org/packages/69/25/eef8d362bd216b11e7d005331a3cca3d19b0aa57569bde680070109b745c/numpy-1.17.0-cp35-cp35m-manylinux1_x86_64.whl (20.2MB)
    100% |████████████████████████████████| 20.2MB 607kB/s
Installing collected packages: numpy, torch
Successfully installed numpy-1.17.0 torch-1.2.0

$ pip install torchvision
Collecting torchvision
  Downloading https://files.pythonhosted.org/packages/1c/f6/e927f7db4f422af037ca3f80b3391e6224ee3ee86473ea05028b2b026f82/torchvision-0.4.0-cp35-cp35m-manylinux1_x86_64.whl (8.8MB)
    100% |████████████████████████████████| 8.8MB 1.3MB/s
Collecting six (from torchvision)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pillow>=4.1.1 (from torchvision)
  Downloading https://files.pythonhosted.org/packages/d6/98/0d360dbc087933679398d73187a503533ec0547ba4ffd2115365605559cc/Pillow-6.1.0-cp35-cp35m-manylinux1_x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 3.6MB/s
Requirement already satisfied: torch==1.2.0 in /private/home/jamarshon/anaconda3/envs/env3.5/lib/python3.5/site-packages (from torchvision) (1.2.0)
Requirement already satisfied: numpy in /private/home/jamarshon/anaconda3/envs/env3.5/lib/python3.5/site-packages (from torchvision) (1.17.0)
Installing collected packages: six, pillow, torchvision
Successfully installed pillow-6.1.0 six-1.12.0 torchvision-0.4.0

$ pip install torchaudio -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torchaudio
  Downloading https://files.pythonhosted.org/packages/fa/39/4bd19792bf6a665eed9d7644a18ea5af65e1e07fe85c94d2e957dd671b35/torchaudio-0.3.0-cp35-cp35m-manylinux1_x86_64.whl (2.6MB)
    100% |████████████████████████████████| 2.6MB 669kB/s
Requirement already satisfied: torch==1.2.0 in /private/home/jamarshon/anaconda3/envs/env3.5/lib/python3.5/site-packages (from torchaudio) (1.2.0)
Requirement already satisfied: numpy in /private/home/jamarshon/anaconda3/envs/env3.5/lib/python3.5/site-packages (from torch==1.2.0->torchaudio) (1.17.0)
Installing collected packages: torchaudio
Successfully installed torchaudio-0.3.0

$python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.2.0'
>>> import torchaudio
>>> torchaudio.__version__
'0.3.0'
>>> torch.cuda.is_available()
True
>>> torch.__file__
'/private/home/jamarshon/anaconda3/envs/env3.5/lib/python3.5/site-packages/torch/__init__.py'
>>> torchaudio.__file__
'/private/home/jamarshon/anaconda3/envs/env3.5/lib/python3.5/site-packages/torchaudio/__init__.py'
```

**Comment by arijit17** [comment]
@jamarshon thanks. 
I’ll look into it when I’m at work on Monday.

I didn’t use conda.
I created virtual env, and then installed with pip.

**Comment by arijit17** [comment]
Hi @jamarshon I tried it. 
Very interesting that everything works in the conda environment as you suggested. 

I installed latest anaconda. 

Then did:
$ conda create --name env3.5 python=3.5
$ conda activate env3.5

Then 
pip3 install torch torchvision
pip3 install torchaudio

And everything works with CUDA10, Python 3.5!
So, closing the issue .... but maybe there is still something fishy for you to investigate, i.e. why it's not working in a non-conda environment.

**Comment by FeliMe** [comment]
I have the same issue with: 

Python 3.5.2
CUDA Version: 10.1 
torch==1.3.0, 
torchaudio=0.3.1

`$ python3
Python 3.5.2 (default, Jul 10 2019, 11:58:48) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.3.0'
>>> torch.cuda.is_available()
True
>>> import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/meissen/venv/lib/python3.5/site-packages/torchaudio/__init__.py", line 8, in <module>
    from torchaudio import transforms, datasets, kaldi_io, sox_effects, compliance, _docs
  File "/home/meissen/venv/lib/python3.5/site-packages/torchaudio/transforms.py", line 6, in <module>
    from . import functional as F
  File "/home/meissen/venv/lib/python3.5/site-packages/torchaudio/functional.py", line 175, in <module>
    @torch.jit.script
  File "/home/meissen/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 1226, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
  File "/home/meissen/venv/lib/python3.5/site-packages/torch/jit/annotations.py", line 79, in get_signature
    return parse_type_line(type_line, rcb, loc)
  File "/home/meissen/venv/lib/python3.5/site-packages/torch/jit/annotations.py", line 133, in parse_type_line
    arg_types = [ann_to_type(ann, resolver) for ann in arg_ann]
  File "/home/meissen/venv/lib/python3.5/site-packages/torch/jit/annotations.py", line 133, in <listcomp>
    arg_types = [ann_to_type(ann, resolver) for ann in arg_ann]
  File "/home/meissen/venv/lib/python3.5/site-packages/torch/jit/annotations.py", line 258, in ann_to_type
    raise ValueError("Unknown type annotation: '{}'".format(ann))
ValueError: Unknown type annotation: 'typing.Union[int, NoneType]'
`

**Comment by emil2099** [comment]
Hi @jamarshon - not sure if you investigated this at all? 

Reporting the same issue as @FeliMe, everything installed with virtualenv in a fresh environment:

Ubuntu 16.04 LTS
Python==3.5.2
CUDA==10.2
torch==1.3.0
torchaudio=0.3.1

**Comment by LearnedVector** [comment]
Same issue. Can we keep this open? Seems to not work in a non conda environment
