### ISSUE TITLE
transforms.py: hann_window does not included in torch

### ISSUE THREAD

**Issue by chbrian** [pytorch/audio#24]
I got the following error when running the transforms.py:
`AttributeError: module 'torch' has no attribute 'hann_window'`

**Comment by saisrinivas047** [comment]
Hi getting the same error. Post it here if you find a solution ?

**Comment by ryanleary** [comment]
I see you already filed an issue on github.com/pytorch/audio. This appears to be an issue with that package. Try installing a previous version until that is resolved.

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/audio/pull/27
