### ISSUE TITLE
Suggestion: The device-aware declaration of variable 'window' in istft function

### ISSUE THREAD

**Issue by ws-choi** [pytorch/audio#240]
Hello. I'm implementing an end-to-end model for speech enhancement.
During the implementation, I encountered the error caused by the conflict between cuda-cpu variables.
I think the variable window should be declared with the device of the given input (i.e. stft_matrix).
After fixing that [line](https://github.com/ws-choi/audio/blob/ws-choi-patch-1/torchaudio/functional.py#L117), my code is running well without errors.

Thank you.

p.s. I'm sorry that the post is not written in the given format.

**Comment by vincentqb** [comment]
Good point. We should also consider inheriting the `dtype` from `stft_matrix`.
