### ISSUE TITLE
[v0.12] Release Tracker

### ISSUE THREAD

**Issue by hwangjeff** [pytorch/audio#2453]
We've cut a [release branch](https://github.com/pytorch/audio/tree/release/0.12) for the 0.12 release.

This issue is for tracking cherry-picks to the release branch.

**Comment by Dabuk** [comment]
is there a bfloat16 support for rnntloss in this update ?

**Comment by mthrok** [comment]
Hi @Dabuk

Unfortunately no. Can you perhaps file a feature request?
