### ISSUE TITLE
Error while importing torchaudio

### ISSUE THREAD

**Issue by saisrinivas047** [pytorch/audio#25]
Hi
I am getting this error while importing torchaudio. can someone please help me solve this.
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 16 2017, 17:29:19)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.

import torchaudio
Traceback (most recent call last):
File "", line 1, in 
File "build/bdist.linux-x86_64/egg/torchaudio/init.py", line 11, in 
from torchaudio import transforms
File "build/bdist.linux-x86_64/egg/torchaudio/transforms.py", line 152, in 
class SPECTROGRAM(object):
File "build/bdist.linux-x86_64/egg/torchaudio/transforms.py", line 166, in SPECTROGRAM
pad=0, window=torch.hann_window, wkwargs=None):
AttributeError: 'module' object has no attribute 'hann_window'

**Comment by crazyoscarchang** [comment]
I get the same error too!

**Comment by srinivas047** [comment]
I got it fixed by reinstalling both anaconda and torchaudio

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/audio/pull/27

**Comment by crazyoscarchang** [comment]
wait did you just fix it?

(i don't use anaconda)

**Comment by crazyoscarchang** [comment]
Ah cool it works for me now thank you!
