### ISSUE TITLE
inference using wav2letter AM 

### ISSUE THREAD

**Issue by sciai-ai** [pytorch/audio#2523]
Hi, I saw that the latest release supports decoding using wav2letter but using wav2vec2 which is great. I have an acoustic model (AM) trained using wav2letter (flashlight), is it possible to do inference using w2l AM (model.bin) as well in pytorch?

**Comment by jacobkahn** [comment]
@sciai-ai — unfortunately, the flashlight/wav2letter model format differs from PyTorch. Writing converters for these is not particularly difficult for many types of models, but there can sometimes be subtle differences in how computations are implemented. Waning PyTorch support for ONNX has made this tougher. While we may eventually have the ability to interoperate, this won't be for some time.

There are a few options here:
1. Launch a Flashlight binary to do inference from Python directly, interchanging input/output tensors with PyTorch
2. Bind a simple C++ function calling Flashlight inference in Python with pybind, then call that from your Python code

We're hoping to also provide PyTorch versions of Flashlight models in the near future. Hopefully that'll make things easier as well! If you can tell us what type of flashlight/wav2letter model you're interested in, this can help us prioritize.

**Comment by sciai-ai** [comment]
@jacobkahn I am using the **RASR** model. I want to be able to do inference without having the need to keep loading the model in memory for each inference request. 

1. Is there anyway to do this natively in flashlight as the current binary will always load the model first. 

2. I was hoping if there is a PyTorch version of RASR, i can do torch.load(model) once

**Comment by jacobkahn** [comment]
@sciai-ai — sorry for the delay. We don't have plans to port those models directly from Flashlight to PyTorch, but one can train an equivalent PyTorch model with a similar setup. At this point there isn't Flashlight <> PyTorch interop, but this may appear before the end of the year.
