### ISSUE TITLE
 OSError: libtorch_hip.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by talhaanwarch** [pytorch/audio#2525]
### 🐛 Describe the bug

I am unable to import torchaudio.

I created a new virtual environment, install torch using following command
`pip install torch==1.10.0+cu111 torchvision==0.11.0+cu111 torchaudio==0.10.0 -f https://download.pytorch.org/whl/torch_stable.html`
But when i import torchaudio I got following error
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Input In [18], in <cell line: 1>()
----> 1 import torchaudio
      3 torchaudio.load('data/commonvoice/clips/common_voice_ur_26562733.mp3')

File ~/venv/lib/python3.8/site-packages/torchaudio/__init__.py:1, in <module>
----> 1 from torchaudio import _extension  # noqa: F401
      2 from torchaudio import (
      3     compliance,
      4     datasets,
   (...)
     11     transforms,
     12 )
     14 from torchaudio.backend import (
     15     list_audio_backends,
     16     get_audio_backend,
     17     set_audio_backend,
     18 )

File ~/venv/lib/python3.8/site-packages/torchaudio/_extension.py:27, in <module>
     23     # This import is for initializing the methods registered via PyBind11
     24     from torchaudio import _torchaudio  # noqa
---> 27 _init_extension()

File ~/venv/lib/python3.8/site-packages/torchaudio/_extension.py:21, in _init_extension()
     16 # In case `torchaudio` is deployed with `pex` format, this file does not exist.
     17 # In this case, we expect that `libtorchaudio` is available somewhere
     18 # in the search path of dynamic loading mechanism, and importing `_torchaudio`,
     19 # which depends on `libtorchaudio` and dynamic loader will handle it for us.
     20 if path.exists():
---> 21     torch.ops.load_library(path)
     22     torch.classes.load_library(path)
     23 # This import is for initializing the methods registered via PyBind11

File ~/venv/lib/python3.8/site-packages/torch/_ops.py:110, in _Ops.load_library(self, path)
    105 path = torch._utils_internal.resolve_library_path(path)
    106 with dl_open_guard():
    107     # Import the shared library into the process, thus running its
    108     # static (global) initialization code in order to register custom
    109     # operators with the JIT.
--> 110     ctypes.CDLL(path)
    111 self.loaded_libraries.add(path)

File /usr/lib/python3.8/ctypes/__init__.py:373, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    370 self._FuncPtr = _FuncPtr
    372 if handle is None:
--> 373     self._handle = _dlopen(self._name, mode)
    374 else:
    375     self._handle = handle

OSError: libtorch_hip.so: cannot open shared object file: No such file or directory
```

### Versions

System: Ubuntu 20.04 focal
Python: 3.8.10

**Comment by carolineechen** [comment]
Hi @talhaanwarch, can you try adding the cuda version to torchaudio as well? 

`pip install torch==1.10.0+cu111 torchvision==0.11.0+cu111 torchaudio==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by jgentes** [comment]
In my case I was using `torch=1.13.1+cpu` and changed it to `torch=1.13.1`, which I believe includes the cuda version.

**Comment by hoseinCode** [comment]
hi i have same error as below:
[/usr/lib/python3.10/ctypes/__init__.py](https://localhost:8080/#) in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    372 
    373         if handle is None:
--> 374             self._handle = _dlopen(self._name, mode)
    375         else:
    376             self._handle = handle

OSError: /usr/local/lib/python3.10/dist-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

**Comment by ShuangMa156** [comment]
> Hi @talhaanwarch, can you try adding the cuda version to torchaudio as well?
> 
> `pip install torch==1.10.0+cu111 torchvision==0.11.0+cu111 torchaudio==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html`
This method sovle my problem, thank you for your contribute.
