### ISSUE TITLE
Can torch.linalg.eig() be replaced with torch.linalg.eigh() in _get_steering_vector_evd() in MVDR?

### ISSUE THREAD

**Issue by CaA23187** [pytorch/audio#2538]
As psd_n and psd_s are Hermitian and symmetric matrices, can torch.linalg.eig() be replaced with torch.linalg.eigh() in _get_steering_vector_evd() for  faster computes the eigenvalue decomposition?

**Comment by nateanl** [comment]
Hi @CaA23187, exactly. In the 0.12 release, the RTF (or steering vector) is computed by `torch.linalg.eigh`. See the `rtf_evd` method in https://github.com/pytorch/audio/blob/main/torchaudio/functional/functional.py#L2061
```python
    _, v = torch.linalg.eigh(psd_s)  # v is sorted along with eigenvalues in ascending order
```
