### ISSUE TITLE
Error for installation using pip on win10

### ISSUE THREAD

**Issue by peterhsu2018** [pytorch/audio#258]
I followed the instruction as below:
`pip install torchaudio -f https://download.pytorch.org/whl/torch_stable.html`
or
`pip install torchaudio`

but got the error:
<pre>
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torchaudio
  ERROR: Could not find a version that satisfies the requirement torchaudio (from versions: none)
ERROR: No matching distribution found for torchaudio
</pre>
Anyone can help me to fix it?

**Comment by peterjc123** [comment]
See https://github.com/pytorch/audio/issues/50 for details.

**Comment by develooper1994** [comment]
I am getting same error.
