### ISSUE TITLE
torch transforms inspired by sox effects

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#260]
## 🚀 Feature

Convert [sox effects](http://sox.sourceforge.net/sox.html#EFFECTS) into transforms. Ideally, we provide enough building blocks to make those transforms easy to assemble.

- [x] allpass (with biquad)
- [x] band (with biquad)
- [x] bandpass/bandreject (with biquad)
- [x] bass (with biquad)
- [x] treble (with biquad)
- [ ] bend
- [x] biquad
- [x] ~channels (we already decided downmix, etc, is easy to do by hand)~
- [ ] chorus
- [ ] compand/mcompand
- [ ] contrast
- [x] dcshift
- [x] deemph (with biquad, related to [this](https://github.com/keunwoochoi/torchaudio-contrib/issues/61#issuecomment-524418049))
- [ ] delay
- [x] dither
- [x] downsample/upsample (available with resample)
- [ ] earwax
- [ ] echo/echos
- [x] equalizer (with biquad, see also [here](https://ccrma.stanford.edu/~jos/filters/Peaking_Equalizers.html))
- [x] fade
- [ ] fir
- [x] flanger
- [x] gain
- [x] highpass/lowpass (with biquad)
- [ ] hilbert
- [ ] ladspa
- [ ] loudness
- [ ] mcompand
- [ ] noiseprof/noisered
- [ ] ~norm (duplicate of gain)~
- [x] ~~oops (simply the difference between two channels)~~
- [x] overdrive
- [x] ~pad/trim (easy to do without transforms)~
- [ ] phaser
- [ ] pitch
- [x] ~rate (resample already available)~
- [x] ~remix (we already decided downmix, etc, is easy to do by hand)~
- [x] ~repeat (`tensor.repeat` or [pad with replicate](https://pytorch.org/docs/stable/nn.functional.html?highlight=pad#torch.nn.functional.pad))~
- [ ] reverb
- [ ] ~reverse~
- [x] riaa (with biquad)
- [ ] silence
- [ ] sinc
- [x] spectrogram
- [x] ~speed (change sample rate)~
- [x] stretch/tempo (vocoder functional available)
- [ ] splice
- [x] ~~stat/stats (only prints information about the waveform)~~
- [x] ~swap~
- [ ] synth
- [ ] tremolo
- [x] vad (in [example](https://github.com/pytorch/audio/blob/master/examples/interactive_asr/vad.py))
- [x] vol

Crossed out: can be done in a simple way with current pytorch operations, so we don't need a dedicated transform. Feel free to point out any updates recommended to this list.

## Additional context

* ~~Remove dependency on sox in [VCTK](https://github.com/pytorch/audio/blob/master/torchaudio/datasets/vctk.py#L39)~~
* ~~Open files in format such as mp3, etc (see [here](https://github.com/keunwoochoi/torchaudio-contrib/issues/31#issuecomment-498336186) and [here](https://github.com/pytorch/audio/issues/110#issuecomment-526741478))~~
* [Comment](https://github.com/pytorch/audio/issues/110#issuecomment-525462367) from #110 linking keunwoochoi/torchaudio-contrib#31
* Some transforms touch on #259
* Performance comparison between libraries for audio loading [here](https://github.com/faroit/python_audio_loading_benchmark)
* [internal doc](https://fb.quip.com/3kdTAwnXWC34)

**Comment by vincentqb** [comment]
[sox effects](http://sox.sourceforge.net/sox.html#EFFECTS):

- [ ] band
- [ ] bandpass/bandreject
- [ ] bass/treble
- [ ] bend
- [ ] biquad
- [ ] ~channels~
- [ ] chorus
- [ ] compand/mcompand
- [ ] contrast
- [ ] dcshift
- [ ] deemph
- [ ] delay
- [ ] dither
- [x] downsample/upsample
- [ ] earwax
- [ ] echo/echos
- [ ] equalizer
- [ ] fade
- [ ] fir
- [ ] flanger
- [ ] gain
- [ ] highpass/lowpass
- [ ] hilbert
- [ ] ladspa
- [ ] loudness
- [ ] mcompand
- [ ] noiseprof/noisered
- [ ] ~norm~
- [ ] oops
- [ ] overdrive
- [ ] ~pad~
- [ ] phaser
- [ ] pitch
- [ ] rate
- [ ] remix
- [ ] repeat
- [ ] reverb
- [ ] reverse
- [ ] riaa
- [ ] silence
- [ ] sinc
- [x] spectrogram
- [x] speed/stretch
- [ ] splice
- [ ] stats
- [ ] swap
- [ ] synth
- [ ] tempo
- [ ] tremolo
- [ ] ~trim~
- [x] vad
- [ ] vol

**Comment by cyrta** [comment]
I can help.  Which should I take as first ?

**Comment by vincentqb** [comment]
The space is open right now :) are you interested in any in particular?

**Comment by engineerchuan** [comment]
We have implemented biquad, lowpass_biquad, highpass_biquad as part of the https://github.com/pytorch/audio/commit/8273c3f4500ac9c01e95f1d78fa3f5752aafdca7

**Comment by vincentqb** [comment]
VCTK depends on four transforms: gain, channels, rate, gain, dither. (Channels doesn't need its own transform, and its debatable for gain. We already have rate as `Resample`.)

From [here](https://github.com/pytorch/audio/blob/b8203182704c59303c62ccfd0a810b6e4060ba14/torchaudio/datasets/vctk.py#L45):
```
        E.append_effect_to_chain("gain", ["-h"])
        E.append_effect_to_chain("channels", [1])
        E.append_effect_to_chain("rate", [16000])
        E.append_effect_to_chain("gain", ["-rh"])
        E.append_effect_to_chain("dither", ["-s"])
```

**Comment by vincentqb** [comment]
> We have implemented biquad, lowpass_biquad, highpass_biquad as part of the [8273c3f](https://github.com/pytorch/audio/commit/8273c3f4500ac9c01e95f1d78fa3f5752aafdca7)

sox uses biquad for other transforms too, see [bottom here](https://sourceforge.net/p/sox/code/ci/master/tree/src/biquads.c).

**Comment by haideraltahan** [comment]
`repeat` ([Pad with replicate option](https://pytorch.org/docs/stable/nn.functional.html?highlight=pad#torch.nn.functional.pad)) can be done with current PyTorch operation?

**Comment by vincentqb** [comment]
> `repeat` can be done with a current PyTorch operation ([Pad with replicate option](https://pytorch.org/docs/stable/nn.functional.html?highlight=pad#torch.nn.functional.pad)) ?

Indeed, it could even be done with `tensor.repeat`.

**Comment by tomassosorio** [comment]
Hey! I will try to remove the pitch dependency of sox.

**Comment by vincentqb** [comment]
> Hey! I will try to remove the pitch dependency of sox, if is no problem @vincentqb :)

Thanks! Looking forward to it :)

**Comment by mthrok** [comment]
During the work of #444 I noticed that currently `highpass_biquad` / `lowpass_biaquad` only supports Q factor as width argument, whereas sox supports other formats such as hertz and octaves.
I made `allpass_biquad` follow the same way and it expects Q value for width parameter.

If the other forms of width is useful/required, then we could add conversion between hertz/octave/Q factor and extend these functions to support this. Thought?

**Comment by bhargavkathivarapu** [comment]
Hi , I am new to pytorch, want to contribute . I went through some Sox effects code and tried implementing them using pytorch . But i  noticed that some of existing functions in torchaudio.functional are 1000x slower than corresponding Sox effects . Below is the code i used to compare the equalizer effect (biquad) 

```python
import torch
import torchaudio
import datetime

#Comparison of Equalizer effect 
E = torchaudio.sox_effects.SoxEffectsChain()
E.append_effect_to_chain("equalizer",[3000,0.707,1])
E.set_input_file("sample.wav")

t1= datetime.datetime.now()
sox_out, sr = E.sox_build_flow_effects()
t2= datetime.datetime.now()
sox_diff = t2-t1
print(f"Sox Effect Time : {sox_diff} \nSox Time seconds: {sox_diff.total_seconds()}")

wave,sr2 = torchaudio.load("sample.wav",normalization=True)

t3= datetime.datetime.now()
func_out = torchaudio.functional.equalizer_biquad(wave,sr2,3000,1,0.707)
t4= datetime.datetime.now()
func_diff = t4-t3
print(f"Torch Functional effect Time : {func_diff} \nFunctional Time seconds: {func_diff.total_seconds()}")

cmp_message = "Sox and Torch functional output same" if torch.allclose(sox_out,func_out, atol=1e-4) else "Sox and Torchfunctional outputs are different"
print(cmp_message)

print(f"Sox effect is  {round(func_diff.total_seconds()/sox_diff.total_seconds())} times faster than Torch effect")
```
I got below output : 
```Latex
Sox Effect Time : 0:00:00.047980 
Sox Time seconds: 0.04798
Torch Functional effect Time : 0:01:28.069414 
Functional Time seconds: 88.069414
Sox and Torch functional output same
Sox effect is  1836 times faster than Torch effect
```
Input file - https://www2.cs.uic.edu/~i101/SoundFiles/StarWars60.wav

Am I doing something wrong in comparison ?
or is torchaudio.functional  expected to be slower than SoX? @vincentqb

**Comment by vincentqb** [comment]
@bhargavkathivarapu -- Thanks for providing the comparison! Given that pytorch is a framework that provides quite a big of deep learning oriented features (e.g. gpu, autograd, jit), we need to expect a cost compared against to a pure C++ implementation. For instance, you can also see another experiment [here](https://github.com/pytorch/audio/pull/290). That being said, once we have the desired features, we definitely want to minimize the impact on performance.

**Comment by mthrok** [comment]
FYI: Regarding the speed, I did simple profiling with the following script and it tells that the most time consuming part is [the iteration in `lfilter`](https://github.com/pytorch/audio/blob/f37d37d628f507003eee7564facbf28e0bb9536d/torchaudio/functional.py#L746-L751)

<Details><Summary>Script</Summary>

```python
import pprofile

import torch
import torchaudio
import torchaudio.functional as F


def profile_biquad():
    waveform, sr = torchaudio.load('test/assets/100Hz_44100Hz_16bit_05sec.wav', normalization=True)

    prof = pprofile.Profile()
    with prof():
        F.equalizer_biquad(waveform, sr, 3000, 1, 0.707)
    prof.print_stats()


profile_biquad()
```

</Details>

<Details><Summary>Most time consuming parts</Summary>

```
   720|    220501|       4.4464|   2.0165e-05| 18.97%|    for i_sample, o0 in enumerate(input_signal_windows.t()):
(call)|         1|  7.86781e-05|  7.86781e-05|  0.00%|# /scratch/moto/pytorch/torch/tensor.py:460 __iter__
(call)|    220500|      2.72458|  1.23564e-05| 11.62%|# /scratch/moto/pytorch/torch/tensor.py:474 <lambda>
   721|    220500|      2.80982|   1.2743e-05| 11.99%|        windowed_output_signal = padded_output_waveform[:, i_sample:(i_sample + n_order)]
   722|    220500|      4.92106|  2.23177e-05| 21.00%|        o0.sub_(torch.mv(windowed_output_signal, a_coeffs_flipped))
   723|    220500|      3.72974|  1.69149e-05| 15.91%|        o0.div_(a_coeffs[0])
   724|         0|            0|            0|  0.00%|
   725|    220500|      4.77714|   2.1665e-05| 20.38%|        padded_output_waveform[:, i_sample + n_order - 1] = o0
```

</Details>

**Comment by bhargavkathivarapu** [comment]
- **stat/stats**

This function in sox just prints some stats regarding input file 
Terminal command : ```sox  StarWars60.wav  -n stat```
<img width="248" alt="Screenshot 2020-04-25 at 7 36 44 PM" src="https://user-images.githubusercontent.com/12258823/80281919-1e9ae580-872c-11ea-9aeb-2f492cd2dfce.png">

Terminal command : ```sox  StarWars60.wav  -n stats```
<img width="167" alt="Screenshot 2020-04-25 at 7 44 10 PM" src="https://user-images.githubusercontent.com/12258823/80282091-28711880-872d-11ea-9584-8023e0ba1b31.png">


When using existing torchaudio  sox effects they do nothing to the waveform
<img width="532" alt="Screenshot 2020-04-25 at 7 41 24 PM" src="https://user-images.githubusercontent.com/12258823/80282032-c9ab9f00-872c-11ea-9f5e-79d8f6c576ab.png">


@vincentqb ,Do we need this stat/stats   summary in functional?


- **oops** 
The oops effect is internally using remix effect  
As remix is not being implemented  can we remove oops also from list?

- **earwax**
This effect is too specific in sox **only** applies for stereo audio(two channel) and sample rate 44.1Khz
Do we need this?

**Comment by vincentqb** [comment]
Thanks for the input!

> * **stat/stats**
> * **oops**

I agree with don't need these two, and marked them as such in the description.

> * **earwax**
>   This effect is too specific in sox **only** applies for stereo audio(two channel) and sample rate 44.1Khz
>   Do we need this?

This is indeed very specific, but I wouldn't object if someone is interested in offering a PR for it. Thoughts?
