### ISSUE TITLE
[v0.13] Release Tracker

### ISSUE THREAD

**Issue by carolineechen** [pytorch/audio#2752]
[0.13 release branch](https://github.com/pytorch/audio/tree/release/0.13) for 0.13 has been cut. The latest common commit with main is [8418790](https://github.com/pytorch/audio/commit/841879099cedbe15addb7f19f17e276cab5bf535)

This issue is for keeping track of cherry-picks to the release branch

**Comment by carolineechen** [comment]
#2747: fix windows python 3.8 loading

**Comment by nateanl** [comment]
#2716: Improve initialization of wav2vec2/hubert model for pre-training

**Comment by carolineechen** [comment]
#2751: add metadata mode for LibriMix

**Comment by nateanl** [comment]
#2744 Improve hubert recipe for pre-training and fine-tuning

**Comment by mthrok** [comment]
#2764 Update tutorial author information

**Comment by carolineechen** [comment]
#2763 Add gtzan download note (docs)
#2762 Add custom lm example to tutorial (tutorial)

**Comment by nateanl** [comment]
Fix fading in hybrid demucs tutorial #2769

**Comment by mthrok** [comment]
#2771 Fix leaking matplotlib figure

**Comment by mthrok** [comment]
#2773 Update resampling tutorial

**Comment by nateanl** [comment]
#2774 Update description of HDemucs pipelines

**Comment by nateanl** [comment]
#2775 Add file_name to the returned item in Snips dataset 
#2776 Add notes on file structure in Voxceleb1 based datasets

**Comment by carolineechen** [comment]
#2777 Update speech commands download path
#2778 Add iemocap dataset variants

**Comment by nateanl** [comment]
#2781 Fix doc in torchaudio.backend
