### ISSUE TITLE
Torchaudio.load does not return Tensor

### ISSUE THREAD

**Issue by shoang22** [pytorch/audio#2753]
### 🐛 Describe the bug

I'm using torchaudio.load() to load an audio file, and instead of getting back a Tensor (ie. tensor([[ 0.1612,  0.2587,  0.2292]], device='cuda:0')), I'm getting <torch.Tensor object at 0x7fcfd7ea0950>. Does anyone know what's causing this?

### Versions

torchaudio 0.12.1

**Comment by nateanl** [comment]
@shoang22  Thanks for sharing the issue. Could you add a script and the audio file you use to reproduce the issue?
You can also share your pytorch and other conda environment via this script for better investigation
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by shoang22** [comment]
So it seems that my problem was loading silent audio resulting in vectors of all zeros. This works fine on loaded audio with noise.
