### ISSUE TITLE
ctc decoder with word piece

### ISSUE THREAD

**Issue by Slyne** [pytorch/audio#2788]
### 🚀 The feature

Hi,
I saw from this [tutorial](https://pytorch.org/audio/main/tutorials/asr_inference_with_ctc_decoder_tutorial.html#sphx-glr-tutorials-asr-inference-with-ctc-decoder-tutorial-py) that ctc decoder is supported by torchaudio.

But not sure if I miss something, there's a `usewordpiece` option mentioned in flashlight [post](https://github.com/flashlight/flashlight/tree/main/flashlight/app/asr#beam-search-decoder) missing in the torchaudio `ctc_decoder` interface. 

Could you help add this feature please?

### Motivation, pitch

Wordpiece is an important feature in asr inference. And since flashlight already supports this, I would suggest torchaudio to add this.

**Comment by carolineechen** [comment]
Hi @Slyne, thanks for question. Word piece decoding is supported by default in the flashlight text decoder, so it should already be supported in the torchaudio ctc decoder as well (although it has not been formally tested yet). To use it with word piece, you would just need to ensure that the token set consists of word pieces, and that the lexicon is defined in terms of those word pieces.

The `--usewordpiece` flag pointed out in flashlight is for figuring out tokenization, and not actually part of the decoding process.

**Comment by Slyne** [comment]
> 

Thanks for the explanation, Caroline.
I've tested it. It works!
There's one sil_token and I just set it to blank token. Hope this is right.
Another thing that is irrelevant to this issue. It would be helpful if you could help me understand this.
In the tutorial, it says *The expected format of the lexicon file is a line per word, with a word followed by its space-split tokens.* The example gives the '|' (which is space symbol in tokens) at the end of each line. I don't understand if this is a must? I didn't add this and just use the plain wordpiece lexicon file without '|' or space token at the end. I'd like to know in what circumstances, this is necessary. Is it due to char/graphme based output unit ? If my model is graphme based and the space token is ' ', should I add ' ' at the end of each line ?
```
# lexcion.txt
a a |
able a b l e |
about a b o u t |
...
```

Thanks again!

**Comment by carolineechen** [comment]
Hi @Slyne, great to hear it's working! 

For the lexicon file, I don't believe the `|` character at the end is necessary, it is more so used to ensure correct word separation/boundaries. This [section](https://github.com/flashlight/flashlight/tree/main/flashlight/app/asr#lexicon-file) of flashlight docs gives a bit more info on that.

Adding multiprocessing support in our library is likely complicated, considering different environments and tricky garbage collection with reusing larger variables (like the language model) across forks. This is something that is probably better kept outside of our library, so it's great to see that it can be done simply with your code snippet! I think this could be a great addition to our tutorial or docs though :)
