### ISSUE TITLE
TorchAudio 0.13 release does not detect FFmpeg

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#2806]
TorchAudio 0.13 binaries seems to have FFmpeg search path hardcoded. In 0.12, FFmpeg installed via conda-forge was detected properly, but it does not work with 0.13 binary.

## Repro:

1. Make a new conda environment
2. Install torchaudio and FFmpeg
    ```
    conda install torchaudio -c pytorch  # Setting torchaudio==0.12 works fine
    conda install -c conda-forge 'ffmpeg<5'
    python -c 'from torchaudio.io import StreamReader'
    ```

## Error:

```
Traceback (most recent call last):
  File "/Users/moto/miniconda3/envs/test-ffmpeg/lib/python3.10/site-packages/torchaudio/_extension.py", line 71, in _init_ffmpeg
    _load_lib("libtorchaudio_ffmpeg")
  File "/Users/moto/miniconda3/envs/test-ffmpeg/lib/python3.10/site-packages/torchaudio/_extension.py", line 52, in _load_lib
    torch.ops.load_library(path)
  File "/Users/moto/miniconda3/envs/test-ffmpeg/lib/python3.10/site-packages/torch/_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "/Users/moto/miniconda3/envs/test-ffmpeg/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/moto/miniconda3/envs/test-ffmpeg/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio_ffmpeg.so, 0x0006): Library not loaded: '/Users/ec2-user/runner/_work/audio/audio/third_party/ffmpeg/lib/libavdevice.58.dylib'
  Referenced from: '/Users/moto/miniconda3/envs/test-ffmpeg/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio_ffmpeg.so'
  Reason: tried: '/Users/ec2-user/runner/_work/audio/audio/third_party/ffmpeg/lib/libavdevice.58.dylib' (no such file), '/usr/local/lib/libavdevice.58.dylib' (no such file), '/usr/lib/libavdevice.58.dylib' (no such file)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/moto/miniconda3/envs/test-ffmpeg/lib/python3.10/site-packages/torchaudio/io/__init__.py", line 21, in __getattr__
    torchaudio._extension._init_ffmpeg()
  File "/Users/moto/miniconda3/envs/test-ffmpeg/lib/python3.10/site-packages/torchaudio/_extension.py", line 73, in _init_ffmpeg
    raise ImportError("FFmpeg libraries are not found. Please install FFmpeg.") from err
ImportError: FFmpeg libraries are not found. Please install FFmpeg.
```

@malfet @seemethere @osalpekar

**Comment by mthrok** [comment]
The following part should be handling the RPATH, is it possible that `if "$(uname)" == Darwin` is not triggered in the build job?

https://github.com/pytorch/audio/blob/86d596d37d0e591d34c86375d516243c21a8ce8e/packaging/ffmpeg/build.sh#L74

https://github.com/pytorch/audio/blob/86d596d37d0e591d34c86375d516243c21a8ce8e/.github/workflows/build-m1-binaries.yml#L63

**Comment by seemethere** [comment]
> The following part should be handling the RPATH, is it possible that `if "$(uname)" == Darwin` is not triggered in the build job?
> 
> https://github.com/pytorch/audio/blob/86d596d37d0e591d34c86375d516243c21a8ce8e/packaging/ffmpeg/build.sh#L74
> 
> https://github.com/pytorch/audio/blob/86d596d37d0e591d34c86375d516243c21a8ce8e/.github/workflows/build-m1-binaries.yml#L63

So issue doesn't appear related to either of those files, checked the output of `ffmpeg/build.sh` on `release/0.12` and `release/0.13` so couldn't be either of those files.

Can also verify that wheels are not affected as well.

**Comment by seemethere** [comment]
Also can't reproduce this when I build the package locally using the same script we provide so not entirely sure what the issue could potentially be.

Might be related to conda versions?

**Comment by seemethere** [comment]
Upon further investigation I believe this might be related to otool versioning on the m1 instances themselves.

For my local otool I get the following:
```
❯ otool --version
llvm-otool(1): Apple Inc. version cctools-1001.2
otool(1): Apple Inc. version cctools-1001.2
disassmbler: LLVM version 14.0.0, (clang-1400.0.29.202)
```

For the AWS instance I get:
```
% otool --version
otool(1): Apple Inc. version cctools-949.0.1
disassmbler: LLVM version 12.0.0
```

I've submitted https://github.com/pytorch/audio/pull/2828 which should hopefully resolve, need to monitor though
