### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by wciurzynski** [pytorch/audio#2837]
### 🚀 The feature

Currently Python 3.11 is not supported and cannot install torchaudio for Python 3.11.
Torch is already available for Python 3.11.

### Motivation, pitch

Python 3.11 has huge optimization and is faster. Upgrading to newest Python is not possible for some project without torchaudio compatibility.

**Comment by mthrok** [comment]
Python 3.11 is not fully supported by PyTorch core yet. https://github.com/pytorch/pytorch/releases/tag/v1.13.0
Only basic functionalities work.
the core team is working to fully support it.
Once PyTorch supports 3.11, the team will add 3.11 support to torchaudio.

**Comment by davidgilbertson** [comment]
Any update, I notice that `torch` and `torchvision` install on 3.11.

**Comment by mthrok** [comment]
@weiwangmeta Could you share the current status please?

**Comment by weiwangmeta** [comment]
Yes, torchaudio is also available to install on 3.11. Actually, we have 2.0 release candidates for you to try out. Could you please follow the command here and let us know of any issues? 
https://dev-discuss.pytorch.org/t/pytorch-release-2-0-rc1-is-available/1065

**Comment by mthrok** [comment]
Closing as PyTorch 2.0.1 / TorchAudio 2.0.2 supports Python 3.11.
