### ISSUE TITLE
AttributeError: module 'torchaudio._internal.module_utils' has no attribute 'requires_sox'

### ISSUE THREAD

**Issue by Justinfungi** [pytorch/audio#2872]
### 🐛 Describe the bug

I am trying to import torchaudio.

The bug "AttributeError: module 'torchaudio._internal.module_utils' has no attribute 'requires_sox'" occurs

My code
```
import torch
import torchaudio

matplotlib.rcParams["figure.figsize"] = [16.0, 4.8]

torch.random.manual_seed(0)
device = "cuda" if torch.cuda.is_available() else "cpu"

print(torch.__version__)
print(torchaudio.__version__)
print(device)
```

Traceback

```
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_129825/1558347532.py in <module>
      1 import torch
----> 2 import torchaudio
      3 
      4 matplotlib.rcParams["figure.figsize"] = [16.0, 4.8]
      5 

~/anaconda3/envs/comp3340/lib/python3.7/site-packages/torchaudio/__init__.py in <module>
      1 from . import extension
      2 from torchaudio._internal import module_utils as _mod_utils
----> 3 from torchaudio import (
      4     compliance,
      5     datasets,

~/anaconda3/envs/comp3340/lib/python3.7/site-packages/torchaudio/transforms/__init__.py in <module>
----> 1 from ._multi_channel import MVDR, PSD, RTFMVDR, SoudenMVDR
      2 from ._transforms import (
      3     AmplitudeToDB,
      4     ComputeDeltas,
      5     Fade,

~/anaconda3/envs/comp3340/lib/python3.7/site-packages/torchaudio/transforms/_multi_channel.py in <module>
      6 import torch
      7 from torch import Tensor
----> 8 from torchaudio import functional as F
      9 
     10 

~/anaconda3/envs/comp3340/lib/python3.7/site-packages/torchaudio/functional/__init__.py in <module>
     23     vad,
     24 )
---> 25 from .functional import (
     26     amplitude_to_DB,
     27     apply_beamforming,

~/anaconda3/envs/comp3340/lib/python3.7/site-packages/torchaudio/functional/functional.py in <module>
   1266 
   1267 
-> 1268 @_mod_utils.requires_sox()
   1269 def apply_codec(
   1270     waveform: Tensor,
```

I have use it in my another code, but same result

The method I have tried:

1.Reinstall pytorch
2. Update torchaudio

But it doesn't work

### Versions

Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.10

Python version: 3.7.7 (default, Mar 26 2020, 15:48:22)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-50-generic-x86_64-with-debian-bookworm-sid
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-lightning==1.3.6
[pip3] pytorch-tabnet==3.0.0
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0
[pip3] torchmetrics==0.5.0
[pip3] torchvision==0.8.2
[pip3] transformer-pytorch==0.0.1
[conda] _pytorch_select           0.1                       cpu_0    anaconda
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0    anaconda
[conda] libmklml                  2019.0.5             h06a4308_0    anaconda
[conda] mkl                       2020.2                      256    anaconda
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.0.6            py37h7dd41cf_0    anaconda
[conda] mkl_random                1.1.1            py37h0573a6f_0    anaconda
[conda] numpy                     1.19.2           py37h54aff64_0  
[conda] numpy-base                1.19.2           py37hfa32c7d_0  
[conda] pytorch                   1.7.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] pytorch-lightning         1.3.6                    pypi_0    pypi
[conda] pytorch-tabnet            3.0.0                    pypi_0    pypi
[conda] torch                     1.13.0                   pypi_0    pypi
[conda] torchaudio                0.13.0                   pypi_0    pypi
[conda] torchmetrics              0.5.0                    pypi_0    pypi
[conda] torchvision               0.4.0                    pypi_0    pypi
[conda] transformer-pytorch       0.0.1                    pypi_0    pypi

**Comment by carolineechen** [comment]
Hi @Justinfungi, what does `print(torch.__version__)` print out? Seems the environment has both `pytorch 1.7.1` and `torch 1.13.0` installed, along with `torchaudio 0.13.0`.

On my end, I don't seem to be able to reproduce this error. Could you try reinstalling torch and torchaudio on a fresh environment and trying again? Either `conda install pytorch torchaudio -c pytorch` or `pip install torch torchaudio` should work.

**Comment by mthrok** [comment]
This happens in notebooks when users update torchaudio and attempt to re-import it without restarting the notebook kernel. 

https://github.com/pytorch/audio/issues/1632
