### ISSUE TITLE
create_fb_matrix should specify frequency format

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/audio#288]
From the code it's clear it expects f_min and f_max in hertz (and not some angular frequency), but this is not mentioned in documentation: https://pytorch.org/audio/functional.html#torchaudio.functional.create_fb_matrix

**Comment by vincentqb** [comment]
Thanks for reporting this! This is fixed in #294, and so will be pushed in the documentation at a later time. I will therefore close this issue, but please feel free to re-open it if this doesn't address it.
