### ISSUE TITLE
torhaudio, AUDIO I/O, buffer transformation tensor

### ISSUE THREAD

**Issue by coolvs4** [pytorch/audio#2884]
Good afternoon. I have a wav file written to a variable as a sequence of bytes, it is necessary to convert this sequence into a tensor object. 

The _TensorFlow_ library is able to cope with this task using the **'tf.audio.decode_wav'** method. 

`tf.audio.decode_wav(
    contents, desired_channels=-1, desired_samples=-1, name=None
)`
Where contents is A Tensor of type string. The WAV-encoded audio, usually from a file.

How can I solve this problem using torch audio?
In the documentation I found only the following method:

`url = "https://download.pytorch.org/torchaudio/tutorial-assets/Lab41-SRI-VOiCES-src-sp0307-ch127535-sg0042.wav"`
`with requests.get(url, stream=True) as response:`
`          waveform, sample_rate = torchaudio.load(response.raw)`

In fact, response.raw is an OS-level file containing byte data - io.FileIO.
Roughly speaking, how do I pass a variable there that already contains a sequence of bytes of an audio file?

`with open('audio.wav', 'rb') as file:`
`        wav = file.read()`

`w2aveform, sample_rate = torchaudio.load(wav)`

**Comment by mthrok** [comment]
Hi

can you try wrapping the byte sequence with io.BytesIO and pass it to torchaudio.load?
