### ISSUE TITLE
StreamReader requires the start of the next frame before returning the decoded previous frame

### ISSUE THREAD

**Issue by lucasw** [pytorch/audio#2887]
### 🐛 Describe the bug

I'm receiving individual frame byte arrays in the h264 or hevc format, each corresponds I believe to either a full keyframe or an intermediate delta frame that needs the keyframe and previous intermediate frames to decode (and they all come from the encoding hardware on an Oak-D-POE camera).  Using https://github.com/pytorch/audio/issues/2685#issuecomment-1252335352 and https://pytorch.org/audio/main/hw_acceleration_tutorial.html I've built up a process that receives each and attempts to decode the images on the gpu, aiming to get the minimum amount of elapsed time since acquisition (but also minimal upstream bandwidth therefore the video compression).  I'm not yet completely certain but it appears that I don't receive the last frame until a newer frame arrives and allows a `read()` to respond with a non-zero length byte array.

There are two threads, one that receives the new frame byte arrays and queues them, and another that is getting the read() calls, it blocks until something arrives in the queue via the other thread instead of returning zero length bytes which would end the stream.

I can provide more source code but here's a sketch:

```python
from torchaudio.io import StreamReader

class Container:
   def __init__(self):
        self.queue = deque([])
        self.cur_pos = 0
...
    def store_frame_packet(self, msg):
            self.queue.append(msg)

    def read(self, n):
        while True:
            if len(self.queue) > 0:
                break
            # wait for other thread to call store_frame_packet()
            time.sleep(0.002)

         # ... get first element of queue, get bytes out of it until empty, then discard it and move on to next element, reset cur_pos to 0
         rv = msg.data[self.cur_pos:self.cur_pos + n]
         ...
         return rv

...
class Reader:
...
        self.config = {
            "decoder": "h264_cuvid",  # Use CUDA HW decoder
            "hw_accel": "cuda:0",  # Then keep the memory on CUDA:0
        }

        self.container = Container()
        self.stream_reader = StreamReader(self.container)
        ... wait for > keyframe interval images to arrive
        frames_per_chunk = 1
        self.stream_reader.add_video_stream(frames_per_chunk, **self.config)

        self.chunk_generator = self.stream_reader.stream()
....
    while True:
        chunk = next(self.chunk_generator)[0]
        ... convert image to bgr, transfer to cpu
```

I've instrumented the `read()` calls to see what they are doing relative to the frame message arrival, and I can see a dense grouping of reads, some delays for a few ms where presumably ffmpeg is decoding, but then nothing until a full frame interval has elapsed- then after the first read() of the new frame the `next()` returns and I can convert to bgr and to the cpu and so on.

Possibly this is a ffmpeg limitation?  Though I was using python-av without hardware acceleration earlier and didn't see this, though I need to redo that test.

### Versions
```
Collecting environment information...
PyTorch version: 1.13.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti
Nvidia driver version: 510.108.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.942
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.1
[pip3] perlin-numpy==0.0.0
[pip3] pytorch-lightning==1.6.4
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.13.0
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.13.0
[pip3] torchmetrics==0.9.2
[pip3] torchvision==0.14.0
[pip3] types-mypy-extensions==0.4
[conda] Could not collect
```

**Comment by mthrok** [comment]
Hi

Thanks for trying out the StreamReader. What happens if you do use CPU decoder instead of GPU decoder?

**Comment by lucasw** [comment]
>  What happens if you do use CPU decoder instead of GPU decoder?

It's the same behavior of reading once from the next frame.  I can dial down the resolution to reduce gpu/cpu load and frame rate (2Hz seems to be the minimum) and see it even more clearly.

**Comment by mthrok** [comment]
I think what happening is that the decoder indeed waits until the next frame comes in so that it is sure that no reordering of frames are necessary. 

There are two locations this could be happening. One for [decoder](https://github.com/pytorch/audio/blob/d8a5a11db64b1670fd0dd8f8e5e80327edbe466d/torchaudio/csrc/ffmpeg/stream_reader/stream_processor.cpp#L74-L92) and one for [filter graph](https://github.com/pytorch/audio/blob/d8a5a11db64b1670fd0dd8f8e5e80327edbe466d/torchaudio/csrc/ffmpeg/stream_reader/sink.cpp#L82-L94)

I think that the corresponding PyAV the corresponding code is [here](https://github.com/PyAV-Org/PyAV/blob/bc4eedd5fc474e0f25b22102b2771fe5a42bb1c7/av/codec/context.pyx#L509-L528). (though I am not entire sure as I have never used PyAV, yet the code structure of [_send_packet_and_recv](https://github.com/PyAV-Org/PyAV/blob/bc4eedd5fc474e0f25b22102b2771fe5a42bb1c7/av/codec/context.pyx#L420-L436) is pretty much the same)

PyAV seems to expose the "flush-ing" API, that is passing `packet=None` to `decode` method/. We have [`drain()` method](https://github.com/pytorch/audio/blob/d8a5a11db64b1670fd0dd8f8e5e80327edbe466d/torchaudio/csrc/ffmpeg/stream_reader/stream_reader.cpp#L375-L387), which does the same thing but it is not exposed to Python interface. We could expose it. But I am not sure how such API can be incorporated to generator-style `stream()` method.

**Comment by mthrok** [comment]
@lucasw  Can you share your PyAV code snippet as a reference?

**Comment by lucasw** [comment]
>  I am not sure how such API can be incorporated to generator-style stream() method.

Can I use a different method to avoid the issue, or that would require api that doesn't exist yet?  I'm fine temporarily doing something brittle that requires more code on my end to get the next frame.

My PyAV code is directly adapted from https://stackoverflow.com/a/67207894

```
rawData = io.BytesIO()
container = av.open(rawData, format="h264", mode='r')
cur_pos = 0
while True:
    data = await websocket.recv()   # or whatever method of getting data, in my case ros messages
    rawData.write(data)
    rawData.seek(cur_pos)
    for packet in container.demux():
        if packet.size == 0:
            continue
        cur_pos += packet.size
        for frame in packet.decode():
            self.frames.append(frame)
```

I get a 1:1 with receiving a packet and decoding a frame (having first received a keyframe, the first few decodes throw exceptions that I tolerate), and it made it easy to associate packet timestamps with frame timestamps (unless I was actually getting a delayed frame from `decode()` instead of the current one, that would be bad- and not clear how to debug, maybe set up two decoders in parallel within one process.

I didn't like storing endless amounts of data in a BytesIO, having to periodically create an overlapping second buffer and retire the first and flip back and forth- maybe a different container with `read(n)` like what can be done with the StreamReader maybe would have solved that and would easily allow instrumentation to see where reads are happening, but I could also wrap BytesIO.

**Comment by mthrok** [comment]
@lucasw Perhaps what you need is a way to tell the association between frames and timestamps?

I looked at this again, and I do not think it is possible to make the decoder object return a frame without inspecting the next packet. Even when an AVPacket object of key frame is fed to a decoder object (with `avcodec_send_packet` function), the function returns the code EAGAIN ("Resource temporarily unavailable"), meaning the decoder needs more data (future frames) to be sure that current decoding result is the right one to release next.

I think `ffmpeg`/`ffprobe` exhibit the same behavior. Let's create an MP4 video 

```
$ffmpeg -hide_banner -y -f lavfi -t  3 -i testsrc -movflags faststart test.mp4
```

Then lookinto the packets and frames

```
$ffprobe -v 0 -show_entries packet=pos,pts,duration -show_entries frame=pts,pict_type -of csv -select_streams v test.mp4
```

```
packet,0,512,1751
packet,2048,512,5400
packet,1024,512,6070
frame,0,I,side_data,

packet,512,512,6229
frame,512,B
packet,1536,512,6278
frame,1024,B
packet,4096,512,6338
frame,1536,B
packet,3072,512,6835
frame,2048,P
packet,2560,512,6961
frame,2560,B
```

Looking at the result, the very first packet is the key frame with PTS==0-512, but the actual frame is not decoded until the third packet is processed. Although at this point the next frame, the one with PTS==512-1024 is still not processed by the decoder, but still that's when decoder is confident to return the decoded data.

I tried the same with StreamReader, by adding bunch of debug print and confirmed that it shows the same behavior. So I don't think there is much thing we can do to achieve the behavior.

**Comment by mthrok** [comment]
The handling of timestamp in decoding and encoding is something brought up as a major improvement points for StreamReader/Writer, so I am considering to provide an easy access to timestamp data.

**Comment by mthrok** [comment]
@lucasw It might help to pass `decoder_option={"threads": 1}` to `add_video_stream` method.

**Comment by lucasw** [comment]
I tried the thread disabling but didn't see any difference.

One thing I tried was to try to return fewer bytes from the first read of the new frame but it does need as many as requested- which appears to be 4096 - number of bytes returned by the last read of the final packet of the previous frames.  I was hoping if I could return only `00 00 00 01 09` (which is always the same, there's a following `30 00 00 00 01 21` which is mostly repeatable but sometimes a `50 00 00  00 01 21` maybe for key frames) it would think that's the start of the frame but it's insisting on only working with 4096 byte buffers.  I wonder if the previous frame was % 4096 then it would decode immediately, or it does want to see the header of the next frame?  It would be nice if I could pad out the final `read()` with zeros and force the decode.

**Comment by lucasw** [comment]
I got end-of-frame decoding working with this system, which is hacky and possibly brittle but works for now with my oak-d camera:

- If between frames always return from read() immediately with the requested number of bytes, all zeros but with this header at the end: `00 00 00 01 09`
- On the next read on the beginning of a frame return the the requested number of bytes from the received data but skip the first 5 (could add a safety check here to make sure the first five were in fact `00 00 00 01 09`, or perhaps initialize the header bytes with actual received headers instead of hard coding)
- On the final read of a frame pad out the returned bytes with zeros to be the requested number of bytes (the requested number ought to be buffer size 4096 which can be specified when StreamReader is constructed)

With that happening the decode is forced, and the extra delay of waiting for the next frame from the camera is eliminated.
