### ISSUE TITLE
The way how the resampling method is set in Resample and F.resample is confusing

### ISSUE THREAD

**Issue by felipeespic** [pytorch/audio#2891]
### 🐛 Describe the bug

The argument `resampling_method` can take the values `'sinc_interpolation'` or `'kaiser_window'`, as if they were different methods. [Actually both are the same sinc function-based method, just using different windows](https://github.com/pytorch/audio/blob/d8a5a11db64b1670fd0dd8f8e5e80327edbe466d/torchaudio/functional/functional.py#L1495-L1502).

Thus, the naming of the methods are confusing, especially in the case of `'kaiser_window'`, which as it doesn't contain the word **'sinc'**, but `'sinc_interpolation'` does, one could infer that `'kaiser_window'` doesn't use the sinc-function as a kernel (but it does). So, I propose to change the way this is set by:

1. Adding the argument `'window'`, which can take the values `'hann'` or `'kaiser'` to switch windows.

2. Removing the `'resampling_method'` argument, keeping it for some time for backward compatibility (throwing a warning).

3. Adding to the documentation that sinc function-based interpolation is the method used by Resample/F.resample always.

### Versions

torch==1.12.1
torchaudio==0.12.1  
(I think anything else is not relevant).

**Comment by mthrok** [comment]
Hi

IIRC - This is due to some historic naming convention.
I think the argument here is valid, though due to the TorchScript-constraint, we might want just reuse the argument name to minimize the BC-breaking change.

@carolineechen thoughts?

**Comment by mthrok** [comment]
> If we only plan on supporting sinc interpolation for the foreseeable future, I think we should reuse the `resampling_method` name to minimize BC-breaking change but change the options to `['hann_window', 'kaiser_window']` and with default being `hann_window` and throw a warning when `sinc_interpolation` is used (but use the hann window code flow to avoid code breakage).

I second this. I am not an expert in this domain, but I do not think there will be a fundamentally different algorithm for audio resampling showing up soon.

**Comment by felipeespic** [comment]
@carolineechen I understand your point, so I would suggest three options:

1. Smilar to your suggestion: Keep `resampling_method`, which can take the values `['sinc_interp_hann', 'sinc_interp_kaiser', 'sinc_interpolation','kaiser_window']`, with the latter two throwing a deprecation warning.   Explanation: I think that the labels need to describe a method. E.g.,  `'hann_window'` doesn't describe a method, but a window, so it would be still confusing (it would be for me, at least), so a more complete description of a method could be in place, such as `'sinc_interp_hann'` or `'sinc_interpolation_hann'`.

3. Your suggestion. Even though I don't totally agree with it, I think it's much better than what it is now. 

5. My original suggestion (I'm sorry for insisting), which in my opinion has the advantage of keeping BC plus having meaningful argument names. If there is no any other method foreseen for the future, so why keep the `resampling_method` argument? I propose:
    -  Keep  `resampling_method` just for some releases (for BC), which can take `['sinc_interpolation',  'kaiser_window']`. Throw a deprection warning when used.
    -  Add `window`, which can take `['hann',  'kaiser']`

**Comment by carolineechen** [comment]
Hi @felipeespic, sorry for the late response and thanks again for the suggestions. I think option 1 makes the most sense to me, and I can go ahead and implement that. I think it provides a pretty good balance of parameter naming and options, and is BC-breaking in a way that is easy to follow.

A couple reasons I do not fully agree with option 3:
- from a BC-breaking perspective, it causes the most confusion. we add a new parameter as we deprecate an existing parameter, which results in releases with two parameters prior to one parameter, and ordering can be especially messy for those who don't set the parameter keyword when setting those values
- say we do add an additional resampling method in the future, reintroducing the parameter would cause further confusion, and the `window` parameter may not be applicable to that new resampling method in which case we would not want window to take on a default value.

**Comment by felipeespic** [comment]
Hi @carolineechen . Thanks for accepting the suggestion and implementing the change.
