### ISSUE TITLE
Looking to add more pre-trained models based on the wav2vec2.0 architecture to torchaudio.pipelines

### ISSUE THREAD

**Issue by xj-111** [pytorch/audio#2893]
### 🚀 The feature

Based on this paper (XLS-R: SELF-SUPERVISED CROSS-LINGUAL SPEECH
REPRESENTATION LEARNING AT SCALE), it is hoped that XLS-R (0.3B), XLS-R (1B), and XLS-R (2B) pre-trained models can be added to torchaudio.pipelines.

### Motivation, pitch

'XLS-R: SELF-SUPERVISED CROSS-LINGUAL SPEECH
REPRESENTATION LEARNING AT SCALE' aims to train pre-trained models based on a large corpus, and special thanks to you for adding the XLR-53 model to torchaudio.pipelines. The important application of these models actually lies in the three models XLS-R (0.3B), XLS-R (1B), and XLS-R (2B), as they have more training speech and fine-tuning. Therefore, the performance of these three models is better in downstream tasks of speech.

**Comment by nateanl** [comment]
Hi @xj-111, thanks for sharing the feature request. I saw there are both pre-trained models and fine-tuned models for XLS-R in https://github.com/facebookresearch/fairseq/tree/main/examples/wav2vec/xlsr. Could you confirm which models you were referring to?

**Comment by xj-111** [comment]
https://dl.fbaipublicfiles.com/fairseq/wav2vec/xlsr2_300m.pt
https://dl.fbaipublicfiles.com/fairseq/wav2vec/xlsr2_960m_1000k.pt
https://dl.fbaipublicfiles.com/fairseq/wav2vec/xlsr2_2B_1000k.pt

Thank you for your reply, the above are the pre-trained models that I want to add to torchaudio.pipelines.

**Comment by mthrok** [comment]
We do not have a strict threshold for paper citation, but it seems the paper is reasonably popular, so I think we can add them. My question is, do we need some trick to load 1B param model? or can it be loaded in the same way as regular models?

**Comment by xj-111** [comment]
How to load the model with 1B or 2B parameters is indeed a serious problem, which may take time to deal with it. I wonder if I can bring in that 300M model first and deal with the rest later.

**Comment by nateanl** [comment]
I think it makes sense to work on the 300M model as a start, meanwhile looking into how to load the big models into GPU.

Btw, although the model checkpoint for the 2B model is 24GB, the model state dictionary part is only 8GB. I also confirm it from HF's model card https://huggingface.co/facebook/wav2vec2-xls-r-2b I'm wondering if 8GB is a reasonable size to load into single GPU?, for example, RTX 3060?

**Comment by nateanl** [comment]
Hi @xj-111, the XLS-R models have been added to torchaudio via #2959 and #2978. You can use them by either installing the nightly version of torchaudio or building from source. Feel free to open an issue if you meet any problem when using the XLS-R models.
