### ISSUE TITLE
Incorrect mel filterbank when f_max != sample_rate // 2

### ISSUE THREAD

**Issue by jongwook** [pytorch/audio#292]
## 🐛 Bug

`MelScale` and thus `MelSpectrogram` will not use the correct filterbank when `f_max` is not equal to `sample_rate // 2`.

## To Reproduce

The following should give the same filterbank matrix:

```python
# Equivalent filterbank construction by Librosa
fb = librosa.filters.mel(sr=22050, n_fft=2048, n_mels=128, fmin=0.0, fmax=8000, htk=True, norm=None)

# TorchAudio's Filterbank
fb = torchaudio.transforms.MelScale(sample_rate=22050, n_mels=128, f_max=8000.0, n_stft=1025).fb
```

## Expected behavior

Librosa's Mel filterbank stops at certain frequency bin, since `f_max` is lower than the Nyquist frequency.

![image](https://user-images.githubusercontent.com/266841/65362593-dd9e8980-dbbc-11e9-8e5d-550ccdc679b8.png)

`MelScale`'s filter will fill up until the Nyquist frequency no matter what:

![image](https://user-images.githubusercontent.com/266841/65362642-032b9300-dbbd-11e9-9381-4ad7b0f2995c.png)

The function `F.create_fb_matrix` uses `f_max` but places at the last frequency bin regardless of `sample_rate`. This ends up creating filters in a wrong Mel scale.

## Environment

Same as #287 

## Additional context

Currently we can work around this bug by assigning Librosa's filterbank in TorchAudio module's filterbank attribute.

**Comment by engineerchuan** [comment]
Hi,

I was able to confirm this issue.  I have created a pull request to fix this.  I ran the following comparison code on the PR and see similar results.

```
# Librosa vs Pytorch
import torchaudio 
import librosa
import matplotlib.pyplot as plt

SAMPLE_RATE = 22050
N_MEL = 10
FMIN = 2000.
FMAX = 8000.

plt.subplot(2, 1, 1)
plt.title('LibRosa Filter Bank')
librosa_fb = librosa.filters.mel(sr=SAMPLE_RATE, n_fft=2048, n_mels=N_MEL, fmin=FMIN, fmax = FMAX, htk=True, norm=None)
print("Librosa Filter Bank is of size: ", len(librosa_fb), len(librosa_fb[0]))
for i in range(len(librosa_fb)):
    plt.plot(librosa_fb[i])


plt.subplot(2, 1, 2)
plt.title('Torchaudio Filter Bank')
fb = torchaudio.transforms.MelScale(sample_rate=SAMPLE_RATE, n_mels=N_MEL, f_min=FMIN, f_max = FMAX, n_stft=1025).fb
print("Torchaudio Filter Bank is of size: ", fb.size(0), fb.size(1))
plt.plot(fb)

plt.show()
```

Thanks,

Chuan

**Comment by vincentqb** [comment]
Thanks for reporting this! #292 should have fixed this. If this is not the case, please feel free to re-open the issue.
