### ISSUE TITLE
torchaudio error: OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xvdp** [pytorch/audio#2932]
### 🐛 Describe the bug

torchaudio fails to open on a fresh conda installation, using cuda 11.6 and ubuntu 18.

```bash
conda create -n abj python=3.9 numpy  matplotlib psutil opencv pandas h5py jupyter networkx accimage
conda activate abj
conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
conda install -c bottler nvidiacub
conda install pytorch3d -c pytorch3d
python
```
```python
import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/z/miniconda3/envs/abj/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/z/miniconda3/envs/abj/lib/python3.9/site-packages/torchaudio/_extension.py", line 103, in <module>
    _init_extension()
  File "/home/z/miniconda3/envs/abj/lib/python3.9/site-packages/torchaudio/_extension.py", line 88, in _init_extension
    _load_lib("libtorchaudio")
  File "/home/z/miniconda3/envs/abj/lib/python3.9/site-packages/torchaudio/_extension.py", line 51, in _load_lib
    torch.ops.load_library(path)
  File "/home/z/miniconda3/envs/abj/lib/python3.9/site-packages/torch/_ops.py", line 256, in load_library
    ctypes.CDLL(path)
  File "/home/z/miniconda3/envs/abj/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
```
Adding `print(path)` to line 255 torch/_ops.py, ie just before `ctypes.CDLL(path)` 
prints  /home/z/miniconda3/envs/abj/lib/python3.9/site-packages/torchaudio/lib/libtorchaudio.so, which exists, and isnt the path that mentioned in the error. 

running 
```~/miniconda3/envs/abj$ find . -name libtorch_cuda_cpp.so```
returns a blank.

I noticed that this error is also mentioned in https://github.com/NVIDIA/NeMo/issues/4406
and seems similar to   https://github.com/pytorch/pytorch/issues/85085
but im not working with pytorch-nightly and im not on the latest cuda. 

I posted this bug to pytorch as well: https://github.com/pytorch/pytorch/issues/91186 
r is this something falling thru the cracks? 

### Versions

Collecting environment information...
PyTorch version: 1.12.1.post201
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 15:55:03)  [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-135-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: NVIDIA TITAN RTX
Nvidia driver version: 510.39.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.0
[pip3] pytorch3d==0.7.2
[pip3] torch==1.12.1.post201
[pip3] torchaudio==0.12.1
[pip3] torchvision==0.14.0a0+2ba5a5d
[conda] cudatoolkit               11.6.0               habf752d_9    nvidia
[conda] magma                     2.5.4                hc72dce7_4    conda-forge
[conda] mkl                       2022.1.0           hc2b9512_224  
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch                   1.12.1          cuda112py39hb0b7ed5_201    conda-forge
[conda] pytorch-cuda              11.6                 h867d48c_1    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch3d                 0.7.2           py39_cu116_pyt1121    pytorch3d
[conda] torchaudio                0.12.1               py39_cu116    pytorch
[conda] torchvision               0.14.0          cuda112py39h1a1de93_0    conda-forge

**Comment by malfet** [comment]
You've installed pytorch from conda-forge (build against cuda 11.2 I guess), but torchaudio from pytorch repository which are not compatible with each other, which I guess is due to pytorch3d dependency. Please consider building `pytorch3d` from source (or ask the maintainer to build against `pytorch` rather than `conda-forge` channel
