### ISSUE TITLE
RuntimeError: torchaudio.sox_effects.sox_effects.apply_effects_tensor requires sox

### ISSUE THREAD

**Issue by StevenMichael3213** [pytorch/audio#2938]
### 🐛 Describe the bug

import torchaudio
from pathlib import Path

in_path = Path('D:\DataSet\zh-CN\clips\common_voice_zh-CN_18524189.mp3').as_posix()
waveform, sr = torchaudio.load(in_path)
target_sr=16_000
converted, converted_sr = torchaudio.sox_effects.apply_effects_tensor(
            waveform, sr, [["rate", str(target_sr)], ["channels", "1"]]
)

When I run the simple code above, I get the following error：
```
Traceback (most recent call last):
  File "d:\STS\fairseq\examples\test\hello.py", line 31, in <module>
    converted, converted_sr = torchaudio.sox_effects.apply_effects_tensor(
  File "D:\STS\fairseq\.venv\lib\site-packages\torchaudio\_internal\module_utils.py", line 143, in wrapped
    raise RuntimeError(f"{func.__module__}.{func.__name__} requires sox")
RuntimeError: torchaudio.sox_effects.sox_effects.apply_effects_tensor requires sox
```
The device is: Windows 10
I have installed sox-14-4-2 and also added its path to my system's environment variables

When I run ``` sox ``` in the command line window, the following information appears
![image](https://user-images.githubusercontent.com/31765462/209467509-c8eda235-9f6d-4d14-8b23-23f6da9e929c.png)

I don't know what should I do to solve this problem please help me

### Versions

Collecting environment information...
PyTorch version: 1.13.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1080
Nvidia driver version: 516.94
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.0
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchvision==0.14.1+cu116
[conda] Could not collect

**Comment by mthrok** [comment]
Hi @StevenMichael3213 

The feature is not supported on Windows. Recent MSVC compilers do not support libsox.
