### ISSUE TITLE
Add ctc beam search decoder using cuda implementation

### ISSUE THREAD

**Issue by yuekaizhang** [pytorch/audio#2957]
### 🚀 The feature

Hi audio team,
I would like propose to integrate a cuda based ctc prefix beam search decoder into torchaudio. It implemented ctc prefix beam search algorithms using cuda kernels, then, gave python api through pybind. It has better performance comparing with current ctc_decoder using cpu.
If you have interests to adopt this implementation, I could prepare a PR for it.  I could put the kernel implementations under third_party or other places, add Python api in https://github.com/pytorch/audio/blob/main/torchaudio/models/decoder/_ctc_decoder.py.  

### Motivation, pitch

Motivation is to accelerate ctc beam search decoding process using GPU.

**Comment by mthrok** [comment]
Hi @yuekaizhang 

Thanks for the proposal, and that's a nice addition, so feel free to make a PR.
The only concern is that is this code compatible with BSD-2 license?

**Comment by yuekaizhang** [comment]
> 
Thanks. This code is good with BSD-2 license. Let me start to prepare a PR.
