### ISSUE TITLE
StreamReader 'Invalid data found when processing input' for batches of h264 frames before eventually working

### ISSUE THREAD

**Issue by lucasw** [pytorch/audio#2972]
### 🐛 Describe the bug

I have a stream of frame packets that I accumulate around 40 (well over the keyframe interval) then create a StreamReader:

```
self.stream_reader = StreamReader(self.container, buffer_size=self.container.buffer_size)
frames_per_chunk = 1
self.stream_reader.add_video_stream(frames_per_chunk,
                                    decoder="h264_cuvid",
                                    hw_accel="cuda:0",
                                    decoder_option={"threads": "1", "thread_type": "slice"},
                                    )
```

The container supports `read()` (some more details in #2887)

Setting up the decoding will fail repeatedly but I can catch the exception and start over and collect another set of frames, eventually it starts working, maybe after 3 tries, maybe after 10.  Once it starts working it doesn't throw again, decodes fine.  

```
[W] [1673367362.236 /camera1/stream_to_image ...akd/scripts/stream_to_image.py:  65]: Failed to open the input "<tc_oakd.torch_decoder.Container object at 0x7fab410eb790>" (Invalid data found when processing input).
Exception raised from get_input_format_context at /root/project/torchaudio/csrc/ffmpeg/stream_reader/stream_reader_wrapper.cpp:56 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x7fabd598a86e in /home/lucasw/.local/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5c (0x7fabd59553a8 in /home/lucasw/.local/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: torchaudio::ffmpeg::get_input_format_context(std::string const&, c10::optional<std::string> const&, c10::optional<c10::Dict<std::string, std::string> > const&, AVIOContext*) + 0x230 (0x7fabd546aec0 in /home/lucasw/.local/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio_ffmpeg.so)
frame #3: <unknown function> + 0x2c03d (0x7fab580bb03d in /home/lucasw/.local/lib/python3.10/site-packages/torchaudio/_torchaudio_ffmpeg.so)
frame #4: <unknown function> + 0x281fd (0x7fab580b71fd in /home/lucasw/.local/lib/python3.10/site-packages/torchaudio/_torchaudio_ffmpeg.so)
frame #5: <unknown function> + 0x1b826 (0x7fab580aa826 in /home/lucasw/.local/lib/python3.10/site-packages/torchaudio/_torchaudio_ffmpeg.so)
<omitting python frames>
frame #11: <unknown function> + 0x34675 (0x7fab64c40675 in /home/lucasw/.local/lib/python3.10/site-packages/torchaudio/_torchaudio.so)
frame #36: <unknown function> + 0x29d90 (0x7fac092f9d90 in /lib/x86_64-linux-gnu/libc.so.6)
frame #37: __libc_start_main + 0x80 (0x7fac092f9e40 in /lib/x86_64-linux-gnu/libc.so.6)
```

Same results if using `h264` without the `_cuvid` and no hw_accel.

Are there decoder_options or similar I could pass in that may help?  Are there are any obvious tests to do on the received set of frames to see if they are unsuitable for decoding?  I looked for out of order frames but didn't find any, next I'll see if they are all of a reasonable size, compare to when there is a successful initial decoding.

I'll also experiment with inspecting the frame for header bytes that indicate a key frame and only send that in to the decoder, but I thought the decoder would know how to do that itself.

### Versions

```
Collecting environment information...
PyTorch version: 1.13.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-57-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti
Nvidia driver version: 510.108.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.942
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.1
[pip3] perlin-numpy==0.0.0
[pip3] pytorch-lightning==1.6.4
[pip3] pytorch-ranger==0.1.1
[pip3] pytorch3d==0.7.2
[pip3] torch==1.13.0
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==2.0.0a0+1717eda
[pip3] torchmetrics==0.9.2
[pip3] torchvision==0.14.0
[pip3] types-mypy-extensions==0.4
[conda] Could not collect
```

**Comment by mthrok** [comment]
Does your MP4 stream have moov atom at the beginning?

**Comment by mthrok** [comment]
Reading [this](https://stackoverflow.com/a/64065331/3670924), it seems like MP4 is not suitable for real-time streaming, as moov atom is generated at the end.

**Comment by lucasw** [comment]
Would an ongoing h264 stream (this is from the oak-d camera) with no start or end have moov atoms peppered through it, and I just have to wait for it?  I could see if it's a repeatable packet that works from a recording of a few thousand images in a stream (it isn't an mp4, just all the raw packets from camera).

**Comment by mthrok** [comment]
If it's the row packet, then the issue is more about the data, than StreamReader.
First thing we need to check is whether `ffmpeg` cli can process the data. 
Can you dump data and run `ffmpeg` on it and convert the data into some common video format? 
If the answer is yes, then there is a good chance that StreamReader can handle it, and we need to find a correct mapping from `ffmpeg` command to StreamReader.

You might need to provide options to make it work. 
`ffmpeg <global options> -f h264 <demuxer options> -i <input> <decoder options> <output>`

demuxer options and decoder options can be obtained as follow
```
$ ffmpeg -h demuxer=h264
Demuxer h264 [raw H.264 video]:
    Common extensions: h26l,h264,264,avc.
generic raw video demuxer AVOptions:
  -framerate         <video_rate> .D.........  (default "25")
  -raw_packet_size   <int>        .D.........  (from 1 to INT_MAX) (default 1024)
```

```
$ ffmpeg -h decoder=h264
Decoder h264 [H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10]:
    General capabilities: dr1 delay threads
    Threading capabilities: frame and slice
    Supported hardware devices: videotoolbox
H264 Decoder AVOptions:
  -is_avc            <boolean>    .D.V..X.... is avc (default false)
  -nal_length_size   <int>        .D.V..X.... nal_length_size (from 0 to 4) (default 0)
  -enable_er         <boolean>    .D.V....... Enable error resilience on damaged frames (unsafe) (default auto)
  -x264_build        <int>        .D.V....... Assume this x264 version if no x264 version found in any SEI (from -1 to INT_MAX) (default -1)
```

Once the ffmpeg command works fine, then you can feed `format="h264"`, demuxer options to `option` argument of the constructor of `StreamReader`, then decoder option to `decoder_option` argument of `add_[basic_]video_stream` method.

Beyond that, it's hard for me to debug without data.
If you can share the dumped data, I can take a look into it as well. email me to moto@meta.com .

**Comment by lucasw** [comment]
My binary file has 852 frames in it, ffmpeg with no options complains initially then outputs a video with 797 frames:

```
ffmpeg -f h264 -i bytes.bin test.mp4
...
[h264 @ 0x556ff1c5c600] decode_slice_header error
[h264 @ 0x556ff1c5c600] no frame!
[h264 @ 0x556ff1c5c600] non-existing PPS 0 referenced
...
[h264 @ 0x556ff1c52680] Stream #0: not enough frames to estimate rate; consider increasing probesize
[h264 @ 0x556ff1c52680] decoding for stream 0 failed
[h264 @ 0x556ff1c52680] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
...
Error while decoding stream #0:0: Invalid data found when processing input
[h264 @ 0x556ff222dc80] non-existing PPS 0 referenced
[h264 @ 0x556ff222dc80] decode_slice_header error
[h264 @ 0x556ff222dc80] no frame!
[NULL @ 0x556ff1c5c600] non-existing PPS 0 referenced
...
[libx264 @ 0x556ff1c78f80] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x556ff1c78f80] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x556ff1c78f80] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=11 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'test3.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt470bg, progressive), 640x360, q=2-31, 25 fps, 12800 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  797 fps=580 q=-1.0 Lsize=    1239kB time=00:00:32.88 bitrate= 308.8kbits/s speed=23.9x    
...
```

[ffmpeg_output.txt](https://github.com/pytorch/audio/files/10393738/ffmpeg_output.txt)

https://user-images.githubusercontent.com/1334122/211845229-64eb472a-e388-4430-a2b1-071858231da4.mp4

(I'll attach the bin next)

**Comment by lucasw** [comment]
This unzips into a 200 MB bytes.bin which produced the above video with ffmpeg

[bytes.zip](https://github.com/pytorch/audio/files/10393774/bytes.zip)

(how did zip get a lossless 10x compression on the h264?)

**Comment by mthrok** [comment]
Okay, so reading comments like https://stackoverflow.com/a/15011264, the error message
`non-existing PPS 0 referenced` means that the frames fed to StreamReader (or underlying H264 decoder) are not key frame.

We can actually see the same errors on `StreamReader` by [setting the log level](https://pytorch.org/audio/main/generated/torchaudio.utils.ffmpeg_utils.html#set-log-level) like the following.

```python
from torchaudio.io import StreamReader
from torchaudio.utils import ffmpeg_utils

ffmpeg_utils.set_log_level(32)

with open("repro/bytes.bin", "rb") as f:
    s = StreamReader(f, format="h264")
```

```
[h264 @ 0x14022b4b0] non-existing PPS 0 referenced
[h264 @ 0x14022b4b0] non-existing PPS 0 referenced
[h264 @ 0x14022b4b0] decode_slice_header error
[h264 @ 0x14022b4b0] no frame!
[h264 @ 0x14022b4b0] non-existing PPS 0 referenced
[h264 @ 0x14022b4b0] non-existing PPS 0 referenced
[h264 @ 0x14022b4b0] decode_slice_header error
[h264 @ 0x14022b4b0] no frame!
[h264 @ 0x14022b4b0] non-existing PPS 0 referenced
[h264 @ 0x14022b4b0] non-existing PPS 0 referenced
[h264 @ 0x14022b4b0] decode_slice_header error
[h264 @ 0x14022b4b0] no frame!
[h264 @ 0x127ac4e80] Stream #0: not enough frames to estimate rate; consider increasing probesize
[h264 @ 0x127ac4e80] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
```

And since you say, it eventually starts working, so if we can let FFmpeg patient to wait for the arrival of keyframe,
then we can make it work. The last error message gives us hit. `Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options`.

The [FFmpeg documentation](https://ffmpeg.org/ffmpeg-formats.html) says
> probesize integer (input)
> Set probing size in bytes, i.e. the size of the data to analyze to get stream information. A higher value will enable detecting more information in case it is dispersed into the stream, but will increase latency. Must be an integer not lesser than 32. It is 5000000 by default.

Adding `{"probesize": "20M"}` to the constructor seems to make it work.

```python
with open("repro/bytes.bin", "rb") as f:
    s = StreamReader(f, format="h264", option={"probesize": "20M"})
    s.add_video_stream(-1, stream_index=0, decoder="h264", )
    s.process_all_packets()
    chunk, = s.pop_chunks()
    print(chunk.shape)
```

prints

```
torch.Size([797, 3, 360, 640])
```

So what I think is happening is that the construction of StreamReader and the start of camera feed are not in-sync, so when StreamReader starts to probe the input stream, they cannot find a keyframe, and they cannot do anything with the intraframes arrived at the beginning and they are dropped.

Assuming that your camera will emit key frames once in few seconds, I think `probesize` parameter to (key frame interval in seconds * frame rate * average frame size in bytes * some margin) could make it work robustly.

**Comment by lucasw** [comment]
Thanks, `StreamReader(f, format="h264", option={"probesize": "20M"})` works.  (I got `Unexpected options: probesize` when I neglected to provide the `format` to stream reader but figured that out quickly)
