### ISSUE TITLE
Nightly CUDA build does not have cuda code

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#2979]
I was testing HW decoding notebook https://pytorch.org/audio/stable/hw_acceleration_tutorial.html, and got error [here](https://github.com/pytorch/audio/blob/main/torchaudio/csrc/ffmpeg/stream_reader/stream_reader.cpp#L243-L247).

The following code on fresh Google colab env reports `None`, where it should print CUDA version.

```python
!pip uninstall -y -q torch torchaudio torchvision torchtext
!pip install --progress-bar off --pre torch torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cu116 2> /dev/null

import torchaudio
print(torchaudio._extension._check_cuda_version())
```

Looking at the nightly build log, USE_CUDA macro is not defined anywhere.

https://github.com/pytorch/audio/actions/runs/3911306154/jobs/6684555785

**Comment by mthrok** [comment]
Perhaps https://github.com/pytorch/audio/pull/2930 caused this,

**Comment by seemethere** [comment]
@DanilBaibak can you take a look at this on Monday?

**Comment by mthrok** [comment]
From https://github.com/pytorch/audio/actions/runs/3914313934/jobs/6691238420, 
`torch.cuda.is_available()` reports `False` [here](https://github.com/pytorch/audio/blob/main/tools/setup_helpers/extension.py#L42).

So it could be either PyTorch installation or GPU availability.

**Comment by malfet** [comment]
Well, `torch.cuda.is_available()` should return false as compilation is running on CPU nodes (presumably)
But `torch.backends.cuda.is_built()` should yield True.
For example, `python -c "import torch;print(torch.cuda.is_available(), torch.backends.cuda.is_built(), torch.backends.mps.is_built())"` returns: `True True False` on Linux box with GPU, `False True False` on Linux box without GPU if PyTorch+CUDA is installed and `False False True` on MacOS

**Comment by mthrok** [comment]
> Well, `torch.cuda.is_available()` should return false as compilation is running on CPU nodes (presumably)
> But `torch.backends.cuda.is_built()` should yield True.
> For example, `python -c "import torch;print(torch.cuda.is_available(), torch.backends.cuda.is_built(), torch.backends.mps.is_built())"` returns: `True True False` on Linux box with GPU, `False True False` on Linux box without GPU if PyTorch+CUDA is installed and `False False True` on MacOS

Thanks for the info. Do we need to change the `USE_CUDA` logic for compilation then?

https://github.com/pytorch/audio/blob/main/tools/setup_helpers/extension.py#L41-L42

**Comment by malfet** [comment]
> Thanks for the info. Do we need to change the `USE_CUDA` logic for compilation then?
> 
> https://github.com/pytorch/audio/blob/main/tools/setup_helpers/extension.py#L41-L42

Wow, this logic is out of this world (/me is running `git blame` and hope that I'm not the one that introduced it ;) )
As far as I remember, the way it worked before is that CI defined `USE_CUDA` or `USE_ROCM` and build happened rather than it was ever properly auto-detected, i.e. this fallback was never hit

**Comment by DanilBaibak** [comment]
There is one more note. If I try to get the package version, it will show the cuda version it was compiled with. If I understand the logic correctly:

```
!pip uninstall -y -q torch torchaudio torchvision torchtext
!pip install --progress-bar off --pre torch torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cu116

import torchaudio

print(torchaudio._extension._check_cuda_version())
print(torchaudio.__version__)
```

Output:
```
None
2.0.0.dev20230122+cu116
```

**Comment by malfet** [comment]
Few comments:
 - When making a BE/no-op/migration changes, it's good to run some basic sanity checks, like total binary size/total number of compiled files should not change. Compilation time would also be a good indicator.
- An easy way to check if CUDA compilation is actually happening, as to grep the log for any `nvcc` invocations, which immediately finds one in CircleCI log (see https://app.circleci.com/pipelines/github/pytorch/audio/13850/workflows/9f6b5295-2185-4548-8d3c-a918b0cdeef9/jobs/1046414?invite=true#step-103-890 ), but none in the github log (see for example https://github.com/pytorch/audio/actions/runs/3986389538/jobs/6834922423 )

**Comment by malfet** [comment]
By the way, looks like torchaudio for ROCm didn't have GPU components even in the old CircleCI build, see https://app.circleci.com/pipelines/github/pytorch/audio/13850/workflows/9f6b5295-2185-4548-8d3c-a918b0cdeef9/jobs/1046413
@jithunnair-amd  is this expected?

**Comment by DanilBaibak** [comment]
@mthrok the issue torchaudio build with CUDA was fixed.
<img width="1100" alt="Screenshot 2023-01-25 at 14 56 41" src="https://user-images.githubusercontent.com/3964975/214583195-c2626d24-680b-4bf6-8efe-b6441b3e35ed.png">
