### ISSUE TITLE
shape = specgram.size() TypeError: int object not callable 

### ISSUE THREAD

**Issue by Andydiantu** [pytorch/audio#2983]
### 🐛 Describe the bug

In the file, torchaudio/functional/functional.py", line 799. It wrote `shape = specgram.size()`, which leads to the error TypeError: int object not callable, which makes the entire transformation not usable. And this error appears 3 times in the file. 

### Versions

wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
--2023-01-14 11:04:05--  https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17278 (17K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py      100%[===================>]  16.87K  --.-KB/s    in 0.001s  

2023-01-14 11:04:05 (17.4 MB/s) - ‘collect_env.py’ saved [17278/17278

**Comment by Andydiantu** [comment]
PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.13 (default, Oct 21 2022, 23:50:54)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-57-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 10.1.243
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1060
Nvidia driver version: 470.161.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.23.4           py38h14f4228_0  
[conda] numpy-base                1.23.4           py38h31eccc5_0  
[conda] pytorch                   1.10.2          cpu_py38hfa7516b_0  
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchvision               0.11.3          cpu_py38h164cc8f_2

**Comment by mthrok** [comment]
I presume NumPy NDArray was fed to the functional, which is not supported.
Though I think `shape` attribute is more intuitive than `size()` and consistent with NumPy.

**Comment by Andydiantu** [comment]
Thank you so much for solving my dummy mistake!
