### ISSUE TITLE
torchaudio.transforms.Loudness is soooo slow on GPU

### ISSUE THREAD

**Issue by turian** [pytorch/audio#3006]
### 🐛 Describe the bug

torchaudio.transforms.Loudness() is painfully slow on a GPU (A100) with, say, 200000 samples.

On CPU it flies.

If this is expected, at least it should be documented and a warning should be given the first time it is run on a GPU.

### Versions

Collecting environment information...
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.991
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.4
[pip3] pytorch-lightning==1.9.0
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchmetrics==0.11.0
[pip3] torchview==0.2.5
[pip3] torchvision==0.13.1
[conda] Could not collect

**Comment by hwangjeff** [comment]
Hi @turian — thanks for creating the issue. Would you mind posting a code snippet that would allow us to reproduce what you're seeing?

**Comment by turian** [comment]
```
import torchaudio
import torch

from tqdm.auto import tqdm

l = torchaudio.transforms.Loudness(sample_rate=44100)
l = l.to("cpu")
x = torch.rand(1, 44100 * 10, device="cpu")
for i in tqdm(list(range(10))):
  l(x)

l = torchaudio.transforms.Loudness(sample_rate=44100)
l = l.to("cuda")
x = torch.rand(1, 44100 * 10, device="cuda")
for i in tqdm(list(range(10))):
  l(x)
```

The first loop takes under a second. 

The second one takes 45 seconds per audio.

**Comment by hwangjeff** [comment]
@turian thanks! Was able to reproduce on my side. It looks like the execution time is dominated by the for loop within lfilter. Coincidentally, there is a related issue open at https://github.com/pytorch/audio/issues/1408 with a solution landing imminently — perhaps you can follow that issue for updates.

**Comment by mthrok** [comment]
Running the given script with #3018 gives the following;

```
100%|██████████| 10/10 [00:00<00:00, 42.81it/s]
100%|██████████| 10/10 [00:02<00:00,  3.50it/s]
```

while on the main branch, it indeed takes forever.

```
100%|██████████| 10/10 [00:00<00:00, 49.14it/s]
```

**Comment by mthrok** [comment]
cc @yoyololicon Thanks for your PR, it is very timely.

**Comment by turian** [comment]
@hwangjeff @mthrok shall we close?
