### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict - size mismatch for mel_spectrogram.mel_scale.fb: copying a param with shape torch.Size([1025, 128]) from checkpoint, the shape in current model is torch.Size([0]).

### ISSUE THREAD

**Issue by vgoklani** [pytorch/audio#301]
Not sure what's going on here, but I've submitted a code example:

	import torch
	import torchaudio

	class Example(torch.nn.Module):
		def __init__(self, time_seconds: int = 1, sr: int = 16000, 
			n_mels: int = 2**7, n_fft: int = 2**11, top_db: int = 80):
			super().__init__()

			self._time_seconds = time_seconds
			self._sr = sr
			self._n_mels = n_mels
			self._n_fft = n_fft
			self._top_db = top_db

			self._hop_length = int(self._n_fft / 4)

			self.mel_spectrogram = torchaudio.transforms.MelSpectrogram(sample_rate=self._sr, 
				n_fft=self._n_fft, hop_length=self._hop_length, 
				n_mels=self._n_mels)
			self.amplitude_to_db = torchaudio.transforms.AmplitudeToDB(stype='power', 
				top_db=self._top_db)

		def forward(self, waveform: torch.Tensor):
			mel_spectrogram = self.mel_spectrogram(waveform)
			return self.amplitude_to_db(mel_spectrogram)

	model1 = Example()
	model2 = Example()

	waveform_batch = torch.randn(1024, 1, 16000).type(torch.FloatTensor)

	model1(waveform_batch[0]); 	# runs on one sample, no batch support!

	model2.load_state_dict(model1.state_dict())

	---------------------------------------------------------------------------
	RuntimeError                              Traceback (most recent call last)
	<ipython-input-19-a8149d9091a8> in <module>
	----> 1 model2.load_state_dict(model1.state_dict())

	/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
	    843         if len(error_msgs) > 0:
	    844             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
	--> 845                                self.__class__.__name__, "\n\t".join(error_msgs)))
	    846         return _IncompatibleKeys(missing_keys, unexpected_keys)
	    847 

	RuntimeError: Error(s) in loading state_dict for Example:
		size mismatch for mel_spectrogram.mel_scale.fb: copying a param with shape torch.Size([1025, 128]) from checkpoint, the shape in current model is torch.Size([0]).

Is there a workaround? Thank you

**Comment by engineerchuan** [comment]
Hi. Are you using the latest master?  We recently pushed some code related to filter bank.

**Comment by vgoklani** [comment]
Hi @engineerchuan thanks for the response. I don't think it's that, but instead, related to https://github.com/pytorch/audio/issues/245

**Comment by vincentqb** [comment]
Thanks for reporting this, and providing a code snippet! I can reproduce on the last release, but on master the issue has been fixed and I get `<All keys loaded successfully>`. I'll close this issue, but please feel free to re-open if this continues on master.
