### ISSUE TITLE
does audio lib has c++ interface, i want to use it for pytorch model online deployment?

### ISSUE THREAD

**Issue by mlinxiang** [pytorch/audio#302]
Does audio lib has C++ interface? I want to use it for pytorch model online deployment.

**Comment by vincentqb** [comment]
Thanks for the request. We do not have an C++ interface. I'm closing this issue, but please feel free to ask further help on the forum as needed.

**Comment by Oktai15** [comment]
@vincentqb what about  certain functions? https://discuss.pytorch.org/t/torchaudio-load-in-c/62400

**Comment by mthrok** [comment]
This is now possible. Please check out our example  https://github.com/pytorch/audio/tree/main/examples/libtorchaudio
