### ISSUE TITLE
Failed to detect the source stream format.

### ISSUE THREAD

**Issue by d4l3k** [pytorch/audio#3022]
### 🐛 Describe the bug

I have some video footage that's packed as raw h265 frames. 

```
reader = io.BytesIO(buf)
r = StreamReader(reader, format='hevc')
stream = r.add_basic_video_stream(
    frames_per_chunk=-1,
    format="yuv420p10le",
)
```

I need to be able to specify pix_fmt since it's raw h265 frames and there's no header information

The corresponding ffmpeg command is:

```
ffmpeg  -f hevc -i - -pix_fmt yuv420p12le ...
```

However, the stream check takes effect before the format setting is applied so it ends up failing

```
RuntimeError: Failed to detect the source stream format.
Exception raised from add_stream at /root/project/torchaudio/csrc/ffmpeg/stream_reader/stream_reader.cpp:248 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7ff6c88a6457 in /home/rice/venvs/o/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x68 (0x7ff6c88704b5 in /home/rice/venvs/o/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: torchaudio::ffmpeg::StreamReader::add_stream(int, AVMediaType, int, int, c10::optional<std::string> const&, c10::optional<std::string> const&, c10::optional<c10::Dict<std::string, std::string> > const&, c10::Device const&) + 0x1cf (0x7ff68e8a8cdf in /home/rice/venvs/o/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio_ffmpeg.so)
frame #3: torchaudio::ffmpeg::StreamReader::add_video_stream(long, long, long, c10::optional<std::string> const&, c10::optional<std::string> const&, c10::optional<c10::Dict<std::string, std::string> > const&, c10::optional<std::string> const&) + 0x5e (0x7ff68e8a8d8e in /home/rice/venvs/o/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio_ffmpeg.so)
frame #4: torchaudio::ffmpeg::StreamReaderFileObj::add_video_stream(long, long, long, c10::optional<std::string> const&, c10::optional<std::string> const&, c10::optional<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > const&, c10::optional<std::string> const&) + 0x56 (0x7ff69d6b95d6 in /home/rice/venvs/o/lib/python3.10/site-packages/torchaudio/_torchaudio_ffmpeg.so)
```

### Versions

PyTorch version: 1.13.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 12.2.0
Clang version: 14.0.6
CMake version: version 3.25.0
Libc version: glibc-2.36

Python version: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0] (64-bit runtime)
Python platform: Linux-6.0.9-arch1-1-x86_64-with-glibc2.36
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 2080
GPU 1: NVIDIA GeForce RTX 3070 Ti
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 520.56.06
cuDNN version: Probably one of the following:
/opt/cudnn6/lib64/libcudnn.so.6.0.21
/usr/lib/libcudnn.so.8.6.0
/usr/lib/libcudnn_adv_infer.so.8.6.0
/usr/lib/libcudnn_adv_train.so.8.6.0
/usr/lib/libcudnn_cnn_infer.so.8.6.0
/usr/lib/libcudnn_cnn_train.so.8.6.0
/usr/lib/libcudnn_ops_infer.so.8.6.0
/usr/lib/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.971
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.1
[pip3] onnx2torch==1.5.4
[pip3] pytorch-memlab==0.2.4
[pip3] pytorch-msssim==0.2.1
[pip3] pytorch3d==0.7.2
[pip3] torch==1.13.1+cu116
[pip3] torchaudio==0.13.1+cu116
[pip3] torchdrive==0.0.1
[pip3] torchmetrics==0.9.3
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.14.1+cu116
[conda] Could not collect

**Comment by mthrok** [comment]
Hi @d4l3k 

The `format` argument in `add_XXX_stream` methods means, you want `StreamReader` to perform conversion from whatever the source pixel format to the one you specify. This is same for `ffmpeg` command when `-pix_fmt` is provided after `-i <src>`.

Once you tell FFmpeg it's `hevc` format, FFmpeg is supposedly parse the bit stream and detect the input format. Can you first test with `add_basic_video_stream`, and see what happens?

**Comment by d4l3k** [comment]
@mthrok I see, got it. It's the same error with add_basic_video_stream/add_video_stream with or without format

My video stream is raw frames without any metadata/container and thus isn't automatically detected by ffmpeg. It requires format to correctly decode

Here's the equivalent PyAV code:

```
        graph = Graph()
        link_nodes(
            graph.add_buffer(
                height=1280, width=960, format="yuv420p10le", time_base=1 / 1000
            ),
            graph.add("scale", f"{self.dim[0]}:{self.dim[1]}"),
            graph.add("swapuv"),
            graph.add("buffersink"),
        )
        graph.configure()
        self.graph: Graph = graph
...
            with av.open(data, format="hevc") as vid:
                # todo seek to each frame
                idx = 0
                for frame in vid.decode():
                    if idx == 0 and not frame.key_frame:
                        raise IndexError(f"{h265_path} first frame not iframe {frame}")
                    frame_idx = decode_idxs[idx]
                    if frame_idx in frames:
                        self.graph.push(frame)
                        frame = self.graph.pull()
                        frame = frame.reformat(format="rgb48le")
                        frame = frame.to_ndarray()
                        frame = (
                            torch.from_numpy(frame.astype(np.float32))
                            .permute(2, 0, 1)
                            .div_(2**16)
                        )
                        out.append(normalize01(frame))
```

https://github.com/d4l3k/torchdrive/blob/main/torchdrive/datasets/rice.py#L195-L204

https://github.com/d4l3k/torchdrive/blob/main/torchdrive/datasets/rice.py#L336-L353

**Comment by mthrok** [comment]
oh I see. This might be a case where StreamReader might not handle well.

For a case of simple raw audio, https://pytorch.org/audio/stable/tutorials/streamreader_basic_tutorial.html#headerless-media one can provide format and option.

But I don't see pixel format option for demuxer option.

```
ffmpeg -hide_banner -h demuxer=hevc
Demuxer hevc [raw HEVC video]:
    Common extensions: hevc,h265,265.
hevc demuxer AVOptions:
  -framerate         <video_rate> .D.........  (default "25")
  -raw_packet_size   <int>        .D.........  (from 1 to INT_MAX) (default 1024)
```

Do you know a ffmpeg command that can generate synthetic data I can play with? or can you share a sample data?

**Comment by d4l3k** [comment]
@mthrok you're totally right and I had a bug in my code so I was trying to decode just a single i frame. Sorry for bothering you! Trying to get 10bit video working now
