### ISSUE TITLE
TorchAudio HW Acceleration Tutorial

### ISSUE THREAD

**Issue by maysteinfeld** [pytorch/audio#3041]
Hi,
it's seems like "TorchAudio_Streaming_API_HW_Acceleration_Tutorial.ipynb" notebook is not updated to the stable version of torchaudio 0.13.1.

docs: https://pytorch.org/audio/0.13.1/hw_acceleration_tutorial.html?highlight=hardware+accelerated+video+decoding+encoding

notebook: https://colab.research.google.com/drive/1DDah_IaGULEO66CfQWltRqaVheBkiXdN#sandboxMode=true

In addition when using the notebook I get:
![image](https://user-images.githubusercontent.com/88133956/217237515-a651174f-efb0-44e8-8cf3-dce508e79b43.png)

to me, it looks like torchaudio is not properly using ffmpeg.

Thanks,

**Comment by mthrok** [comment]
Hi @maysteinfeld 

Thanks for the report. It looks like they updated Google Colab's runtime environment and they have everything needed to run GPU decoding pre-installed.

Can you restart the Colab (disconnect and relaunch) and connect GPU instance then just start from the section you had the issue?

I confirm that decoding part of the tutorial works. There is some issue with the encoding, which I have never seen before, so I will look into it.

https://pytorch.org/audio/stable/hw_acceleration_tutorial.html#Check-FFmpeg-installation

**Comment by maysteinfeld** [comment]
Hi, thanks @mthrok,
If I'm skipping all installation part and moving forward to the "Check-FFmpeg-installation" part, the decoding part is working.
waiting for your solution regarding the encoding part, because this is what is most relevant for me.
It's possible to fix the installation part - requirements, etc in the docs? because I want to integrate this into my local code.
(if I re-compile the FFmpeg and run the installation part local or in the collab- the decoding is not working also)

Thanks

**Comment by mthrok** [comment]
The encoding part works if one installs nightly build with CUDa 11.7.

So what I suggest as a temporary workaround is that
1. Install nightly with cu117. `!pip install --progress-bar off --pre torch torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cu117 2> /dev/null`
2. Skip the manual FFmpeg build part and start from `Check FFmpeg Installation section`.

**Comment by maysteinfeld** [comment]
Thanks,
And if I want to set up my local env, what are the installations I need?
which FFmpeg?

**Comment by mthrok** [comment]
If you need it in your local setup, then you need to install FFmpeg with GPU decoder/encoder capability. But the license does not allow to re-distribute FFmpeg with GPU capabilities, so I don't normally find a distribution channel which includes this, so the best ways is to build it from the source.
(One exception I am aware is Windows and Conda. [Conda-forge Windows 64 binary](https://anaconda.org/conda-forge/ffmpeg) has somehow GPU capability enabled, so if your environment happens to be Windows/Conda, then you can install it via conda and it just works.)

Once you install FFmpeg, and set the right path, then TorchAudio will pick up.

Now, there are couple of things you need to be aware.
1. If you are using TorchAudio official binary distribution, then the version of FFmpeg has to be between 4.1 and 5.
2. If you are building TorchAudio from source, you can use FFmpeg 5.

Common trap is that if you have multiple FFmpeg installed, torchaudio might pick up a different one than you are expecting, so it is recommended to have only one installation of FFmpeg, unless you are absolutely sure about runtime library path manipulation. https://stackoverflow.com/a/74141751 (I wonder why everyone ended up repeating the same phrase "torchaudio is not using ffmpeg properly")

**Comment by maysteinfeld** [comment]
Thanks, for now, seem to be working. If I will see more issues in the future I will reach out.
Have a great day
