### ISSUE TITLE
HW acceleration

### ISSUE THREAD

**Issue by maysteinfeld** [pytorch/audio#3054]
Hi,
follow the tutorial: 
https://pytorch.org/audio/stable/hw_acceleration_tutorial.html#Check-FFmpeg-installation

I succeed to use this in my environment and it works really well, Thanks.

I wanted to know if it's possible to give the Stream writer different ffmpeg filters to use and still work from GPU to GPU.
for example: send another torch of a logo to overlay over the video or scale the video to a different resolution.

Thanks

**Comment by mthrok** [comment]
It seems that people use `-filter_complex overlay` for this kind of jobs. Unfortunately filter_complex is not supported in `torchaudio.io`. So you need to do it manually.

**Comment by maysteinfeld** [comment]
Ok thanks
