### ISSUE TITLE
Floating point n_steps in torchaudio.transforms.PitchShift

### ISSUE THREAD

**Issue by turian** [pytorch/audio#3065]
### 🚀 The feature

`n_steps` in `torchaudio.transforms.PitchShift` should be a float.

### Motivation, pitch

If `n_steps` in `torchaudio.transforms.PitchShift` is a float, it is differentiable and can be optimized for particular applications.

### Alternatives

Increasing `bins_per_octave` to 1000.

**Comment by mthrok** [comment]
It's an interesting idea, but IIRC, PitchShit uses phase_vocoder, which is not differentiable.

**Comment by turian** [comment]
@mthrok Will close the issue.

Quick question while we're on this topic. PitchShift and then un-PitchShift sounds pretty good, almost indistinguishable from the original. But transforms.TimeStretch in a quick listening test I did, when applying it and reversing it, introduced a lot of artifacts. Is there a high-quality fast time stretch in torchaudio?

**Comment by mthrok** [comment]
Unfortunately, there isn't one in torchaudio. I hear https://pypi.org/project/rubberband/ (https://breakfastquay.com/rubberband/) is good in quality.

Adding such a function to torchaudio was my interest, but I did not have the bandwidth to do it.

**Comment by turian** [comment]
@mthrok closing this issue. I hear also that https://www.surina.net/soundtouch/soundstretch.html is good from the soundtouch library
