### ISSUE TITLE
Google colab notebook pointing to PyTorch 1.13.1

### ISSUE THREAD

**Issue by agunapal** [pytorch/audio#3153]
### 📚 The doc issue

When I open https://pytorch.org/audio/main/tutorials/audio_data_augmentation_tutorial.html in google colab and try running the notebook, I see that the PyTorch version is 1.13.1
![Screenshot 2023-03-06 at 6 17 58 PM](https://user-images.githubusercontent.com/16617092/223302468-664694ef-ddf3-4b67-953e-91fb75a94677.png)

**Comment by mthrok** [comment]
When opening the notebook, it uses the default environment of Google Colab, so this is working as expected.
If the notebook you open requires features from nightly build, there should be messages and instructions to install nightly build at the begnning.
