### ISSUE TITLE
Conflicts installing torchaudio-cpu through conda

### ISSUE THREAD

**Issue by mcollins42** [pytorch/audio#317]
## 🐛 Bug

Installing torchaudio-cpu through conda (python 3.7) fails with conflicts.

## To Reproduce

1. start clean continuumio/anaconda3 container with docker.

`docker run --rm -i -t continuumio/anaconda3 /bin/bash`

2. Inside the container, attempt to install torchaudio-cpu

```
# conda install torchaudio-cpu -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                              

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package tk conflicts for:
python=3.7 -> tk[version='>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0']
Package sqlite conflicts for:
python=3.7 -> sqlite[version='>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.29.0,<4.0a0']
Package scipy conflicts for:
torchaudio-cpu -> scipy
Package libffi conflicts for:
python=3.7 -> libffi[version='>=3.2.1,<4.0a0']
Package pytorch-cpu conflicts for:
torchaudio-cpu -> pytorch-cpu[version='>=1.1.0']
Package sox conflicts for:
torchaudio-cpu -> sox
Package zlib conflicts for:
python=3.7 -> zlib[version='>=1.2.11,<1.3.0a0']
Package readline conflicts for:
python=3.7 -> readline[version='>=7.0,<8.0a0']
Package libstdcxx-ng conflicts for:
python=3.7 -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
Package openssl conflicts for:
python=3.7 -> openssl[version='>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a']
Package ncurses conflicts for:
python=3.7 -> ncurses[version='>=6.1,<7.0a0']
Package libgcc-ng conflicts for:
python=3.7 -> libgcc-ng[version='>=7.2.0|>=7.3.0']
Package pip conflicts for:
python=3.7 -> pip
Package librosa conflicts for:
torchaudio-cpu -> librosa[version='>=0.4.3']
Package xz conflicts for:
python=3.7 -> xz[version='>=5.2.4,<6.0a0']

```

## Expected behavior

Expect torchaudio-cpu to install without conflicts and to install and work with pytorch-cpu.

## Environment

docker container as indicated above

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster)
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] numpydoc==0.9.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0

## Additional context

We build Docker images that include pytorch, torchaudio and torchvision. One of the images is CPU-only, so we currently install pytorch and torchvision through conda:

  conda install -y pytorch-cpu torchvision-cpu -c pytorch

We would like to install torchaudio-cpu the same way but the errors above prevent that. Is the torchaudio-cpu package supported through conda? 

Is a conda install of torchaudio CPU-only and compatible with pytorch-cpu? 

Is there a cpu-only pip package that would be compatible with pytorch-cpu?

We have been building from source after the install of pytorch-cpu like this:

    apt-get install -y sox libsox-dev libsox-fmt-all
    pip install cffi
    pip install git+git://github.com/pytorch/audio.git

This has been working, but the recent changes to Tensor.data<T> to Tensor.data_ptr<T> have broken that build because we are building against PyTorch 1.1.0 headers (https://github.com/pytorch/audio/issues/262)

**Comment by vincentqb** [comment]
Thanks for pointing this out. I can reproduce this on linux:
```
conda create -n audio-cpu python=3.7
conda activate audio-cpu
conda install -c pytorch torchaudio-cpu

# UnsatisfiableError
```

The new build for `torchaudio-cpu` needs to be published [here](https://anaconda.org/pytorch/repo), #308.

**Comment by vincentqb** [comment]
> The new build for `torchaudio-cpu` needs to be published [here](https://anaconda.org/pytorch/repo), #308.

But `pytorch-cpu` has not been updated either.

**Comment by vincentqb** [comment]
I see that @ezyang uploaded the last torchaudio-cpu, and @soumith uploaded the last pytorch-cpu.

@ezyang -- Do you have the instructions for the conda binary package for cpu only?

**Comment by mcollins42** [comment]
I'm not sure if it's relevant, but the PyTorch getting started page lists two different conda commands for installing CPU-only. The one under [start locally](https://pytorch.org/get-started/locally/#start-locally) is:

`conda install pytorch torchvision cpuonly -c pytorch`

While the one further down the page under [Anaconda/No CUDA](https://pytorch.org/get-started/locally/#no-cuda) is:

`conda install pytorch-cpu torchvision-cpu -c pytorch`

**Comment by soumith** [comment]
the `start locally` is the correct one. I'll work on removing the Anaconda / No CUDA ones, they are outdated.

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch.github.io/commit/667f3d966ce937c3aed480bd35bfd8e7da9f39e5

**Comment by mcollins42** [comment]
For clarification on the torchaudio side, if I add torchaudio to the correct install line for pytorch No CUDA, will the version of torchaudio be appropriate for a No CUDA environment?  This is what a dry run of the conda install says. pytorch and torchvision indicate that the CPU versions will be installed, torchaudio doesn't have any clear indication.

```
conda install pytorch torchvision torchaudio cpuonly -c pytorch --dry-run
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - cpuonly
    - pytorch
    - torchaudio
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cpuonly-1.0                |                0           2 KB  pytorch
    ninja-1.9.0                |   py37hfd86e86_0         1.2 MB
    pytorch-1.3.0              |      py3.7_cpu_0        36.1 MB  pytorch
    torchaudio-0.3.1           |             py37         3.7 MB  pytorch
    torchvision-0.4.1          |         py37_cpu        14.6 MB  pytorch
    typing-3.6.4               |           py37_0          45 KB
    ------------------------------------------------------------
                                           Total:        55.7 MB

The following NEW packages will be INSTALLED:

  cpuonly            pytorch/noarch::cpuonly-1.0-0
  ninja              pkgs/main/linux-64::ninja-1.9.0-py37hfd86e86_0
  pytorch            pytorch/linux-64::pytorch-1.3.0-py3.7_cpu_0
  torchaudio         pytorch/linux-64::torchaudio-0.3.1-py37
  torchvision        pytorch/linux-64::torchvision-0.4.1-py37_cpu
  typing             pkgs/main/linux-64::typing-3.6.4-py37_0
```

**Comment by mcollins42** [comment]
@ezyang Can you confirm that torchaudio-cpu is no longer needed/supported and the regular torchaudio package is appropriate for No CUDA environments?

**Comment by ezyang** [comment]
Yes, the regular torchaudio should work with both CPU and CUDA builds of PyTorch. If this is not the case, please let us know.
