### ISSUE TITLE
formats: no handler for file extension 'mp4'

### ISSUE THREAD

**Issue by LeeYongHyeok** [pytorch/audio#318]
## To Reproduce

1. python `3.7.3`
2. last version of `torchaudio`, `PyTorch`
3. load `mp4` format 

## Expected behavior
`import torchaudio`
`data, sr = torchaudio.load('mp4File.mp4')`

`formats: no handler for file extension 'mp4'`
`Traceback (most recent call last):`

## Environment

 - What commands did you used to install torchaudio (conda/pip/build from source)?
 - If you are building from source, which commit is it?
 - What does `torchaudio.__version__` print? (If applicable)
`print(torchaudio.__version__)`
`'0.3.1'`

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): `1.3.0`
 - OS (e.g., Linux): `Linux`
 - How you installed PyTorch (`conda`, `pip`, source): `conda`
 - Build command you used (if compiling from source): 
 - Python version: `3.7.3`
 - CUDA/cuDNN version: `10.2`
 - GPU models and configuration: 'TITAN V`
 - Any other relevant information:

**Comment by faroit** [comment]
sox does not support mp4 files

**Comment by LeeYongHyeok** [comment]
but in README, I can find torchaudio supports `aiff, au, amr, mp2, mp4, ac3, avi, wmv,` extension.

**Comment by soumith** [comment]
the `sox` that you installed should support all relevant codecs. sometimes `sox` does not get installed with all codecs. We should change README i think

**Comment by vincentqb** [comment]
The README currently says "Load the following formats into a torch Tensor using sox". 

@LeeYongHyeok -- please feel free to open a pull request and suggest a phrasing that would clarify this.
