### ISSUE TITLE
How to train a wav2vec 2.0 pretrain model from scratch ?

### ISSUE THREAD

**Issue by kobenaxie** [pytorch/audio#3206]
### 🚀 The feature

There is an example for hubert training [here](https://github.com/pytorch/audio/tree/main/examples/self_supervised_learning), but  has no example aboult wav2vec 2.0.

### Motivation, pitch

I'm woking on ssl with/without a pretrained model to continue train the pretrained model like wav2vec  2.0 on other dataset,

**Comment by hwangjeff** [comment]
Hi @kobenaxie, we currently do not have plans to release a wav2vec 2.0 training example. If you're interested in one, SpeechBrain recently published theirs [here](https://github.com/speechbrain/speechbrain/tree/develop/recipes/LibriSpeech/self-supervised-learning/wav2vec2).

**Comment by kobenaxie** [comment]
Thank~
