### ISSUE TITLE
Resampling method values corrupted in torchaudio.functional.resample

### ISSUE THREAD

**Issue by nouranali** [pytorch/audio#3210]
### 📚 The doc issue
I was practicing this tutorial https://pytorch.org/audio/stable/tutorials/audio_resampling_tutorial.html
and the default value of the resampling methods here in https://pytorch.org/audio/stable/generated/torchaudio.functional.resample.html
are listed as : Options: ["sinc_interp_hann", "sinc_interp_kaiser"] 
using these values raises a ValueError: Invalid resampling method: sinc_interp_hann
when checking the help method I found that the values should be one of Options: [``"sinc_interpolation"``, ``"kaiser_window"``]

pytorch version:1.13.1+cu116
torchaudio version: 0.13.1+cu116

**Comment by mthrok** [comment]
These values have been changed in the latest release. 

For the version you are using (0.13.1), please refer to https://pytorch.org/audio/0.13.1/generated/torchaudio.functional.resample.html .
