### ISSUE TITLE
typo in tutorial 

### ISSUE THREAD

**Issue by nouranali** [pytorch/audio#3211]
### 📚 The doc issue

in this tutorial https://pytorch.org/audio/stable/tutorials/audio_resampling_tutorial.html
there's a typo in https://pytorch.org/audio/stable/tutorials/audio_resampling_tutorial.html#performance-benchmarking 

![Screenshot from 2023-03-28 13-54-12](https://user-images.githubusercontent.com/35102830/228228222-d8461e70-b246-40b2-8cee-d4a5665d59b5.png)

**Comment by nateanl** [comment]
Hi @nouranali, thanks for posting the issue. It will be fixed in #3212.
