### ISSUE TITLE
[v2.0.1] Release Tracker

### ISSUE THREAD

**Issue by nateanl** [pytorch/audio#3237]
This issue is for tracking TODO lists which are supposed to be cherry-picked to the release branch. Following is [release branch](https://github.com/pytorch/audio/tree/release/2.0) for the 2.0.1 release.

**Comment by mthrok** [comment]
https://github.com/pytorch/audio/pull/3230 resolves https://github.com/pytorch/audio/issues/3218, which existed since earlier release

**Comment by mthrok** [comment]
https://github.com/pytorch/audio/pull/3204 fixes issue with multiple formats, which existed since the initial release of StreamReader.

**Comment by mthrok** [comment]
https://github.com/pytorch/audio/pull/3243 fixes issue with FFmpeg backend which was introduced in 2.0

---

**Comment by nateanl** [comment]
#3252 fixes WavLM model when it is called in `torch.no_grad()`.

**Comment by nateanl** [comment]
#3253 improves Wav2Vec2/HuBERT by using `scaled_dot_product_attention` to increase efficiency.
