### ISSUE TITLE
Torchaudio.load ignores normalize=False for 8 bit ulaw

### ISSUE THREAD

**Issue by robz** [pytorch/audio#3256]
### 🐛 Describe the bug

According to [the docs](https://pytorch.org/audio/stable/backend.html#load), `torchaudio.load(normalize=False)` shouldn’t convert data to floats when loading wav files. But it appears to ignore `normalize=False` when the file uses 8 bit mu-law encoding:

```
audio = torch.sin(2 * torch.pi * torch.linspace(0, 1, 100))
torchaudio.save('temp.wav', audio[None, :], format='wav', encoding='ULAW', bits_per_sample=8, sample_rate=16_000)
info = torchaudio.info('temp.wav')
print(info) # sample_rate=16000, num_frames=100, num_channels=1, bits_per_sample=8, encoding=ULAW
data = torchaudio.load('temp.wav', normalize=False)
print(data[0].dtype) # torch.float32 ?! expected uint8
```

I originally posted this in [a pytorch discussion thread](https://discuss.pytorch.org/t/torchaudio-load-ignores-normalize-false-for-8-bit-ulaw/176209/1), but was pointed to make a bug report here.

### Versions

--2023-04-09 22:25:36--  https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21550 (21K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py      100%[===================>]  21.04K  --.-KB/s    in 0s      

2023-04-09 22:25:37 (81.7 MB/s) - ‘collect_env.py’ saved [21550/21550]

Collecting environment information...
PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.9.16 (main, Dec  7 2022, 01:11:51)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.147+-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7B12
Stepping:                        0
CPU MHz:                         2249.998
BogoMIPS:                        4499.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        512 KiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr arat npt nrip_save umip rdpid

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==2.0.0+cu118
[pip3] torchaudio==2.0.1+cu118
[pip3] torchdata==0.6.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.1
[pip3] torchvision==0.15.1+cu118
[pip3] triton==2.0.0
[conda] Could not collect

**Comment by nateanl** [comment]
Hi @robz, what is your use case of using mulaw encoding? torchaudio has [`MuLawEncoding`](https://pytorch.org/audio/stable/generated/torchaudio.transforms.MuLawEncoding.html?highlight=mulaw#torchaudio.transforms.MuLawEncoding) transform that can transform `float32` dtype waveform to int dtype. Does it satisfy your use case?

**Comment by robz** [comment]
> what is your use case of using mulaw encoding

In order to compand and train on a large audio dataset (for other usecase of mulaw, see: https://en.wikipedia.org/wiki/%CE%9C-law_algorithm)

> torchaudio has [MuLawEncoding](https://pytorch.org/audio/stable/generated/torchaudio.transforms.MuLawEncoding.html?highlight=mulaw#torchaudio.transforms.MuLawEncoding) transform that can transform float32 dtype waveform to int dtype. Does it satisfy your use case?

That's the workaround for this bug, but it isn't satisfying :). Note the issue here isn't encoding (as you see from the code I posted -- the audio is encoded correctly into wav with 8bit mulaw when saving)--the issue is decoding. Because of this bug where it ignores `normalize=False`, torchaudio.load automatically converts uint8 in the file into float32, so I'd have to convert it back to uint8s again with MuLawEncoding.

To avoid that, I've dropped use of torchaudio.load/save and instead have to encode the audio into uint8 .pt tensors. Then I can read them without the automatic float conversion happening. But .pt format isn't in an audio format like .wav, so it can't be used in other tools that expect audio data. :/

**Comment by mthrok** [comment]
When you say uint8, are the samples applied u-law function to waveform? that is no longer raw waveform?

> > what is your use case of using mulaw encoding
> 
> In order to compand and train on a large audio dataset (for other usecase of mulaw, see: https://en.wikipedia.org/wiki/%CE%9C-law_algorithm)
> 
> > torchaudio has [MuLawEncoding](https://pytorch.org/audio/stable/generated/torchaudio.transforms.MuLawEncoding.html?highlight=mulaw#torchaudio.transforms.MuLawEncoding) transform that can transform float32 dtype waveform to int dtype. Does it satisfy your use case?
> 
> That's the workaround for this bug, but it isn't satisfying :). Note the issue here isn't encoding (as you see from the code I posted -- the audio is encoded correctly into wav with 8bit mulaw when saving)--the issue is decoding. Because of this bug where it ignores `normalize=False`, torchaudio.load automatically converts uint8 in the file into float32, so I'd have to convert it back to uint8s again with MuLawEncoding.
> 
> To avoid that, I've dropped use of torchaudio.load/save and instead have to encode the audio into uint8 .pt tensors. Then I can read them without the automatic float conversion happening. But .pt format isn't in an audio format like .wav, so it can't be used in other tools that expect audio data. :/
