### ISSUE TITLE
`StreamReader` fails to properly handle in-memory data

### ISSUE THREAD

**Issue by szalpal** [pytorch/audio#3270]
### 🐛 Describe the bug

Hello!

I'm testing streamed video decoding using NVDEC. I believe there is a problem with `StreamReader`. It fails to decode in-memory data. Repro, based on [this tutorial](https://pytorch.org/audio/stable/hw_acceleration_tutorial.html)

```python
cuda_conf = {
    "decoder": "h264_cuvid",  # Use CUDA HW decoder
    "hw_accel": "cuda:0",  # Then keep the memory on CUDA:0
}

def test_decode(src, config, i_sample):
  s = StreamReader(src)  # Problematic line
  s.add_video_stream(5, **config)

  num_frames = 0
  for i, (chunk, ) in enumerate(s.stream()):
    if i == 0:
      print(' - Chunk:', chunk.shape, chunk.device, chunk.dtype)
    if i == i_sample:
      sample = chunk[0]
    num_frames += chunk.shape[0]
  elapsed = time.monotonic() - t0
  return elapsed, sample


# Assuming I have 'input.mp4' file
test_decode('input.mp4', cuda_conf, 50)  # (1) Works properly
raw_video = np.fromfile('input.mp4', dtype=np.uint8)
test_decode(raw_video, cuda_conf, 50)  # (2) Does not work
torch_raw_video = torch.Tensor(raw_video).to(dtype=torch.uint8)
test_decode(torch_raw_video, cuda_conf, 50)  # (3) Does not work either
with tempfile.NamedTemporaryFile as fp:
    raw_video.tofile(fp)
    test_decode(fp.name, cuda_conf, 50)  # (4) Works again
```
The error that prompts in the problematic usages:
```
ValueError: `src` must be either string, Tensor or file-like object.
```
I believe, that in case `2` and `3` I've put together a Tensor properly. Could you verify this error?

### Versions

`404: Not Found` For the `collect_env.py` script.

Anyway, I've run my program in Docker environment:

```docker
ARG TRITON_VERSION=23.03
ARG BASE_IMAGE=nvcr.io/nvidia/tritonserver:${TRITON_VERSION}-py3
FROM ${BASE_IMAGE} as builder

RUN apt update && apt install -y ffmpeg

RUN pip3 install ipdb
RUN pip3 install --progress-bar off --pre torch torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cu117 2> /dev/null
RUN pip3 install --progress-bar off boto3 2> /dev/null
```

**Comment by szalpal** [comment]
Got it, thanks for explanation. I've got confused, since the documentation suggests, that the Tensor input is possible: https://pytorch.org/audio/stable/generated/torchaudio.io.StreamReader.html#torchaudio.io.StreamReader . I suppose the documentation does not capture that as well, if that's a unreleased thingy yet.

Thanks anyway :)

**Comment by hwangjeff** [comment]
@szalpal note that the docs you linked correspond to the current stable release (2.0.1). Since you are using the nightly build, you should be looking at the nightly build docs, e.g. https://pytorch.org/audio/main/generated/torchaudio.io.StreamReader.html#torchaudio.io.StreamReader. Having said that, the docs are still not completely correct here — will fix. Thanks for flagging.
