### ISSUE TITLE
Installing torchaudio on Jetson AGX xavier

### ISSUE THREAD

**Issue by will46616** [pytorch/audio#3275]
Hi, I'm trying installing torchaudio 0.10.0 on AGX xavier, but I can't find the wheel of torchaudio 0.10.0. By the way, I've already installed Pytorch and torchvision on my AGX xavier, and my Jetpack verison is 5.0.2.
Best regards,
Will

**Comment by mthrok** [comment]
Hi @will46616 

We do not publish ARM wheels that can be used on Jetson platform.
Nvidia publishes PyTorch for Jetson, and torchaudio has to be built and linked against that.
The following is written based on PyTorch 1.13 / TorchAudio 0.13, but the same step should work for 0.10.

https://pytorch.org/audio/stable/build.jetson.html#install-pytorch

**Comment by will46616** [comment]
Thank you for your reply. I will give it a try.
