### ISSUE TITLE
FFmpeg backend seems to lose some samples in select FLAC files

### ISSUE THREAD

**Issue by pzelasko** [pytorch/audio#3283]
### 🐛 Describe the bug

It works correctly for most of LibriSpeech, but for some files the ffmpeg backend returns less samples than sox and soundfile.

```python
import os
os.environ["TORCHAUDIO_USE_BACKEND_DISPATCHER"] = "1"

import torchaudio

p = "download/LibriSpeech/train-clean-100/7067/76048/7067-76048-0021.flac"
print("File:", p)
print()
for backend in ("ffmpeg", "sox", "soundfile"):
    print(f"{torchaudio.info(p, backend=backend).__dict__=}")
    print(f"{torchaudio.load(p, backend=backend)[0].shape=}")
    print()
```

Output:

```
File: download/LibriSpeech/train-clean-100/7067/76048/7067-76048-0021.flac

torchaudio.info(p, backend=backend).__dict__={'sample_rate': 16000, 'num_frames': 233472, 'num_channels': 1, 'bits_per_sample': 16, 'encoding': 'FLAC'}
torchaudio.load(p, backend=backend)[0].shape=torch.Size([1, 233472])

torchaudio.info(p, backend=backend).__dict__={'sample_rate': 16000, 'num_frames': 252480, 'num_channels': 1, 'bits_per_sample': 16, 'encoding': 'FLAC'}
torchaudio.load(p, backend=backend)[0].shape=torch.Size([1, 252480])

torchaudio.info(p, backend=backend).__dict__={'sample_rate': 16000, 'num_frames': 252480, 'num_channels': 1, 'bits_per_sample': 16, 'encoding': 'FLAC'}
torchaudio.load(p, backend=backend)[0].shape=torch.Size([1, 252480])
```

It's easily verified that it actually discards useful audio by plotting it:

```python
import matplotlib.pyplot as plt

fig, axes = plt.subplots(3, 1, figsize=(12, 6), sharex=True)
for idx, backend in enumerate(("ffmpeg", "sox", "soundfile")):
    audio = torchaudio.load(p, backend=backend)[0]
    axes[idx].plot(audio[0].numpy())
```

<img width="716" alt="image" src="https://user-images.githubusercontent.com/15930688/234942014-3a381d1c-f3a1-4f85-9726-b342f9c50c8d.png">

You can reproduce it with some files in LibriSpeech. Here's a few that I found:
- LibriSpeech/train-clean-100/7067/76048/7067-76048-0021.flac
- LibriSpeech/train-clean-360/5093/29101/5093-29101-0006.flac
- LibriSpeech/train-clean-360/6782/61316/6782-61316-0059.flac
- LibriSpeech/train-clean-360/7867/110742/7867-110742-0014.flac
- LibriSpeech/train-other-500/551/129024/551-129024-0030.flac

### Versions

Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.3.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.25.0
Libc version: N/A

Python version: 3.10.4 (main, Mar 31 2022, 03:37:37) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-13.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] flake8==5.0.4
[pip3] k2==1.23.4.dev20230412+cpu.torch2.0.0
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchvision==0.15.0
[conda] k2                        1.23.4.dev20230412+cpu.torch2.0.0          pypi_0    pypi
[conda] numpy                     1.23.5          py310hb93e574_0
[conda] numpy-base                1.23.5          py310haf87e8b_0
[conda] pytorch                   2.0.0                  py3.10_0    pytorch
[conda] torch                     1.12.1                   pypi_0    pypi
[conda] torchaudio                2.0.0                 py310_cpu    pytorch
[conda] torchvision               0.15.0                py310_cpu    pytorch

**Comment by pzelasko** [comment]
This is what I got:

```python
torchaudio.utils.ffmpeg_utils.get_versions()
```

```
{'libavutil': (56, 31, 100),
 'libavcodec': (58, 54, 100),
 'libavformat': (58, 29, 100),
 'libavfilter': (7, 57, 100),
 'libavdevice': (58, 8, 100)}
```

Since I don't see the ffmpeg version there, here's some extra info:
```
$ which ffmpeg
/Users/pzelasko/miniconda3/envs/lhotse-py3.10/bin/ffmpeg
$ ffmpeg -version
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
built with clang version 12.0.0
configuration: --prefix=/Users/pzelasko/miniconda3/envs/lhotse-py3.10 --cc=arm64-apple-darwin20.0.0-clang --disable-doc --enable-avresample --enable-gmp --enable-hardcoded-tables --enable-libfreetype --enable-libvpx --enable-pthreads --enable-libopus --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame --disable-nonfree --enable-gpl --enable-gnutls --disable-openssl --enable-libopenh264 --enable-libx264
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```

So in order to use 5.1, I would need to build both ffmpeg and torchaudio from source? If 5.1 indeed fixes the issue, is it possible to upgrade to it in the next torchaudio binary release?

**Comment by mthrok** [comment]
> So in order to use 5.1, I would need to build both ffmpeg and torchaudio from source? If 5.1 indeed fixes the issue, is it possible to upgrade to it in the next torchaudio binary release?

Yes, right now to use 5.1 one needs to build torchaudio from source.
Now that conda-forge has 5.1 for all the platforms, it seems reasonable to upgrade to 5.1.

**Comment by mthrok** [comment]
I tested this with different versions of FFmpeg from conda-forge.
The issue happens with ffmpeg 4.1 and 4.2 but does not happen on 4.3, 4.4 and 5.1.

@pzelasko We have minor release scheduled in couple of weeks, but the window for cherry-pick has been closed.
Changing the FFmpeg version has to wait until the next major version. Meanwhile if possible, can you try FFmpeg 4.3 or 4.4?

**Comment by pzelasko** [comment]
Thanks @mthrok! I just checked ffmpeg=4.4 from conda-forge and indeed the issue is gone.
