### ISSUE TITLE
Default bit per sample for wav PCM_S is incorrect

### ISSUE THREAD

**Issue by tomschelsen** [pytorch/audio#3304]
### 🐛 Describe the bug

Using ```torch audio.save(..., format="wav", encoding="PCM_S")``` results in a 32bitLE file where as per the documentation it should be 16bit. Explicitely adding ```bits_per_sample=16``` does provide the desired 16bit file. 

### Versions

torchaudio~=2.0.0
Linux (pytorch2.0 official Docker image)
SoX backend

**Comment by mthrok** [comment]
Hi @tomschelsen 

Thanks for the report.
Looks like the following line is causing the issue.

https://github.com/pytorch/audio/blob/8d7268f172259b276930f58d1845dfe11cc03f11/torchaudio/csrc/sox/utils.cpp#L225-L226C60

Changing 32 to 16 should do it.

@tomschelsen If you want, feel free to open a PR for the fix. I will try to find time for this, but meanwhile I will make the issue also open to OSS comunity.
