### ISSUE TITLE
Request adding yuv420p10le support for cpu decoders

### ISSUE THREAD

**Issue by w238liu** [pytorch/audio#3331]
### 🚀 The feature

Propose to add cpu decoder (`hevc`) support for reading out yuv420p10le data from HDR/10bit HEVC videos.

### Motivation, pitch

I am trying to train my model with HDR/10 bit videos, and then I find this [PR](https://github.com/pytorch/audio/pull/3023), which enables torchaudio to read 10bit HEVC videos with `hevc_cuvid` decoder. However, I would like to decode the 10bit videos with the cpu `hevc` decoder as the server I am using has much more CPUs than GPUs. Unfortunately, it seems like the cpu `hevc` decoder does not support yuv420p10le output yet as shown in the example below. Therefore I propose to add this feature.

Example:

I created a synthetic video with `ffmpeg -f lavfi -i mandelbrot -t 3 -c:v libx265 -pix_fmt yuv420p10le -vtag hvc1 -y test.mp4`. Then the following code

```python
from torchaudio.io import StreamReader

src = "test.mp4"
decode_config = {
    'buffer_chunk_size': 50,
    'decoder': 'hevc',
    "format": None,
}

video = StreamReader(src=src)

video.add_basic_video_stream(1, **decode_config)

stream = video.stream()
frame, = next(stream)

print(frame.device, frame.shape, frame.dtype)
```
gives me the following error message:
```shell
RuntimeError: Unexpected video format: yuv420p10le
```

### Additional context

With GPU decoder, the `test.mp4` is decoded successfully:

```python
from torchaudio.io import StreamReader

src = "test.mp4"
decode_config = {
    'buffer_chunk_size': 50,
    'decoder': 'hevc_cuvid',
    'hw_accel': 'cuda',
    "format": None,
}

video = StreamReader(src=src)

video.add_basic_video_stream(1, **decode_config)

stream = video.stream()
frame, = next(stream)

print(frame.device, frame.shape, frame.dtype)

```

The output is as expected.
```shell
cuda:0 torch.Size([1, 3, 480, 640]) torch.int16
```

**Comment by mthrok** [comment]
Hi @w238liu 

Thanks for the request. It is doable but I need to ask, do you train the model with YUV format?
Most video models are trained on RGB formats, and StreamReader can perform color space conversion for the case of CPU.
yuv420p10le support for GPU case is a sort of workaround for the lack of the kernel for converting the color space.

If you are decoding on CPU, changing the `format` argument to something that is supported, like `rgb24`,
and StreamReader will convert it for you.

**Comment by w238liu** [comment]
> It is doable but I need to ask, do you train the model with YUV format?

Hi @mthrok 

Thanks for the quick response. To your question, the answer is yes. We are working on HDR video quality evaluation. 8bit SDR videos (e.g. RGB24) often have lower quality compared to 10bit HDR, but our model won't tell this if the input has already been converted to 8bit anyways. BTW, I believe the default colour conversion in ffmpeg is not very accurate according to this [discussion](https://stackoverflow.com/questions/70893502/why-does-ffmpeg-output-slightly-different-rgb-values-when-converting-to-gbrp-and). So we want to extract the raw data, and perform necessary colour transofrms by ourselves.

**Comment by mthrok** [comment]
@w238liu Thanks for the detail. I am landing #3332 now, which allows to decode YUV420P10LE format as YUV444P with 16bit signed int samples. If it lands fine, it will be available tomorrow's nightly build.

There are certain subtle difference from CUVID version. The value range is `[0, 2**10)`.

**Comment by mthrok** [comment]
Regarding the colorspace conversion, I did not know this detail. Thanks for sharing. I wonder if we can pass `-sws_flags`  to one of StreamReader options.

**Comment by mthrok** [comment]
@w238liu 

It turned out that one can pass `sws_flags` to `StreamReader`.
It is par-stream option and can be passed as option to `scale` filter.
One can construct custom transform with `add_video_stream` method as follow.

```python
# default scale + rgb24 conversion
# similar to what happens when you use `add_basic_video_stream` method.
r.add_video_stream(
    -1, filter_desc="scale=dst_format=rgb24,format=rgb24")

# scale with custom sws_flags then rgb24 conversion
r.add_video_stream(
    -1, filter_desc="scale=sws_flags=accurate_rnd+full_chroma_int:dst_format=rgb24,format=rgb24")
```

![Figure_1](https://github.com/pytorch/audio/assets/855818/aed7ee23-e7c6-47a7-8a34-3b3501abd7e5)


<details><summary>code</summary>

```python
import matplotlib.pyplot as plt

from torchaudio.io import StreamReader

src = "test/torchaudio_unittest/assets/testsrc.hevc"
r = StreamReader(src=src)

r.add_video_stream(-1, filter_desc="scale=dst_format=rgb24,format=rgb24")
r.add_video_stream(-1, filter_desc="scale=sws_flags=accurate_rnd+full_chroma_int:dst_format=rgb24,format=rgb24")
r.process_all_packets()
rgb1, rgb2 = r.pop_chunks()

rgb1 = rgb1[0].permute(1, 2, 0)
rgb2 = rgb2[0].permute(1, 2, 0)
diff = (rgb1.float() - rgb2.float()).abs()

f, ax = plt.subplots(2, 2)

ax[0][0].imshow(rgb1)
ax[0][1].imshow(rgb2)

im = ax[1][0].imshow(diff[..., 0], vmin=-5, vmax=+5, cmap="seismic")
plt.colorbar(im, ax=ax[1][0])

print((diff ** 2).mean())

plt.show()
```
</details>

**Comment by mthrok** [comment]
> > @w238liu Thanks for the detail. I am landing #3332 now, which allows to decode YUV420P10LE format as YUV444P with 16bit signed int samples. If it lands fine, it will be available tomorrow's nightly build.
> > There are certain subtle difference from CUVID version. The value range is `[0, 2**10)`.
> 
> Hi @mthrok
> 
> Thanks for the quick action. Do you mean the value range of YUV420P10LE from the CPU decoder is `[0, 2**10)`?

Yes, it was confusing to me as well, but the value range of `hevc_cuvid` decoder (`P010` format) is `[-2**15, 2**15)`,  while `hevc` (`YUV420P10LE`) is `[0, 2**10)`. People say those are different format, and I do not know enough about the difference, but we generally minimize the custom data transform in StreamReader, so, for now they are kept that way.

**Comment by w238liu** [comment]
> @w238liu
> 
> It turned out that one can pass `sws_flags` to `StreamReader`. It is par-stream option and can be passed as option to `scale` filter. One can construct custom transform with `add_video_stream` method as follow.
> 
> ```python
> # default scale + rgb24 conversion
> # similar to what happens when you use `add_basic_video_stream` method.
> r.add_video_stream(
>     -1, filter_desc="scale=dst_format=rgb24,format=rgb24")
> 
> # scale with custom sws_flags then rgb24 conversion
> r.add_video_stream(
>     -1, filter_desc="scale=sws_flags=accurate_rnd+full_chroma_int:dst_format=rgb24,format=rgb24")
> ```
> 
> ![Figure_1](https://user-images.githubusercontent.com/855818/238809073-aed7ee23-e7c6-47a7-8a34-3b3501abd7e5.png)
> 
> code

This is a great finding! Thanks.

> > > @w238liu Thanks for the detail. I am landing #3332 now, which allows to decode YUV420P10LE format as YUV444P with 16bit signed int samples. If it lands fine, it will be available tomorrow's nightly build.
> > > There are certain subtle difference from CUVID version. The value range is `[0, 2**10)`.
> > 
> > 
> > Hi @mthrok
> > Thanks for the quick action. Do you mean the value range of YUV420P10LE from the CPU decoder is `[0, 2**10)`?
> 
> Yes, it was confusing to me as well, but the value range of `hevc_cuvid` decoder (`P010` format) is `[-2**15, 2**15)`, while `hevc` (`YUV420P10LE`) is `[0, 2**10)`. People say those are different format, and I do not know enough about the difference, but we generally minimize the custom data transform in StreamReader, so, for now they are kept that way.

Yeah, this is interesting. I just tried to decode the same 10bit video with `-c:v hevc` or `-c:v hevc_cuvid` before `-i` using ffmpeg. The output from `hevc_cuvid` seems to equal to the output from `hevc` left-shifted by 6 bits. Below are the two sample commands I ran
`ffmpeg -ss 00:00:00 -c:v hevc -i test.mp4 -vcodec rawvideo -vframes 1 -f rawvideo -an hevc.bin`
`ffmpeg -ss 00:00:00 -c:v hevc_cuvid -i test.mp4 -vcodec rawvideo -vframes 1 -f rawvideo -an hevc_cuvid.bin`

**Comment by w238liu** [comment]
> @w238liu Thanks for the detail. I am landing #3332 now, which allows to decode YUV420P10LE format as YUV444P with 16bit signed int samples. If it lands fine, it will be available tomorrow's nightly build.
> 
> There are certain subtle difference from CUVID version. The value range is `[0, 2**10)`.

BTW, when will the new feature be released in a stable version?

**Comment by mthrok** [comment]
> > @w238liu Thanks for the detail. I am landing #3332 now, which allows to decode YUV420P10LE format as YUV444P with 16bit signed int samples. If it lands fine, it will be available tomorrow's nightly build.
> > There are certain subtle difference from CUVID version. The value range is `[0, 2**10)`.
> 
> BTW, when will the new feature be released in a stable version?

We don't have the timeline yet. Usually, it's once in 3-4 months. so could be late summer / autumn.

**Comment by mthrok** [comment]
Closing this as the feature is added to nightly build. If there is an issue with the feature, please open a new issue. Thanks!
