### ISSUE TITLE
undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev

### ISSUE THREAD

**Issue by someonewating** [pytorch/audio#3335]
Hi guys. I got a problem. I request your help.😥
I'm using pytorch.audio on both x86 and aarch64 platforms. And for some specific reasons, I compiled pytorch.audio v0.13.1 from the source code into a wheel file. In the aarch64 platform computer, which is a raspberry pi 4B, I installed ptrorch.audi using `pip install [wheel-file-name]`, it succeed, but I got an error when I try to import pytorch.audio: 
```
OSError: /home/pi/.pyenv/versions/3.8.16/envs/diart/lib/python3.8/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev
```
all libraries related to pytorch are: 
```
pip list | grep torch

pytorch-lightning         1.6.5
pytorch-metric-learning   1.7.3
torch                     1.13.1
torch-audiomentations     0.11.0
torch-pitch-shift         1.2.4
torchaudio                0.13.1+b90d798
torchmetrics              0.11.4
torchvision               0.14.1
```
The machine I used to compile pytorch.audio is using pytorch 1.13.1.
```
conda list | grep torch
pytorch                   1.13.1          cpu_py38haaa41f7_0
```

And today on my another machine, which is a brand new x86 cloud virtual machine, I was trying to install pytorch, torchaudio and torchversion using conda. As recommended on the official website`https://pytorch.org/get-started/previous-versions/`, I use this command `conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 cpuonly -c pytorch`, and the exactly same error happened again:
```
OSError: /home/azureuser/miniconda3/envs/diart/lib/python3.8/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
```
the version of other torch libraries are: 
```
conda list | grep torch

cpuonly                   2.0                           0    pytorch
pytorch                   1.13.1          cpu_py38h92724a6_0
pytorch-lightning         1.6.5                    pypi_0    pypi
pytorch-metric-learning   1.7.3                    pypi_0    pypi
pytorch-mutex             1.0                         cpu    pytorch
torch-audiomentations     0.11.0                   pypi_0    pypi
torch-pitch-shift         1.2.4                    pypi_0    pypi
torchaudio                0.13.1                 py38_cpu    pytorch
torchmetrics              0.11.4                   pypi_0    pypi
torchvision               0.14.1                 py38_cpu    pytorch
```

Now I'm totally confused.😵 I'm quite sure I did something wrong but I can't find my mistake. If someone would like to give me any suggestions or help I will be very very appreciative.

**Comment by mthrok** [comment]
Hi

This sort of errors mean that the library files (the ones written in C++) from PyTorch and torchaudio do not match. Since torchaudio binaries are linked against PyTorch's C++ library, they have to match. This means that one cannot mix torchaudio and PyTorch of different versions, and that one cannot mix those from different distributers. In other words, if you are using torchaudio from official distribution channel, then you also need to use PyTorch official channel. (I don't know if it is possible to mix official binaries from conda distribution and PyPI.)

These days there are some PyTorch distributions from third-party distributors. I do not know about the situation exactly, but they unlikely distribute torchaudio. 

Now, what looks peculiar to me about your environment is that PyTorch version number `cpu_py38h92724a6_0` looks like it's not from PyTorch's channel.

I just tested `conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 cpuonly -c pytorch` in a new conda environment (Linux, X86), the following is what it says.

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    brotlipy-0.7.0             |py38h27cfd23_1003         323 KB
    certifi-2023.5.7           |   py38h06a4308_0         152 KB
    cffi-1.15.0                |   py38h7f8727e_0         226 KB
    cpuonly-2.0                |                0           2 KB  pytorch
    cryptography-39.0.1        |   py38h9ce1e76_0         1.4 MB
    ffmpeg-4.3                 |       hf484d3e_0         9.9 MB  pytorch
    freetype-2.12.1            |       h4a9f257_0         626 KB
    idna-3.4                   |   py38h06a4308_0          93 KB
    lame-3.100                 |       h7b6447c_0         323 KB
    lcms2-2.12                 |       h3be6417_0         312 KB
    lerc-3.0                   |       h295c915_0         196 KB
    libdeflate-1.17            |       h5eee18b_0          69 KB
    libiconv-1.16              |       h7f8727e_2         736 KB
    libtasn1-4.19.0            |       h5eee18b_0          63 KB
    libtiff-4.5.0              |       h6a678d5_2         479 KB
    libwebp-1.2.4              |       h11a3e52_1          86 KB
    libwebp-base-1.2.4         |       h5eee18b_1         376 KB
    lz4-c-1.9.4                |       h6a678d5_0         154 KB
    mkl-service-2.4.0          |   py38h7f8727e_0          59 KB
    mkl_fft-1.3.1              |   py38hd3c417c_0         180 KB
    mkl_random-1.2.2           |   py38h51133e4_0         308 KB
    numpy-1.24.3               |   py38h14f4228_0          11 KB
    numpy-base-1.24.3          |   py38h31eccc5_0         6.9 MB
    openh264-2.1.1             |       h4ff587b_0         711 KB
    pillow-9.4.0               |   py38h6a678d5_0         723 KB
    pyopenssl-23.0.0           |   py38h06a4308_0          96 KB
    pysocks-1.7.1              |   py38h06a4308_0          31 KB
    pytorch-1.13.1             |      py3.8_cpu_0        81.6 MB  pytorch
    pytorch-mutex-1.0          |              cpu           3 KB  pytorch
    requests-2.29.0            |   py38h06a4308_0          96 KB
    torchaudio-0.13.1          |         py38_cpu         6.4 MB  pytorch
    torchvision-0.14.1         |         py38_cpu        25.3 MB  pytorch
    typing_extensions-4.5.0    |   py38h06a4308_0          46 KB
    urllib3-1.26.15            |   py38h06a4308_0         197 KB
    zstd-1.5.5                 |       hc292b87_0         647 KB
    ------------------------------------------------------------
                                           Total:       138.7 MB
```

I don't know the detail but `cpu_py38h92724a6_0` pattern looks like it's coming from conda or related channel.

**Comment by someonewating** [comment]
> 

Hi @mthrok,

Now my problem has been solved by avoiding using the Torchaudio library. Thank you for your help.
