### ISSUE TITLE
Missing audio frames from `StreamReader.stream` when `frames_per_chunk` is too low.

### ISSUE THREAD

**Issue by lokesh1199** [pytorch/audio#3343]
### 🐛 Describe the bug

In StreamReader, when frames_per_chunk is given a small value, there seems to loss of audio when streaming. However this is fixed by assigning `buffer_chunk_size=1`. As per the documentation, StreamReader drops frames older than the internal buffer size. Since I am streaming the audio chunks without any delay. It shouldn't happen right? If it is supposed to happen, Kindly provide a way to calculate a safe value for `buffer_chunk_size` based on the given input audio sample rate and `frames_per_chunk`

Audio's sample rate = 16000, duration = 3.0 secs
Code to replicate the issue

```python
reader = torchaudio.io.StreamReader(file)
reader.add_basic_audio_stream(frames_per_chunk=frames_per_chunk)
sample_rate = reader.get_src_stream_info(reader.default_audio_stream).sample_rate
total_frames = 0

for idx, chunk in enumerate(reader.stream()):
    chunk = chunk.pop().t()
    total_frames += chunk.shape[-1]

print(f'{total_frames=}, duration={total_frames / sample_rate} secs')
```

frames_per_chunk = 16000 -> `total_frames=48000, duration=3.0 secs`
frames_per_chunk = 1000 -> `total_frames=47000, duration=2.9375 secs`
frames_per_chunk = 1000 and buffer_chunk_size = -1 -> `total_frames=48000, duration=3.0 secs`

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.31



Versions of relevant libraries:
[pip3] mypy==0.961
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==2.0.0
[pip3] torch==2.0.0+cu118
[pip3] torch-poly-lr-decay==0.0.1
[pip3] torchaudio==2.0.0+cu118
[pip3] torchmetrics==0.11.4
[pip3] triton==2.0.0
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-lightning         2.0.0                    pypi_0    pypi
[conda] torch                     2.0.0+cu118              pypi_0    pypi
[conda] torch-poly-lr-decay       0.0.1                    pypi_0    pypi
[conda] torchaudio                2.0.0+cu118              pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi
```

**Comment by mthrok** [comment]
Hi

`frames_per_chunk` controls the unit number of samples returned to client code, and `buffer_chunk_size` controls the internal buffer size. However, neither can affect how many samples are coming in from the source. FFmpeg uses a notion of packet, which is a slice of binary data of the media, which contains certain number of audio samples. StreamReader process packet by packet, but it cannot have a say in how many samples each packet should contain. The exact number of samples contained in each packet vary, and if the value of `frames_per_chuhnk` * `buffer_chunk_size` is smaller than the number of samples contained in a packet, StreamReader has to drop some samples. That's what is likely happening when you set the value of `frames_per_chunk` small.

**Comment by lokesh1199** [comment]
If we set `buffer_chunk_size = -1`, What will be the size of internal buffer.

**Comment by mthrok** [comment]
> If we set `buffer_chunk_size = -1`, What will be the size of internal buffer.

Unbounded. It will keep buffering until it hits OOM.
