### ISSUE TITLE
`apply_codec` spams console 

### ISSUE THREAD

**Issue by iCorv** [pytorch/audio#3358]
### 🐛 Describe the bug

The `apply_codec`-function spams console with the message `formats: vorbis can't encode Vorbis to 16-bit`, although the resulting audio seems to have Vorbis compression applied. Blocking all output to `stdout` doesn't prevent this behavior. 

```python
import soundfile as sf
import torch
import torchaudio
from torchaudio.functional import apply_codec

torchaudio.utils.sox_utils.set_verbosity(1)

if __name__ == "__main__":
    sr = 48_000
    waveform = torch.rand(1, 48_000)

    param = {"format": "vorbis", "compression": -1, "bits_per_sample": None}
    # apply vorbis compression
    augmented = apply_codec(waveform, sr, **param)

    sf.write(
        "noise_vorbis.wav", augmented.numpy().squeeze(), sr
    )
```

```
/media/bigboss/ssd1/aic/research/v-diffusion/venv/lib/python3.8/site-packages/torchaudio/backend/sox_io_backend.py:416: UserWarning: File-like object support in sox_io backend is deprecated, and will be removed in v2.1. See https://github.com/pytorch/audio/issues/2950 for the detail.Please migrate to the new dispatcher, or use soundfile backend.
  warnings.warn(_deprecation_message)

formats: vorbis can't encode Vorbis to 16-bit

/media/bigboss/ssd1/aic/research/v-diffusion/venv/lib/python3.8/site-packages/torchaudio/backend/sox_io_backend.py:235: UserWarning: File-like object support in sox_io backend is deprecated, and will be removed in v2.1. See https://github.com/pytorch/audio/issues/2950 for the detail.Please migrate to the new dispatcher, or use soundfile backend.
  warnings.warn(_deprecation_message)
```

### Versions

Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 13 2023, 10:26:41)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-70-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

Nvidia driver version: 525.85.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          80
On-line CPU(s) list:             0-79
Thread(s) per core:              2
Core(s) per socket:              20
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Silver 4316 CPU @ 2.30GHz
Stepping:                        6
CPU MHz:                         2571.577
CPU max MHz:                     3400,0000
CPU min MHz:                     800,0000
BogoMIPS:                        4600.00
Virtualization:                  VT-x
L1d cache:                       1,9 MiB
L1i cache:                       1,3 MiB
L2 cache:                        50 MiB
L3 cache:                        60 MiB
NUMA node0 CPU(s):               0-19,40-59
NUMA node1 CPU(s):               20-39,60-79
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] audio-data-pytorch==0.0.19
[pip3] audio-diffusion-pytorch==0.1.3
[pip3] audiolm-pytorch==0.30.0
[pip3] ema-pytorch==0.2.3
[pip3] lion-pytorch==0.1.2
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==1.7.7
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchmetrics==0.11.4
[pip3] triton==2.0.0
[pip3] vector-quantize-pytorch==1.4.1
[conda] Could not collect

**Comment by mthrok** [comment]
Hi @iCorv 

#3358 should fix the issue, but the next stable release won't happen until October, so this is not immediately applicable to you unless you build torchaudio by yourself.

One way to workaround is to use StreamWriter/StreamReader, to save audio to file or memory with Vorbis coding and read it. (which is what `apply_codec` function does under the hood, using `libsox`) We are also going to release this feature in the next release, but this is Python only implementation so one can port it easily. See https://pytorch.org/audio/main/tutorials/effector_tutorial.html#codecs and refer to https://github.com/pytorch/audio/blob/main/torchaudio/io/_effector.py for the implementation.
