### ISSUE TITLE
"ONLINE ASR WITH EMFORMER RNN-T" inference does not work

### ISSUE THREAD

**Issue by janniss91** [pytorch/audio#3429]
### 🐛 Describe the bug

I cannot run inference for the "ONLINE ASR WITH EMFORMER RNN-T" tutorial (https://pytorch.org/audio/2.0.1/tutorials/online_asr_tutorial.html).

I ran the connected jupyter notebook on my machine and on colab.
I used the following versions:
- Ubuntu Versions 22.04 and 20.04 (tried both)
- torch 2.0.0 (as suggested)
- torchaudio 2.0.1 (as suggested)
- sentencepiece 0.1.99
- ffmpeg 4.2.7-0ubuntu0.1. (as suggested)

The bug appears in the first `run_inference()` cell.
I haven't changed anything about the script but get the following error message:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-9-922929568568>](https://localhost:8080/#) in <cell line: 1>()
----> 1 run_inference()

10 frames
[/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py](https://localhost:8080/#) in decorate_context(*args, **kwargs)
    113     def decorate_context(*args, **kwargs):
    114         with ctx_factory():
--> 115             return func(*args, **kwargs)
    116 
    117     return decorate_context

[<ipython-input-8-33a5cd90a1e6>](https://localhost:8080/#) in run_inference(num_iter)
     27         segment = cacher(chunk[:, 0])
     28         features, length = feature_extractor(segment)
---> 29         hypos, state = decoder.infer(features, length, 10, state=state, hypothesis=hypothesis)
     30         hypothesis = hypos
     31         transcript = token_processor(hypos[0][0], lstrip=False)

[/usr/local/lib/python3.10/dist-packages/torchaudio/models/rnnt_decoder.py](https://localhost:8080/#) in infer(self, input, length, beam_width, state, hypothesis)
    341 
    342         enc_out, _, state = self.model.transcribe_streaming(input, length, state)
--> 343         return self._search(enc_out, hypothesis, beam_width), state

[/usr/local/lib/python3.10/dist-packages/torchaudio/models/rnnt_decoder.py](https://localhost:8080/#) in _search(self, enc_out, hypo, beam_width)
    238 
    239         a_hypos: List[Hypothesis] = []
--> 240         b_hypos = self._init_b_hypos(hypo, device)
    241         for t in range(n_time_steps):
    242             a_hypos = b_hypos

[/usr/local/lib/python3.10/dist-packages/torchaudio/models/rnnt_decoder.py](https://localhost:8080/#) in _init_b_hypos(self, hypo, device)
    119 
    120         one_tensor = torch.tensor([1], device=device)
--> 121         pred_out, _, pred_state = self.model.predict(torch.tensor([[token]], device=device), one_tensor, state)
    122         init_hypo = (
    123             [token],

[/usr/local/lib/python3.10/dist-packages/torchaudio/models/rnnt.py](https://localhost:8080/#) in predict(self, targets, target_lengths, state)
    640                     representing internal state generated in current invocation of ``predict``.
    641         """
--> 642         return self.predictor(input=targets, lengths=target_lengths, state=state)
    643 
    644     @torch.jit.export

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1499                 or _global_backward_pre_hooks or _global_backward_hooks
   1500                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501             return forward_call(*args, **kwargs)
   1502         # Do not call functions when jit is used
   1503         full_backward_hooks, non_full_backward_hooks = [], []

[/usr/local/lib/python3.10/dist-packages/torchaudio/models/rnnt.py](https://localhost:8080/#) in forward(self, input, lengths, state)
    375         """
    376         input_tb = input.permute(1, 0)
--> 377         embedding_out = self.embedding(input_tb)
    378         input_layer_norm_out = self.input_layer_norm(embedding_out)
    379 

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1499                 or _global_backward_pre_hooks or _global_backward_hooks
   1500                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501             return forward_call(*args, **kwargs)
   1502         # Do not call functions when jit is used
   1503         full_backward_hooks, non_full_backward_hooks = [], []

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/sparse.py](https://localhost:8080/#) in forward(self, input)
    160 
    161     def forward(self, input: Tensor) -> Tensor:
--> 162         return F.embedding(
    163             input, self.weight, self.padding_idx, self.max_norm,
    164             self.norm_type, self.scale_grad_by_freq, self.sparse)

[/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py](https://localhost:8080/#) in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   2208         # remove once script supports set_grad_enabled
   2209         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 2210     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
   2211 
   2212 

RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)
```

### Versions

PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.107+-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           79
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
Stepping:                        0
CPU MHz:                         2199.998
BogoMIPS:                        4399.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        256 KiB
L3 cache:                        55 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.1
[pip3] torchdata==0.6.1
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] Could not collect

**Comment by janniss91** [comment]
I replaced the `decoder.infer(features, length, 10, state=state, hypothesis=hypothesis)` call for streaming with the non-streaming call `decoder(features, length, 10)` and this works but I need the streaming functionality.

**Comment by mthrok** [comment]
Hi @janniss91 

I confirm that the issue reproduces on Google Colab, but strangely, it does not reproduce on my laptop or our CI (which is why we did not notice).

It is something about `state` and `hypothesis`. If I replace `decoder.infer(features, length, 10, state=state, hypothesis=hypothesis)` with `decoder.infer(features, length, 10, state=None, hypothesis=None)` it does not fail.

Perhaps the length count in RNNT decoder is sometimes producing float type for some reason.

cc @hwangjeff

**Comment by janniss91** [comment]
Hi @hwangjeff 

Thanks for the answer!

I also thought that this was happening and I tried changing the data type in the torch code before the error happens (as a hack) but no success either.
Do you think this issue might be tackled anytime soon?

**Comment by hwangjeff** [comment]
@janniss91 it turns out that our documentation for the stable release incorrectly links to the Colab notebook for the nightly, and that notebook uses the TorchAudio stable release. Sorry for the confusion — we'll work on fixing this. In the meantime, you can do one of two things:

1. Install the nightly release for the notebook you're currently using and rerun the notebook.
2. Switch over to the notebook that corresponds to the stable release (https://colab.research.google.com/github/pytorch/audio/blob/gh-pages/2.0.1/_downloads/bd34dff0656a1aa627d444a8d1a5957f/online_asr_tutorial.ipynb).
