### ISSUE TITLE
Error while using PitchShift on GPU tensor

### ISSUE THREAD

**Issue by DanTremonti** [pytorch/audio#3446]
### 🐛 Describe the bug

The following piece of code
```py
import torch
from torchaudio.transforms import PitchShift

waveform = torch.randn(1600, device=torch.device("cuda:0"))
effect = PitchShift(
    sample_rate = 16000,
    n_steps = 1,
)
output_tensor = effect(waveform)
```

raises exception
```sh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dhanvanth/anaconda3/envs/z3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/dhanvanth/anaconda3/envs/z3/lib/python3.9/site-packages/torchaudio/transforms/_transforms.py", line 1705, in forward
    waveform_stretch = _stretch_waveform(
  File "/home/dhanvanth/anaconda3/envs/z3/lib/python3.9/site-packages/torchaudio/functional/functional.py", line 1801, in _stretch_waveform
    spec_f = torch.stft(
  File "/home/dhanvanth/anaconda3/envs/z3/lib/python3.9/site-packages/torch/functional.py", line 641, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: stft input and window must be on the same device but got self on cuda:0 and window on cpu
```

It seems like [here](https://github.com/pytorch/audio/blob/main/torchaudio/transforms/_transforms.py#LL1716C18-L1716C44) in `PitchShift`'s init, device arg has not been passed to `window_fn` (before `waveform` is passed in forward).
```py
window = window_fn(self.win_length) if wkwargs is None else window_fn(self.win_length, **wkwargs)
```

As it is mentioned that this class supports both these devices - cpu and cuda, I hope we can expect the above exception to not be raised without having to do
```py
output_tensor = effect.to(waveform.device)(waveform)
```

### Versions

<details>
  <summary>Versions</summary>

PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.31

Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-75-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Quadro P1000
Nvidia driver version: 470.182.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           158
Model name:                      Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
Stepping:                        10
CPU MHz:                         2600.000
CPU max MHz:                     4300.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5199.98
L1d cache:                       192 KiB
L1i cache:                       192 KiB
L2 cache:                        1.5 MiB
L3 cache:                        9 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy==0.961
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==2.0.0
[pip3] torch==2.0.0+cu118
[pip3] torch-poly-lr-decay==0.0.1
[pip3] torchaudio==2.0.0+cu118
[pip3] torchmetrics==0.11.4
[pip3] triton==2.0.0
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-lightning         2.0.0                    pypi_0    pypi
[conda] torch                     2.0.0+cu118              pypi_0    pypi
[conda] torch-poly-lr-decay       0.0.1                    pypi_0    pypi
[conda] torchaudio                2.0.0+cu118              pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

</details>

**Comment by mahtin** [comment]
Sadly, the came issue comes up when using waveforms on `cuda` and using `torchaudio.pipelines.EMFORMER_RNNT_BASE_LIBRISPEECH`.

**Comment by mthrok** [comment]
Couple of thoughts

1. This "move to CUDA" device is the pattern adopted from early time when PyTorch was in alpha. And it is common assumption throughout codebase. I understand it's annoying for new users, though.
2. Modules using resampling is an exception and it uses LazyModuleMixin because `dtype` affects the numerical behavior.
3. LazyModuleMixin was prototype when we used it in resample, but now it looks like more stable?
4. Using LazyModuleMixin is not free of side effect. It changes some semantic about serialization. (it needs a dry run)
5. If we want to get rid of the move-to-CUDA semantic, we could apply LazyModuleMixin to all the transforms, however, the maintenance team does not have bandwidth to do this. It needs to be user-led efforts with good prospect of completion.

**Comment by DanTremonti** [comment]
@mthrok thanks for the explanation

**Comment by mahtin** [comment]
@DanTremonti - I'm not convinced this should be closed. It's still a valid issue. Thoughts?

**Comment by DanTremonti** [comment]
@mahtin I was inclined to close this issue as I realized that this behaviour is not just observed for `PitchShift` transform. It seems to be an outcome of the design and
> It needs to be user-led efforts with good prospect of completion.

Maybe a newer issue pointing out this behaviour by all transforms can be opened to address this? I think that would be more appropriate.

**Comment by mthrok** [comment]
Yes, we need to discuss first if we want to change the semantic of the entire codebase. What's the pros and cons?
Then we need to create an issue to track the progress. A new issue would be more appropriate.
