### ISSUE TITLE
transforms.AmplitudeToDB top_db cut-off inconsistent between single-sample and batched/multichannel data.

### ISSUE THREAD

**Issue by RicherMans** [pytorch/audio#3448]
### 🐛 Describe the bug

Hey there,
so I recently came across the same problem as in #994, but I think that the current code still does not properly work for batched inputs vs. single inputs.

Currently this [implementation here](https://github.com/pytorch/audio/blob/77cdd160f15f63f18c35e7f2d885dcc14e85a846/torchaudio/functional/functional.py#L390) seems to handle batches and single samples differently in this code sample:

```python
# Expand batch
shape = x_db.size()
packed_channels = shape[-3] if x_db.dim() > 2 else 1
x_db = x_db.reshape(-1, packed_channels, shape[-2], shape[-1])

x_db = torch.max(x_db, (x_db.amax(dim=(-3, -2, -1)) - top_db).view(-1, 1, 1, 1))

# Repack batch
x_db = x_db.reshape(shape)
```

Considering two cases that for 1. the input is not batched (i.e., some waveform with length 16000) and 2. the input is batched with size i.e., [BATCH, 16000].

In case of 1. `shape = x_db.size()` will return some size of [time, frame], `packed_channels=1` and the shape of `x_db` is `[1,1,time,frame]` , which leads to `x_db.amax(dim=(-3, -2, -1)) ` being a single value for the single input, which is expected.

In case of 2. `shape = [BATCH, time, frame]`, `packed_channels=BATCH` and the shape of `x_db` is `[1,BATCH,time,frame]` , which leads to `x_db.amax(dim=(-3, -2, -1)) ` being a single value for all the batches in the input, leading to inconsistent behaviour.

I think the problem is the docs somehow specify that the input should have an added [channel dimension](https://github.com/pytorch/audio/blob/77cdd160f15f63f18c35e7f2d885dcc14e85a846/torchaudio/functional/functional.py#L375), which leads to a confusion between batch and channel dimensions.

A quick and easy fix would be to check for 4d > tensors, which should have a channel dimension, otherwise just pad the channel dimension as 1:

```python
packed_channels = shape[-3] if x_db.dim() > 3 else 1
```

I checked with my local version of torchaudio and at least for some simple experiments this seems to fix the problem.

### Versions

2.0.2

**Comment by mthrok** [comment]
Hi @RicherMans 

Thanks for filing the issue. Sorry for the late response.
It seems to me that this is a matter of expectation. IIUC, the implementation and the doc are aligned on 4D case. The 3D case is ambiguous from doc. The implementation considers `3D == [channel, freq, time]`, while you expect `3D == [batch, freq, time]`, which also seems reasonable expectation.

In my understanding, the proposed change will treat the 3D input differently than before, and it is backward compatibility breaking change. However, if users are using the function properly, then they are passing 4D tensor for this use case, `[Batch, 1, freq, time]`, so they should not be affected. Those who are passing 3D tensor with `[channel, freq, time]` will start to see a different result. Breaking backward compatibility is something we want to avoid unless it's absolutely.

In this case, warning an issue when input is 3D and encourage users to reshape the input tensor to 4D seems to be also reasonable improvement.

What do you think?

**Comment by RicherMans** [comment]
Hey @mthrok,
thanks for the quick response!

So at least from my side, I would have expeced the implementation to the follow "pytorch standard" to only allow batched inputs, i.e., that for the case of a single sample, that sample needs to have a dimension of `batch x samples`.
After you just now mentioned it, I never realized that `torchaudio.load` returns a tensor of `channel x time` , because I thought that the first dimension is the batch dimension (since all pytorch models require that).

> In my understanding, the proposed change will treat the 3D input differently than before, and it is backward compatibility breaking change.

Yeah I completely agree, but I am just curious if you could think about maybe changing that for a later "major" release. It of course depends on the amount of people that (like me) misused this function. 

> In this case, warning an issue when input is 3D and encourage users to reshape the input tensor to 4D seems to be also reasonable improvement.

I would much agree, maybe just explicitly state that as a warning in the docs for `AmplitudeToDB`, that when passing a batched tensor you need to have `batch x channel ... `, otherwise the results are inconsistent.
What I would say is a bit of a problem is that this function is generally within a pipeline, i.e., `nn.Sequential(MelSpectrogram(), AmplitudeToDB())`, thus one should already during the extraction of a melspectrogram know the caveats of the amplitudetodb function. 

Thanks !
