### ISSUE TITLE
Env var used for building are ignored

### ISSUE THREAD

**Issue by elmuz** [pytorch/audio#3472]
### 🐛 Describe the bug

It seems that even though I am passing some variables they are ignored during cmake config. I am using docker, and in particular in the Dockerfile I am running the following command to build torchaudio:
```
RUN cd /tmp && \
    git clone https://github.com/pytorch/audio.git && \
    cd audio && \
    git checkout v2.0.2 && \
    USE_FFMPEG=1 USE_CUDA=1 USE_CUDNN=1 TORCH_CUDA_ARCH_LIST='6.0 6.1 7.0 7.5' python setup.py install && \
    cd ../ && \
    rm -r audio
```
However, then I get following console output, as the previous flags were ignored.
```
#0 78.11 -- USE_CUDNN is set to 0. Compiling without cuDNN support
#0 78.11 CMake Warning at /usr/local/lib/python3.8/site-packages/torch/share/cmake/Caffe2/public/utils.cmake:385 (message):
#0 78.11   In the future we will require one to explicitly pass TORCH_CUDA_ARCH_LIST
#0 78.11   to cmake instead of implicitly setting it as an env variable.  This will
#0 78.11   become a FATAL_ERROR in future version of pytorch.
```
Also... even though
```
#16 67.54 -- Found FFMPEG: /usr/local/include (found suitable version "5.1.3", minimum required is "4.1") found components: avdevice avfilter avformat avcodec avutil
```
then I only have the `['sox_io']` backend.

Is it happening also to you?

### Versions

PyTorch version: 2.0.0a0+gite9ebda2
Is debug build: False
CUDA used to build PyTorch: 11.5
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.8.17 (default, Jul 10 2023, 08:50:09)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-50-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla V100-SXM2-32GB
Nvidia driver version: 495.29.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          48
On-line CPU(s) list:             0-47
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz
Stepping:                        7
CPU MHz:                         1500.000
CPU max MHz:                     3500.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        4800.00
Virtualization:                  VT-x
L1d cache:                       768 KiB
L1i cache:                       768 KiB
L2 cache:                        24 MiB
L3 cache:                        33 MiB
NUMA node0 CPU(s):               0-11,24-35
NUMA node1 CPU(s):               12-23,36-47
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.0.0a0+gite9ebda2
[pip3] torchaudio==2.0.2+31de77d
[conda] Could not collect

**Comment by mthrok** [comment]
Hi

The part about the environment variables are as expected. we pass a subset of environment variables to CMake. 

https://github.com/pytorch/audio/blob/786066b46c5961470b3eb57106263f594c2c6c79/tools/setup_helpers/extension.py#L22-L45

You can see that `USE_FFMPEG` is reflected.

`USE_CUDNN` is not used because torchaudio does not use cuDNN APIs. It is PyTorch's CMakeLists, who is searching for cuDNN so that it can set the proper linker flag (in case it is required), so you can ignore it. If you want to, you can edit the above code to pass the environment variable.

About the backend, we do not integrate ffmpeg in the old-style backend. We are deprecating the global backend and moving to par-function-call backend dispatch. `list_audio_backend` could be obsolete. Could you try `torchaudio.load("foo.wav", backend="ffmpeg")` and see what happens?

**Comment by elmuz** [comment]
Thanks for the reply. Ok for the USE_CUDNN flag. Regarding FFmpeg this is what I get:
```
>>> a, sr = torchaudio.load("data/audio.mp4", backend="ffmpeg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: load() got an unexpected keyword argument 'backend'
>>> torchaudio.__version__
'2.0.2+31de77d'
```
I am passing a video instead of extracting the audio but I don't think that's the issue.

**Comment by mthrok** [comment]
I missed that you are using 2.0.2.
2.0.2 is a transition phase in IO change, and setting `TORCHAUDIO_USE_BACKEND_DISPATCHER=1` when importing torchaudio will enable the `backend` keyword. in 2.1 (main branch) this is now default.
Can you try that and see if it works?

**Comment by elmuz** [comment]
Yes, I can confirm it works. I am closing this, thank you.
