### ISSUE TITLE
请问以下这个错误时什么问题AttributeError: module 'torchaudio' has no attribute 'open'

### ISSUE THREAD

**Issue by lzy473** [pytorch/audio#3481]
### 🐛 Describe the bug

input_stream = torchaudio.open(input_device)这是报错的代码

### Versions

这是报错代码input_stream = torchaudio.open(input_device)

**Comment by lzy473** [comment]
input_device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
input_stream = torchaudio.open(input_device)

**Comment by mthrok** [comment]
There is not such API in torchaudio.
