### ISSUE TITLE
Diagram showing relationship between audio features has wrong relationship for MFCC and LFCC

### ISSUE THREAD

**Issue by gau-nernst** [pytorch/audio#3485]
### 📚 The doc issue

The photo shown on this page is wrong about MFCC and LFCC.

https://pytorch.org/audio/2.0.1/transforms.html

From what I understand, MFCC is Mel-scale spectrogram + DCT. Thus, "apply filter bank" arrow is not correct. The filter bank is the T.MelScale.

Similarly, LFCC = Spectrogram -> linear filter banks -> DCT. Therefore, the arrow from Mel-scale spectrogram to LFCC should not exist.

### Suggest a potential alternative/fix

- Mel-scale spectrogram to MFCC: DCT only (perhaps we can include "taking log" here also)
- Remove arrow from Mel-scale spectrogram to LFCC
- Power spectrogram to LFCC: linear filter bank + DCT (with possible "taking log" as above)

**Comment by mthrok** [comment]
Hi @gau-nernst 

Thanks for pointing out. How does this look? If it looks okay, I will update the diagram.

![torchaudio feature extractions](https://github.com/pytorch/audio/assets/855818/c6638a87-dd86-4107-a8f8-aa0f9f9c8295)

**Comment by gau-nernst** [comment]
That looks awesome! Thank you for the quick update.

**Comment by gau-nernst** [comment]
One small question that I'm not sure by myself also. From Raw spectrogram (complex-valued) to Power spectrogram (real-valued), I think it is magnitude squared, so it should be abs + square?

https://github.com/pytorch/audio/blob/63244623c1d4af5472942c262e9d488aeece6c6a/torchaudio/functional/functional.py#L146-L150

**Comment by mthrok** [comment]
@gau-nernst 

>  From Raw spectrogram (complex-valued) to Power spectrogram (real-valued), I think it is magnitude squared, so it should be abs + square?

yes, it's `abs` and `power(2)` (square), I will update the diagram

> MFCC/LFCC, is there a square for the spectrogram before applying filter bank? 

Both MFCC and LFCC have square component, by default. One can change it but I don't think it's common to change it.

MFCC is melspec + log

https://github.com/pytorch/audio/blob/63244623c1d4af5472942c262e9d488aeece6c6a/torchaudio/transforms/_transforms.py#L699-L704

and melspec is spec + melscale

https://github.com/pytorch/audio/blob/63244623c1d4af5472942c262e9d488aeece6c6a/torchaudio/transforms/_transforms.py#L619-L620

and spectrogram is initialized with power=2

https://github.com/pytorch/audio/blob/63244623c1d4af5472942c262e9d488aeece6c6a/torchaudio/transforms/_transforms.py#L594-L606

LFCC is spectrogram filter bank + log + DCT

https://github.com/pytorch/audio/blob/63244623c1d4af5472942c262e9d488aeece6c6a/torchaudio/transforms/_transforms.py#L805-L814

and spectrogram is initialized with default values, which is power=2

https://github.com/pytorch/audio/blob/63244623c1d4af5472942c262e9d488aeece6c6a/torchaudio/transforms/_transforms.py#L778-L779

**Comment by mthrok** [comment]
I uploaded the new diagram. It seems it takes a while for CDN to update. Currently I see the updated diagram only when I use incognito mode for some reason. They should eventually update.

I will close the issue but feel free to suggest other improvements.
Thanks,

**Comment by gau-nernst** [comment]
Thank you so much. I can see it's updated from my side. The incognito issue is probably due to caching by the browser.
