### ISSUE TITLE
Small typo in melscale_fbanks

### ISSUE THREAD

**Issue by gau-nernst** [pytorch/audio#3486]
### 📚 The doc issue

In this page

https://pytorch.org/audio/main/generated/torchaudio.functional.melscale_fbanks.html

The "Returns" says

> the applied result would be `A * melscale_fbanks(A.size(-1), ...)`.

I believe the multiplication should have been matrix multiplication i.e. `@`

### Suggest a potential alternative/fix

Change `*` to `@`. Or more explicitly, write `torch.matmul()`

**Comment by mthrok** [comment]
Fix: https://github.com/pytorch/audio/pull/3487
