### ISSUE TITLE
category audio on discuss.pytorch.org

### ISSUE THREAD

**Issue by cyrta** [pytorch/audio#35]
Hi, 
I am just curious why there is no category *audio* on pytorch discussion forum.
There seems to be _vision_, _nlp_ but no _audio_.
I feel that are some greater number of post 
https://discuss.pytorch.org/search?q=audio

@apaszke  @soumith  what do you think? Can you introduce that ?

**Comment by apaszke** [comment]
Good idea. I've just created it
