### ISSUE TITLE
Assertion failed (core dumped) at `sox/src/formats.c:227`

### ISSUE THREAD

**Issue by hkctkuy** [pytorch/audio#3508]
### 🐛 Describe the bug

Hi, I've been fuzzing torchaudio project with [sydr-fuzz](https://github.com/ispras/oss-sydr-fuzz) and found crash at `sox/src/formats.c:227`.

 I think that assertion fails because `sox_append_comment() `function accepts `""` string as a second argument from `metadata->data.vorbis_comment.comments[i].entry` in `/audio/build/third_party/sox/src/sox/src/flac.c:133`.

**How to reproduce**

1. Build docker from [here](https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/torchaudio) and run the container:

```
 sudo docker build -t oss-sydr-fuzz-torchaudio .
 sudo docker run --privileged --rm -v `pwd`:/fuzz -it oss-sydr-fuzz-torchaudio /bin/bash
```

2. Run the target on this input: [crash-55b22b3ea8bdcd9831675d58d11741a9ae985fb3](https://github.com/dse/bug-reports/uploads/f7abbbbe3771af56c8aaa03ea5b9fe47/crash-55b22b3ea8bdcd9831675d58d11741a9ae985fb3)

```
/load_audio_afl crash-55b22b3ea8bdcd9831675d58d11741a9ae985fb3
```

3. You will see the following output:

```
Reading 4533 bytes from crash-55b22b3ea8bdcd9831675d58d11741a9ae985fb3
load_audio_afl: /audio/build/third_party/sox/src/sox/src/formats.c:227: void sox_append_comment(sox_comments_t *, const char *): Assertion `comment' failed.
Aborted (core dumped)
```

### Versions

torchaudio version: 30afaa9b2f460ca3baf6ac177bce4f6b5da8b99c
pytorch version: 0f1621df1a0a73956c7ce4e2f72f069e610e0137
sox version: [14.4.2](https://github.com/pytorch/audio/blob/63244623c1d4af5472942c262e9d488aeece6c6a/third_party/sox/CMakeLists.txt#L194)
OS: Ubuntu 20.04

**Comment by mthrok** [comment]
#3497 has landed, and now torchaudio links to sox dynamically. We no longer compile the specified code by ourselves and therefore this issue is now irrelevant.

Feel free to fuzz the code under `torchaudio/csrc`, and report issues there. Thanks,
