### ISSUE TITLE
Illegal instruction (core dumped) at `sox/src/adpcm.c:131`

### ISSUE THREAD

**Issue by hkctkuy** [pytorch/audio#3509]
### 🐛 Describe the bug

Hi, I've been fuzzing torchaudio project with [sydr-fuzz](https://github.com/ispras/oss-sydr-fuzz) and found crash at `sox/src/adpcm.c:131`.

**How to reproduce**

1. Build docker from [here](https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/torchaudio) and run the container:

```
sudo docker build -t oss-sydr-fuzz-torchaudio .
sudo docker run --privileged --rm -v `pwd`:/fuzz -it oss-sydr-fuzz-torchaudio /bin/bash
```

2. Run the target on this input: [crash-6fda0b654b9c4b1672c5bf5ab8126403ca1a2446](https://github.com/dse/bug-reports/uploads/98ed538f60a8eb5678e897db8b6238a8/crash-6fda0b654b9c4b1672c5bf5ab8126403ca1a2446)

```
/load_audio_afl crash-6fda0b654b9c4b1672c5bf5ab8126403ca1a2446
```

3. You will see the following output:

```
Illegal instruction (core dumped)
```

### Versions

torchaudio version: 30afaa9b2f460ca3baf6ac177bce4f6b5da8b99c
pytorch version: 0f1621df1a0a73956c7ce4e2f72f069e610e0137
sox version: [14.4.2](https://github.com/pytorch/audio/blob/63244623c1d4af5472942c262e9d488aeece6c6a/third_party/sox/CMakeLists.txt#L194)
OS: Ubuntu 20.04

**Comment by mthrok** [comment]
#3497 has landed, and now torchaudio links to sox dynamically. We no longer compile the specified code by ourselves and therefore this issue is now irrelevant.

Feel free to fuzz the code under `torchaudio/csrc`, and report issues there. Thanks,
