### ISSUE TITLE
Reverse MelScale, Griffin-Lim transformation

### ISSUE THREAD

**Issue by jaeyeun97** [pytorch/audio#351]
## 🚀 Feature

I have implemented PyTorch versions of `librosa`'s ` mel_to_stft` and `griffinlim`, which I believe would be useful for any generation task using mel-spectrograms. You can see it as a part of my Melnet implementation here: https://github.com/jaeyeun97/MelNet/blob/master/audio.py. While it currently does not conform to the standards of this repo with a little touch here and there I think it would be a good addition.

## Motivation

1. `librosa` has `mel_to_stft`, which solves for a spectrogram of linear frequency scale from a Mel scale spectrogram. Having a pure PyTorch implementation would remove the need of a `librosa` dependency and add support for GPU processing (which speeds up the processes significantly)

2. Similarly, Griffin-Lim algorithm provides an approximation for phase in order to provide a better spectrogram inversion, and since this project provides an implementation for `istft` I thought I would use it to port the `griffinlim` function from `librosa`.

## Pitch

I would like to add the code for Griffin-Lim and mel-to-linear scaling I referenced above to this repository.

I don't know why this hasn't been done before--was there any license issue, etc. regarding porting the code? Otherwise, I think this would be a relatively a painless merge into the repository.

**Comment by maximecb** [comment]
This would be useful to me :+1:

**Comment by vincentqb** [comment]
Yes, that sounds like good additions. Please feel free to open pull requests.

**Comment by jaeyeun97** [comment]
Cool, had a look into the test codes--I'll open a pull request soon.

**Comment by jaeyeun97** [comment]
@vincentqb Would you like these as separate pull requests or as one?

**Comment by vincentqb** [comment]
> @vincentqb Would you like these as separate pull requests or as one?

I usually separate, but please do what's convenient for you for this :)

**Comment by vincentqb** [comment]
Thanks again for working on this @jaeyeun97! #448 merged the second request made in this issue.
