### ISSUE TITLE
Signal written in "htk" format using sox_io_backend gives out wrong sample_rate

### ISSUE THREAD

**Issue by DanTremonti** [pytorch/audio#3513]
### 🐛 Describe the bug

Code to reproduce this behaviour
```py
import torch
import torchaudio
torchaudio.set_audio_backend("sox_io")

sample_rate = 48000
duration = 2.0
num_samples = duration * sample_rate
t = torch.randn((1, int(num_samples)))

audio_formats = ["wav", "mp3", "ogg", "vorbis", "amb", "flac", "sph", "htk"]
for audio_format in audio_formats:
    file_path = f"/home/audios/signal.{audio_format}"
    torchaudio.backend.sox_io_backend.save(
        filepath=file_path,
        src=t,
        sample_rate=sample_rate,
        channels_first=True,
        format=audio_format,
    )
    written_signal, written_sample_rate = torchaudio.backend.sox_io_backend.load(
        file_path,
        channels_first=True,
        format=audio_format,
    )

    print(audio_format)
    # not expecting precisely matching values here
    print(t[0][0], t[0][-1])
    print(written_signal[0][0], written_signal[0][-1])

    print("written_signal.shape: ", written_signal.shape[-1])
    print("written_sample_rate: ", written_sample_rate)
    print("torchaudio.info: ", torchaudio.info(file_path).sample_rate)
    print("")

```

stdout

```sh
wav
tensor(1.2368) tensor(0.1041)
tensor(1.) tensor(0.1041)
written_signal.shape:  96000
written_sample_rate:  48000
torchaudio.info:  48000

mp3
tensor(1.2368) tensor(0.1041)
tensor(0.) tensor(0.0001)
written_signal.shape:  97920
written_sample_rate:  48000
torchaudio.info:  48000

ogg
tensor(1.2368) tensor(0.1041)
tensor(0.7111) tensor(-0.1528)
written_signal.shape:  96000
written_sample_rate:  48000
torchaudio.info:  48000

vorbis
tensor(1.2368) tensor(0.1041)
tensor(0.7111) tensor(-0.1528)
written_signal.shape:  96000
written_sample_rate:  48000
torchaudio.info:  48000

amb
tensor(1.2368) tensor(0.1041)
tensor(1.) tensor(0.1041)
written_signal.shape:  96000
written_sample_rate:  48000
torchaudio.info:  48000

flac
tensor(1.2368) tensor(0.1041)
tensor(1.0000) tensor(0.1041)
written_signal.shape:  96000
written_sample_rate:  48000
torchaudio.info:  48000

sph
tensor(1.2368) tensor(0.1041)
tensor(1.) tensor(0.1041)
written_signal.shape:  96000
written_sample_rate:  48000
torchaudio.info:  48000

htk
tensor(1.2368) tensor(0.1041)
tensor(1.0000) tensor(0.1041)
written_signal.shape:  96000   -------> right number of samples
written_sample_rate:  48076    -------> wrong sample_rate
torchaudio.info:  48076        -------> wrong sample_rate
```

### Versions

<details>
  <summary>Versions</summary>

PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.9.16 (main, May 15 2023, 23:46:34)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Quadro P1000
Nvidia driver version: 470.199.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           158
Model name:                      Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
Stepping:                        10
CPU MHz:                         3024.331
CPU max MHz:                     4300.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5199.98
L1d cache:                       192 KiB
L1i cache:                       192 KiB
L2 cache:                        1.5 MiB
L3 cache:                        9 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy==0.961
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==2.0.0
[pip3] torch==2.0.0+cu118
[pip3] torch-poly-lr-decay==0.0.1
[pip3] torch-stoi==0.1.2
[pip3] torchaudio==2.0.0+cu118
[pip3] torchmetrics==0.11.4
[pip3] triton==2.0.0
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-lightning         2.0.0                    pypi_0    pypi
[conda] torch                     2.0.0+cu118              pypi_0    pypi
[conda] torch-poly-lr-decay       0.0.1                    pypi_0    pypi
[conda] torch-stoi                0.1.2                    pypi_0    pypi
[conda] torchaudio                2.0.0+cu118              pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

</details>

**Comment by mthrok** [comment]
Hi

I looked at this and I think this is an issue with libsox itself. 
I tried your script with the nightly build and `torchaudio.info`, which uses FFmpeg backend, reports `Invalid data found when processing input`.

If I do a similar thing with `sox` and `ffmpeg` command, the same issue is reported.

```bash
$ sox -V3 --no-dither -R --bits 16 --rate 4800 --null --channels 1 foo.htk synth 3 sawtooth 1
sox:      SoX v

Input File     : '' (null)
Channels       : 1
Sample Rate    : 4800
Precision      : 16-bit
Endian Type    : little
Reverse Nibbles: no
Reverse Bits   : no

sox INFO sox: Overwriting `foo.htk'
sox WARN htk: rounding sample period 2083.333333 (x 100ns) to nearest integer

Output File    : 'foo.htk'
Channels       : 1
Sample Rate    : 4800
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM
Endian Type    : big
Reverse Nibbles: no
Reverse Bits   : no
Comment        : 'Processed by SoX'

sox INFO sox: effects chain: input         4800Hz  1 channels
sox INFO sox: effects chain: synth         4800Hz  1 channels
sox INFO sox: effects chain: output        4800Hz  1 channels
```
```bash
$ ffprobe foo.htk
ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
  configuration: --prefix=/Users/moto/miniconda3 --enable-sdl --enable-opengl --disable-static --enable-shared --enable-libmp3lame --enable-decoder=mp3 --enable-libfreetype --enable-libfontconfig
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
foo.htk: Invalid data found when processing input
```

I looked into our side of the code, and the following is relevant for encoding HTK, but this seems to be correct. 

https://github.com/pytorch/audio/blob/8588fba15a7b1ee3a73c626fa59c87bd501dc99b/torchaudio/csrc/sox/utils.cpp#L300-L307

Therefore, I don't think we can do anything to fix this.

**Comment by DanTremonti** [comment]
Thanks @mthrok Based on your insights, I'm closing this issue.

**Comment by DanTremonti** [comment]
I noticed that the number of samples increased from **96000** to **97920** in case of **mp3** format. Is this expected behaviour?

**Comment by mthrok** [comment]
Yes, it is a known issue. It happens because underlying implementation does not remove the extra padding added in encoding step. It happens inside of libsox, so it's not something we can fix. Using FFmpeg would avoid the problem. 

See https://github.com/pytorch/audio/issues/1500
