### ISSUE TITLE
IndexError: list index out of range while running ONLINE ASR WITH EMFORMER RNN-T 

### ISSUE THREAD

**Issue by akshaybaviskar** [pytorch/audio#3530]
### 🐛 Describe the bug

I tried running the emformer RNN-T inference as described in this tutorial:
https://pytorch.org/audio/stable/tutorials/online_asr_tutorial.html#online-asr-with-emformer-rnn-t

I am able to run it with following stable torch and torchaudio versions:
torch 2.0.1+cu117
torchaudio 2.0.2+cu117 

However, it fails with latest nightly torch and torchaudio version:
torch 2.1.0.dev20230803+cu121
torchaudio 2.1.0.dev20230803+cu121

with the following error:
```
2.1.0.dev20230803+cu121
2.1.0.dev20230803+cu121
Sample rate: 16000
Main segment: 2560 frames (0.16 seconds)
Right context: 640 frames (0.04 seconds)
SourceAudioStream(media_type='audio', codec='mp3', codec_long_name='MP3 (MPEG audio layer 3)', format='fltp', bit_rate=128000, num_frames=0, bits_per_sample=0, metadata={}, sample_rate=44100.0, num_channels=2)
OutputAudioStream(source_index=0, filter_description='aresample=16000,aformat=sample_fmts=fltp', media_type='audio', format='fltp', sample_rate=16000.0, num_channels=2)
Traceback (most recent call last):
  File "examples/pytorch/emformer_rnn_inference.py", line 107, in <module>
    run_inference()
  File "/home2/a/.venv/rnnt3.8nightly/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "examples/pytorch/emformer_rnn_inference.py", line 94, in run_inference
    hypos, state = infer(features, length, 10, state=state, hypothesis=hypothesis)
  File "examples/pytorch/emformer_rnn_inference.py", line 83, in infer
    return decoder.infer(features, length, 10, state=state, hypothesis=hypothesis)
  File "/home2/a/.venv/rnnt3.8nightly/lib/python3.8/site-packages/torchaudio/models/rnnt_decoder.py", line 339, in infer
    return self._search(enc_out, hypothesis, beam_width), state
  File "/home2/a/.venv/rnnt3.8nightly/lib/python3.8/site-packages/torchaudio/models/rnnt_decoder.py", line 244, in _search
    next_token_probs = self._gen_next_token_probs(enc_out[:, t : t + 1], a_hypos, device)
  File "/home2/a/.venv/rnnt3.8nightly/lib/python3.8/site-packages/torchaudio/models/rnnt_decoder.py", line 130, in _gen_next_token_probs
    predictor_out = torch.stack([_get_hypo_predictor_out(h) for h in hypos], dim=0)
  File "/home2/a/.venv/rnnt3.8nightly/lib/python3.8/site-packages/torchaudio/models/rnnt_decoder.py", line 130, in <listcomp>
    predictor_out = torch.stack([_get_hypo_predictor_out(h) for h in hypos], dim=0)
  File "/home2/a/.venv/rnnt3.8nightly/lib/python3.8/site-packages/torchaudio/models/rnnt_decoder.py", line 21, in _get_hypo_predictor_out
    return hypo[1]
IndexError: list index out of range
```

Following is the `emformer_rnn_inference.py` code, i.e., exactly same as described in the tutorial:

```
import torch
import torchaudio

print(torch.__version__)
print(torchaudio.__version__)

import IPython

bundle = torchaudio.pipelines.EMFORMER_RNNT_BASE_LIBRISPEECH

feature_extractor = bundle.get_streaming_feature_extractor()
decoder = bundle.get_decoder()
token_processor = bundle.get_token_processor()

sample_rate = bundle.sample_rate
segment_length = bundle.segment_length * bundle.hop_length
context_length = bundle.right_context_length * bundle.hop_length

streamer = StreamReader(src)
streamer.add_basic_audio_stream(frames_per_chunk=segment_length, sample_rate=bundle.sample_rate)

class ContextCacher:
    """Cache the end of input data and prepend the next input data with it.

    Args:
        segment_length (int): The size of main segment.
            If the incoming segment is shorter, then the segment is padded.
        context_length (int): The size of the context, cached and appended.
    """

    def __init__(self, segment_length: int, context_length: int):
        self.segment_length = segment_length
        self.context_length = context_length
        self.context = torch.zeros([context_length])

    def __call__(self, chunk: torch.Tensor):
        if chunk.size(0) < self.segment_length:
            chunk = torch.nn.functional.pad(chunk, (0, self.segment_length - chunk.size(0)))
        chunk_with_context = torch.cat((self.context, chunk))
        self.context = chunk[-self.context_length :]
        return chunk_with_context

cacher = ContextCacher(segment_length, context_length)
state, hypothesis = None, None
stream_iterator = streamer.stream()

@torch.inference_mode()
def run_inference(num_iter=100):
    global state, hypothesis
    chunks = []
    feats = []
    for i, (chunk,) in enumerate(stream_iterator, start=1):
        segment = cacher(chunk[:, 0])
        features, length = feature_extractor(segment)
        hypos, state = decoder.infer(features, length, 10, state=state, hypothesis=hypothesis)
        hypothesis = hypos[0]
        transcript = token_processor(hypothesis[0], lstrip=False)
        print(transcript, end="", flush=True)

        chunks.append(chunk)
        feats.append(features)
        if i == num_iter:
            break

    # Plot the features
    return IPython.display.Audio(torch.cat(chunks).T.numpy(), rate=bundle.sample_rate)

run_inference()
```

Repro: python emformer_rnn_inference.py

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230803+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 11.0.0-2~ubuntu20.04.1
CMake version: version 3.27.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD Ryzen Threadripper 3970X 32-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         2200.000
CPU max MHz:                     3700.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        7386.30
Virtualization:                  AMD-V
L1d cache:                       1 MiB
L1i cache:                       1 MiB
L2 cache:                        16 MiB
L3 cache:                        128 MiB
NUMA node0 CPU(s):               0-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] pytorch-triton==2.1.0+e6216047b8
[pip3] torch==2.1.0.dev20230803+cu121
[pip3] torchaudio==2.1.0.dev20230803+cu121
[pip3] torchvision==0.16.0.dev20230803+cu121
[conda] Could not collect

**Comment by mthrok** [comment]
cc @hwangjeff @lakshmi-speak I think this is related to #3295.

**Comment by hwangjeff** [comment]
Hi @akshaybaviskar, note that https://github.com/pytorch/audio/pull/3295 made changes to both the decoder and the tutorials that use it. As a consequence, if you want to use the latest nightly TorchAudio version's decoder, you'll also need to use the latest nightly version's tutorial (https://pytorch.org/audio/main/tutorials/online_asr_tutorial.html).
