### ISSUE TITLE
Online beam decoding for ctc

### ISSUE THREAD

**Issue by janvainer** [pytorch/audio#3574]
### 🚀 The feature

Support online beam-search decoding for CTC-based ASR.

### Motivation, pitch

Recently, an awesome beam decoding feature for CTC-based ASR was added to torchaudio. However, the [documentation](https://pytorch.org/audio/main/tutorials/asr_inference_with_ctc_decoder_tutorial.html) does not mention any streaming/online decoding capabilities. Is it somehow possible to extend the current tools to allow streaming/online decoding? It would be useful for streaming asr applications, where RNN-T is not an option for whatever reason.

### Alternatives

An alternative for now is to use the [ctcdecode](https://github.com/parlance/ctcdecode) package.

**Comment by mthrok** [comment]
Hi

The upstream flashlight-text supports online beam decoding. https://github.com/flashlight/text/issues/56

In fact, offline decoding is just executing online beam decoding inside of [`decode` method](https://github.com/flashlight/text/blob/7cfcc54b3b91d06ec97f6207e5eb69cb43fdd5ff/flashlight/lib/text/decoder/Decoder.h#L52-L57), which is exposed [here](https://github.com/flashlight/text/blob/7cfcc54b3b91d06ec97f6207e5eb69cb43fdd5ff/bindings/python/flashlight/lib/text/_decoder.cpp#L362) and called by TorchAudio [here](https://github.com/pytorch/audio/blob/e057d7d144e2716588b80255f0a143662fd5c10d/torchaudio/models/decoder/_ctc_decoder.py#L300)

For TorchAudio to support online decoding, we need to add proper wrapper methods, but meanwhile, you can instantiate the `flashlight.lib.text.decoder.LexiconFreeDecoder` (or other Decoder variant) and call [`decode_begin`](https://github.com/flashlight/text/blob/7cfcc54b3b91d06ec97f6207e5eb69cb43fdd5ff/bindings/python/flashlight/lib/text/_decoder.cpp#L354), [`decode_step`](https://github.com/flashlight/text/blob/7cfcc54b3b91d06ec97f6207e5eb69cb43fdd5ff/bindings/python/flashlight/lib/text/_decoder.cpp#L355-L360) multiple times then [`decode_end`](https://github.com/flashlight/text/blob/7cfcc54b3b91d06ec97f6207e5eb69cb43fdd5ff/bindings/python/flashlight/lib/text/_decoder.cpp#L361).

cc @jacobkahn

**Comment by mthrok** [comment]
#3594 adds the support for online decoding.

**Comment by janvainer** [comment]
Thanks this is awesome! :)
