### ISSUE TITLE
could the ctcdecode be serialized and executed in non-Python environments, such as torchscript?

### ISSUE THREAD

**Issue by johnson-magic** [pytorch/audio#3579]

**Comment by mthrok** [comment]
CTC decoder is exposed to Python via PyBind11, therefore it does not support TorchScript. To use the CTC decoder in non-Python environment, I think it is more straightforward to use the C++ API from the upstream project. https://github.com/flashlight/text

**Comment by johnson-magic** [comment]
我已收到，。
