### ISSUE TITLE
torchaudio.load() doesn't work on simple ogg example

### ISSUE THREAD

**Issue by Oktai15** [pytorch/audio#358]
## 🐛 Bug

torchaudio.load() doesn't work on simple ogg example from `librosa`

## To Reproduce

```python
import librosa
import torchaudio

filename = librosa.util.example_audio_file()
waveform, sample_rate = torchaudio.load(filename, filetype="ogg")
```

## Expected and real behavior 

Should be successful loaded, but I got the following error:

```
formats: no handler for given file type `ogg'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.7/site-packages/torchaudio/__init__.py", line 90, in load
    filetype)
RuntimeError: Error opening audio file
```

In the same time, everything is okay with `librosa`:
```python
y, sr = librosa.load(filename)
```
## Environment

 - What commands did you used to install torchaudio? conda
 - What does `torchaudio.__version__` print? 0.3.0+120f693

 - PyTorch Version: 1.3.0
 - OS: Ubuntu
 - How you installed PyTorch: conda
 - Python version: 3.7
 - CUDA/cuDNN version: 9.2

**Comment by Oktai15** [comment]
Related with another problem.

**Comment by HudsonHuang** [comment]
Did this problem solved? I got same error with ".amr" file, how could we fix this?
Version:
torch=1.4.0
torchaudio=0.4.0
sox=14.4.1

**Comment by madav-tech** [comment]
> Related with another problem.

Could you say which?
I'm trying to look for a fix
