### ISSUE TITLE
No handler for .mp4 format.

### ISSUE THREAD

**Issue by bjuncek** [pytorch/audio#36]
When I try to read an audio track from .mp4 file (Kinetics dataset), 
I get the following error:
`formats: no handler for file extension 'mp4'`
with the full stack trace:

```
~/bin/miniconda3/envs/pytorch03/lib/python3.6/site-packages/torch/utils/ffi/__init__.py in safe_call(*args, **kwargs)
    178                      for arg in args)
    179         args = (function,) + args
--> 180         result = torch._C._safe_call(*args, **kwargs)
    181         if isinstance(result, ffi.CData):
    182             typeof = ffi.typeof(result)

FatalError: [read_audio_file] Failure to read file at torchaudio/src/generic/th_sox.c:42
```

I take it it has something to do with my SoX install, but for the life of me can't figure out what I'm missing. Any ideas?

**Comment by faroit** [comment]
on linux you may have luck installing `libsox-fmt-ffmpeg`, but I think this where we hit the limits of libsox....

**Comment by bjuncek** [comment]
Is there a compile-it-from-source installation? The only thing I see are `.deb` packages and I have neither debian nor sudo access for package installation.

**Comment by bjuncek** [comment]
Edit - closing this issue, as that is out of scope - support for this would have to come from SoX
