### ISSUE TITLE
AttributeError: module 'torch.nn.utils.parametrizations' has no attribute 'weight_norm'

### ISSUE THREAD

**Issue by guanbaoy** [pytorch/audio#3618]
### 🐛 Describe the bug

When running inference.py from audio/examples/asr/librispeech_ctc_decoder by using the command below:
```shell
python inference.py --librispeech_path ./librispeech/ --split test-other --model WAV2VEC2_ASR_BASE_960H --beam-size 1500 --lm-weight 1.74 --word-score 0.52
```
It raised: AttributeError: module 'torch.nn.utils.parametrizations' has no attribute 'weight_norm'.
I use torch of version 2.0.0, and it seems that we should use nn.utils.weight_norm instead (have tried and it works).

### Versions

I think this issue is only related to torch version, which is 2.0.0 in my case.

**Comment by mthrok** [comment]
Hi

I think you have a combination of PyTorch and torchaudio that do not work together. 

`nn.utils.weight_norm` is a deprecated function and so we recently migrated to `nn.utils.parametrizations.weight_norm`.
This change wa sapplied in https://github.com/pytorch/audio/pull/3523, and it's not part of public release yet. (except 2.1 release candidate).

If you are using PyTorch 2.0, you need to use torchaudio 2.0. We do not guarantee the compatibility of other combinations.

**Comment by guanbaoy** [comment]
Ok, thanks for updating me this! Close this issue now.
