### ISSUE TITLE
torchaudio/compliance/kaldi.py FBank _get_window function can not support multiprocessing?

### ISSUE THREAD

**Issue by haha010508** [pytorch/audio#3619]
### 🐛 Describe the bug

i use torchaudio 0.13.0+cu117 to get Fbank, if i use it in one thread is ok, but i want to use multiprocessing, like this
`p = multiprocessing.Pool(1)
xx = p.apply_async(audio_functiong, arg=(audio_in,))
p.close()
p.join()
emb = xx.get()`
the code will hold on, and get nothing, i use debug found this function _get_window in kaldi.py can not run, so please help fix it,thanks!

### Versions
python 3.8

**Comment by mthrok** [comment]
Please share a runnable reproduction code.
