### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by sterlind** [pytorch/audio#3621]
### 🐛 Describe the bug

A badly-formatted log statement in `torchaudio.datasets.utils._extract_tar()` causes a logging error to be thrown:

```python
def _extract_tar(from_path: str, to_path: Optional[str] = None, overwrite: bool = False) -> List[str]:
    if to_path is None:
        to_path = os.path.dirname(from_path)
    with tarfile.open(from_path, "r") as tar:
        logging.info("Opened tar file {}.", from_path)
```

Minimal repro (note: bug won't trigger unless you do a fresh download):

```python
import torchaudio
import logging
from tempfile import TemporaryDirectory

logging.basicConfig(level=logging.INFO)

with TemporaryDirectory() as tmp_dir:
    test_dataset = torchaudio.datasets.LIBRISPEECH(
        tmp_dir,
        url='dev-clean',
        folder_in_archive="LibriSpeech",
        download=True
    )
```

### Versions

Collecting environment information...
PyTorch version: 2.2.0.dev20230912
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.15.90.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 545.29
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.8.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          32
On-line CPU(s) list:             0-31
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen Threadripper 1950X 16-Core Processor
CPU family:                      23
Model:                           1
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
Stepping:                        1
BogoMIPS:                        6787.38
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr virt_ssbd arat npt nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload
Virtualization:                  AMD-V
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       512 KiB (16 instances)
L1i cache:                       1 MiB (16 instances)
L2 cache:                        8 MiB (16 instances)
L3 cache:                        8 MiB (1 instance)
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] audiolm-pytorch==1.4.1
[pip3] clip-anytorch==2.5.2
[pip3] ema-pytorch==0.2.3
[pip3] lion-pytorch==0.1.2
[pip3] numpy==1.22.0
[pip3] pytorch-lightning==2.0.9
[pip3] pytorch-metric-learning==2.3.0
[pip3] rotary-embedding-torch==0.3.0
[pip3] torch==2.2.0.dev20230912
[pip3] torch-audiomentations==0.11.0
[pip3] torch-pitch-shift==1.2.4
[pip3] torchaudio==2.2.0.dev20230912
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==1.2.0
[pip3] torchsde==0.2.5
[pip3] torchvision==0.17.0.dev20230912
[pip3] triton==2.1.0
[pip3] vector-quantize-pytorch==1.7.1
[conda] audiolm-pytorch           1.4.1                    pypi_0    pypi
[conda] blas                      1.0                         mkl    conda-forge
[conda] clip-anytorch             2.5.2                    pypi_0    pypi
[conda] ema-pytorch               0.2.3                    pypi_0    pypi
[conda] lion-pytorch              0.1.2                    pypi_0    pypi
[conda] mkl                       2023.1.0         h213fc3f_46343  
[conda] numpy                     1.22.0                   pypi_0    pypi
[conda] pytorch                   2.2.0.dev20230912 py3.10_cuda12.1_cudnn8.9.2_0    pytorch-nightly
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch-nightly
[conda] pytorch-lightning         2.0.9                    pypi_0    pypi
[conda] pytorch-metric-learning   2.3.0                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] rotary-embedding-torch    0.3.0                    pypi_0    pypi
[conda] torch-audiomentations     0.11.0                   pypi_0    pypi
[conda] torch-pitch-shift         1.2.4                    pypi_0    pypi
[conda] torchaudio                2.2.0.dev20230912     py310_cu121    pytorch-nightly
[conda] torchdiffeq               0.2.3                    pypi_0    pypi
[conda] torchmetrics              1.2.0                    pypi_0    pypi
[conda] torchsde                  0.2.5                    pypi_0    pypi
[conda] torchtriton               2.1.0+6e4932cda8           py310    pytorch-nightly
[conda] torchvision               0.17.0.dev20230912     py310_cu121    pytorch-nightly
[conda] vector-quantize-pytorch   1.7.1                    pypi_0    pypi

**Comment by mthrok** [comment]
Hi

Thanks for the report. https://github.com/pytorch/audio/pull/3624 should fix it.
