### ISSUE TITLE
Unexpected pts on audio streams of webm files

### ISSUE THREAD

**Issue by wylley** [pytorch/audio#3625]
### 🐛 Describe the bug

I was trying to get the size of chunks returned by StreamReader.stream() without having to parse all the options a user could input to the ffmpeg decoder by probing streams with chunks that contain a single frame, when I noticed an odd behavior.

When using the StreamReader to read chunks from an audio stream with a .webm video link, the pts returns unexpected values.
For example, on a video where the audio has a sampling rate of 48000, the pts of the chunks returned increases by a millisecond even though we expect it to increase by 1/48000th of a second.

```python
from torchaudio.io import StreamReader

stream_reader = StreamReader('http://upload.wikimedia.org/wikipedia/commons/transcoded/c/c0/Big_Buck_Bunny_4K.webm/Big_Buck_Bunny_4K.webm.2160p.vp9.webm')

#we can see that the audio has a sample rate of 48000.0
for i in range(stream_reader.num_src_streams):
  print(stream_reader.get_src_stream_info(i))

stream_reader.add_audio_stream(frames_per_chunk=1)

stream_generator = stream_reader.stream()

#but pts increases by 0.001
for i in range(10):
  chunks = next(stream_generator)
  print('-'*5 + str(i) + '-'*5)
  for chunk in chunks:
    print(f'pts: {chunk.pts}')
```
I only noticed this happening on .webm files, .mp4 work as expected.

### Versions

PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.27.4
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.120+-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
CPU family:                      6
Model:                           79
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        4399.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB (1 instance)
L1i cache:                       32 KiB (1 instance)
L2 cache:                        256 KiB (1 instance)
L3 cache:                        55 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchdata==0.6.1
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] Could not collect

**Comment by mthrok** [comment]
Can you set`buffer_chunk_size=-1` ?

`frames_per_chunk` only controls how many of frames to return to user code. It does not control how many samples it decode from the source. This is a constraint posed by the FFmpeg API.

When you set `frames_per_chunk=1` with default `buffer_chunk_size=3`, `StreamReader` stores 3 frames (== 1 [frame  / chunk] * 3 chunks) of the incoming samples and discard the rest. Usually, hundreds or thousands of samples are processed at a time.

**Comment by wylley** [comment]
Indeed when using ```buffer_chunk_size=-1``` I get a chunk of 960 frames for 0.02 seconds of audio which corresponds to the sampling rate. I'm guessing that ~960 frames is the minimum imposed by ffmpeg and making the behavior consistent with the one of .mp4 would require special handling of this case.

Thanks for the quick reply and clearing things up.
Also, could you please tell me if the ffmpeg API allows you to preview the shape of frames without having to decode them or parse the decoder options ? Probing by creating streams with a single frame per chunk  and then recreating them with a different chunk size so that they fit a memory budget seems inefficient.

**Comment by mthrok** [comment]
> I'm guessing that ~960 frames is the minimum imposed by ffmpeg and making the behavior consistent with the one of .mp4 would require special handling of this case.

This is a elaborated topic and I am not an expert on this matter, but I think this usually varies on how the original data is encoded, therefore knowing a format is not enough to estimate the packet size, and the packet size could change in the middle of stream. If you can control how the data source encode data, you might be able to ensure that packet size does not exceed some value.

 > Also, could you please tell me if the ffmpeg API allows you to preview the shape of frames without having to decode them or parse the decoder options ?

No, as far as I know, there is no such API. (though I don't know the entire API surface of FFmpeg)
And, in my understanding, the reason why it's not possible is because that's how media codecs are defined.

FYI: The way FFmpeg works internally is something like
1. parse the incoming byte stream until it figures out the container format and the stream formats. (this can consume arbitrary number of the stream, and buffers those data)
2. Initialize a demuxer, and decoders.
3. demuxer slices the incoming byte streams into packets  a chunk of audio samples encoded together
4. decoder decodes the packet, this is when we know how many samples are there in the packet.
5. repeat 3 &4

If the formats your application needs to deal with is limited to MP4 and WEBM, then you might narrow down something more and create a better heuristics.

**Comment by wylley** [comment]
I understand, thanks for the explanations they were of great help !
