### ISSUE TITLE
GIL-free In-Memory Buffer Reading for torchaudio.io.StreamReader

### ISSUE THREAD

**Issue by RuneBlaze** [pytorch/audio#3640]
### 🚀 The feature

`torchaudio.io.StreamReader` can benefit from having a way to read from an in-memory buffer while remaining *GIL-free* when reading from that buffer.

### Motivation, pitch

In the versions prior to 2.1, `StreamReader` could read from `uint8` tensors without acquiring the GIL. Since version 2.0, this feature has been deprecated (by #3086) and in version 2.1 removed. The suggested alternative, Python `io.BytesIO` buffers need to be `read` (relevant code [here](https://github.com/pytorch/audio/blob/e3b11a8e5ab41201cbe0e54fdc550f3ce5b78af3/torchaudio/csrc/ffmpeg/pybind/pybind.cpp#L119)), which will then force the holding of the GIL. Using `BytesIO`, if N threads decodes from N different buffers, only one thread can read a buffer at a time. Ideally N threads should all be able to read from their separate buffers.

Video decoding is trivially parallelizable so allowing thread-level parallelization can really help. Decoding from memory saves me from data trips when writing/reading from disk.

### Alternatives

I can try subclassing [StreamReaderCustomIO](https://github.com/pytorch/audio/blob/e3b11a8e5ab41201cbe0e54fdc550f3ce5b78af3/torchaudio/csrc/ffmpeg/stream_reader/stream_reader.h#L366) in a C++ extension to allow reading directly from `bytes` or from `torch.uint8` tensors. However, I am a bit worried about creating a C++ extension on-top-of torchaudio. If this is the recommended path, are there foreseeable challenges or concerns related to binding with torchaudio in a torch native extension?

**Comment by mthrok** [comment]
Hi @RuneBlaze 

Thanks for the suggestion. I was not aware of the GIL contention resulting from the use of `io.BytesIO`. I think this is a reasonable addition.
Our preference now is to minimize the use of torch from C++, so `bytes` is the way to go.
With the cleaned up StreamReaderCustomIO interface, it should be straightforward to add this back.
I will add this to my backlog, but since you have some familiarity to C++, it would be great and welcomed if you can make a PR.

**Comment by mthrok** [comment]
Actually, I could cook up the bytes support rather simply.

https://github.com/mthrok/audio/commit/e4e192a03402a48fc09c729ee15912c8a97dd9c8

I will make a PR later.

**Comment by mthrok** [comment]
Addressed by #3642

**Comment by RuneBlaze** [comment]
Thanks! It is incredible how fast this feature gets implemented 😂
