### ISSUE TITLE
Request to update torchaudio-torch mapping table

### ISSUE THREAD

**Issue by jingxu10** [pytorch/audio#3689]
### 📚 The doc issue

2.1 had been released, but the matrix only shows till 2.0.1.
Request to update the matrix.
![image](https://github.com/pytorch/pytorch/assets/25193121/a0a015e0-c4c8-49b3-bf7f-bd7661c1cb40)

**Comment by tmbrantley** [comment]
> This won't be part of the docathon effort and should be opened against the pytorch/audio repo.

Thank you for the clarification, I was wondering why I wasn't able to locate the corresponding doc file in pytorch/pytorch lol

**Comment by mthrok** [comment]
Hi

https://github.com/pytorch/audio/pull/3690 will handle it. BTW It might be better to consolidate this into somewhere common, as torchvision/torchaudio maintain separately.

**Comment by mthrok** [comment]
Updated https://pytorch.org/audio/stable/installation.html#compatibility-matrix
