### ISSUE TITLE
torchaudio build fails due to torchconfig cmake file missing but file is there

### ISSUE THREAD

**Issue by jdgh000** [pytorch/audio#3696]
### 🐛 Describe the bug

Build error shows can not find torch-config.cmake or TorchConfig.cmake but as you can below, file is there and pointed by during build

```
cmake -DCMAKE_PREFIX_PATH=../../pytorch/build ..
-- The C compiler identification is GNU 11.4.1
-- The CXX compiler identification is GNU 11.4.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at cmake/TorchAudioHelper.cmake:1 (find_package):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:93 (include)

-- Configuring incomplete, errors occurred!
See also "/root/gg/git/audio/build/CMakeFiles/CMakeOutput.log".
[root@localhost build]# find ../.. -name TorchConfig.cmake
../../pytorch/torch/share/cmake/Torch/TorchConfig.cmake
../../pytorch/build/TorchConfig.cmake
[root@localhost build]#

```

### Versions

ersions of relevant libraries:
[pip3] numpy==1.26.1
[pip3] optree==0.10.0
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==2.2.0a0+gitef49f61
[pip3] torchvision==0.17.0a0+15c166a

**Comment by mthrok** [comment]
Need to pass the path from the built/installed PyTorch, which is `<install_prefix>/torch/share/cmake`.
You are passing the path to the build directory.
Please use `torch.utils.cmake_prefix_path` to fetch the correct one.

**Comment by jdgh000** [comment]
i did but it still causes another caffe2 error. I am not sure if this is due to caffe2 not installed but i had torch built and installed successfully onto system. 

 cmake -DCMAKE_PREFIX_PATH=../../pytorch/torch/share/cmake ..
CMake Error at /root/gg/git/pytorch/build/Caffe2Config.cmake:9 (include):
  include could not find requested file:

    /root/gg/git/pytorch/build/public/utils.cmake
Call Stack (most recent call first):
  /root/gg/git/pytorch/build/TorchConfig.cmake:68 (find_package)
  cmake/TorchAudioHelper.cmake:1 (find_package)
  CMakeLists.txt:93 (include)


CMake Error at /root/gg/git/pytorch/build/Caffe2Config.cmake:74 (include):
  include could not find requested file:

    /root/gg/git/pytorch/build/public/LoadHIP.cmake
Call Stack (most recent call first):
  /root/gg/git/pytorch/build/TorchConfig.cmake:68 (find_package)
  cmake/TorchAudioHelper.cmake:1 (find_package)
  CMakeLists.txt:93 (include)


CMake Error at /root/gg/git/pytorch/build/Caffe2Config.cmake:109 (include):
  include could not find requested file:

    /root/gg/git/pytorch/build/public/mkldnn.cmake
Call Stack (most recent call first):
  /root/gg/git/pytorch/build/TorchConfig.cmake:68 (find_package)
  cmake/TorchAudioHelper.cmake:1 (find_package)
  CMakeLists.txt:93 (include)


CMake Error at /root/gg/git/pytorch/build/Caffe2Config.cmake:113 (include):
  include could not find requested file:

    /root/gg/git/pytorch/build/Caffe2Targets.cmake
Call Stack (most recent call first):
  /root/gg/git/pytorch/build/TorchConfig.cmake:68 (find_package)
  cmake/TorchAudioHelper.cmake:1 (find_package)
  CMakeLists.txt:93 (include)


CMake Error at /root/gg/git/pytorch/build/TorchConfig.cmake:182 (set_target_properties):
  set_target_properties Can not find target to add properties to: torch
Call Stack (most recent call first):
  cmake/TorchAudioHelper.cmake:1 (find_package)
  CMakeLists.txt:93 (include)


CMake Error at /root/gg/git/pytorch/build/TorchConfig.cmake:187 (set_property):
  set_property could not find TARGET torch.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  cmake/TorchAudioHelper.cmake:1 (find_package)
  CMakeLists.txt:93 (include)


CMake Error at cmake/TorchAudioHelper.cmake:11 (get_target_property):
  get_target_property() called with non-existent target "torch_cpu".
Call Stack (most recent call first):
  CMakeLists.txt:93 (include)


-- Found ccache
-- Configuring incomplete, errors occurred!
See also "/root/gg/git/audio/build/CMakeFiles/CMakeOutput.log".
[root@localhost build]#
