### ISSUE TITLE
Termux patch for default APT version of audio - for relative file paths, tilde (~) expansion not working in filepath for torchaudio.load()

### ISSUE THREAD

**Issue by Manamama** [pytorch/audio#3802]
### Description
When using `torchaudio.load()` with a filepath that includes a tilde (`~`) to represent the home directory, the function fails to load the audio file. This is because the tilde is not being expanded to the full home directory path.

Quick patch for the impatient among us:
`sed -i '251i\        filepath = os.path.expanduser(filepath)' /data/data/com.termux/files/usr/lib/python3.11/site-packages/torchaudio/backend/sox_io_backend.py`
- only for this particular version, see below! 

### Steps to Reproduce
1. Use a filepath with a tilde in the `torchaudio.load()` function.
2. Observe that the function fails to load the audio file.

### Error Message
```
RuntimeError: Failed to load audio from ~/downloads/Sample_shop_1.wav
```

### Expected Behavior
The `torchaudio.load()` function should expand the tilde to the full home directory path and successfully load the audio file.

### Actual Behavior
The function fails to load the audio file, treating the tilde as a literal character in the filepath.

### Proposed Fix
In the `load()` function in `sox_io_backend.py`, add tilde expansion before the filepath is processed:

```python
if not torch.jit.is_scripting():
    if hasattr(filepath, "read"):
        # ... (existing code for file-like objects)
    filepath = os.path.expanduser(filepath)
filepath = os.fspath(filepath)
```

This change ensures that any tilde in the filepath is expanded to the full home directory path before being processed by `os.fspath(filepath)` and `torch.ops.torchaudio.sox_io_load_audio_file`.

### Additional Context
This issue was encountered while using the TTS library, which internally uses `torchaudio.load()`. The fix has been tested and confirmed to resolve the issue in the Termux environment.

### Possible Impact
This change would improve the usability of `torchaudio.load()` for users who rely on tilde expansion in filepaths, especially in Unix-like environments. It maintains consistency with common Unix path handling conventions.

NB. Update of Torch to `Successfully installed torchaudio-2.3.1` fails for another reason, this one https://github.com/pytorch/audio/issues/18, but it is another issue 

### Environment
- torchaudio version: 2.0.1
- PyTorch version: 2.1.2
- Operating System: Android (Termux)
- Python version: 3.11
- System information: Linux localhost 4.14.186+ #1 SMP PREEMPT Thu Mar 17 16:28:22 CST 2022 aarch64 Android

**Comment by f0k** [comment]
This is completely normal behavior in Python:
```
from pathlib import Path
Path('~').exists()  # False
Path('~').expanduser().exists()  # True
import os
os.listdir('~')  # FileNotFoundError
```
Paths should be expanded outside if needed.

**Comment by Manamama** [comment]
Ah, so it is not a bug but a feature? I vaguely remember it was caused by some `tts [smth] ~/downloads/Sample_shop_1.wav ... [smth] [smth] ` . (After my hacky fix I forgot about it by now.)

**Comment by f0k** [comment]
If you call a script from the command line, then usually the shell would expand the tilde, unless you specifically prevent so by using quotation marks. Try this:
```bash
python3 -c "import sys; print(sys.argv)" ~ '~'
```
These are the conventions :shrug: Given how they are, the solution is not to add `expanduser` to any Python function out there which accept paths.

**Comment by Manamama** [comment]
I know what you mean:
```
~ $ python3 -c "import sys; print(sys.argv)" ~ '~'
['-c', '/data/data/com.termux/files/home', '~']
~ $
```
A  literal string, not substituted. 
It was caused by some 'the shell would not expand the tilde' (before passing it on to some .py pipelines)  case, despite no quote marks, but I do not remember the context by now, so let us close it.

**Comment by Manamama** [comment]
.
