### ISSUE TITLE
Ceiling of integer division (Python 2 compatibility)

### ISSUE THREAD

**Issue by kostmo** [pytorch/audio#381]
In the `_compute_nccf` function, there are two computations which take `math.ceil` of the result of an integer division.  It seems that either the `math.ceil` function is unnecessary, or the division should be performed on floating point arguments (which in Python 2 is not necessarily the case with the single-slash (`/`) division operator.

[Here](https://github.com/pytorch/audio/blob/805d7922e0128c8a160e4f828cda258e615bb4d3/torchaudio/functional.py#L1096):

    lags = math.ceil(sample_rate / freq_low) 

and [here](https://github.com/pytorch/audio/blob/805d7922e0128c8a160e4f828cda258e615bb4d3/torchaudio/functional.py#L1101):

    num_of_frames = math.ceil(waveform_length / frame_size)

and [here](https://github.com/pytorch/audio/blob/805d7922e0128c8a160e4f828cda258e615bb4d3/torchaudio/functional.py#L1150):

    lag_min = math.ceil(sample_rate / freq_high)

with this last example, the "empirical calibration offset" in the subsequent code makes me wonder, since the output of `math.ceil` will generally be `1` higher with floating point arguments than integer arguments:

    # Add back minimal lag
    indices += lag_min
    # Add 1 empirical calibration offset
    indices += 1

**Comment by vincentqb** [comment]
Can you clarify which command in `_compute_nccf` would behave differently in python 2?

PS. [Here](https://github.com/vincentqb/audio-tutorial/blob/master/pitch.ipynb)'s a notebook to experiment with this.

**Comment by kostmo** [comment]
OK, I have disproved my theory of the "empirical calibration offset" being obsolete with Python 3/floating-point-division-inside-ceil.  Removing the `+1` calibration offset, even with floating point division, causes the tests to fail.

**Comment by vincentqb** [comment]
Thanks for investigating! Based on your response, I will close this issue.
