### ISSUE TITLE
Is batching-for-transform done?

### ISSUE THREAD

**Issue by keunwoochoi** [pytorch/audio#383]
Hi, I assumed it's done by #337 (which is great!), but at least `transforms.MFCC` is not. What's the current state?
Also related, the docstrings of `transforms` need to be updated. The current version reads like it only deals with a single audio signal.

**Comment by vincentqb** [comment]
Thanks for pointing this out. The intention is to have all supported, and so MFCC should indeed be updated. Let me know if you notice another one that doesn't support it. 

Which docstring is not updated?

**Comment by keunwoochoi** [comment]
Sorry I didn't make it clear - The docstrings of `functionals` are updated for example
```
waveform (torch.Tensor): Tensor of audio of dimension (..., channel, time)
```
, but the corresponding `transforms` are not, for example, [here](https://github.com/pytorch/audio/blob/master/torchaudio/transforms.py#L65),
```
waveform (torch.Tensor): Tensor of audio of dimension (channel, time)
```

**Comment by keunwoochoi** [comment]
how could you fix everything in one day? 👍👍
