### ISSUE TITLE
'Power' in spectrogram

### ISSUE THREAD

**Issue by keunwoochoi** [pytorch/audio#389]
In `functional.spectrogram`, the docstring says
```
        power (int): Exponent for the magnitude spectrogram,
            (must be > 0) e.g., 1 for energy, 2 for power, etc.
            If None, then the complex spectrum is returned instead.
```
which is implemented as ([link](https://github.com/pytorch/audio/blob/master/torchaudio/functional.py#L268))
```python
    if power is not None:
        spec_f = spec_f.pow(power).sum(-1)  # get power of "complex" tensor
```

If I'm not missing something, I think the right implementation is i) convert complex to magnitude ii) then apply the power on it, i.e.,
```python
    if power is not None:
        magnitude_spec = torch.sqrt(spec_f.pow(2).sum(-1))  # i)
        return magnitude_spec.pow(power)  # ii)
```

Or equivalently, using `complex_norm`..
```python
    if power is not None:
        return complex_norm(spec_f, power=power)
```

Any thought?

**Comment by vincentqb** [comment]
`Spectrogram` is meant to be consistent with librosa, e.g. [docstring](https://librosa.github.io/librosa/generated/librosa.feature.melspectrogram.html#librosa.feature.melspectrogram), [internal test](https://github.com/pytorch/audio/blob/master/test/test_transforms.py#L223). However, the librosa implementation indeed uses `numpy.abs` which is our `complex_norm` as you mention.

Thanks for reporting this. I've opened #392 to align with librosa.

**Comment by keunwoochoi** [comment]
thanks!
