### ISSUE TITLE
TorchScript format

### ISSUE THREAD

**Issue by DenisYarullin** [pytorch/audio#405]
If I have pytorch model which use torchaudio. Then I want to save model to TorchScript. Can I load that TorchScript model in C++?

**Comment by vincentqb** [comment]
Yes, you can, see [tutorial](https://pytorch.org/tutorials/advanced/cpp_export.html) :) I'll close this issue, but if this doesn't answer it, please feel free to re-open or use the [forum](https://discuss.pytorch.org/).
