### ISSUE TITLE
Adding LJ Speech dataset

### ISSUE THREAD

**Issue by taras-sereda** [pytorch/audio#429]
## 🚀 Feature
Adding publicly available [LJ Speech](https://keithito.com/LJ-Speech-Dataset/) dataset, widely used for TTS tasks.

## Motivation

It will be convenient for researchers in speech synthesis (and speech processing in general) to get directly to model development and spend less time on building custom pipelines for loading datasets. Also LJ Speech is considered as a benchmark dataset and many papers in speech synthesis report their performance scores based on it.

## Additional context

I'd like to contribute by adding LJ Speech dataset to torchaudio. What repository owners thing of having it in the library?

**Comment by vincentqb** [comment]
Yes, we would welcome this dataset. In general, we try to keep the available datasets to the most popular and requested. 

Please keep in mind that we keep the structure of the code very close to the ones currently available, see for instance [librispeech](https://github.com/pytorch/audio/blob/master/torchaudio/datasets/librispeech.py).
