### ISSUE TITLE
module 'torch' has no attribute 'hann_window' when importing torchaudio

### ISSUE THREAD

**Issue by Aditay** [pytorch/audio#43]
I have installed torchaudio on top of pytorch 0.3.1 for python3.5.
But When I try to import torchaudioI get the following error:

AttributeError: module 'torch' has no attribute 'hann_window'

Please help.

**Comment by soumith** [comment]
torchaudio now requires `torch >= 0.4`. I'll update torchaudio's requirements to reflect that.

**Comment by Aditay** [comment]
@soumith You mean pytorch >= 0.4 ?

**Comment by soumith** [comment]
yes, i meant `torch` in the `pip install torch` sense.
