### ISSUE TITLE
Resample Batch of Waveforms 

### ISSUE THREAD

**Issue by ahmed-fau** [pytorch/audio#431]
Hello,
I would like to use the `Resample` class for up/down sampling the learned features during the training. Exactly the same way as `F.interpolate`. However, the batch dimension is not accepted by the `Resample` class so that I need to reshape the tensor to have only the channel and temporal dimensions.

Any help on how to resample a batch of waveforms/multi-channel features without any need to reshape?

Thanks in advance.

**Comment by vincentqb** [comment]
Thanks for pointing this out: I've opened a pull request to address this.

**Comment by ahmed-fau** [comment]
Thanks, @vincentqb  for taking care of this. I should then let you know that the same behavior occurs when using other transform modules like `Spectrogram` and `MelSpectrogram`. The modules cannot accept three-dimensional tensors (batch, channel, time). Only two-dimensional tensors (channel, time) are supported so that the batch dimension is dealt as the cannel one, while the remaining dimensions should be flattened in order to work.

**Comment by vincentqb** [comment]
Can you provide an example for these? Which version are you using? These should support batching since #391.

**Comment by ahmed-fau** [comment]
> Can you provide an example for these? Which version are you using? These should support batching since #391.

Sorry for the confusion. I tried this on a previous version. Batching for spectrograms works fine with version 0.4
