### ISSUE TITLE
Adding Speech Command Dataset

### ISSUE THREAD

**Issue by tomassosorio** [pytorch/audio#434]
## 🚀 Feature
Adding to the possible datasets to use the Speech Command Dataset
https://arxiv.org/abs/1804.03209

## Motivation
As a beginner steps into audio manipulation using the Speech Command Dataset is a must since it is simple and allows us to use it as a classification problem or end-to-end Automatic Speech Recognition.

## Pitch
Allowing beginner to have a starting point to a dataset that can allow the training of interesting models is an easy way.

**Comment by vincentqb** [comment]
Since this dataset is very recent, I am not inclined to consider adding it at this time. Do you have references for such successful model? Have you considered LibriSpeech or CommonVoice?

**Comment by tomassosorio** [comment]
It is a dataset that would be an easy start for a beginner to start touching with ASR since it does not necessitate many moving parts and does not need that many parameters to a model to have good performances with.

Sure, but if you want to detect, a phone number or something similar this dataset would be much simpler than training with Librispeech or CommonVoice.

repo using this dataset: https://github.com/LearnedVector/Wav2Letter

**Comment by vincentqb** [comment]
Nice example, and good to see that the dataset appeared on [kaggle](https://www.kaggle.com/c/tensorflow-speech-recognition-challenge/data) :) Alright, we would welcome this dataset. In general, we try to keep the available datasets to the most popular and requested. Would you be interested in opening a pull request for it?

Please keep in mind that we keep the structure of the code very close to the ones currently available, see for instance [librispeech](https://github.com/pytorch/audio/blob/master/torchaudio/datasets/librispeech.py).

**Comment by tomassosorio** [comment]
Yes, I am totally interested in doing the PR! Thanks!!

Sure, I will take into account that!
