### ISSUE TITLE
No matching distribution found for torchaudio

### ISSUE THREAD

**Issue by dachosen1** [pytorch/audio#436]
## ❓ Questions and Help

I currently have PyTorch installed, I tried to install torchaudio and got the following error. 

```
pip install torchaudio -f https://download.pytorch.org/whl/torch_stable.html
```

```
 Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torchaudio
  Could not find a version that satisfies the requirement torchaudio (from versions: )
No matching distribution found for torchaudio
```

 - PyTorch Version (e.g., 1.0): 1.4
 - OS (e.g., Linux):  Window 
 - How you installed PyTorch (`conda`, `pip`, source): pip 
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration:  NVIDIA GeForce GTX 1050
 - Any other relevant information:

## Additional context
I have numpy, future  sox, and six installed

**Comment by haideraltahan** [comment]
Windows is currently not supported (#425).

**Comment by dachosen1** [comment]
I see. Thanks
