### ISSUE TITLE
MEL2 gives incorrect output for n_mels=80

### ISSUE THREAD

**Issue by pfriesch** [pytorch/audio#44]
The MEL2 transform seems to work fine for `n_mels=40`, howver `n_mels=80` gives artifacts.
#### `n_mels=40`
![mel_40](https://user-images.githubusercontent.com/3247619/39570632-3112e462-4ec9-11e8-85ab-d55283b9b869.png)
#### `n_mels=80`
![mel_80](https://user-images.githubusercontent.com/3247619/39570633-312e191c-4ec9-11e8-972a-0ae1780ebb7d.png)

 ```python
import torchaudio
from torchaudio import transforms
import matplotlib.pyplot as plt


def spect_loader(path):
    y, sr = torchaudio.load(path, normalization=True)
    # n_mels = 40
    n_mels = 80

    to_melspec = transforms.Compose([
        transforms.LC2CL(),
        transforms.MEL2(sr, n_mels=n_mels)
    ])
    melspec = to_melspec(y)
    return melspec


if __name__ == '__main__':
    mel = spect_loader("00f0204f_nohash_0.wav")
    plt.matshow(mel[0].numpy().T)
    plt.colorbar()
    plt.savefig("mel.png")
    plt.clf()
    print(mel.shape)

```

**Comment by Rikorose** [comment]
This is expected behavior, there is no fft bin for this mel band. See [here](https://electronics.stackexchange.com/questions/12407/what-is-the-relation-between-fft-length-and-frequency-resolution#12412).

You could for instance increase the window size, eg. `ws=1024`.
