### ISSUE TITLE
Adding Module Models

### ISSUE THREAD

**Issue by tomassosorio** [pytorch/audio#446]
## 🚀 Feature
Similar to [torchvision](https://pytorch.org/docs/stable/torchvision/models.html) would be interesting to have the architecture of the most important models available, such as Wav2Letter, DeepSpeech, DeepSpeech2 between others... 

## Motivation
When trying to train a model it is already available most features needed such as Datasets, Data Transformations, however it is not available any architecture of a known model.

## Pitch
Adding a module with the architecture of the most known models.

**Comment by vincentqb** [comment]
This is a good idea. Would you like to contribute some?

**Comment by tomassosorio** [comment]
Sure!

I will inspire into torchvision structure and add at first Wav2Letter.

At the time I cannot offer the model with the trained weights, but I can talk with my company to see if we could offer this to torchaudio in the future.

**Comment by vincentqb** [comment]
Let's start with just the model class, untrained. Hosting trained models (and datasets) is a separate discussion :)

**Comment by vincentqb** [comment]
@tomassosorio -- thanks again for merging wav2letter! Which other ones do you believe would be a good idea to request help to implement?

- [x] Wav2Letter
- [ ] DeepSpeech
- [ ] DeepSpeech2

**Comment by tomassosorio** [comment]
Yes, I fell both of them would be good alternatives, such as the [Wav2Letter++](https://github.com/facebookresearch/wav2letter/tree/master/recipes/models), in this link there is also some other models that could be interesting to implement :)

**Comment by koukyo1994** [comment]
How about [PANNs](https://github.com/qiuqiangkong/audioset_tagging_cnn)? It has rich collections of pre-trained audio models.

**Comment by limazix** [comment]
Hi guys, I'd like to help with this task. Where can I start?

**Comment by Edresson** [comment]
@vincentqb  I think it would be interesting to implement [Jasper](https://arxiv.org/pdf/1904.03288.pdf) too, as it reported state of the art on LibreSpeech :). 

It is available on [OpenSeq2Seq](https://github.com/NVIDIA/OpenSeq2Seq)

What do you think about converting the checkpoints of these models to pytorch and using them in the initialization of model weights?

**Comment by vincentqb** [comment]
> @vincentqb I think it would be interesting to implement [Jasper](https://arxiv.org/pdf/1904.03288.pdf) too, as it reported state of the art on LibreSpeech :).
> 
> It is available on [OpenSeq2Seq](https://github.com/NVIDIA/OpenSeq2Seq)

Thanks for suggesting jasper here, and [there](https://github.com/pytorch/audio/issues/913#issuecomment-700059647) :) Do ping me when you open a pull request for it :)

> What do you think about converting the checkpoints of these models to pytorch and using them in the initialization of model weights?

We do plan on offering some pre-trained models for those we offer. Is that what you mean?

**Comment by vincentqb** [comment]
@Edresson -- thanks also for suggestion [wav2vec](https://github.com/pytorch/audio/issues/913#issuecomment-700075153) -- it is on our radar, and we would love to have example pipeline such as [wav2letter](https://github.com/pytorch/audio/tree/master/examples/pipeline_wav2letter) for it :) we can talk more about this if this is of interest to you

**Comment by Edresson** [comment]
> > @vincentqb I think it would be interesting to implement [Jasper](https://arxiv.org/pdf/1904.03288.pdf) too, as it reported state of the art on LibreSpeech :).
> > It is available on [OpenSeq2Seq](https://github.com/NVIDIA/OpenSeq2Seq)
> 
> Thanks for suggesting jasper here, and [there](https://github.com/pytorch/audio/issues/913#issuecomment-700059647) :) Do ping me when you open a pull request for it :)
> 
> > What do you think about converting the checkpoints of these models to pytorch and using them in the initialization of model weights?
> 
> We do plan on offering some pre-trained models for those we offer. Is that what you mean?


Yes, I thought about maybe converting the openseq2seq checkpoints. But training and providing a checkpoint may be a better option.

**Comment by discort** [comment]
@vincentqb 

I'd like to add vanilla deepspeech model

**Comment by mthrok** [comment]
Closing the issue as torchaudio now has models submodule.

For adding a new model, please propose it by opening a new issue.
