### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mpariente** [pytorch/audio#458]
First, thanks for the package, that's pretty cool !

What are the current priorities? 
Is making a backpropagable complex tensor on of them? 

I'm starting to develop support for complex numbers in [asteroid](https://github.com/mpariente/asteroid) where I have a different convention for complex numbers. Depending of the goals of torchaudio, I would completely rely on your code, or I'd keep on in the current way. 

Thanks

**Comment by vincentqb** [comment]
Hi! Thanks for asking :) Yes, we are currently working on extending complex number support, see [here](https://github.com/pytorch/pytorch/issues/33152) on pytorch core repository to track the current work. 

An item that is more specific to torchaudio is the replacement of sox, see [here](https://github.com/pytorch/audio/issues/260). Are there specific things you would like to see happens or even contribute?

Our general aim for torchaudio is to apply PyTorch to the audio domain, and follow the same philosophy as PyTorch of providing strong GPU acceleration, having a focus on trainable features through the autograd system, and having consistent style (tensor names and dimension names).

**Comment by mpariente** [comment]
Thanks for your answer. 

> Hi! Thanks for asking :) Yes, we are currently working on extending complex number support, see [here](https://github.com/pytorch/pytorch/issues/33152) on pytorch core repository to track the current work.
> 
Thanks for the pointer, I'll be watching closely.

About sox, this is very ambitious and it sounds very nice ! :-)

**Comment by vincentqb** [comment]
Great! I'll close this issue, but please feel free to re-open if you want to continue the discussion :)
