### ISSUE TITLE
Python 2 Deprecated

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#477]
The 0.4.0 release of torchaudio was the last one supporting python 2, and master no longer officially supports python 2. We're looking to strip the code of python 2 references.
- [x] No longer use package `six` and `backports` for cross-compatibility
- [x] Convert to inline type hinting
- [x] No `__future__` import
- [x] ~~Change string formatting style~~
- [ ] Remove mention of python 2.7 in `setup.py`
- [x] Remove older code path in [_check_module_exists](https://github.com/pytorch/audio/blob/master/torchaudio/common_utils.py#L26) and no longer need to check python 3 is not used [at the end of the file](https://github.com/pytorch/audio/blob/master/torchaudio/common_utils.py#L38)
- [x] Update `unicode_decoder` to python 3 only, [here](https://github.com/pytorch/audio/blob/master/torchaudio/datasets/utils.py#L22).
- [x] Replace calls to [makedir_exist_ok](https://github.com/pytorch/audio/blob/master/torchaudio/datasets/utils.py#L51) to `os.makedirs(.., exist_ok=True)`

**Comment by tomassosorio** [comment]
I can take care of type hinting tomorrow :)

**Comment by james-mchugh** [comment]
Do you need an extra hand with this or is everything covered?

**Comment by vincentqb** [comment]
For completeness, I did a quick grep through files, and I see the following reference to python 2. 

```
setup.py:        "Programming Language :: Python :: 2.7",
test/test_librosa_compatibility.py:    # Using a decorator here causes parametrize to fail on Python 2
torchaudio/common_utils.py:    if not PY3:  # Python 2
torchaudio/common_utils.py:    elif not PY34:  # Python [3, 3.4)
torchaudio/common_utils.py:    else:  # Python >= 3.4
torchaudio/common_utils.py:# On Py2, importing librosa 0.6.1 triggers a TypeError (if using newest joblib)
torchaudio/common_utils.py:# TODO: allow Py2 when librosa 0.6.2 releases
torchaudio/datasets/utils.py:    r"""Since the standard csv library does not handle unicode in Python 2, we need a wrapper.
torchaudio/datasets/utils.py:    Python2 support for os.makedirs(.., exist_ok=True)
torchaudio/datasets/utils.py:    # Required for Python 2.7 compatibility
```

In here, also a reference to python less than 3.5 which is no longer supported on master, see [here](https://github.com/pytorch/audio/pull/538#issuecomment-613468667).

**Comment by mthrok** [comment]
https://github.com/pytorch/audio/pull/625 addressed `setup.py`.

**Comment by vincentqb** [comment]
Not [this one](https://github.com/pytorch/audio/blob/master/setup.py#L77) :)
