### ISSUE TITLE
Add checksum to datasets

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#492]
All datasets that download an archive should have a checksum when downloading from the default address, see [comment](https://github.com/pytorch/audio/issues/483#issuecomment-607487378).

md5 would be enough for capturing obvious archive corruption.

- [x] VCTK: `45e8dede780278ef5541fde0b82ac292`
- [x] YesNo:
- [x] LibriSpeech:
- [x] SpeechCommands:
- [x] LJSpeech:
- [ ] CommonVoice:

**Comment by tomassosorio** [comment]
speech_commands_v0.02 -> `6b74f3901214cb2c2934e98196829835`
