### ISSUE TITLE
Flake8 should not ignore F821 and F841

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#494]
The current flake8 configuration is too relaxed. Especially F821 (undefined name) and F841 (local variable is assigned to but never used).

Ignoring F841 caused accidental introductions of unused arguments in function signatures (like reported in https://github.com/pytorch/audio/pull/482#issue-396361603) and fixing this involves breaking backward compatibility. F841 should never be ignored.

Similarly F821 should not be ignored either, but this one is there so that comment type annotation to work. Once the type annotation is converted to inline version [as part of Python2 removal](#477 ), this can be removed and we should enforce F821 too.

```
$ flake8 torchaudio
torchaudio/functional.py:467:5: F841 local variable 'freqs' is assigned to but never used
torchaudio/functional.py:714:5: F841 local variable 'dim' is assigned to but never used
torchaudio/functional.py:826:5: F841 local variable 'A' is assigned to but never used
torchaudio/functional.py:828:5: F841 local variable 'mult' is assigned to but never used
torchaudio/functional.py:859:5: F841 local variable 'A' is assigned to but never used
torchaudio/functional.py:861:5: F841 local variable 'mult' is assigned to but never used
torchaudio/functional.py:1033:5: F841 local variable 'alpha' is assigned to but never used
torchaudio/compliance/kaldi.py:653:5: F821 undefined name 'Tuple'
torchaudio/compliance/kaldi.py:653:5: F821 undefined name 'Tensor'
torchaudio/compliance/kaldi.py:653:5: F821 undefined name 'Tensor'
torchaudio/compliance/kaldi.py:784:5: F821 undefined name 'Tensor'
torchaudio/compliance/kaldi.py:784:5: F821 undefined name 'Tensor'
```

**Comment by vincentqb** [comment]
For reference (only), pytorch has both of them, see [here](https://github.com/pytorch/pytorch/blob/master/.flake8).

**Comment by vincentqb** [comment]
We should also catch the ones picked up [internally](https://our.internmc.facebook.com/intern/diff/D20011052/).
