### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by sshkhr** [pytorch/audio#50]
Now that PyTorch 0.4.0 supports Windows does torchaudio support Windows ? If yes could the installation instructions for the dependencies for Windows be added to the README. Thanks

**Comment by iariav** [comment]
+1 for that request please

**Comment by JiveyGuy** [comment]
This would be VERY VERY much appreciated.

**Comment by soumith** [comment]
@JiveyGuy the library shouldn't need the gcc compiler to be installed.

**Comment by soumith** [comment]
let me quickly check. @goldsborough @peterjc123 do cpp-extensions work on Windows?

**Comment by goldsborough** [comment]
Yes @peterjc123 made it work

**Comment by peterjc123** [comment]
@soumith I guess the problem is on libsox. According to this [post](https://sourceforge.net/p/sox/mailman/message/32638200/), it seems that building libsox as a static library is broken. As for cpp-extensions, it should no problem for that.

**Comment by peterjc123** [comment]
@soumith Now I tried to compile it for x64, but it seems that there's some inline assembly code in `flac`, a dependency of `libsox`, which is prohibited by MSVC. Is it possible that we change to another one that has better support for Windows?

**Comment by soumith** [comment]
@peterjc123 isn't it optional dependency of `libsox`?

> Is it possible that we change to another one that has better support for Windows?

I couldn't find any good ones.

**Comment by peterjc123** [comment]
Oh, what a sad story. I'll try to build without `flac`, but I guess it can hardly work on Windows as a static library.

**Comment by vincentqb** [comment]
For reference: pytorch/pytorch#24859

**Comment by vincentqb** [comment]
> I guess the problem is on libsox. According to this [post](https://sourceforge.net/p/sox/mailman/message/32638200/), it seems that building libsox as a static library is broken on Windows. As for cpp-extensions, it should be no problem for that.

@peterjc123 -- Following #355, torchaudio now loads sox lazily only when used, and the backend can be switched to libsndfile. Would that help building a version of torchaudio without sox and relying only on libsndfile instead?

**Comment by peterjc123** [comment]
I'll try when I have time.

**Comment by vincentqb** [comment]
For reference pytorch/pytorch#24859
