### ISSUE TITLE
tag for torch==0.3.X

### ISSUE THREAD

**Issue by miguelvr** [pytorch/audio#51]
I'm trying to install a repo that still uses `torchaudio` as a dependency and since the new pytorch 0.4 update, it's not possible to do a clean install from a new user point of view.

I guess I won't be the only one having this problem. Is it possible to make a tag on the last commit compatible with torch v0.3?

Thanks,
Miguel

**Comment by mit2nil** [comment]
Ran into same error. Can be worked around for now by switching to commit https://github.com/pytorch/audio/commit/0fe0305a54d84161008d84492268d279279fb3bb

`git checkout 0fe0305a54d84161008d84492268d279279fb3bb` before doing `python setup.py install`

This is purely based on the fact that pytorch 0.4.0 was released on April 24th (https://github.com/pytorch/pytorch/releases). This is the last commit before April 24th on torch audio.

**Comment by cpuhrsch** [comment]
@miguelvr - Is this issue still current? Based on the comments and due to our recent releases I am assuming it is not and am closing it for now. Please feel encouraged to reopen this issue at any point, if this is not the case.
