### ISSUE TITLE
Making test code device aware.

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#515]
Currently, test code does not have a standard way to handle device, which led to CUDA tests added disorganized ways, such as [1](https://github.com/pytorch/audio/blob/5f5df1d649de8504c68ec532195ab1ba3fb54680/test/test_functional_filtering.py#L36-L41), [2](https://github.com/pytorch/audio/blob/5f5df1d649de8504c68ec532195ab1ba3fb54680/test/test_functional_filtering.py#L90-L99) and [3](https://github.com/pytorch/audio/blob/5f5df1d649de8504c68ec532195ab1ba3fb54680/test/test_torchscript_consistency.py#L311-L331). 
Also it is worth noting that **Travis CI is not running any of CUDA test**. [See here, search for `test_lfilter_cuda`](https://travis-ci.org/github/pytorch/audio/jobs/671779349).

We should have a standard way to add CUDA test.

FYI: PyTorch has [a mechanism to instantiate test class for different devices at runtime](https://github.com/pytorch/pytorch/blob/4ef383d5db38c5a837093089fe50770d132cc47c/test/test_torch.py#L5298).

**Comment by mthrok** [comment]
I also noticed that in [1](https://github.com/pytorch/audio/blob/master/test/test_functional_filtering.py#L36-L41), the test result looks like it passes when it was actually skipped.

**Comment by vincentqb** [comment]
* I would be in favor of deprecating Travis CI in favor of CircleCI only, e.g. #493.
* We should also add GPU testing in CircleCI.

**Comment by mthrok** [comment]
The choice of CI is adjacent and we should discuss down the road. (though I have no objection to the migration to CircleCI)

The followings are what I think needs to be sorted out for the next steps.

(here I consider only CPU and CUDA for device option.)

1. Add CUDA test
   1.1 Define a standard way to add device name to tests (or add CUDA test).
     - The bottom line is that device name (if not on CPU) should be visible in test result. so that we can see which tests PASSED/FAILED/ERROR/SKIPPED on which device.
     - CUDA test will be automatically skipped if CUDA device is not found, but also we should have option to force CUDA test and fail if CUDA is not available so that we can catch misconfiguration on CI.
   
   1.2 Find an efficient way to actually add device name to tests.
     - We can do this manually, but it can get tedious.
     - PyTorch parameterize device and instantiate test for different devices (CPU, CUDA, XLA ROCm).

2. Identify which test we should run on CUDA.
   - `torchaudio.functional`
   - `torchaudio.transforms`

3. Run test on CI

**Comment by mthrok** [comment]
#520 is my initial attempt to make CPU/GPU distinguish clear and parameterize device for a set of tests.
