### ISSUE TITLE
"fatal error: sox.h: No such file or directory" during installation

### ISSUE THREAD

**Issue by sizhky** [pytorch/audio#53]
When I try to install the module on " CentOS Linux release 7.2.1511 (Core)", I get the above error. I've done `yum install sox` and `yum install sox-devel`. I'm not sure what else I'm missing...

**Comment by sizhky** [comment]
I could resolve the issue using `include_dirs=['/usr/include/sox"]` as part of `CppExtension` in the setup.py file, but I'm obtaining a segmentation fault - as I raised in https://github.com/pytorch/audio/issues/54 - when I run torchaudio.load(<file>)

**Comment by jinserk** [comment]
by changing `#include <sox.h>` to `#include <sox/sox.h>` in `torchaudio/torch_sox.cpp`, I could install and run without error. But it's just a workaround and we need some general solution for this issue.

**Comment by mojesty** [comment]
Try installing packages `sox libcurl4-openssl-dev clang libopencv-dev libsox-dev`, it helped me. However, they require about 650M of disk space.

**Comment by luckmoon** [comment]
Here is my solution, referencing [this](https://github.com/hltcoe/vaporengine/blob/master/README.md)
`sudo  ln -s /usr/include/sox/sox.h /usr/include/sox.h`

**Comment by rfalcon100** [comment]
I am having this issue on OSX. I installed sox with  `brew install sox` , and the sox installation is located in directory `~/Homebrew/bin/sox`.

I managed to get pass the first error `fatal error: sox.h: No such file or directory`, by adding `include_dirs=['~/Homebrew/opt/sox/include/]` to the `CppExtension `. However, now i am getting:

`ld: library not found for -lsox
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang++' failed with exit status 1`

Does anyone have any ideas?

**Comment by vincentqb** [comment]
We now have binaries that can be install directly from `pip` and `conda`, see [here](https://github.com/pytorch/audio#Installation).

Since the original author has not expressed further issue, I will close this. Please feel free to re-open and provide the information given [here](https://github.com/pytorch/audio/issues/new?template=bug-report.md) if this is still happening.

@rfalcon100 -- Please feel free to open a separate issue for your installation with MacOS. This will allow us to collect more information about your particular environment. The installation instructions are given [here](https://github.com/pytorch/audio#Installation). Please also consider using the binaries via `pip` and `conda` instead of compiling from source.

**Comment by jieruan02** [comment]
> I am having this issue on OSX. I installed sox with `brew install sox` , and the sox installation is located in directory `~/Homebrew/bin/sox`.
> 
> I managed to get pass the first error `fatal error: sox.h: No such file or directory`, by adding `include_dirs=['~/Homebrew/opt/sox/include/]` to the `CppExtension `. However, now i am getting:
> 
> `ld: library not found for -lsox clang: error: linker command failed with exit code 1 (use -v to see invocation) error: command 'clang++' failed with exit status 1`
> 
> Does anyone have any ideas?

I had the same issue and solved it by manually creating symlinks in the search directory linking to the libsox.a and libsox.dylib for the clang++ linker.

**Comment by eacevedo1** [comment]
> > I am having this issue on OSX. I installed sox with `brew install sox` , and the sox installation is located in directory `~/Homebrew/bin/sox`.
> > I managed to get pass the first error `fatal error: sox.h: No such file or directory`, by adding `include_dirs=['~/Homebrew/opt/sox/include/]` to the `CppExtension `. However, now i am getting:
> > `ld: library not found for -lsox clang: error: linker command failed with exit code 1 (use -v to see invocation) error: command 'clang++' failed with exit status 1`
> > Does anyone have any ideas?
> 
> I had the same issue and solved it by manually creating symlinks in the search directory linking to the libsox.a and libsox.dylib for the clang++ linker.

Both of this work for me. Thanks! 

In my case files where actually on `/opt/homebrew/opt/sox/lib` so I add 
`include_dirs=['opt/homebrew/opt/sox/include/]` to the `CppExtension ` 

And for making the symlinks:
`ln -s /opt/homebrew/Cellar/sox/14.4.2_5/lib/libsox.a /usr/local/lib/libsox.a`
`ln -s /opt/homebrew/Cellar/sox/14.4.2_5/lib/libsox.dylib /usr/local/lib/libsox.dylib`
