### ISSUE TITLE
Nightly installation fails

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#545]
As reported by @cpuhrsch, when following [readme](https://github.com/pytorch/audio/blob/master/README.md) for nightlies,
```
conda create -n nightly
conda activate nightly
conda install pip
pip install numpy
pip install torchaudio_nightly -f https://download.pytorch.org/whl/nightly/torch_nightly.html
```

```
Looking in links: https://download.pytorch.org/whl/nightly/torch_nightly.html
ERROR: Could not find a version that satisfies the requirement torchaudio_nightly (from versions: none)
ERROR: No matching distribution found for torchaudio_nightly
```

cc @seemethere #306

**Comment by seemethere** [comment]
You should actually be installing `torchaudio` instead of `torchaudio_nightly`

**Comment by vincentqb** [comment]
Oops :) We do need to update the readme.

**Comment by mthrok** [comment]
Reopening as `--pre` is still missing. See [here](https://github.com/pytorch/audio/pull/547#issuecomment-613741627)
