### ISSUE TITLE
any specific usage for Windows

### ISSUE THREAD

**Issue by CarolinGao** [pytorch/audio#563]
Hi!
I have browsed all issues about windows support, but I am still confused about how to use it.
Can you add some specific instructions on Read me?
Thank you very much!

**Comment by vincentqb** [comment]
We do not yet officially support windows, see #425. If you would like to help extend the support, you can try compiling torchaudio from source, though we do not have instructions yet.

@cpuhrsch -- could you describe how you've compiled torchaudio from source on windows?

**Comment by peterjc123** [comment]
Well, you don't really need to compile. There isn't any C/C++ extensions so you could just do `python setup.py install` or just setting `PYTHONPATH` to the path of this repo.

**Comment by vincentqb** [comment]
As of torchaudio 0.6, torchaudio can be installed in torchaudio in windows. I'm closing this issue, but please feel free to re-open if this does not address it :)
