### ISSUE TITLE
lfilter: clamp in [-1, 1] to be optional

### ISSUE THREAD

**Issue by r9y9** [pytorch/audio#596]
## 🚀 Feature

Make clamp [-1, 1] behavior to be optional by adding an optional argument `clamp=False or True` to `torchaudio.functional.lfilter`.

## Motivation

I want to apply filters for non-waveform signals, which have values outside [-1, 1].
## Pitch

It seems that the input and output are assumed to be *waveform* ([-1, 1]). However, we can apply filters on arbitrary signals, which may not be in the range of [-1, 1]. Removing or making the clipping behavior optional should give more flexibility to users.

I think the clipping behavior should be disabled in general, but we'd want to make it optional and enabled by default for backward compatibility.

## Additional context

https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.lfilter.html

scipy.signal.lfilter doesn't apply clipping.

A different topic though, function arguments (name, order, etc) are not same as the scipy's one and I was confused at first. We may want to improve compatibility. Any comments are appreciated.

**Comment by vincentqb** [comment]
Some of the transform may assume the input is in the range `[-1,1]` even without clamp, so removing clamp doesn't mean that the transform does what one would want :)

I agree with the idea nonetheless. This also gives the freedom to the user to decide how to keep the waveform within the range.

Either we add a toggle to disable `clamp` or we deprecate it altogether. Even in the latter case, we should give the user at least one release to update their code. And to do so we would need a toggle anyway. Let's add an option `clamp` that defaults to `True`. Would you like to open a pull request?

We can decide later to add a deprecation warning that the option will be remove and that the future behavior will be `clamp=False` without an option.

**Comment by cpuhrsch** [comment]
I think this assumption of signals being within range [-1, 1] is something that is a bit larger than this particular ask. If various operations make this assumptions they should be clearly flagged as such as we might want to consider some kind of dtype dependent standardization around this.

In my experience [-1, 1] is used for conversions of audio signals into float32, whereas for integers the full range is used at their width often corresponds to the bit depths of the original signal (e.g. int16 for CD audio). We, however, mostly operate on floats for many reasons.

**Comment by r9y9** [comment]
I am not quite familiar with other transforms which may or may not assume signals being in the range [-1, 1]. Let me first fix this for the particular `lfilter` case. I will open a PR for adding a toggle. 

For your information, my real use-case is that I wanted to apply digital filters on a fundamental frequency sequence of speech. In speech synthesis, there are also other cases where we want to apply filters on signals not being in the range [-1, 1]. .e.g., mel-cepstrum, band aperiodicity features.
