### ISSUE TITLE
it can not calculate on GPU

### ISSUE THREAD

**Issue by YihengJiang** [pytorch/audio#61]
I try to make it on GPU,but it can not run, I want to know whether it can work on GPU if I try to revise code?

thank you,author!!!

**Comment by vincentqb** [comment]
You can find the current instructions to install pytorch with GPU support [here](https://pytorch.org/). Please feel free to re-open the issue or [create a new one](https://github.com/pytorch/audio/issues/new?template=bug-report.md) if you are still having it, and provide the information requested in the new issue template. You can also [visit the forum](https://discuss.pytorch.org/).
