### ISSUE TITLE
Clean up helper function of batch consistency test.

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#610]
Batch consistency test checks whether a function produces consistent outputs when an input tensors contain multiple of samples.
The helper function [_test_batch_consistency](https://github.com/pytorch/audio/blob/b4998409224f53d9f04c84c2d5a445f35f49d30f/test/test_batch_consistency.py#L12-L23) takes a function and a single sample. Then check if the output produced from the single sample and the output produced from the batch of the same samples are numerically consistent.

This helper function set random seed, as without it, some functions produce flaky results.
However, setting the same seed in helper function is not right as in the future when a new function is added, that function might fail on the seed value.
Therefore it is ideal to decide what seed value should be used on test function side, and not in helper function.
To do this each test case have to define inner function which set seed, then run the target function.
This approach is similar to [torchscript test](https://github.com/pytorch/audio/blob/b4998409224f53d9f04c84c2d5a445f35f49d30f/test/test_torchscript_consistency.py#L40-L52).

If someone can help us with this. Please leave the comment bellow.

**Comment by kunalb6** [comment]
I can work on this.
