### ISSUE TITLE
missing type hints for mypy

### ISSUE THREAD

**Issue by csukuangfj** [pytorch/audio#615]
For the following test code (hello.py)

```python
import torchaudio
import torch
```

`mypy hello.py` produces

```
hello.py:1: error: Skipping analyzing 'torchaudio': found module but no type hints 
or library stubs
hello.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

**Note that** there are no errors for `import torch` !

<details open>
<summary> Env </summary>

`python -m torch.utils.collect_env`

```
Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 16.04 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.11.0

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU xxx (removed manually): TITAN Xp

Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.5.0
[pip3] torchaudio==0.5.0
[conda] Could not collect
```
</details>

**Comment by tomassosorio** [comment]
if you try with any other libraries such as: `torchvision`, `torchtext` or `torchserve` for example the same happens.

So I would suggest using a [mypy config](https://github.com/pytorch/audio/blob/master/mypy.ini) and enable `ignore_missing_imports = True`

**Comment by csukuangfj** [comment]
> So I would suggest using a mypy config and enable ignore_missing_imports = True

thanks, I am currently using this approach as a workaround.

It would be great if `touchaudio` does a **better** job than `torchvision`, `torchtext`,
`torchserve` or other `torch*` in this aspect.

**Comment by mthrok** [comment]
Seems the issue is resolved. `ignore_missing_imports = False` and mypy reports `Success: no issues found in 1 source file`.
