### ISSUE TITLE
multiple definitions of `SoxEffect`.

### ISSUE THREAD

**Issue by csukuangfj** [pytorch/audio#628]
`SoxEffect` is defined both in

https://github.com/pytorch/audio/blob/00d38203e401b8d9472a8f8394a10e2c309be02c/torchaudio/torch_sox.h#L50-L54

and

https://github.com/pytorch/audio/blob/00d38203e401b8d9472a8f8394a10e2c309be02c/torchaudio/torch_sox.cpp#L73-L77

-----

-----

`torch_sox.h` can be included into `torch_sox.cpp` so that `SoxEffect` needs to be defined
only once in the header.

**Comment by vincentqb** [comment]
Good catch. Do you want to open a PR for this?
