### ISSUE TITLE
cannot download libsox-dev and libsox-fmt-all

### ISSUE THREAD

**Issue by nsrikanth548** [pytorch/audio#63]
I work in a network of linux clusters and cant use sudo command: **sudo apt-get install sox libsox-dev libsox-fmt-all**
howelse can I install libsox-dev and libsox-fmt-all ?
I tried all  ways but getting stuck with some error occuring while building '_torch_sox' extension.
Any help would be appreciated.

**Comment by bjuncek** [comment]
You can compile them from source -> https://github.com/jacksonh/sox/blob/master/INSTALL

**Comment by vincentqb** [comment]
We now have pre-compiled binaries that you can install using `pip` and `conda`, see [here](https://github.com/pytorch/audio/blob/master/README.md#Installation). You can also install sox using `conda`. Please feel free to re-open this issue if this does not address your use-case. Feel free to also visit [the forum](https://discuss.pytorch.org/).
