### ISSUE TITLE
Change in `F2M`; more docstrings including examples

### ISSUE THREAD

**Issue by keunwoochoi** [pytorch/audio#64]
Hi, I think I could work on these if they seem useful for users/maintainers. 

* in [transforms.F2M](https://github.com/pytorch/audio/blob/master/torchaudio/transforms.py#L233), 
  - The computation of filterbanks (`fb`) can be move to `init()` to remove its redundancy. 

* Would more docstrings be useful?

* Seems like there could be potential `-inf` or `NaN` during applying `_tlog10()` ([Example](https://github.com/pytorch/audio/blob/master/torchaudio/transforms.py#L295)). Perhaps we could make it little more stable?

**Comment by dhpollack** [comment]
@keunwoochoi sorry, I didn't see this.  I recently made a change to F2M that's in master.  Perhaps you could take a look at it for me and tell me what you think.
