### ISSUE TITLE
For Gammatone filters

### ISSUE THREAD

**Issue by WangHelin1997** [pytorch/audio#649]
Hi.
Could you please update the code for Gammatone filters in the future?
Thanks a lot.

**Comment by vincentqb** [comment]
Thanks for posting! I'm assuming you mean that you would like to see gammatone filter banks implemented in torchaudio? If so, would you like to work on this and open a pull request?

**Comment by underdogliu** [comment]
@vincentqb Hi I happened to met this post and I am very happy to work on this one. We can borrow some ideas from relevant established repos such as [nnAudio](https://github.com/KinWaiCheuk/nnAudio), if it is legitimate to do so.
