### ISSUE TITLE
AttributeError: type object 'BuildExtension' has no attribute 'with_options'

### ISSUE THREAD

**Issue by KiAlexander** [pytorch/audio#673]
## To Reproduce

```
~$ python setup.py install
-- Building version 0.6.0a0+da59f59
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    'build_ext': setup_helpers.BuildExtension.with_options(no_python_abi_suffix=True)
AttributeError: type object 'BuildExtension' has no attribute 'with_options'
```

## Expected behavior
install torchaudio sucessfully

## Environment

 - What commands did you used to install torchaudio (conda/pip/build from source)?
from source 
python setup/py. install
 - If you are building from source, which commit is it?
[6c3cc16](https://github.com/pytorch/audio/commit/6c3cc16ddb2e5dd5da1dcc5bceec6b1e10e9003a)
 - What does `torchaudio.__version__` print? (If applicable)
Not applicable

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

```
$ python collect_env.py 
Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.16.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)
GPU 2: TITAN X (Pascal)
GPU 3: TITAN X (Pascal)

Nvidia driver version: 410.78
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.6

Versions of relevant libraries:
[pip3] numpy==1.13.3
[pip3] numpydoc==0.7.0
[conda] numpy                     1.16.3                   pypi_0    pypi
[conda] torch                     1.0.1                    pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchsnooper              0.7.1                    pypi_0    pypi
[conda] torchvision               0.3.0                    pypi_0    pypi
```

**Comment by mthrok** [comment]
Hi @KiAlexander 

To use master branch of torchaudio, the latest PyTorch is required. Please upgrade your PyTorch.

**Comment by vincentqb** [comment]
To be more specific, the master branch of torchaudio depends on the master branch of pytorch.

I will close this issue, but please feel free to re-open if the issue persists with a compiled version of the lastest pytorch master.
