### ISSUE TITLE
🚀 Feature Request: Opus audio format support

### ISSUE THREAD

**Issue by zhukovaes** [pytorch/audio#688]
## 🚀 Feature

Add opus format 
## Motivation

Opus is a good and popular lossy audio coding format. A lot of audio files are stored in opus format but it's impossible to use it with torchaudio.load(). 
## Pitch

Please, make possible to do 
audio = torchaudio.load("my_audio.opus")

**Comment by mthrok** [comment]
Hi @zhukovaes 

Thanks for bringing up the request.
How are you installing `torchaudio` and which backend are you using?
I see two possible solutions;
1. If you have `sox` with `opus` support in your system, building `torchaudio`'s C++ extension from source and making it depend on external `libsox` should allow you to use `opus` file. 
2. Similarly, if you have `libsndfile` with `opus` support in your system, switching to `soundfile` backend will do.
Please refer to README for the instruction for building from source and backend. If something is not clear feel free to ask further questions.

If you are using binary distributions of `torchaudio`, the best way to bring `opus` support is your contribution to add support for it. Currently, we use [this script](https://github.com/pytorch/audio/blob/master/build_tools/setup_helpers/build_third_party.sh) to build `libsox` statically with support for `lame`, `libmad` and `flac`. If you can successfully modify this script to add `opus` support, and open a PR, we can review it.

**Comment by mthrok** [comment]
Opus support has been added. Nightly build and coming 0.6.0 should support it.
