### ISSUE TITLE
Naming conventions in torchaudio models

### ISSUE THREAD

**Issue by jimchen90** [pytorch/audio#721]
## 🚀 Feature
For size names, add naming conventions `n_*` in torchaudio models

## Motivation

As mentioned in [torchaudio conventions](https://github.com/pytorch/audio#conventions), "For size names, the prefix `n_` is used (e.g. "a tensor of size (`n_freq`, `n_mel`)") whereas dimension names do not have this prefix (e.g. "a tensor of dimension (channel, time)")"

How about we change the size names in torchaudio models [wav2letter](https://github.com/pytorch/audio/blob/master/torchaudio/models/wav2letter.py) and waveRNN(#705, #724 ) so that they follow this `n_*` format?

For example: `num_*` to `n_*`

**Comment by vincentqb** [comment]
Good idea. Since wav2letter has not been part of a release yet, we can go ahead and modify the interface without being BC-breaking.
