### ISSUE TITLE
doc for bg_iterator et al

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#733]
The [documentation](https://pytorch.org/audio/datasets.html) for torchaudio does not include `bg_iterator` and `disk_cache_iterator` from [code](https://github.com/pytorch/audio/blob/master/torchaudio/datasets/utils.py). Thanks to [comment](https://discuss.pytorch.org/t/audio-dataset-load-large-file-into-memory-in-background/85943) to point this out :)

**Comment by vincentqb** [comment]
Example usage with any iterator:
```
for i in bg_iterator(some_iterator):
    # do stuff
```
In particular with `data_loader`:
```
for datapoint in bg_iterator(data_loader):
    # training
```

**Comment by faroit** [comment]
I evaluated the use of `bg_iterator` in my pipeline and got almost no speed up regardless which loading backend I used. 

@vincentqb Can you share your experience when to expect an improvement using it especially in combination with the number of workers?

**Comment by faroit** [comment]
furthermore together with torch 1.7 I now get deadlocks when using `bg_iterator`... simular to [this report](https://discuss.pytorch.org/t/possible-deadlock-training-example-gets-stuck/94221). Is there anything that could have caused this?

**Comment by mthrok** [comment]
@vincentqb Do you want to look into this?

**Comment by mthrok** [comment]
@AzizCode92 found a bug in `bg_iterator`. It hangs when loading fails. https://github.com/pytorch/audio/pull/1126#issuecomment-751279803

So the `bg_iterator` is
1. no speed up
2. not documented
3. buggy

I do not think this utility is providing any value, and this is a pure technical debt. I suggest we remove it from the library.
