### ISSUE TITLE
Add support for file-like object

### ISSUE THREAD

**Issue by liuyuyuil** [pytorch/audio#754]
## 🚀 Feature

Add support to directly read file-like object for torchaudio.load , e.g. BytesIO.

**Comment by mthrok** [comment]
Hi @liuyuyuil 

What type of data do you expect to be in the file-like object?
Is it raw samples or decoded/compressed?

**Comment by liuyuyuil** [comment]
> Hi @liuyuyuil
> 
> What type of data do you expect to be in the file-like object?
> Is it raw samples or decoded/compressed?

It is just the same as current `torchaudio.load` function supports. Right now, the first parameter of `load `function is `filepath`, which can only be the audio file path from the disk, currently I want to load audio from cloud-storage, such as S3 on AWS and OSS on AlibabaCloud, I have to download my audio files from remote into temporary files before loading.

Can we access the audio file like this:
```
from io import BytesIO
fp = bucket.get_object('xxx/xxx.wav')
d, sr = torchaudio.load(BytesIO(fp.read()), **)
```

**Comment by mthrok** [comment]
> It is just the same as current torchaudio.load function supports

That's very broad. In such case, loading audio data involves detection of audio format then decoding process, which we do not implement by ourselves but rely on widely used external C++ libraries (such as `libsox` and `libsndfile`). We cannot pass `BytesIO` directly to them.

If you know that your files are wav format, then you can use [`scipy.io.wavfile.read`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.wavfile.read.html) or [`soundfile.read`](https://pysoundfile.readthedocs.io/en/latest/#soundfile.read) to get NumPy representation of data from `BytesIO`, and convert it to Tensor type with `torch.from_numpy`.

**Comment by mthrok** [comment]
I have found a way to pass file-like object to libsox. #1108

**Comment by mthrok** [comment]
Support for file-like object has been added in #1158
