### ISSUE TITLE
Add TED-LIUM 3 dataset 

### ISSUE THREAD

**Issue by jiwidi** [pytorch/audio#765]
## 🚀 Feature
Hi! I saw torchaudio is missing the TED-LIUM dataset from https://arxiv.org/abs/1805.04699, https://www.openslr.org/51/ which is commonly used in ASR benchmarks and I would like to propose the addition of it to the list of avaliable datasets (And propose myself to code and contribute for it! :) )

## Motivation

TED-LIUM is a very common dataset in ASR benchmarking tasks and we should include it on the library.

## Pitch

Add TED-LIUM 3 dataset to the list of datasets

I would like to work in a PR to introduce it if it sounds good to the main contributors :)

**Comment by vincentqb** [comment]
Sounds good to me, and you can open a PR for this! Please make sure to follow the current dataset code organization when doing so :)

**Comment by jiwidi** [comment]
> Sounds good to me, and you can open a PR for this! Please make sure to follow the current dataset code organization when doing so :)

Nice! Will do :)

**Comment by vincentqb** [comment]
Closed by #882 -- please feel free to re-open if this is not the case :)
