### ISSUE TITLE
Error installing torchaudio from source

### ISSUE THREAD

**Issue by faraazn** [pytorch/audio#767]
## To Reproduce

1. `python setup.py build`

```
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
-- Building version 0.7.0a0+4b583ea
running build
running build_py
creating build
creating build/lib.linux-ppc64le-3.6
creating build/lib.linux-ppc64le-3.6/torchaudio
copying torchaudio/transforms.py -> build/lib.linux-ppc64le-3.6/torchaudio
copying torchaudio/__init__.py -> build/lib.linux-ppc64le-3.6/torchaudio
copying torchaudio/kaldi_io.py -> build/lib.linux-ppc64le-3.6/torchaudio
copying torchaudio/version.py -> build/lib.linux-ppc64le-3.6/torchaudio
copying torchaudio/functional.py -> build/lib.linux-ppc64le-3.6/torchaudio
creating build/lib.linux-ppc64le-3.6/torchaudio/compliance
copying torchaudio/compliance/kaldi.py -> build/lib.linux-ppc64le-3.6/torchaudio/compliance
copying torchaudio/compliance/__init__.py -> build/lib.linux-ppc64le-3.6/torchaudio/compliance
creating build/lib.linux-ppc64le-3.6/torchaudio/_internal
copying torchaudio/_internal/misc_ops.py -> build/lib.linux-ppc64le-3.6/torchaudio/_internal
copying torchaudio/_internal/module_utils.py -> build/lib.linux-ppc64le-3.6/torchaudio/_internal
copying torchaudio/_internal/__init__.py -> build/lib.linux-ppc64le-3.6/torchaudio/_internal
creating build/lib.linux-ppc64le-3.6/torchaudio/sox_effects
copying torchaudio/sox_effects/__init__.py -> build/lib.linux-ppc64le-3.6/torchaudio/sox_effects
copying torchaudio/sox_effects/sox_effects.py -> build/lib.linux-ppc64le-3.6/torchaudio/sox_effects
creating build/lib.linux-ppc64le-3.6/torchaudio/datasets
copying torchaudio/datasets/gtzan.py -> build/lib.linux-ppc64le-3.6/torchaudio/datasets
copying torchaudio/datasets/librispeech.py -> build/lib.linux-ppc64le-3.6/torchaudio/datasets
copying torchaudio/datasets/__init__.py -> build/lib.linux-ppc64le-3.6/torchaudio/datasets
copying torchaudio/datasets/utils.py -> build/lib.linux-ppc64le-3.6/torchaudio/datasets
copying torchaudio/datasets/ljspeech.py -> build/lib.linux-ppc64le-3.6/torchaudio/datasets
copying torchaudio/datasets/commonvoice.py -> build/lib.linux-ppc64le-3.6/torchaudio/datasets
copying torchaudio/datasets/vctk.py -> build/lib.linux-ppc64le-3.6/torchaudio/datasets
copying torchaudio/datasets/yesno.py -> build/lib.linux-ppc64le-3.6/torchaudio/datasets
copying torchaudio/datasets/speechcommands.py -> build/lib.linux-ppc64le-3.6/torchaudio/datasets
copying torchaudio/datasets/cmuarctic.py -> build/lib.linux-ppc64le-3.6/torchaudio/datasets
creating build/lib.linux-ppc64le-3.6/torchaudio/models
copying torchaudio/models/wav2letter.py -> build/lib.linux-ppc64le-3.6/torchaudio/models
copying torchaudio/models/__init__.py -> build/lib.linux-ppc64le-3.6/torchaudio/models
copying torchaudio/models/_wavernn.py -> build/lib.linux-ppc64le-3.6/torchaudio/models
creating build/lib.linux-ppc64le-3.6/torchaudio/extension
copying torchaudio/extension/extension.py -> build/lib.linux-ppc64le-3.6/torchaudio/extension
copying torchaudio/extension/__init__.py -> build/lib.linux-ppc64le-3.6/torchaudio/extension
creating build/lib.linux-ppc64le-3.6/torchaudio/backend
copying torchaudio/backend/sox_backend.py -> build/lib.linux-ppc64le-3.6/torchaudio/backend
copying torchaudio/backend/__init__.py -> build/lib.linux-ppc64le-3.6/torchaudio/backend
copying torchaudio/backend/utils.py -> build/lib.linux-ppc64le-3.6/torchaudio/backend
copying torchaudio/backend/sox_io_backend.py -> build/lib.linux-ppc64le-3.6/torchaudio/backend
copying torchaudio/backend/common.py -> build/lib.linux-ppc64le-3.6/torchaudio/backend
copying torchaudio/backend/soundfile_backend.py -> build/lib.linux-ppc64le-3.6/torchaudio/backend
copying torchaudio/backend/no_backend.py -> build/lib.linux-ppc64le-3.6/torchaudio/backend
running build_ext
building 'torchaudio._torchaudio' extension
creating build/temp.linux-ppc64le-3.6
creating build/temp.linux-ppc64le-3.6/home
creating build/temp.linux-ppc64le-3.6/home/faraaz
creating build/temp.linux-ppc64le-3.6/home/faraaz/workspace
creating build/temp.linux-ppc64le-3.6/home/faraaz/workspace/audio
creating build/temp.linux-ppc64le-3.6/home/faraaz/workspace/audio/torchaudio
creating build/temp.linux-ppc64le-3.6/home/faraaz/workspace/audio/torchaudio/csrc
/home/software/spack/gcc/8.3.0-xdjkb2mmftikxvoeeyaxtxcjtpltcgiz/bin/gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/faraaz/workspace/audio -I/nobackup/users/faraaz/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include -I/nobackup/users/faraaz/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/nobackup/users/faraaz/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include/TH -I/nobackup/users/faraaz/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include/THC -I/nobackup/users/faraaz/anaconda3/envs/py36/include/python3.6m -c /home/faraaz/workspace/audio/torchaudio/csrc/typedefs.cpp -o build/temp.linux-ppc64le-3.6/home/faraaz/workspace/audio/torchaudio/csrc/typedefs.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_torchaudio -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
In file included from /home/faraaz/workspace/audio/torchaudio/csrc/typedefs.cpp:1:
/home/faraaz/workspace/audio/torchaudio/csrc/typedefs.h:7:46: error: expected class-name before '{' token
 struct SignalInfo : torch::CustomClassHolder {
                                              ^
error: command '/home/software/spack/gcc/8.3.0-xdjkb2mmftikxvoeeyaxtxcjtpltcgiz/bin/gcc' failed with exit status 1
```

## Expected behavior

Expected to run building / installation without error.

## Environment

 - What commands did you used to install torchaudio (conda/pip/build from source)?
Build from source: `python setup.py build`
 - If you are building from source, which commit is it?
commit 4b583eab6afbd98af9c0a57bce65f5affdc3b027
 - What does `torchaudio.__version__` print? (If applicable)
n/a

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

```
python collect_env.py 
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Red Hat Enterprise Linux Server release 7.6 (Maipo)
GCC version: (Spack GCC) 8.3.0
CMake version: version 3.15.4

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB

Nvidia driver version: 418.87.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.4.0
[pip3] torchtext==0.5.0
[pip3] torchvision==0.5.0a0
[conda] _pytorch_select           2.0             gpu_23447.g18a1a27    https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access
[conda] cudatoolkit               10.2.89            681.g0f7a43a    https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access
[conda] numpy                     1.17.4           py36hd5be1e1_0  
[conda] numpy-base                1.17.4           py36h2f8d375_0  
[conda] pytorch                   1.4.0            23447.g18a1a27    https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access
[conda] pytorch-base              1.4.0           gpu_py36_23447.g18a1a27    https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access
[conda] torchtext                 0.5.0           py36_639.g075ab52    https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access
[conda] torchvision-base          0.5.0           gpu_py36_661.g83acb06    https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access
```

## Additional context

I'm using PowerPC64 computer architecture which is not very common, so I have been unable to install torchaudio using conda, pip, etc. However, it is important to note that I am getting the exact same issue when I run this command on another computer with x86_64 architecture. 

Attempts to fix: I tried adding additional header files to `typedefs.h` like `<torch/custom_class.h>` and `<.../ivalue.h>` but I received the same error.

**Comment by mthrok** [comment]
Hi @faraazn 

At a glance, it seems that your compiler is not able to parse C++. Is your build environment correctly setup?
Is your `gcc` able to compile C++ code? What happens if you use `c++` or `g++` if that's available?

> Attempts to fix: I tried adding additional header files to `typedefs.h` like `<torch/custom_class.h>` and `<.../ivalue.h>` but I received the same error.

That does not seem to be relevant here, because compiler cannot parse C++ source code.

**Comment by mthrok** [comment]
In my environment (Ubuntu), I see compilation commands like the following and I do not see `gcc` as compilation command.

```
[1/7] c++ -MMD -MF /scratch/moto/torchaudio/build/temp.linux-x86_64-3.8/scratch/moto/torchaudio/torchaudio/csrc/typedefs.o.d -pthread -B /home/moto/conda/envs/PY3.8-cuda101/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/moto/torchaudio -I/scratch/moto/torchaudio/third_party/install/include -I/scratch/moto/pytorch/torch/include -I/scratch/moto/pytorch/torch/include/torch/csrc/api/include -I/scratch/moto/pytorch/torch/include/TH -I/scratch/moto/pytorch/torch/include/THC -I/home/moto/conda/envs/PY3.8-cuda101/include/python3.8 -c -c /scratch/moto/torchaudio/torchaudio/csrc/typedefs.cpp -o /scratch/moto/torchaudio/build/temp.linux-x86_64-3.8/scratch/moto/torchaudio/torchaudio/csrc/typedefs.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_torchaudio -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
```

**Comment by faraazn** [comment]
Thanks for your reply @mthrok , here's what I get when I run using c++ / g++:

```
which g++
/home/software/spack/gcc/8.3.0-xdjkb2mmftikxvoeeyaxtxcjtpltcgiz/bin/g++
```


```
(py36) [faraaz@service0001 audio]$ /home/software/spack/gcc/8.3.0-xdjkb2mmftikxvoeeyaxtxcjtpltcgiz/bin/g++ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/faraaz/workspace/audio -I/nobackup/users/faraaz/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include -I/nobackup/users/faraaz/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/nobackup/users/faraaz/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include/TH -I/nobackup/users/faraaz/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include/THC -I/nobackup/users/faraaz/anaconda3/envs/py36/include/python3.6m -c /home/faraaz/workspace/audio/torchaudio/csrc/typedefs.cpp -o build/temp.linux-ppc64le-3.6/home/faraaz/workspace/audio/torchaudio/csrc/typedefs.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_torchaudio -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
In file included from /home/faraaz/workspace/audio/torchaudio/csrc/typedefs.cpp:1:
/home/faraaz/workspace/audio/torchaudio/csrc/typedefs.h:7:46: error: expected class-name before '{' token
 struct SignalInfo : torch::CustomClassHolder {
                                              ^
```


```
which c++
/home/software/spack/gcc/8.3.0-xdjkb2mmftikxvoeeyaxtxcjtpltcgiz/bin/c++
```


```
(py36) [faraaz@service0001 audio]$ c++ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/faraaz/workspace/audio -I/nobackup/users/faraaz/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include -I/nobackup/users/faraaz/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/nobackup/users/faraaz/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include/TH -I/nobackup/users/faraaz/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include/THC -I/nobackup/users/faraaz/anaconda3/envs/py36/include/python3.6m -c /home/faraaz/workspace/audio/torchaudio/csrc/typedefs.cpp -o build/temp.linux-ppc64le-3.6/home/faraaz/workspace/audio/torchaudio/csrc/typedefs.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_torchaudio -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
In file included from /home/faraaz/workspace/audio/torchaudio/csrc/typedefs.cpp:1:
/home/faraaz/workspace/audio/torchaudio/csrc/typedefs.h:7:46: error: expected class-name before '{' token
 struct SignalInfo : torch::CustomClassHolder {
                                              ^
```

I'm not very familiar with C++ so I appreciate the help.

**Comment by nsarwar89** [comment]
Any updates on the issues? I am getting the same error

`In file included from /Work19/2019/nabil/envs/audio-master/torchaudio/csrc/typedefs.cpp:
/Work19/2019/nabil/envs/audio-master/torchaudio/csrc/typedefs.h:7:46: error: expected cl{’ token
 struct SignalInfo : torch::CustomClassHolder {
                                              ^
error: command 'gcc' failed with exit status 1
`

Here is my environment info from collect_env.py:

`Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: CentOS Linux release 7.4.1708 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: version 3.17.3

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.1.0
[pip3] torchaudio==0.3.1
[pip3] torchvision==0.3.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               9.0                  h13b8566_0
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.1.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.18.5           py37ha1c710e_0
[conda] numpy-base                1.18.5           py37hde5b4d6_0
[conda] pytorch                   1.1.0           py3.7_cuda9.0.176_cudnn7.5.1_0    pyto
[conda] torchaudio                0.3.1                     <pip>
[conda] torchvision               0.3.0           py37_cu9.0.176_1    pytorch
`

**Comment by faraazn** [comment]
@mthrok I ended up downloading a zip of a previous version torchaudio (version 0.4.0a0), and that worked for me. I no longer need this issue resolved, but it suggests that there is a bug in the codebase rather than an issue with my compiler.

**Comment by mthrok** [comment]
Please note that `torchaudio` master is developed on PyTorch nightly build and we do not intend to keep the compatibility with the older PyTorch releases.

@nsarwar89 In your case your PyTorch version is too old. Please use PyTorch 1.5 

@faraazn This could also apply to you too. I was looking at the release note of PyTorch 1.5 and TorchScript Custom class is only added at 1.5. I thought 1.4 works but I could be wrong.

https://pytorch.org/blog/pytorch-1-dot-5-released-with-new-and-updated-apis/#custom-c-classes-experimental

**Comment by faraazn** [comment]
@mthrok Ah I assumed the nightly build would be backwards compatible and it makes sense why that wouldn't be a good assumption to make. Thanks!

**Comment by nsarwar89** [comment]
@mthrok I can only use pytorch version 9.0 as I am using a cluster with older driver :( `The NVIDIA driver on your system is too old (found version 8000).` That is why I am trying to compile from source. It says that I need a G++ compiler instead of C++, but I tried installing all the variants from conda/pip, i.e. `gcc_linux-64, gxx_linux-64, conda make, conda cmake` - nothing seems to work. I am thinking of compiling pytorch from source and try again.

**Comment by mthrok** [comment]
@nsarwar89 Which feature of `torchaudio` do you intend to use? If you do not need sox-based features (load/save function based on `libsox` or `sox effects` filters), then you can use it without compiling the extensions. However, at this moment there is no way to install `torchaudio` while disabling extension building (unless on Windows) without modifying the code. If you need such feature I can add it rather quickly.

**Comment by nsarwar89** [comment]
@mthrok I am actually trying to run some codes from here: [https://github.com/JusperLee/Dual-Path-RNN-Pytorch/tree/master/data_loader], I am not sure what features I need yet - any workaround to get the code running for now would be great. Thanks a lot for your support :)

**Comment by mthrok** [comment]
@nsarwar89 It seems that they only use `load` and `save` functions, in that case, you can use `torchaudio` without compiling the extension. Here are your options (from the easiest to more complicated)

1. Use binary distribution. `conda install -c pytorch torchaudio==0.4.0` or `0.5.0` depending on your `torch` version.
2. Install the master version without extension. This requires you to modify code after you clone it. Change [this function](https://github.com/pytorch/audio/blob/c375490f4f6d0fe90156767995cfdba14812a95f/build_tools/setup_helpers/extension.py#L120) to return `None`, like it is done for `windows`. This way it will not attempt to install extension, but the other Python code will just work. (You need `soundfile` as alternative dependency though).
2. Build PyTorch (1.5 or newer) from source, then build `torchaudio` from source. This way, you should not have the error mentioned in this issue.

**Comment by mthrok** [comment]
> @mthrok Ah I assumed the nightly build would be backwards compatible and it makes sense why that wouldn't be a good assumption to make. Thanks!

@faraazn If you have time, can you try with `PyTorch==1.5.0` ??

**Comment by nsarwar89** [comment]
@mthrok It did not work.. it seems I also need _torch_sox `  File "/Work19/2019/nabil/envs/env_d/lib/python3.7/site-packages/torchaudio/__init__.py", line 5, in <module>
    import _torch_sox
ImportError: /Work19/2019/nabil/envs/env_d/lib/python3.7/site-packages/_torch_sox.cpython-37m-x86_64-linux-gnu.so: undefined symbol: `_ZN6caffe26detail37_typeMetaDataInstance_preallocated_29E``

**Comment by mthrok** [comment]
@nsarwar89 That error indicates that it could not find a symbol which
should be defined in libtorch. That means the version of torchaudio you
tried does not match the version of PyTorch in your system. Try another
version or, try the approach 2 I mentioned earlier.

Moto 🛵
