### ISSUE TITLE
🚀 Feature Request: Add Filtfilt (scipy.signal.filtfilt equivalent)

### ISSUE THREAD

**Issue by v-goncharenko** [pytorch/audio#789]
## 🚀 Feature

Add utility `filtfilt` to `torchaudio.functional`. This utility applies `lfilt` twice: in forward and backward direction, so phase of resulting signal is preserved. This function exist for example in `scipy` (see [their docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.filtfilt.html)) and is frequently used in signal processing.

## Motivation

I frequently need this function, so I've already wrote and tested it, so I would make a PR to include it to core library.

## Pitch

Add bidirectional filtering function `filtfilt` commonly used in signal processing.

**Comment by mthrok** [comment]
Hi @v-goncharenko 

Thanks for the suggestion. I do not have anything against adding this to `torchaudio`, especially if it's well tested. @vincentqb your thoughts?

If your existing code is publicly available, can I take a look at it?
Adding code to `torchaudio` will likely to have different requirements for testing. You can read about it [here](https://github.com/pytorch/audio/tree/master/test#torchaudio-test-suite). This case, we will need to add new type of test (spicy compatibility).

**Comment by mthrok** [comment]
Question: the `spicy` doc says 

> The function `sosfiltfilt` (and filter design using `output='sos'`) should be preferred over `filtfilt` for most filtering tasks, as second-order sections have fewer numerical problems.

What's your take on this one? I am not familiar with these functions so would like to hear your opinion.

**Comment by vincentqb** [comment]
> Thanks for the suggestion. I do not have anything against adding this to `torchaudio`, especially if it's well tested. @vincentqb your thoughts?

Yup, I'm ok with having this in torchaudio too @mthrok :) As usual, testing will need to ensure that the implementation support batch, torchscript, and correctness. It may be a good idea to have some testing around numerical stability given @mthrok's observation.

@v-goncharenko, please feel free to open a pull request for this!

**Comment by v-goncharenko** [comment]
> Adding code to torchaudio will likely to have different requirements for testing. You can read about it here. This case, we will need to add new type of test (spicy compatibility).

My tests aimed to check scipy compatibility. And of course I'm ready to write some more if needed.

> What's your take on this one? I am not familiar with these functions so would like to hear your opinion.

Well, this requires `sosfilt` to be implemented, but now we have only `lfilter`, so this is topic for another issue and PR.

> @v-goncharenko, please feel free to open a pull request for this!

Sure! Hope I'll have some time during this weekend.
