### ISSUE TITLE
Making Spectrogram as a layer

### ISSUE THREAD

**Issue by ksanjeevan** [pytorch/audio#79]
Having the spectrogram transform be a layer for a custom model has big benefits (GPU computation, no need to store the transforms, etc.). Similar to [kapre](https://github.com/keunwoochoi/kapre) (more in [this paper](https://arxiv.org/abs/1706.05781)). Making a few modifications to the *SPECTROGRAM* class would allow for such usage (subclassing *nn.Module*, using *nn.Paramater* instead of *autograd.Variable* for the window, etc.). Thoughts?

**Comment by faroit** [comment]
Indeed. Actually @keunwoochoi and me discussed this already offline. We were actually working on a proposal that would require some major API change for torch audio. Maybe we can collaborate on this proposal?

**Comment by ksanjeevan** [comment]
Gotcha. Sounds great @faroit, let me know.

**Comment by dhpollack** [comment]
I'd be open to major API changes.  Either create an issue here or get in touch with me on the pytorch slack.  :+1:

**Comment by f0k** [comment]
@faroit I'd be interested to join the discussion.

**Comment by soumith** [comment]
i added everyone here to slack. feel free to discuss in #audio

**Comment by EgorLakomkin** [comment]
I started hacking on making spectrogram as a layer for my own experiments - curious if there was any progress on this here?

**Comment by tsauri** [comment]
Any progress so far,
and how to join pytorch slack

**Comment by dhpollack** [comment]
Nope, the last big discussion was about making torchaudio more like librosa. It's been fairly quiet since then. 

To get into Pytorch slack, you need to contact soumith.

**Comment by faroit** [comment]
@keunwoochoi @ksanjeevan and me were working a proposal that we will make public in a separate repo for discussion in a few days. 

@tsauri @f0k @EgorLakomkin @dhpollack Happy to get you all on board then, to make torchaudio awesome ;-)

@soumith can you add me to the slack channel, please?

**Comment by soumith** [comment]
@faroit done. join #audio once inside.

**Comment by EgorLakomkin** [comment]
@soumith can I also join, please?

**Comment by tsauri** [comment]
@soumith  can I join the slack channel? Thanks in advance
