### ISSUE TITLE
Loading sph audio files

### ISSUE THREAD

**Issue by jiwidi** [pytorch/audio#868]
## Can audio.load load NIST sphere format (SPH) files?

Hi!

So I have tried to load sph files from tedlium dataset with simply:

```
torchaudio.load("pathtofile")
```
The load was successful but when saving it to a .wav file to check if the torchaudio read correctly the audio then I realized it was not working.

My question then is if this type of audio files is currently supported by torchaudio and if so, could you provide some link/code that refers how to? I haven't been able to find anything about torchaudio and sph files (but I know sox supports sph and allows to conversion into wav)

In case someone needs sph files here there are some sample ones https://filesamples.com/formats/sph. I got mines from the TEDLIUM dataset.

Thanks

**Comment by mthrok** [comment]
Hi @jiwidi 

Thanks for reporting this. 

Could you share the following things?
 - Your environment: the output of `python -m torch.utils.collect_env`
 - code snippet you used to save audio

The correctness of the `save` function in [`"sox"` backend](https://pytorch.org/audio/backend.html#backend) is never tested with `"sph"` format. We are moving away from "sox" backend but we do not support `"sph"` format in `"sox_io"` backend yet. Maybe we can add `"sph"` support to "sox_io" backend.

**Comment by jiwidi** [comment]
Yes @mthrok!

Environment on my macbook:
```
Collecting environment information...
PyTorch version: 1.7.0.dev20200807
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.5
GCC version: (Homebrew GCC 4.9.4_2) 4.9.4
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.7.0.dev20200807
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      233
[conda] mkl-include               2020.1                      216
[conda] mkl-service               2.3.0            py37hfbe908c_0
[conda] mkl_fft                   1.1.0            py37hc64f4ea_0
[conda] mkl_random                1.1.1            py37h959d312_0
[conda] numpy                     1.19.1           py37h3b9f5b6_0
[conda] numpy-base                1.19.1           py37hcfb5961_0
[conda] pytorch                   1.7.0.dev20200807         py3.7_0    pytorch-nightly
[conda] torch                     1.6.0                    pypi_0    pypi
```


The code (with the first sample from the link in first message):
```
import torchaudio
wave,sample = torchaudio.load("sample1.sph")
torchaudio.save("sample1.wav",wave,sample)
```
I checked if the sample returned from the loading was the same specified as in the sph (44100) and they match.
I try open the wav file and its now a 2hour snoring version

**Comment by mthrok** [comment]
@jiwidi Thanks, and you are working on `torchaudio` master branch, right?

I added support for `sph` format in `"sox_io"` backend.
Can you try my branch mthrok/sph or cherry pick this commit https://github.com/mthrok/audio/commit/f78ebf9556cf237de9e2fb8b3b156dca90769435
 and try `"sox_io"` backend?

```
import torchaudio
torchaudio.set_audio_backend("sox_io")
wave, sample = torchaudio.load("sample1.sph")
torchaudio.save("sample1.wav", wave, sample)
```

I believe this works, and if you can confirm I will merge it to master branch.

**Comment by jiwidi** [comment]
@mthrok I can confirm it works :+1: Thank you very much for the quick PR!

**Comment by mthrok** [comment]
@jiwidi Thanks for confirming. I merged the commit to master.
