### ISSUE TITLE
building torchaudio on armv6

### ISSUE THREAD

**Issue by sidwa** [pytorch/audio#870]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
As specified in the installation instruction to build from source I installed the apt library dependencies and then proceeded to do
python3.7 setup.py install
(pytorch built for python3.7)
I got the following error(s):
![bug_report](https://user-images.githubusercontent.com/13067900/89808923-e071d800-db08-11ea-838f-d13b49f3a907.png)

**Comment by mthrok** [comment]
Hi @sidwa 

Look very similar to https://github.com/pytorch/audio/issues/767.
What is the version of PyTorch you are using? When you build torchaudio from master, It has to use the master build of PyTorch.
Please run `python -m torch.utils.collect_env` and paste the result.

**Comment by sidwa** [comment]
Hi @mthrok ,
Here's what I got:
```
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Raspbian GNU/Linux 10 (buster)
GCC version: (Raspbian 8.3.0-6+rpi1) 8.3.0
CMake version: version 3.13.4

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.1.0
[conda] Could not collect

```

**Comment by mthrok** [comment]
Thanks.

So, as suspected, the version of PyTorch is too old.
`1.1.0` does not have Torchscript C++ extensions, thus the error you get. 

Please use nightly-build (most preferred way but may not be available for your platform), master source build, or `1.6.0`.
Please checkout the official instruction for the installation. https://pytorch.org

> I was building torchaudio without conda since for some reason it can't find pytorch in conda env.

`pip` installation should work too if conda is not available.

**Comment by sidwa** [comment]
Building pytorch on raspberry pi-0 easily takes about 4 days. Which is not possible for me to do as of now. So I have to rely on the pre-built torch version 1.1.0. Do you think any of the torchaudio versions would be compatible with pytorch version that I currently have?

**Comment by mthrok** [comment]
> Building pytorch on raspberry pi-0 easily takes about 4 days. Which is not possible for me to do as of now. So I have to rely on the pre-built torch version 1.1.0. Do you think any of the torchaudio versions would be compatible with pytorch version that I currently have?

I do not know which version of torchaudio work with 1.1.0, so you might want to try them one by one.

Another thing you can try is to disable C++ extension. If you change the following `get_ext_modules` function to return `None`, it will not compile C++ extension. The downside is that you cannot use functions based off of `libsox`. (such as sox effects and audio I/O. You need to install soundfile separately for audio I/O).

https://github.com/pytorch/audio/blob/2a6b6b555cb0bf24d26e43a1734a4867bd89082e/build_tools/setup_helpers/extension.py#L120-L133

**Comment by sidwa** [comment]
I tried to search but effects are present in Sox effects? I definitely don't need audio I/O

**Comment by mthrok** [comment]
> I tried to search but effects are present in Sox effects? I definitely don't need audio I/O

Sox effects is the module found [here](https://github.com/pytorch/audio/blob/master/torchaudio/sox_effects/sox_effects.py), which allows to apply the same effects as `sox` CLI on tensors.

If all you do not need either sox effects or sox-based I/O, then you can skip the C++ extension build, and you should be able to use (most of) the rest of functions. The master version is tested against PyTorch nightly build, so there might be some functions that do not work with `1.1.0` due to the change on PyTorch side.

**Comment by sidwa** [comment]
Turns out version 0.2.0 has all the functionality I need and is compatible with torch 1.1.0. Thank you for the help @mthrok  :grin: . No need to go through the Sox effects code.. Phew
