### ISSUE TITLE
Where is version.py if I insist on building from source?

### ISSUE THREAD

**Issue by jiapei100** [pytorch/audio#876]
When I tried to install by `pip setup.py build`, I obtained the following **ERROR** message:

```console
-- Building version 0.7.0a0
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    with open(version_path, 'w') as f:
TypeError: expected str, bytes or os.PathLike object, not PosixPath
```

It looks **version.py** is missing.

Cheers

**Comment by mthrok** [comment]
Hi @jiapei100 

The error is not about version.py missing, but about wrong type being given to built-in 'open' function. What is your version of Python? It's confirmed to work on supported versions, 3.6, 3.7 or 3.9.

Also, our setup.py is not fully compatible with pip, so please use 'python setup.py <SUBCOMMAND>'.
