### ISSUE TITLE
torchaudio-contrib

### ISSUE THREAD

**Issue by keunwoochoi** [pytorch/audio#88]
Hi all, the [torchaudio-contrib](https://github.com/keunwoochoi/torchaudio-contrib) repo became public just now. We (@faroit, @ksanjeevan and myself @keunwoochoi) have been working on it so far and there are lots of things to discuss. 
Everyone's invited :) let's talk!

**Comment by keunwoochoi** [comment]
(note - It's also related to #79)

**Comment by drscotthawley** [comment]
Re.

> "At this stage, discussion primarily takes place in the pytorch #audio slack channel; please request an invitation at pytorch/audio#88 if you want to join."  

I'm writing to request an invitation.  It looks like certain email addresses can add themselves to PyTorch slack, but my .edu address is not on the approved list.
