### ISSUE TITLE
“torchaudio C++ extension is not available”

### ISSUE THREAD

**Issue by LaplaceFourior** [pytorch/audio#887]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by cpuhrsch** [comment]
Hello @LaplaceFourior - could you add some more detail to this question please? Do you have a code snipped that reproduces this issue? Could you post some information about your environment (please see the instructions in the issue templates when creating a new issue).?

**Comment by LaplaceFourior** [comment]
@cpuhrsch Ok.I'am sorry for my  incorrect question format.I'll withdraw my question and upload the questions with the right format later.Thank you for your suggestion.
