### ISSUE TITLE
docstring should be worded for audio

### ISSUE THREAD

**Issue by marc-moreaux** [pytorch/audio#89]
I guess _'takes in an PIL image'_ should be changed to something like _'takes in raw audio'_

https://github.com/pytorch/audio/blob/7212f245ab738b2f65f398f8da92ba2cc43858e2/torchaudio/datasets/vctk.py#L83

https://github.com/pytorch/audio/blob/7212f245ab738b2f65f398f8da92ba2cc43858e2/torchaudio/datasets/yesno.py#L20

**Comment by soumith** [comment]
closed via #90
