### ISSUE TITLE
Backend inconsistency with torch.load

### ISSUE THREAD

**Issue by timlod** [pytorch/audio#902]
## 🐛 Bug

`sox` and `soundfile` backends use the parameter `normalization`, whereas `sox_io` uses `normalize`.
Code defaulting on one and falling back on another therefore will throw errors due to a wrong keyword argument.
Similarly, `sox_io` uses `frame_offset` instead of `offset`.

## To Reproduce

1. `torchaudio.set_audio_backend("sox_io")`
2. `torchaudio.load(..., normalization=False)`

## Expected behavior

Consistent keyword naming across backends.

## Environment

torchaudio 0.6.0 

## Additional context

I saw some typos in the new documentation and may make a pull request for the lot if I get the time soon.
While I actually prefer `normalize`, `normalization` is probably preferred for backwards compatibility.

**Comment by timlod** [comment]
I also found that `sox_io` does not currently support `pathlib` Paths for loading, where other backends do.

**Comment by timlod** [comment]
And I reread the warning note and find that it does advise the changed signature :)
I would still suggest accepting `pathlib` Paths for the `filepath` argument.

**Comment by mthrok** [comment]
Hi @timlod 

Thanks for the report. I am also feeing the need to make "sox_io" backend compatible with `"pathlib.Path"` type. If you would like to make a PR, let me know, else I will work on it some time.

**Comment by timlod** [comment]
I'll have a look on Sunday, and will probably submit a PR then (I don't think it should be a lot of work?)!

**Comment by mthrok** [comment]
@timlod 

> I'll have a look on Sunday, and will probably submit a PR then (I don't think it should be a lot of work?)!

Thanks.
Yes, I think it's just changing the type annotation and adding `path=str(path)` to convert it to string internally before passing it to C++ code.
