### ISSUE TITLE
Add CONTRIB.md

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#926]
We should add a CONTRIB.md file to empower users in contributing more.

cc [comment](https://github.com/pytorch/audio/pull/566#pullrequestreview-397433345), T57210445

**Comment by vincentqb** [comment]
It should

- point to [the README for tests](https://github.com/pytorch/audio/tree/master/test/torchaudio_unittest), 
- remind to test for correctness against librosa/sox/scipy/kaldi/etc, torchscriptability, batchable
- add documentation

Thoughts?

**Comment by bhargavkathivarapu** [comment]
@vincentqb , I would like to help with this . How do you want to organize this ?
I am thinking of below organization. thoughts ?
1. Basic setups & installations
2. Some resources to understand pytorch tensors 
3. A generic workflow from raise issue , code change , code linting , submitting PR , merging 
4. Then some different ways of contributing and details,checklist specific to each type of contribution 
    - Contribute to Datasets
    - Contribute to Transforms
    - Contribute to Functional 
    - Contribute to Examples
    - Contribute to documentation 
    - Other contributions
