### ISSUE TITLE
DownmixMono channels_first wrong default value

### ISSUE THREAD

**Issue by ptrblck** [pytorch/audio#93]
While the [docs](https://pytorch.org/audio/transforms.html#torchaudio.transforms.DownmixMono) state the default value for `channels_dim` is `True`, it seems to be set to `None` instead as shown [here](https://pytorch.org/audio/_modules/torchaudio/transforms.html#DownmixMono).

This would yield to the default channel dimension as dim1:
```python
channels_first = None
ch_dim = int(not channels_first)
print(ch_dim)
> 1
```

Reported in the forum [here](https://discuss.pytorch.org/t/how-does-torchaudio-transforms-downmixmono-work/41135).

If you want, I could create a fast fix using `channels_first=True` as the default value or update the docs instead.

Best,
ptrblck

**Comment by jamarshon** [comment]
Removed DownmixMono here https://github.com/pytorch/audio/pull/152
