### ISSUE TITLE
tgetnum issue workaround doesn't help

### ISSUE THREAD

**Issue by prashantserai** [pytorch/audio#936]
## 🐛 Bug

I'm getting an "Undefined reference to `tgetnum' when using `BUILD_SOX`"

## To Reproduce

In a conda environment with Python 3.7 on RHEL 6

# Install Pytorch from Source
1. git clone --recursive https://github.com/pytorch/pytorch
2. cd pytorch 
3. git submodule sync
4. git submodule update --init --recursive
5. BLAS=OpenBLAS python setup.py install

#Install Torch Audio
6. git clone https://github.com/pytorch/audio
7. BUILD_SOX=1 python setup.py install

```
...
libtool: link: gcc -O3 -ffast-math -funroll-loops -Wall -pipe -o lame lame_main.o main.o brhist.o console.o get_audio.o lametime.o parse.o ti
mestatus.o  ../libmp3lame/.libs/libmp3lame.a -lncurses -lm
/opt/rh/devtoolset-6/root/usr/libexec/gcc/x86_64-redhat-linux/6.3.1/ld: console.o: undefined reference to symbol 'tgetnum'
//lib64/libtinfo.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:357: recipe for target 'lame' failed
gmake[5]: *** [lame] Error 1
Makefile:349: recipe for target 'all-recursive' failed
gmake[4]: *** [all-recursive] Error 1
Makefile:276: recipe for target 'all' failed
gmake[3]: *** [all] Error 2
CMakeFiles/libmp3lame.dir/build.make:132: recipe for target '../src/libmp3lame-stamp/libmp3lame-build' failed
gmake[2]: *** [../src/libmp3lame-stamp/libmp3lame-build] Error 2
CMakeFiles/Makefile2:162: recipe for target 'CMakeFiles/libmp3lame.dir/all' failed
gmake[1]: *** [CMakeFiles/libmp3lame.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
gmake: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    zip_safe=False,
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 175, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 161, in call_command
    self.run_command(cmdname)
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/data/data24/scratch/serai/audio/build_tools/setup_helpers/extension.py", line 139, in build_extension
    _build_third_party()
  File "/data/data24/scratch/serai/audio/build_tools/setup_helpers/extension.py", line 113, in _build_third_party
    check=True,
  File "/homes/3/serai/.conda/envs/speechb/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2.
```

## Expected behavior

torchaudio installs without errors

## Environment

> Collecting environment information...
> PyTorch version: 1.7.0a0+9f67176
> Is debug build: True
> CUDA used to build PyTorch: 10.2
> ROCM used to build PyTorch: N/A
> 
> OS: Red Hat Enterprise Linux Server release 6.10 (Santiago) (x86_64)
> GCC version: (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)
> Clang version: Could not collect
> CMake version: version 3.18.2
> 
> Python version: 3.7 (64-bit runtime)
> Is CUDA available: True
> CUDA runtime version: 10.2.89
> GPU models and configuration: GPU 0: Quadro P6000
> Nvidia driver version: 440.82
> cuDNN version: Could not collect
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> 
> Versions of relevant libraries:
> [pip3] numpy==1.19.1
> [pip3] torch==1.7.0a0
> [conda] _pytorch_select           0.2                       gpu_0  
> [conda] blas                      1.0                         mkl    anaconda
> [conda] cudatoolkit               10.2.89              hfd86e86_1  
> [conda] magma-cuda102             2.5.2                         1    pytorch
> [conda] mkl                       2020.2                      256  
> [conda] mkl-include               2020.2                      256  
> [conda] mkl-service               2.3.0            py37he904b0f_0  
> [conda] mkl_fft                   1.2.0            py37h23d657b_0  
> [conda] mkl_random                1.1.1            py37h0573a6f_0  
> [conda] numpy                     1.19.1           py37hbc911f0_0  
> [conda] numpy-base                1.19.1           py37hfa32c7d_0  
> [conda] torch                     1.7.0a0                   <pip>

 - PyTorch Version (e.g., 1.0): 1.7
 - OS (e.g., Linux): RHEL 6
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): BLAS=OpenBLAS python setup.py install
 - Python version: 3.7.9
 - CUDA/cuDNN version: 10.2/7.6.5
 - GPU models and configuration: Nvidia Quadro P6000
 - Any other relevant information:
Environment summary from the PyTorch build is here: https://discuss.pytorch.org/t/pytorch-building-from-source-fails/97181/5

## Additional context

I built PyTorch from source and that is why I was advised to build torchaudio from source too so that it is able to link to the PyTorch installed from source.

**Comment by mthrok** [comment]
Hi @prashantserai 

Looks like the error message suggests you hit the same error as [this](https://sourceforge.net/p/lame/mailman/message/32754132/).

To fix this, linker needs to be told to link against `tinfo` explicitly.
Since I do not have the same environment as you, I cannot give the exact direction, 
but here is the gist of what I think could work.

`torchaudio` uses CMake to build the third party libraries and the step to build `libmp3lame` is defined as 

https://github.com/pytorch/audio/blob/e3d1d746f2f1c741ef4be9f8cf9cc55e8276806c/third_party/CMakeLists.txt#L19-L25

(BTW this is different from the time https://github.com/pytorch/audio/issues/666 , so #666 is no longer applicable.)

If you look at the configuration script of `libmp3lame`,

https://github.com/rhishi/lame/blob/ab5a540ff8ea8af7619365479f62799232192118/configure#L1670-L1688

it says

>  LIBS        libraries to pass to the linker, e.g. -l<library>

So one possible solution is to define the environment variable `LIBS` when performing the configuration step of `libmp3lame`.

According to [this](https://stackoverflow.com/a/62437353), one way to pass environment variable is to use `cmake -E env`.
Changing [this line](https://github.com/pytorch/audio/blob/master/third_party/CMakeLists.txt#L24) to the following line

```
  CONFIGURE_COMMAND ${CMAKE_COMMAND} -E env LIBS=-ltinfo ${CMAKE_CURRENT_SOURCE_DIR}/src/libmp3lame/configure ${COMMON_ARGS} --enable-nasm
```

could work.

To check what command is actually ran, you can do 

```diff
diff --git a/build_tools/setup_helpers/extension.py b/build_tools/setup_helpers/extension.py
index b9fb30e..76f174f 100644
--- a/build_tools/setup_helpers/extension.py
+++ b/build_tools/setup_helpers/extension.py
@@ -103,12 +103,12 @@ def _build_third_party():
     build_dir = str(_TP_BASE_DIR / 'build')
     os.makedirs(build_dir, exist_ok=True)
     subprocess.run(
-        args=['cmake', '..'],
+        args=['cmake', '..', '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON'],
         cwd=build_dir,
         check=True,
     )
     subprocess.run(
-        args=['cmake', '--build', '.'],
+        args=['cmake', '--build', '.', '-j', '1'],
         cwd=build_dir,
         check=True,
     )
```

This way, you should see something like the following, when building `torchaudio`.

```
[ 70%] Performing configure step for 'libmp3lame'
cd /scratch/moto/torchaudio/third_party/src/libmp3lame-build && /scratch/moto/torchaudio/third_party/src/libmp3lame/configure --quiet --disable-shared --enable-static --prefix=/scratch/moto/torchaudio/third_party/install --with-pic --disable-dependency-tracking --disable-debug --disable-examples --disable-doc --enable-nasm

...

/bin/bash ../libtool --tag=CC   --mode=link gcc  -O3  -ffast-math 			-funroll-loops -Wall -pipe       -static  -o lame lame_main.o main.o brhist.o console.o get_audio.o lametime.o parse.o timestatus.o ../libmp3lame/libmp3lame.la -lm
libtool: link: gcc -O3 -ffast-math -funroll-loops -Wall -pipe -o lame lame_main.o main.o brhist.o console.o get_audio.o lametime.o parse.o timestatus.o  ../libmp3lame/.libs/libmp3lame.a -lm
```

If the configuration fails, you can check the log at `third_party/src/libmp3lame-build/config.log`.

In my environment (Ubuntu), the suggested change gave the following build log and the build  succeeded. (but not sure if `tifno` made difference here)

```
[ 70%] Performing configure step for 'libmp3lame'
cd /scratch/moto/torchaudio/third_party/src/libmp3lame-build && /home/moto/conda/envs/PY3.8-cuda101/lib/python3.8/site-packages/cmake/data/bin/cmake -E env LIBS=-ltinfo /scratch/moto/torchaudio/third_party/src/libmp3lame/configure --quiet --disable-shared --enable-static --prefix=/scratch/moto/torchaudio/third_party/install --with-pic --disable-dependency-tracking --disable-debug --disable-examples --disable-doc --enable-nasm

...

/bin/bash ../libtool --tag=CC   --mode=link gcc  -O3  -ffast-math 			-funroll-loops -Wall -pipe       -static  -o lame lame_main.o main.o brhist.o console.o get_audio.o lametime.o parse.o timestatus.o ../libmp3lame/libmp3lame.la -lm -ltinfo
libtool: link: gcc -O3 -ffast-math -funroll-loops -Wall -pipe -o lame lame_main.o main.o brhist.o console.o get_audio.o lametime.o parse.o timestatus.o  ../libmp3lame/.libs/libmp3lame.a -lm -ltinfo
```

**Comment by prashantserai** [comment]
I think this workaround was successful, thanks so much!
