### ISSUE TITLE
Out of date link to librosa

### ISSUE THREAD

**Issue by AngledLuffa** [pytorch/audio#938]
https://pytorch.org/audio/transforms.html

There is a link in the description of AmplitudeToDB

https://librosa.github.io/librosa/_modules/librosa/core/spectrum.html

This link no longer works

**Comment by mthrok** [comment]
@AngledLuffa 

Thanks for reporting this. We will address this, but if you are interested in contributing, we welcome you to make a PR for the fix. I think this is the new link. https://librosa.org/doc/latest/generated/librosa.amplitude_to_db.html

**Comment by AngledLuffa** [comment]
Thank you for the offer, but I would be happy just to see it fixed!
