### ISSUE TITLE
Add pathlib.Path support all io

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#950]
Since pathlib is the standard python library for handling paths since python 3.4, let's add explicit support for pathlib in i/o operations. 

- [x] `sox_io`
- [ ] ~~`sox` (won't update)~~
- [x] "new" `soundfile` 
- [ ] ~~legacy `sox` (won't update)~~
- [ ] ~~`apply_effects_file`, [here](https://github.com/pytorch/audio/blob/master/torchaudio/sox_effects/sox_effects.py#L163), jit does not support union, see [comment](https://github.com/pytorch/audio/pull/1048#issuecomment-730450782)~~

There are also datasets who consume paths as string in their constructor, which could be extended to pathlib. (This means adding a conversion at the beginning of each function to convert path to string so the rest can proceed as expected.)

- [x] cmuarctic
- [x] commonvoice
- [x] gtzan
- [x] librispeech
- [x] libritts
- [x] ljspeech
- [x] speechcommands
- [x] tedlium
- [x] vctk
- [x] yesno
- [ ] ~~see dataset utils consuming a path [here](https://github.com/pytorch/audio/blob/master/torchaudio/datasets/utils.py)~~

cc offline discussion with @mthrok and @cpuhrsch about #907

**Comment by mthrok** [comment]
Can you provide the road map for this?

Note that `"sox_io"` backend and the new interface of `"soundfile"` backend support `path lib.Path` already, so no need to change the implementation.

Since we are getting rid of `"sox"` backend and the legacy interface of `"soundfile"` backend, I would not put them on a high priority, rather I would leave them as is.

**Comment by vincentqb** [comment]
> Note that `"sox_io"` backend and the new interface of `"soundfile"` backend support `path lib.Path` already, so no need to change the implementation.
> 
> Since we are getting rid of `"sox"` backend and the legacy interface of `"soundfile"` backend, I would not put them on a high priority, rather I would leave them as is.

Agree.

> Can you share the list of action items for this?

The datasets, and `apply_effects_file` are the other places were files are being used. That's all I can think of. Some/All may already support, we should just double check :) Any others?

**Comment by mthrok** [comment]
Can you clarify on what **actions** are needed for each component?

`apply_effects_file` makes sense and I was not aware so thanks for listing up, however, it is not immediately clear to me why dataset implementations are on the list. They are not responsible for I/O, nor they receive path from client code.

**Comment by vincentqb** [comment]
I'm referring to the parameters in the constructor, .e.g [`root`](https://github.com/pytorch/audio/blob/master/torchaudio/datasets/cmuarctic.py#L101) which is a string, but really a path.

**Comment by mthrok** [comment]
> I'm referring to the parameters in the constructor, .e.g [`root`](https://github.com/pytorch/audio/blob/master/torchaudio/datasets/cmuarctic.py#L101) which is a string, but really a path.

ah make sense. Thanks for the clarification.

**Comment by vincentqb** [comment]
Thanks for the contributions! I'll mark this as done now :)
