### ISSUE TITLE
Wrong info about amplitude range for torchaudio.load

### ISSUE THREAD

**Issue by ailzhang** [pytorch/audio#98]
Copied from https://github.com/pytorch/pytorch/issues/19507 by @f90
Documentation for torchaudio.load says that the resulting audio is normalized to [0,1] range. However, simply loading an audio signal and looking at the output of torch.min(signal) reveals it's actually normalized to [-1,1], so the documentation should be fixed.

**Comment by calclavia** [comment]
I'm able to replicate this same issue. Is it a documentation issue or a bug in the code?
