### ISSUE TITLE
How should I do Audio Decoding from RF and Morse Code using Pytorch

### ISSUE THREAD

**Issue by waszee** [pytorch/audio#983]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by waszee** [comment]
I am looking for advise on how to process audio signals from a HAM radio, especially morse code patterns.  I want to try applying an AI decoding solution.   I am new to Python, PyTorch, and especially TorchAudio and have been using the Deep Learning and PyTorch textbook for learning and meanwhile writing some code to create spectrograms and make synthetic morse code audio patterns.  A discussion of my first attempts and idea was posted on https://github.com/deep-learning-with-pytorch/dlwpt-code/issues/25 with some images of actual frequency domain signals.  My coding attempts are posted in waszee/SignalStudies_RF. 

I am now trying to decide how best to make images of a moving window of code patterns.  I know I can easily convert to a tensor from the numpy array but how big and how much data to take at a time is something new to me and I am looking for experts that might give me some hints.  The discussions here indicate some of you might have ideas.  The attached image will give you a picture of the problem I hope.  Please make suggestions as to where to get help and how to feed the information to the learning engine. I am thinking I should slide along a single tone but that might be limiting.

![Figure_3](https://user-images.githubusercontent.com/71347227/97061566-4c3edb00-1565-11eb-952a-611187383b82.png)

**Comment by vincentqb** [comment]
Thanks for opening an issue on torchaudio! However, the best way to get help for these topics is to open a question on the pytorch forum [linked above](https://discuss.pytorch.org/). Have you tried this? 

This looks like a "speech recognition problem" were the "speech" are the "beeps" and "language" is the "dash-dot". This models well as a sequence-to-sequence problem. In fact, there's a tutorial [here](https://towardsdatascience.com/cracking-morse-code-with-rnns-e5883355a6f3) that does just that with RNN. Have you seen it? Hope this help!

In the meanwhile, I will close this issue, and encourage you to open a question on the pytorch forum [linked above](https://discuss.pytorch.org/) for the best support. But please feel free to re-open the issue if you want :)

**Comment by waszee** [comment]
Thank you  for the advice.  I am too new at this to have seen anything and will follow up the suggested items. I did not even know where I should post the need some help question.  I saw the title Questions/Help in torchaudio and thought this might be a place to start.

Waszee

**Comment by waszee** [comment]
fyi - posted a query on the discuss.pytorch topic as you suggested.  The cracking morse code article is interesting but assumes you have the dit dah pattern and that is easily handled in python using a dictionary as many others have shown.  The real problem is getting the pattern isolated from the radio audio signal or from a RF band pass depending on the type of receiver you have as well as how to work with a continuous and live signal.  Thanks for the input and the suggestions will be interesting to see how goes from here.  Did play with the torchaudio spectrogram and it worked well except I am not sure why the FFT n/2+1 size as my numpy built arrays did not.  That is given 1024 window I expected 512 frequency channels not 513 frequency channels, assuming index starting at 0 and ending at 511.
