### ISSUE TITLE
[DRAFT] 1 to 1 match between functionals and transforms?

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#985]
The [transforms](https://github.com/pytorch/audio/blob/master/torchaudio/transforms.py) are meant to be a convenient interface subclassed from `nn.Module` to [functionals](https://github.com/pytorch/audio/blob/master/torchaudio/functional.py) who then do the computations needed. 

- Why is dividing the code into transforms/functionals a good idea in the first place? The computation part isolated in a functional form means it's decoupled from the rest and easier to know what are the inputs. The transform part is convenient to use.
- Why enforcing the match? Each time we create a functional, we need to manually create a transform. Some functionals don't have corresponding transforms implemented. The names of transforms isn't consistent across transforms/functionals, or even across transforms. The default parameters may not all match in a functional-transform pair.

**Comment by mthrok** [comment]
Before posing the constraint of 1 on 1 match, I suggest to clarify why 1 on 1 matching is a good constraint, what problem it solves or who benefits from that constraints. If you come up with a good reason for that, then I think it will naturally narrow down the path for reducing the maintenance cost, but if you do not come up with a good reason, you can just abandon such constraint, and move on.

**Comment by vincentqb** [comment]
I meant this mostly as a note to think and talk about this. That being said, I'm not advocating for this, and so will close the issue.

**Comment by Stehsegler** [comment]
@vincentqb Well, from my user's perspective, it's indeed not quite comprehensible why for some functionals, a corresponding transform is provided and for others, it's not. Based on which criteria was this decision made for the existing transforms?

For users of the library, it would of course be nice to be able to use all functionality directly in a transform chain without having to write more-or-less boilerplate custom transform classes.

**Comment by vincentqb** [comment]
@Stehsegler -- thanks for commenting! I'll re-open to keep conversation going :)
