### ISSUE TITLE
"sox_io" does not handle SPH format compressed with 'shorten' algorithm

### ISSUE THREAD

**Issue by saurabh-kataria** [pytorch/audio#989]
Some SPHERE files (.sph) cannot be opened by torchaudio.info. I get the following error on some file
"formats: can't open input file `filename.sph': sph: unsupported coding `ulaw,embedded-shorten-v2.00'"
I cannot share the file although.
Such files are easily handled by special package like:
https://pypi.org/project/sphfile/

There is some tool called NIST's sph2pipe which might help:
http://www.cs.columbia.edu/~ecooper/tts/raw.html
https://www.ldc.upenn.edu/language-resources/tools/sphere-conversion-tools

I am using torch.__version__ = 1.8.0.dev20201028

**Comment by mthrok** [comment]
Hi @saurabh-kataria 

Thanks for the report. Can you tell us which backend/interface you are using?
Are you on Linux/macOS/Windows?

**Comment by saurabh-kataria** [comment]
It is sox_io since it fails on Line 25 `sinfo = torch.ops.torchaudio.sox_io_get_info(filepath)` of `.../python3.8/site-packages/torchaudio/backend/sox_io_backend.py`. OS is Debian/linux.

**Comment by mthrok** [comment]
Reading [the sox's documentation](http://sox.sourceforge.net/soxformat.html), `libsox` does not support `shorten` format.

> SoX can read these files when they contain μ-law and PCM data. It will ignore any header information that says the data is compressed using shorten compression and will treat the data as either μ-law or PCM. This will allow SoX and the command line shorten program to be run together using pipes to encompasses the data and then pass the result to SoX for processing.

Reading the description from [here](https://github.com/robd003/sph2pipe), looks like commonly used code for `shorten` format is [copy-protected](https://github.com/robd003/sph2pipe/blob/master/shorten_x.c#L1-L23), which I guess is why sox does not adopt it.

I am not sure how we can handle this or if it is possible for `torchaudio` to support these formats. One workaround will be to use other library, as you pointed out, to read it into NumPy NDArray, and convert it to Torch Tensor.

**Comment by saurabh-kataria** [comment]
Thanks for looking into it. Meanwhile, I have been using NIST reader sphfile https://pypi.org/project/sphfile/ successfully to numpy arrays.

**Comment by mthrok** [comment]
I will close the issue as there is no immediate action torchaudio can take on this. Thanks again for reporting it though.
