### ISSUE TITLE
ImportError: undefined symbol

### ISSUE THREAD

**Issue by hajix** [pytorch/audio#99]
importing torchaudio thrown import  error:

>
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-4cf0a64f61c0> in <module>()
    ----> 1 import torchaudio
    ~/repo/audio/torchaudio/__init__.py in <module>()
          3 
          4 import torch
    ----> 5 import _torch_sox
          6 
          7 from torchaudio import transforms, datasets, sox_effects, legacy
    ImportError: /usr/local/lib/python3.5/dist-packages/_torch_sox.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

**Comment by soumith** [comment]
this means you have an old / mismatched version of PyTorch since torchaudio was compiled. Recompile / reinstall torchaudio, or fix your pytorch install.
